### ISSUE TITLE
What about this mistake，How do I get rid of this error?

### ISSUE THREAD

**Issue by hpugongying** [docsifyjs/docsify#1003]
![image](https://user-images.githubusercontent.com/30855747/72437267-54e7d100-37dd-11ea-832e-ad1efe75e336.png)

request this link
http://sangfor-3f8d:100/src/iwa/index.js?t=1579083283
401 error

**Comment by hpugongying** [comment]
> ![image](https://user-images.githubusercontent.com/30855747/72437267-54e7d100-37dd-11ea-832e-ad1efe75e336.png)
> 
> request this link
> http://sangfor-3f8d:100/src/iwa/index.js?t=1579083283
> 401 error

**Comment by cobish** [comment]
@hpugongying 请问这个问题你解决了吗，我也遇到了
