### ISSUE TITLE
How to put my documents in the site subdirectory

### ISSUE THREAD

**Issue by fengsec** [docsifyjs/docsify#1012]
## Bug Report
I want to put my documents in a subdirectory of the website. What should I do?

#### Steps to reproduce
When I put my document in a subdirectory of the site： `/doc/`
and then I visit that：`http://mydomain.com/doc/`, 

#### What is current behaviour
* The browser will always automatically download an invalid file：`http://mydomain.com/doc/`
* When I put the file in the root directory of the site, I successfully access it through my domain name：``http://mydomain.com/#/``

#### What is the expected behaviour
I can access my documents through this link  `http://mydomain.com/doc/#/`

#### Other relevant information
* `Dir`
├──`index.html`
├──`/pages/`
│   ├── `README.md`
│   ├── `_sidebar.md`
│   ├── `_coverpage.md`
│   ├── `my_pages`
├──`/res/`
│   ├── `docsify.min.js`
│   ├── `vue.css`
│   ├── `favicon.ico`

* `index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Doc</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="res/vue.css">
  <link rel="shortcut icon" href="res/favicon.ico">
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
      basePath: '/pages/',
      subMaxLevel: 2,  
      auto2top: true, 
      loadSidebar: true,
      coverpage: true 
    }
  </script>
  <script src="res/docsify.min.js"></script>
</body>
</html>
```

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: `none`
- npm/yarn version: `none`
- Browser version: ` Chrome_79.0.3945.130`
- Docsify version:  `4.9.4`
- Docsify plugins: `none`

**Comment by anikethsaha** [comment]
I have a folder  structure like this 

```
- root 
  |- test
     |- docs  <-- docsify site
```

and when I run a local server from `root` I can access the site in using the link

`http://127.0.0.1:8080/test/docs/#/`

**Comment by fengsec** [comment]
> I have a folder structure like this
> 
> ```
> - root 
>   |- test
>      |- docs  <-- docsify site
> ```
> 
> and when I run a local server from `root` I can access the site in using the link
> 
> `http://127.0.0.1:8080/test/docs/#/`
> 
> docsify is simply a static HTML site, refactor the project structure as you do for HTML pages

I found out why. Maybe something's wrong with [qiniu](https://www.qiniu.com/). I switched to [upyun](https://www.upyun.com/) and it worked
