### ISSUE TITLE
Images with spaces in filename not rendered

### ISSUE THREAD

**Issue by Kosteg** [docsifyjs/docsify#1013]
#### Steps to reproduce
When I use screenshots with spaces in filename (default mac os screenshot name):
![Screenshot](Screenshot 2020-01-31 at 17.33.53.png)

#### What is current behaviour
They are not rendered and docsify leave the markup as is.

#### What is the expected behaviour
Rendering to img tag

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: Chrome 79.0.3945.130, Safari 12.1.2
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
This is the behavior of `markedjs` use 
`![Screenshot](Screenshot-2020-01-31-at-17.33.53.png)` instead to render it as an image.

[refer this](https://marked.js.org/demo/?outputType=html&text=!%5BScreenshot%5D(Screenshot-2020-01-31-at-17.33.53.png)%0A%0A%0A!%5BScreenshot%5D(Screenshot%202020-01-31%20at%2017.33.53.png)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
