### ISSUE TITLE
New dark theme

### ISSUE THREAD

**Issue by sushantrahate** [docsifyjs/docsify#1019]
## Feature request
New dark theme with green touch
#### What problem does this feature solve?
New Theme for docsify

#### What does the proposed API look like?
Its new css file

#### How should this be implemented in your opinion?
By adding new css file

#### Are you willing to work on this yourself?
Yes, I've already made it and using it form few days
![dakly](https://user-images.githubusercontent.com/19269251/74263212-6791ef00-4d24-11ea-8023-251c63a04649.png)

**Comment by anikethsaha** [comment]
cc @docsifyjs/core your takes !!
---

@sushantrahate this looks cool 👍



How do you want to make it available? do you want this to be added in this repo or you want to distribute using your own repo and as the package ?

if you want to add it here, we need it in `stylus` preprocessor.
[`check here`](http://stylus-lang.com/)

**Comment by jhildenbiddle** [comment]
Third-party themes should not be added to the docsify repo. They should be added to the awesome-docsify repo here: https://github.com/docsifyjs/awesome-docsify

**Comment by anikethsaha** [comment]
@sushantrahate as @jhildenbiddle , you can distribute as your style and add a link to the awesome-docsify repo. It will be reflected in the docsify website 👍

**Comment by sushantrahate** [comment]
Im glad you like it.
Sorry for the late reply, I was eating.

So should I create a repo in my account and give live link ?

**Comment by sushantrahate** [comment]
@anikethsaha, @jhildenbiddle  I'm glad you like it. Sure, will do that. Thanks
