### ISSUE TITLE
JavaScript error: Uncaught Error: Token with "list_end" type was not found.

### ISSUE THREAD

**Issue by Acconitum** [docsifyjs/docsify#1027]
#### Steps to reproduce

* Include multiple files
* Reload page

#### What is current behaviour

Fails to load content after the coverpage.md and shows following error message in developer console:

docsify.min.js:1 Uncaught Error: Token with "list_end" type was not found.
    at c.tok (docsify.min.js:1)
    at c.parse (docsify.min.js:1)
    at Function.c.parse [as parser] (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
    at se.compile (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
    at docsify.min.js:1
    at XMLHttpRequest.<anonymous> (docsify.min.js:1)

#### What is the expected behaviour

Content getting loaded as expected with no JavaScript-Errors

#### Other relevant information

As mentioned the error occures not everytime I reload the page.
It looks like there is an async problem behind this error.
I think, the token "list_end" sometimes getting added milliseconds to slow before antoher function makes use of it.

Possibly related to https://github.com/docsifyjs/docsify/issues/970 -> Getting same issues on top.

JavaScript delivered locally. (No difference when loading via CDN)

- [x ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 12.14.1
- npm/yarn version: npm 6.13.4
- Browser version: Google Chrome 79.0.3945.130
- Docsify version: latest
- Docsify plugins: search -> latest

**Comment by anikethsaha** [comment]
can you share a reproducible repo! maybe a sandbox. hard to debug this way

**Comment by Acconitum** [comment]
Hi anikethsaha

I've created a repo for you:

https://github.com/Acconitum/docsify-testrepo

**Comment by anikethsaha** [comment]
> Hi anikethsaha
> 
> I've created a repo for you:
> 
> https://github.com/Acconitum/docsify-testrepo

Thanks a lot . I will check this soon

**Comment by anikethsaha** [comment]
@Acconitum I checked. everything is working fine. I reloaded several times , didnt get any error in console.

**Comment by Acconitum** [comment]
@anikethsaha I did some tests on different machines and I where able to reproduce the error. on every instance.
 
As I mentioned the error does not trigger every time. Would you mind to add some more inclusions and test again? 

I'm sorry that I can't give yu more information. The error follows no special rule to reproduce. It appears very radomly.

**Comment by anikethsaha** [comment]
ok. I will do some test if I get some time. 👍
