### ISSUE TITLE
sidebar active class and expand don't work as expect when use "space" in markdown filename

### ISSUE THREAD

**Issue by csu-feizao** [docsifyjs/docsify#1032]
#### Steps to reproduce
1. create an markdown file and use `test sidebar.md` as it's name
2. make sure this markdown file has some content so that can generate some item in sidebar
3. open the url `/#/test%20sidebar`
4. click the sidebar item, and you will see sometimes the item doesn't has `active` class
5. create more markdown file, and set `loadSidebar` to use custom sidebar
6. config `subMaxLevel`
7. click the sidebar item, and you will find out that the sidebar item can't be expanded

#### What is current behaviour
1. sidebar item doesn't has `active` class when click
2. sidebar item doesn't been expanded when click

#### What is the expected behaviour
1. sidebar item has `active` class when click
2. sidebar item will be expanded when click

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OS 10.13.6 (17G65)
- Node.js version: N/A
- npm/yarn version: N/A (use index.html)
- Browser version: Chrome 79.0.3945.130
- Docsify version: unpkg latest
- Docsify plugins: N/A

**Comment by anikethsaha** [comment]
Can you share a reproducible repo?  

> create an markdown file and use `test sidebar.md` as it's name

Just a note that it is never recommended to use a space in a markdown file name. Use `-` instead of space.

**Comment by csu-feizao** [comment]
> Can you share a reproducible repo? having a repo makes things quicker 👍
> 
> > create an markdown file and use `test sidebar.md` as it's name
> 
> Just a note that it is never recommended to use a space in a markdown file name. Use `-` instead of space.

hi, [this is the repo](https://github.com/csu-feizao/docsifyjs-demo), sorry for reply so late

**Comment by anikethsaha** [comment]
Thanks I will take a look . 
Feel free to investigate and submit a fix if its a bug to make the process faster. cause I think i cant investigate it any time soon.

**Comment by anikethsaha** [comment]
as per the repo you shared, I could get the hightlighted sidebar links for activeBug page
and I can confirm with the expand bug , its a bug

**Comment by enzy** [comment]
PR provided
