### ISSUE TITLE
 Is it possible to add a user permission system for the company's internal document library

### ISSUE THREAD

**Issue by WangShuXian6** [docsifyjs/docsify#1034]
>想用 docsify 作为公司知识库来使用，请求增加用户权限系统，或者简单的验证也可以。

>I want to use docsify as the company's knowledge base, can it add a user permission system, or simple verification?

>For example, add an optional authentication API option that accepts a username and password and returns true or false. If the server returns true, the page can render and load the makedown file.

**Comment by anikethsaha** [comment]
Please translate

**Comment by anikethsaha** [comment]
Currently, it's not possible from the core. 

try creating a plugin but it won't be appropriate as plugins don't have access to the request method from the core and without it, it's not really a permission system.
