### ISSUE TITLE
support attachments downloading

### ISSUE THREAD

**Issue by cygnusyang** [docsifyjs/docsify#1041]
## Feature request

Is it possible that support attachments downloading?

#### What problem does this feature solve?

If docsify can support attachments downloading, we can add a link in the markdown. The user can download them from the markdown documents. It is more convenient. 

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

Sorry, I don't know.

#### Are you willing to work on this yourself?

No. I am not familiar with JS and Web skills. Sorry.

**Comment by anikethsaha** [comment]
I am working on a similar plugin. Will open source it and add here the link once its done !!

**Comment by anikethsaha** [comment]
https://www.npmjs.com/package/docsify-print
