### ISSUE TITLE
Pagination documentation incorrect.

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1042]
The Pagination section of the documentation references "a plugin to make it easy to join up codefund". https://docsify.js.org/#/plugins

**Comment by anikethsaha** [comment]
i didnt get your issue. please explain

**Comment by joetidee** [comment]
Well, shouldn't a section called Pagination refer to pagination, rather than another plugin?

**Comment by anikethsaha** [comment]
ohh i see, just need a header with codefund name below it
