### ISSUE TITLE
A way to prevent links from breaking...

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1044]
####  Feature request
When renaming `.md` files and moving pages around, the link break. Would be good to have a central dictionary of links with UUID and that UUID is used in the pages directly. When docsify builds the pages, it can search the link dictionary and replace the UUID's in the pages with the actual link detail and auto-generate the relative/root path.

**For example:**
```
const links = {
  '345873n45dgfg56': {
    linkText: 'Click here to see something',
    isExternal: false,
  },
  'dghnvtcy7tctc5dgw': {
    linkText: 'See more on Google',
    isExternal: true,
    url: 'http://www.google.com',
  }
};
```

#### What problem does this feature solve?
Prevent links from breaking and will improve the reliability of updating the documentation.

#### What does the proposed API look like?
N/A

#### How should this be implemented in your opinion?
Maintain the links centrally, then update them link placeholders in the pages when the application builds.

#### Are you willing to work on this yourself?
Potentially.

**Comment by anikethsaha** [comment]
what I understood from your proposal is whenever we make changes with  the `.md` files like moving or renaming, have some kind of mapping for it so that in future we will redirect the links to the new location ! right ?

Well, this will have benefits but I am curious about the implementation. You need some kind of storage that will have this metadata about the changes and it should be generated in runtime, store somewhere statefully and need to be accessed in runtime. As of now, docsify doesnt support building and output static files. Everything is at runtime just the source is static.

Would like to hear your solution for implementing this !

**Comment by joetidee** [comment]
Have `links.json` to contain:

```
const links = {
  '345873n45dgfg56': {
    linkText: 'Click here to see something',
    isExternal: false,
  },
  'dghnvtcy7tctc5dgw': {
    linkText: 'See more on Google',
    isExternal: true,
    url: 'http://www.google.com',
  }
};
```

In the documentation markdown file `some-doc.md`, add the reference:
```
# Some header

[link:345873n45dgfg56]
```

**Comment by anikethsaha** [comment]
> Have `links.json` to contain:
> 
> ```
> const links = {
>   '345873n45dgfg56': {
>     linkText: 'Click here to see something',
>     isExternal: false,
>   },
>   'dghnvtcy7tctc5dgw': {
>     linkText: 'See more on Google',
>     isExternal: true,
>     url: 'http://www.google.com',
>   }
> };
> ```
> 
> In the documentation markdown file `some-doc.md`, add the reference:
> 
> ```
> # Some header
> 
> [link:345873n45dgfg56]
> ```

Actually , this may cause some perf issues as it requires addition IO on FS (I am assuming you would store the `.json` file with your assets folder. ? )!


Also, Can you describe the steps that  will take place in it. for example 
I changed `post1.md`  --> `post2.md`

can you mention the steps involve!

**Comment by joetidee** [comment]
If you were to rename `post1.md` to `post2.md` then you would have to update `links.json`. 
If you simply moved `post1.md` to `/another-folder/post2.md` then no need to update `links.json`.

**Comment by anikethsaha** [comment]
> If you were to rename post1.md to post2.md then you would have to update links.json.

I would have to update it manually ?

> If you simply moved post1.md to /another-folder/post1.md then no need to update links.json.

Why not ?

**Comment by joetidee** [comment]
> I would have to update it manually ?

Yes

> If you simply moved post1.md to /another-folder/post1.md then no need to update links.json.

Because `links.json` would have the path to the link within `post1.md`.

**Comment by joetidee** [comment]
In my example above, 
```
# Some header

[link:345873n45dgfg56]
```

is in `post1.md`.

**Comment by anikethsaha** [comment]
> > I would have to update it manually ?
> 
> Yes

But if I am doing it manually, cant we simply change the link in the source (`.md`) itself ?

**Comment by joetidee** [comment]
What if I have 6 pages linking to it? I would have to remember to update the links in those 6 pages.

**Comment by anikethsaha** [comment]
> What if I have 6 pages linking to it? I would have to remember to update the links in those 6 pages.

**For these cases I would suggest using the `alias` config**


if it is not in the scope of runtime. I wouldnt implement this in the core as if does increase the perf issues. 
cause currently docsify does a lot while reading a source page which sometime leads to slow loading (if the page has a lot of embeds and other plugins working in it). It wouldnt make sense to do more work in this amount of time. 


Can you please explain more like how are you planning to achieve it ? may be it can be added in the cli.

**Comment by joetidee** [comment]
```
const links = {
  '345873n45dgfg56': {
    linkText: 'Click here to see the doc.',
    isExternal: false,
    path: 'some/doc/folder/doc.md',
  },
  'dghnvtcy7tctc5dgw': {
    linkText: 'A file with a link in it',
    isExternal: false,
    path: 'another/place/article.md',
  }
};
```

1) Rename the file `doc.md` to `doc2.md`:
Update the path entry in `links.json`.

2) Move file `doc.md` from `some/doc/folder/` to `some/`:
Update the path entry in `links.json`.

**Comment by joetidee** [comment]
> For these cases I would suggest using the alias config

Ah, ok, didn't know about that.

**Comment by anikethsaha** [comment]
> ```
> const links = {
>   '345873n45dgfg56': {
>     linkText: 'Click here to see the doc.',
>     isExternal: false,
>     path: 'some/doc/folder/doc.md',
>   },
>   'dghnvtcy7tctc5dgw': {
>     linkText: 'A file with a link in it',
>     isExternal: false,
>     path: 'another/place/article.md',
>   }
> };
> ```
> 
> 1. Rename the file `doc.md` to `doc2.md`:
>    Update the path entry in `links.json`.
> 2. Move file `doc.md` from `some/doc/folder/` to `some/`:
>    Update the path entry in `links.json`.

And how it would work from core ? cause this is how the core fetching works

you have `post1.md` 
and a `a` link which has `href` to this link
and when docsify sees this with `.md` in the end, it parses the `.md` and converts it into `html`
so even if you change it to `link.json` you will have to change the name of the file with this UUID or else have to use `alias` ....SO I am -1 for this. 
Sorry.
Please suggest a better solution if you want this feature to get alone.
Thanks for your time 💯

**Comment by joetidee** [comment]
So, is there any way for docsify to detect a change in the location or naming of an `.md` file and warn in the console if there are links still pointing to the old reference?

**Comment by anikethsaha** [comment]
> So, is there any way for docsify to detect a change in the location or naming of an .md file and warn in the console if there are links still pointing to the old reference?

No, docsify doesnt know about your source file unless they are request upon. If it finds it , it will render it else it will throw 404

**Comment by joetidee** [comment]
Tried using alias, but now my links in the address bar look like this:

`http://localhost:3000/#/link-dfgb4588g45g8df`

:(

**Comment by anikethsaha** [comment]
yes....you done have to use ugly UUID....but now you can use this link and you dont have to change every link when you renamed or moved the md
