### ISSUE TITLE
A cross-origin url cannot be redirected to if "externalLinkTarget" is set to "_self" and "routerMode" is set to "history"

### ISSUE THREAD

**Issue by ustc-zzzz** [docsifyjs/docsify#1046]
#### Steps to reproduce

Set the options firstly:

```javascript
window['$docsify'] = {
  routerMode: 'history',
  externalLinkTarget: '_self'
}
```

Then write a link whose url is from another domain:

```markdown
Example: [example.com](https://example.com/)
```

#### What is current behaviour

If our domain were `docsify.now.sh`, it would do nothing and pop an error on the debug console:

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://example.com/' cannot be created in a document with origin 'https://docsify.now.sh' and URL 'https://docsify.now.sh/'.
    at https://unpkg.com/docsify@4.10.2/lib/docsify.min.js:1:61459
```

The corresponding source code is [here](https://github.com/docsifyjs/docsify/blob/v4.10.2/src/core/router/history/html5.js#L30).

#### What is the expected behaviour

Redirect to `https://example.com/` normally.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: `Linux ZZZ-PC-4 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`
- Node.js version: `v12.14.0`
- npm/yarn version: `6.13.4`
- Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36`
- Docsify version: `4.10.2`
- Docsify plugins: `None`

**Comment by ustc-zzzz** [comment]
Also available on Firefox Browser (`Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`):

```
SecurityError: The operation is insecure. docsify.min.js:formatted:1
    onchange docsify.min.js:2341
```

**Comment by Koooooo-7** [comment]
excuse me. 
I can't reproduce ur bug. 
can u give me a simple demo plz. 

FYR:
```
Docsify version : 4.10.2
OS: windows10
Browser: Chrome. 
Settings as u posted above
```

**Comment by ustc-zzzz** [comment]
@Koooooo-7 Sorry. I forgot to report that `routerMode` should be set to `history`.
I have made a demo which is available on <https://ustc-zzzz.github.io/docsify-issue-1046-demo/>.

**Comment by Koooooo-7** [comment]
thx a lot.
I checked it and there is a `same-origin policy` issue about the ` history.pushState()` .
[this documentation](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) mentions something about the url param.
> The new URL must be of the same origin as the current URL; otherwise, pushState() will throw an exception. 

@anikethsaha 
tbh, I m not sure if there is a bug or security thing.
I plan to have a simple link checking before the `history.pushState()`,[html5.js](https://github.com/docsifyjs/docsify/blob/v4.10.2/src/core/router/history/html5.js#L30).
if the urls were `cross-origin`, I just  use `window.open(url,'_self')` instead.
what's ur oppion?

**Comment by anikethsaha** [comment]
Thanks @Koooooo-7 for triaging this  ! 💯 

I am not so into security things that's why I can't give 100% opinion. 
But as per the docs you mentioned, it seems pretty reasonable behavior of having same origin !

> if the urls were cross-origin, I just use window.open(url,'_self') instead.

What do you think about having a separate option for this ?

**Comment by Koooooo-7** [comment]
@anikethsaha  
normally, there would have the `non cross origin` URLs and the `cross origin`, so I think it is better that there have a sign (but I don't wanna make the URL congratulations messy)  to mark the `cross origin` url, thus we don't need the URL checking. 
I don't have some good idea about the seperate option right now. 
could u show me some details about the seperate options.

**Comment by anikethsaha** [comment]
by option, I meant separate option for `window.open(url,'_self')` like if the option is `true` then we would check the url and use `window.open(url,'_self')` if required for opening. 
else it would be the same operation like the present one !

**Comment by anikethsaha** [comment]
History mode by default shows the origin issue, so bypassing (doing the workaround to show the page) by default won't be a good idea .
its kind of the web standard behavior. But still, we can have some way to tackle this !

What do you think ?

**Comment by Koooooo-7** [comment]
@anikethsaha 

> by option, I meant separate option for `window.open(url,'_self')` like if the option is `true` then we would check the url and use `window.open(url,'_self')` if required for opening.

yep, where do u wanna set the option? As an  independent configuration or the configuration with the URL?
> else it would be the same operation like the present one !

yep, we do keep the present one. 


As a independent option, it seems like this:
```js
if ( optionFlag&& isCrossOriginUrl (url)){
    windows. open(url, '_self')
}
windows. history. pushState(... )
```
and, how about setting a sign/flag with the URL? only if we find the flag, we use  `windows. open` instead of checking all the URLs. 
such as `Example: [example.com](https://example.com/   :crossurl=true)`

**Comment by anikethsaha** [comment]
> `Example: [example.com](https://example.com/   ':crossurl=true')`

this is much better. Lets do this one

**Comment by BeamerIsHere** [comment]
@Koooooo-7 @anikethsaha 
I've got the same issue with external links. 

I have a _coverpage file and added some external links to it and also enabled history routing mode. Getting the same error.
Since I have the links in the _coverpage file( not in MD), I'm confused by the solutions above.

I'll add my coverpage and index.html file here.

Thanks in advance!

Getting this error 

----
Index page 



<!DOCTYPE html>

<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify/themes/vue.css">
    
    
    
    
    
    <style>
        .sidebar::-webkit-scrollbar {
            width: 10px;
        }/* ... */
        .center {
            margin-left: auto;
            margin-right: auto;
        }
        img.cover {
            width: 100;
            height: 100;
        }
    </style>
    
  </head>
  <body>
    <div id="app"></div>
  
    <script>
      
      window.$docsify = {
        //...
        loadSidebar: true,
        routerMode: 'history',
        externalLinkTarget: '_self',
       
        alias: {
          '/.*/_sidebar.md': '/_sidebar.md',
        },
        subMaxLevel: 3,
        relativePath: false,
        //homepage: 'docs-home.md',
        name: '',
        coverpage: true,
        onlyCover: true,
        // create custom headings for Flexible Alerts
        'flexible-alerts': {
          note: {
            label: "Note"
          },
          tip: {
            label: "Tip"
          },
          warning: {
            label: "Caution"
          },
          danger: {
            label: "Attention"
          },
          style: 'callout'
        },  
       
        plugins: [
      function(hook, vm) {
      hook.beforeEach(function(html) {
        var url =
          'https://somelink.com/'.concat(vm.route.file,"&version=GBmaster&_a=contents") ;
        var editHtml = '[Edit this page](' + url + ')\n';
        return (
          html +
          '\n----\n' +
          editHtml 
        );
      });
    }
    ]
    
      }
    </script>
    <script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
    

    
    <script src="//unpkg.com/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js"></script>
    
    <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
    
    <script src="https://unpkg.com/docsify-copy-code@2"></script> -->
    
    <script src="https://unpkg.com/docsify-plugin-flexible-alerts"></script>
    
    <script src="//unpkg.com/mermaid/dist/mermaid.js"></script>
    <script src="//unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js"> 
    <script>mermaid.initialize({ startOnLoad: true });</script>

  </body>
</html>


----
Coverpage 

![logo](docs/.attachments/icon_logo.svg ':size=150px')


<h1>Data Tools Landing Page</h1>
<div class="center" style="text-align: justify; max-width:600px">
<b>Welcome to the Data Tools Landing Page for Advanced Solutions.</b> Here you will find access to and documentation for (almost) all the data management, analytics, modeling and visualization tools supported by Advanced Solutions.
Please reach out on <a href=https://somelink.com/0e4-7765-4ce9-ba7a-2b01ad36e6dd&tenantId=db64ac37-9cb0-48e0-adbd-125fff4b1452>Teams</a> if you have any questions or concerns.
</div>
&nbsp;
&nbsp;
<table class="center" class="cover_table">
  <tr> 
    <td align="right">
      <h3>Analytics</h3>
    </td>
    <td align="center" style="padding-left:40px">
      <a href="https://somelink.com/">
      <img width="60" src="docs/.attachments/landing-icon-rsp.png">
      </a>
    </td>
    <td align="left" style="padding-right:40px">
      <b>RStudio Server</b><br/>
      <a href="https://somelink.com/">Login</a><br />
      <a href="docs/r/rsconnect">Docs</a>
    </td>

  </tr>
  <tr> 
    <td align="right">
      <h3>Warehousing</h3>
    </td>
    <td align="center" style="padding-left:40px">
      <a href="https://zv62821.east-us-2.privatelink.snowflakecomputing.com/console/login#/">
      <img width="60" height="60" src="docs/.attachments/landing-icon-snowflake.png">
      </a>
    </td>                                                                                    
    <td align="left" style="padding-right:40px">
      <b>Snowflake</b><br />
      <a href="https://somelink.com/">Login</a><br />
      <a href="docs/big-data/snowflake-guide">Docs</a>
    </td>
  </tr>
  <tr> 
    <td align="right" >
      <h3>Visualization</h3>
    </td>
    <td align="center" style="padding-left:40px">
      <img width="60" height="60" src="docs/.attachments/landing-icon-spotfire.png">
      </a>
    </td>
    <td align="left" style="padding-right:40px">
      <b>Spotfire</b><br />
      <a href="https://somelink.com/">Dev</a><code>|</code><a href="https://somelink.com/">Test</a><code>|</code><a href="https://somelink.com/m-login/guidehouselogin.html?targetUrl=%2Fspotfire%2F">UAT</a><code>|</code><a href="https://analytics.navigant.com/spotfire/resources/custom-login/guidehouselogin.html?targetUrl=%2Fspotfire%2Fwp%2Fanalysis%3Ffile%3D%26waid%3DR5k2cF8LFUyF6-hgGJ_HU-050744b66aEzzg%26wavid%3D0">Prod</a><br />
      <a href="docs/visualisation/spotfire-dashboard-setup">Docs</a>
    </td>
    <td align="center" >
      <a href="https://somelink.com/">
      <img height="60" src="docs/.attachments/landing-icon-rsc.png">
      </a>
    </td>
    <td align="left" style="padding-right:40px">
      <b>RStudio Connect</b><br />
      <a href="https://somelink.com/">Login</a><br />
      <a href="docs/r/rsconnect">Docs</a>
    </td>
  </tr>
  <tr> 
    <td align="right">
      <h3>Collaboration</h3>
    </td>
    <td align="center" style="padding-left:40px">
      <a href="https://tfs.insidenci.com/">
      <img width="60" height="60" src="docs/.attachments/landing-icon-ado.png">
      </a>
    </td>             
    <td align="left" style="padding-right:40px">
      <b>Azure DevOps</b><br />
      <a href="https://tfs.insidenci.com/">Login</a><br />
      <a href="docs/version-control/git-version-control">Docs</a>
    </td>
    <td align="center">
      <a href="https://somelink.com/ersations?groupId=87a5a0e4-7765-4ce9-ba7a-2b01ad36e6dd&tenantId=db64ac37-9cb0-48e0-adbd-125fff4b1452">
      <img width="60" height="60" src="docs/.attachments/landing-icon-teams.png">
      </a>
    </td>             
    <td align="left">
      <b>MS Teams</b><br />
      <a href="https://somelink.com/dd&tenantId=db64ac37-9cb0-48e0-adbd-125fff4b1452">Login</a><br />
      <a href="docs/collaboration-home">Docs</a>
    </td>
  </tr>
</table>
&nbsp;
&nbsp;
&nbsp;
&nbsp;


[Go to `TechDocs`](docs-home.md)

![color](#f0f0f0)



"Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://tfs.insidenci.com/Energy-=contents' cannot be created in a document with origin 'http://127.0.0.1:5500' and URL 'http://127.0.0.1:5500/docs-home'."

**Comment by Koooooo-7** [comment]
@BeamerIsHere  thx for ur report!
Could you please open a new issue to let us check it in process ? somehow, I can't open ur sites to check the configurations, so I guess u need provide ur repo also in case of the site is unavailable.
