### ISSUE TITLE
!bug My website doesnt work on mobile.

### ISSUE THREAD

**Issue by phuongbag** [docsifyjs/docsify#1047]
#### Steps to reproduce

Overload with _sidebar

#### What is current behaviour

Unable to use on the mobile. Using format .md

#### What is the expected behaviour

Cant use on the mobile.
eg: neetvn.net

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: lastedt (node 13.9.0)
- npm/yarn version: lastest
- Browser version: N/a
- Docsify version: lastest
- Docsify plugins: lastest

**Comment by anikethsaha** [comment]
Please give more detials and try to search for the breakpoint as this is responsive issue which is hard to reproduce.

**Comment by phuongbag** [comment]
The bug came from Tabs plugins? for some reason when disable it it didnt work in first time.
