### ISSUE TITLE
How to parse markdown links?

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1053]
####  Feature request
Just trying to figure out how to parse and override markdown links. In the docs it states that you can capture the link using this:

```
markdown: {
  renderer: {
    link: function(link) {
      // do something with link 
     }
  }
},
```

I would have expected the link to be an object, with `title`, `href` and `text`. But it is just a string that correlates to the href. How do I access all the link properties in one single renderer function?

**Comment by anikethsaha** [comment]
thats not in the scope of a markdown parser to parse a link. use https://www.npmjs.com/package/url-parse to parse it

**Comment by anikethsaha** [comment]
hope that helps.
Feel free to leave feedback if required

**Comment by joetidee** [comment]
Ok, found out - it is:

```
markdown: {
  renderer: {
    link: function(href, title, text) {
      // do something with link 
     }
  }
},
```

**Comment by anikethsaha** [comment]
> Ok, found out - it is:
> 
> ```
> markdown: {
>   renderer: {
>     link: function(href, title, text) {
>       // do something with link 
>      }
>   }
> },
> ```

Thanks. I didnt know about that 🎉
