### ISSUE TITLE
Why does the url need 'index'?

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1055]
If you navigate to a url without 'index' on the end, it takes the person to a 404 page. It would make the url more friendly if it didn't need to have 'index' on the end.

For example:
`/#/web/` instead of `/#/web/index`

**Comment by anikethsaha** [comment]
seems similar to https://github.com/docsifyjs/docsify/issues/1018 !

**Comment by anikethsaha** [comment]
having `/#/web/` will lead to 404 as well. check #1018 .
having `/index` tells docsify to render the homepage to that folder instead of showing the 404. 

> If you navigate to a url without 'index' on the end, it takes the person to a 404 page

not sure if this is true always

**Comment by joetidee** [comment]
Yes, same as 1018.
