### ISSUE TITLE
uncaught reference in 4.11

### ISSUE THREAD

**Issue by akhmerov** [docsifyjs/docsify#1057]
## Bug Report

When using the freshly released version 4.11 I observe that the library doesn't load and the problem seems to be on the docsify side.

![image](https://user-images.githubusercontent.com/2069677/76211724-2ac3f580-6207-11ea-9ee3-51d8c498ac67.png)

#### Steps to reproduce

Use index.html like [this one](https://github.com/virtualscienceforum/virtualscienceforum/blob/58f7922339c4799bcc7dc0dd1885f6dca0db45db/index.html)

#### What is current behaviour

docsify doesn't load

#### What is the expected behaviour

docsify loads :)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 
- Browser version: chrome Version 80.0.3987.132 (Official Build) (64-bit)
- Docsify version: 4.11
- Docsify plugins: docsify-katex (but the problem appears also without it).

**Comment by anikethsaha** [comment]
ohh shoot !
Please use `4.10.2`
I will fix it now . Something wrong with rollup config

**Comment by akhmerov** [comment]
Yeah, I pinned 4.10.2, sure, no problem.

**Comment by vardaro** [comment]
Wow you guys are fast!

**Comment by anikethsaha** [comment]
if anyone can help with this rollup issue .

![image](https://user-images.githubusercontent.com/26347874/76212634-ecdac780-622e-11ea-8d40-b59b562eca53.png)

Thanks

**Comment by slikts** [comment]
There shouldn't be untested releases; the default setup doesn't pin the version, so every site that uses it is now broken. It's also why the default template should include a fallback link.

Pinned location: `//unpkg.com/docsify@4.10.2/lib/docsify.min.js`

**Comment by anikethsaha** [comment]
released `v4.11.1`
Please confirm if there are any issues or not

**Comment by slikts** [comment]
`v4.11.1` appears to work, thanks for the fix, but please add automated testing to the process.

**Comment by anikethsaha** [comment]
> `v4.11.1` appears to work, thanks for the fix, but please add automated testing to the process.

We do have some e2e tests but they are not so strong and not many! 
I am not so into testing so I couldn't able to write strong tests. 
So I request community to help with strong tests!

**Comment by anikethsaha** [comment]
Closing as its been fix.
Please open new issue if any other issue is there

**Comment by jeffin143** [comment]
> > `v4.11.1` appears to work, thanks for the fix, but please add automated testing to the process.
> 
> We do have some e2e tests but they are not so strong and not many!
> I am not so into testing so I couldn't able to write strong tests.
> So I request community to help with strong tests!

I will be there from next weekend to help :)

Great work anyways

**Comment by anikethsaha** [comment]
> > > `v4.11.1` appears to work, thanks for the fix, but please add automated testing to the process.
> > 
> > 
> > We do have some e2e tests but they are not so strong and not many!
> > I am not so into testing so I couldn't able to write strong tests.
> > So I request community to help with strong tests!
> 
> I will be there from next weekend to help :)
> 
> Great work anyways

🎉 

Thanks

**Comment by trusktr** [comment]
Just FYI the new unit tests in https://github.com/docsifyjs/docsify/pull/1189 shoudl catch any instance of the script not loading.

**Comment by anikethsaha** [comment]
will it catch while running in development mode ? cause this issue occurred after running the build and ignoring the warning of rollup.

**Comment by trusktr** [comment]
Oh wait, actually the `test` script currently tests whatever build you last made. I will update `test` to test specifically the prod build.

**Comment by anikethsaha** [comment]
> Oh wait, actually the test script currently tests whatever build you last made. I will update test to test specifically the prod build.

Post build tests ? worth it though, may be in a separate PR ?

**Comment by trusktr** [comment]
Oh wait, I take it back, PR #1189 was in fact testing that the production build script was loading properly as I originally though in my comment above. I added more comments into the pull request explaining it.
