### ISSUE TITLE
How to automatically render <title>?

### ISSUE THREAD

**Issue by mzaini30** [docsifyjs/docsify#1059]
#### What is current behaviour

Page title isn't change if I change page

#### What is the expected behaviour

If in markdown:

```markdown
# my post

......
```

Then, generate `<title>my post</title>`

#### Other relevant information

- Your OS: android 9
- Node.js version: 13.0.0
- npm/yarn version: 6.12.0
- Browser version: via
- Docsify version: 4.4.0
- Docsify plugins:

**Comment by anikethsaha** [comment]
Please fill the issue template.
