### ISSUE TITLE
Background color option of cover page is broken in 4.11.1

### ISSUE THREAD

**Issue by xuqingkuang** [docsifyjs/docsify#1060]
## Bug Report
In the doc - https://docsify.js.org/#/cover?id=custom-background

Define a `![color](#f0f0f0)` can custom the background color.

But it's broken in the recent version 4.11.1.

#### Steps to reproduce
1. Here's an online site that using docsify: http://hippyjs.org (Sorry the page is written in Chinese) -- the site is using recommend reference method from unpkg.
2. As you can see, there's `color` with a broken image link.
3. And the links with `section.cover .cover-main>p:last-child a` from vue theme is working incorrectly. 
4. It's the color option - https://github.com/Tencent/Hippy/blame/master/docs/_coverpage.md#L15
5. If you remove the color line from inspect, the layout will return ok. 

#### What is current behaviour

1. `section.cover .cover-main>p:last-child a` links from vue theme working incorrectly.
2. the color option is displaying on the page.

#### What is the expected behaviour

1. the link return ok.
2. the color option will not render.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
Its a bug!
Feel free to investigate and send PR

**Comment by anikethsaha** [comment]
In the meantime , you can use `v4.10.2`

**Comment by anikethsaha** [comment]
Fix is coming soon !

**Comment by anikethsaha** [comment]
fixed at [`4.11.2`](https://www.jsdelivr.com/package/npm/docsify?version=4.11.2)
