### ISSUE TITLE
Disqus error?

### ISSUE THREAD

**Issue by mzaini30** [docsifyjs/docsify#1063]
![](https://i.ibb.co/9bvgZYj/Screenshot-2020-03-11-18-10-15-74-a87fd7db6caa850b517aa6fa9d2fcd0e.png)

**Comment by anikethsaha** [comment]
seems like disqus changed their API. 
need to investigate

**Comment by mzaini30** [comment]
I use disqus with code from docsify site. Then, my friend comment in my blogpost. After that, I get email and link inside it. I click this link, then I get <http://localhost:3000/-/skeleton/pug#comment-4828429963>. But, link in my blogpost is <https://mzaini30.com/#/skeleton/pug>
