### ISSUE TITLE
使用docsify自动生成侧边栏标题，但如果我的标题是以数字开头，侧边栏标题无法自动跳转

### ISSUE THREAD

**Issue by floatLig** [docsifyjs/docsify#1066]
比如，我的Markdown写了“**# 1. 大标题**”，这是一个一级标题，侧边栏标题的超链接自动生成“**id=1-大标题**”，但是这无法跳转到文章对应位置。

我该怎么解决这个问题？

**Comment by anikethsaha** [comment]
Please translate it to english

**Comment by Koooooo-7** [comment]
Please fill the issue template. 

As per ur information, it is no reproducible now. 
it is better to have a simple demo for us to investigate.
