### ISSUE TITLE
Problem about <title> of the web page.

### ISSUE THREAD

**Issue by Erimus-Koo** [docsifyjs/docsify#1068]
## Bug Report
This is a question, and I'm a rookie user.

#### Steps to reproduce
- In the `index.html`, wrote `<title>demo</title>`. 
- And the markdown file is named `doc.md`.

#### What is current behaviour
- If I have a `_sidebar.md`, the <title> will display `doc - demo`.
- If I set `loadSidebar: false`, the <title> will display `demo`, not `doc`. When I shared many pages, they all named `demo`, cannot be distinguished.

#### What is the expected behaviour
1. I wish the <title> can  display `doc`, while `loadSidebar: false`.
2. Can there be an option, display <title> as `doc`, without ` - demo`. Even if I wrote nothing in `<title></title>` of the `index.html`, it will still display `doc - `.

#### Other relevant information
```
    window.$docsify = {
        name: 'demo',
        repo: '',
        maxLevel: 6, 
        auto2top: true, 
        homepage: 'HOME.md',  

        // ========== sidebar
        loadSidebar: false,
        subMaxLevel: 3,
        logo: 'icon.png',
        autoHeader: true,

        // ========== search
        search: {
            noData: {
                '/': 'No results!'
            },
            paths: 'auto',
            placeholder: {
                '/': 'Search'
            }
        },

        formatUpdated: '{YYYY}-{MM}-{DD} {HH}:{mm}',
    }
```

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
> Your OS:
> 
> Node.js version:
> 
> npm/yarn version:
> 
> Browser version:
> 
> Docsify version:
> 
> Docsify plugins:

Please fill this. 
also, try with both docsify version `4.11.x` and `4.10.2` and check if it exists in both ?

**Comment by Erimus-Koo** [comment]
@anikethsaha 
Your OS: win10 1909

Node.js version: 10.12.0

npm/yarn version: 6.4.1

Browser version: chrome Version 80.0.3987.132 (Official Build) (64-bit)

Docsify version: 4.10.2 and 4.11.2 I've tried both version, its same, exists.

Docsify plugins: I've remove all plugins, its same.

**Comment by Erimus-Koo** [comment]
If the title show the name of doc, or the first #header in the document, it will be help.  

I can understood that if I have a single page, I can just write the title manual.

But in my case, I've wrote the name of `sidebar.md` as a key in local storage, if user have that key, they can get the correct `sidebar.md` file. I shared one page to them, and they can see the current page, and can use sidebar to guide to other docs. And if they do not have the key, will see the page what I shared only.

**Comment by anikethsaha** [comment]
it looks like it has been missed or left intentionally. Need to have a look. Feel free to investigate and submit the fix

**Comment by Erimus-Koo** [comment]
@anikethsaha thanks.

I've search in the source code, maybe cause in this part, line 592 v4.11.2:
```
    if (autoTitle) {
      $.title = target
        ? target.title || ((target.innerText) + " - " + title)
        : title;
    }
```

If no specific sidebar, the target is undefined. 

I hope "display the doc name/first header as page title" can be a feature.

In my case, the sidebar shows only the headers of the doc, it's just I need. I hope this part could be keep.

**Comment by anikethsaha** [comment]
THanks for taking time !

> I hope "display the doc name/first header as page title" can be a feature.

This needs a discussion as this might conflict with the homepage title which needs to be the title passed (eg `demo` for your case) otherwise it would be `demo - demo`.
