### ISSUE TITLE
Problem about <strong> wrap in <em>

### ISSUE THREAD

**Issue by Erimus-Koo** [docsifyjs/docsify#1071]
Yep, its me again.

This is a special case, let me show you a **sample**:

```
The evil of men is that they like to be teachers of others

The evil of men is that they *like to be **teacher**s of* others

The evil of men is that they *like to be **teacher**s of oth*ers

The evil of men is that they **like to be *teacher*s of** others

The evil of men is that they **like to be *teacher*s of oth**ers
```

#### Github
This 5 sentences looks in **github**, looks like below.

> The evil of men is that they like to be teachers of others
>
> The evil of men is that they *like to be **teacher**s of* others
>
> The evil of men is that they *like to be **teacher**s of oth*ers
>
> The evil of men is that they **like to be *teacher*s of** others
>
> The evil of men is that they **like to be *teacher*s of oth**ers

#### Typora
In **typora** (an marddown editor), looks like (I've repalce the Italic with underline):
![image](https://user-images.githubusercontent.com/17139670/76640180-70c3e500-658a-11ea-87e5-51a725b8cb93.png)

#### Docsify
![image](https://user-images.githubusercontent.com/17139670/76640284-9e109300-658a-11ea-95e6-b01438978d60.png)

### Problem

The 3rd line looks different. That should be a html parse problem.   
It appears with 2 condition:
1. Outside is em/Italic style, inside is strong/bold style.
2. No space follows the `*` at the end of em/italic style.   
    Line 2 has a `space` after last `*` , it looks good.  
    In English, this would not be a problem, because of the `*` at a word's end mostly, and English words always gap with `space`. But in many east Asia languages, there's no space.

I do not sure is that a markdown rule, or something went wrong.
Maybe you can have a look about this.

**Comment by anikethsaha** [comment]
it should have been similar to the github one. `marked.js` does parse it correctly so its a bug from ourside.

**Comment by Koooooo-7** [comment]
> it should have been similar to the github one. `marked.js` does parse it correctly so its a bug from ourside.

nah, I used `marked.js` [demo page](https://marked.js.org/demo/?text=The%20evil%20of%20men%20is%20that%20they%20*like%20to%20be%20**teacher**s%20of%20oth*ers%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master), they render
```md
The evil of men is that they *like to be **teacher**s of oth*ers
```
to 
<p>The evil of men is that they <em>like to be *</em>teacher*<em>s of oth</em>ers</p>

----- 
Besides that.
those cases are interesting:

```md
**a`b**c`d**
The evil of men is that **they *like to be **teacher**s of oth*ers**
```
### github
 - **a`b**c`d**
- The evil of men is that **they *like to be **teacher**s of oth*ers**

### Marked.js(master) && Typora(v  0.9.75) 
 - <p><strong>a`b</strong>c`d**</p>
 -  <p>The evil of men is that <strong>they <em>like to be *</em>teacher</strong>s of oth<em>ers*</em>  </p>

   (  I picked the [**a`b**c`d** case from marked's issue](https://github.com/markedjs/marked/issues/189) )


I think they haven't solve those issues yet. or I guess there are different synax standards about those cases.

**Comment by anikethsaha** [comment]
Opps my bad , i tested with wrong example !

`***asd***`

as I thought the behavior will be the same even having space in between
thanks a lot, @Koooooo-7 , 

***its an issue with upstream (`markedjs`)***
