### ISSUE TITLE
h2 titile with `## 1. What We Mean by “Spring”` report #1-what-we-mean-by-spring' is not a valid selector

### ISSUE THREAD

**Issue by degbug** [docsifyjs/docsify#1075]
## Bug Report
h2 titile with `## 1. What We Mean by “Spring”` report #1-what-we-mean-by-spring' is not a valid selector

#### Steps to reproduce

h2 titile with `## 1. What We Mean by “Spring”` report '#1-what-we-mean-by-spring' is not a valid selector

#### What is current behaviour

this is the error:
![image](https://user-images.githubusercontent.com/11486075/76698636-7d5a5180-66e0-11ea-8c52-053e1f3639dc.png)

#### What is the expected behaviour

the title start with number can work well
or how can configure to make is well.
thx!

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  macos catalina
- Node.js version:  v12.16.1
- npm/yarn version: 6.13.4
- Browser version: chrome 80
- Docsify version: 4.11.2
- Docsify plugins:

**Comment by anikethsaha** [comment]
generally, h2 tags should be linkable meaning that when clicked it should navigate towards it. 
having spaces in links never works correctly as when it goes to the header, it gets converted to escaped char. 
So maximum markdown renderer adds a hyphen instead of space which stops the behavior and brings consistency. 
This is the same behavior with github as well.

**Comment by degbug** [comment]
@anikethsaha 
thank you for your reply, maybe I not understand your explain. I know docsify adds a hyphen instead of space, but 
the problem is the text start with number, when I use document.querySelector('#1-what"), it report 
`#1-what` is not a valid selector。
the selector should not start with number, should start with a letter。

**Comment by anikethsaha** [comment]
github does the same 

https://github.com/anikethsaha/vsc-material-theme/tree/md-exp#1-override-theme-colors

We cant change the behavior , it will break other docs

**Comment by degbug** [comment]
@anikethsaha 
but I fall back to v4.10.2,  it's ok.  

for example, the h2 tag with text `1. first para`,  the generated id is `_1-first-para` in version 4.10.2.
but at v4.11.2  the generated id changed to `1-first-para`. the underline was removed.

if you mean, in order to make it same as github, you change the behavior in v4.11.2 ?

**Comment by anikethsaha** [comment]
Yes having `_` in front is not right.... It was changed intentionally
