### ISSUE TITLE
Does docsify transpile?

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1077]
Does Docsify transpile any Javascript in index.html for use in older browsers? The docs says it is compatible with IE11.

**Comment by anikethsaha** [comment]
I cant assure you about IE11 right now as we might have made some changes like adding some dep which may not be compatible. Can you share if you faced any issue then we can look deeper in it then and fix it !

**Comment by anikethsaha** [comment]
we have a discussion to drop the support completely in the next major version

**Comment by joetidee** [comment]
ok, IE11 aside, does it transpile the JS and if so, how does it do it?

**Comment by anikethsaha** [comment]
if you meant transpiling from some other es version to current, then it doesnt. 

can you mention your use case then I can try to help if possible !

**Comment by joetidee** [comment]
For example, if writing a plugin to go into index.html:
```
function(hook) {
      hook.afterEach(function(html) {
        var footer = [
          '<footer>',
          `<small>Last updated: ${window.$docsify.lastUpdated}</small>`,
          '</footer>'
        ].join('');
        return html + footer;
      });
    },
```
Is this going to be transpiled in any way before it hits the browser, i.e. I can't use `let` and `const` if I want full IE11 support?

**Comment by anikethsaha** [comment]
no docsify doesn't do any transpilation for es versions.
max browser out there supports `let` and  `const` but not all , so you can either not use it or else write it like that and use babel with webpack/rollup to make them compatible!

I would recommend using `var` as everything gets transpiled to `var` only at the engine of any browser so no point to have extra tooling if you are creating simple/small plugin
