### ISSUE TITLE
Embed with :type=code replacing entire page when other embeds are present

### ISSUE THREAD

**Issue by randName** [docsifyjs/docsify#1078]
## Bug Report
(potentially related to #791 and #866 or #970)

#### Steps to reproduce
Include a file as a `.html` and then as a code block, i.e.

```md
[embed](embed.html ':include')

[source](embed.html ':include :type=code :fragment=demo')
```

[raw files](https://gist.github.com/randName/9b2675aa92487228b18c81ff8bb14e1a)

[rendered version](https://bl.ocks.org/randName/raw/9b2675aa92487228b18c81ff8bb14e1a/)

Tested in Chrome, Firefox and Edge

#### What is current behaviour
The code block overwrites the page content (after a short delay).

The order of embedding does not matter, and even if the linked files are different this will happen.

If either block is removed there is no issue, and it seems unrelated to the fragment nor highlight type.

#### What is the expected behaviour
Multiple embed blocks remain visible.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 x64
- Browser version: Chrome 80.0.3987.132
- Docsify version: latest (4.11.2)
- Docsify plugins: None

**Comment by anikethsaha** [comment]
we do have a issue with multiple embedding!

I need to look in it !

Feel free to investigate and submit the fix

**Comment by kerim** [comment]
I am having a similar issue. Not with type=code, but just with multiple embeds. The entire page gets replaced with one of the embeds, until I do a browser refresh.

**Comment by sebastienbarbier** [comment]
I am having this issue with latest @4, may be roll back to a previous version might be temporary solution ? anyone know when this issue first appears ?

**Comment by madhavarshney** [comment]
I'm can confirm this as well. Are there any known workarounds?

**Comment by madhavarshney** [comment]
This bug has been fixed in the latest version of docsify with the upgrade to `marked`. The [demo linked above](https://bl.ocks.org/randName/raw/9b2675aa92487228b18c81ff8bb14e1a/#/) is also working.
