### ISSUE TITLE
How to position a 'last updated' text before pagination...

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1079]
I want to place a `Last updated: ${window.$docsify.lastUpdated}` text after the article content, but before the pagination block. I cannot do this with either the `hook.beforeEach` of `hook.afterEach` plugin method - how can I achieve this?

**Comment by anikethsaha** [comment]
try keeping the pagination plugin at the last script and use `beforeEach` and add the markdown for that. pagination plugin is using `afterEach` hook i think

**Comment by joetidee** [comment]
If I use `beforeEach`, I get: 

> Last updated: undefined

I'm guessing that `beforeEach` doesn't have access to the `window` object (?)

**Comment by anikethsaha** [comment]
try using `vm.` instead of windows. I don't remember the exact object name and its properties. Need to look there. Check the docsify object inside the vm if present.

**Comment by joetidee** [comment]
Weirdly, I can see `vm.config.lastUpdated` in the `vm` object, but when I `console.log` it, it is `undefined` !

**Comment by anikethsaha** [comment]
vm.config is from the config object of docsify
I can suggest a solution (hacky)
 you can set the `lastUpdate` manually using js in your HTML
or in `beforeEach` hook you place a placeholder something like `__lastUpdate__` and in `afterEach` you do regex and replace it with the lastUpdate property as it wont be undefined at that time.

Its more like a templating

**Comment by joetidee** [comment]
ok, I'll try this, but is there going to be an opportunity down the line to be able to append to the article without a hacky approach?

**Comment by anikethsaha** [comment]
> ok, I'll try this, but is there going to be an opportunity down the line to be able to append to the article without a hacky approach?

it depends on how other plugins are written and how they are being used. 
if you are using a pagination plugin after your plugin, it shouldn't be an issue then. 
its like a waterfall approach

**Comment by joetidee** [comment]
The hack worked.

**Comment by anikethsaha** [comment]
any reason to re-open this ?

**Comment by joetidee** [comment]
ok, it didn't quite work :(. But I'm just trying to figure out what the correct way to format sidebar content is before I post a reply because lastupdated text is appearing correctly on some pages and not on others.

**Comment by joetidee** [comment]
Do you have any guidelines on formatting sidebar content?

**Comment by anikethsaha** [comment]
I would recommend you checking the docsify's docs folder and also this https://github.com/posthtml/posthtml.org.

**Comment by joetidee** [comment]
Problem is that none of these examples have nested folders in their docs with sidebar files in each folder.

**Comment by joetidee** [comment]
Would be good just to understand what the purpose of the sidebar is - it is to navigate just what's on the page, or to navigate the whole site?

**Comment by anikethsaha** [comment]
just on the page + other pages present in the docs (by manually adding content in `_sidebar.md`)

**Comment by joetidee** [comment]
ok, on one page I am getting `lastupdated` just appearing, and other pages it works correctly - not sure why there is the inconsistency (?)
<img width="1100" alt="Screenshot 2020-03-18 at 14 14 40" src="https://user-images.githubusercontent.com/8842431/76969995-18db0480-6923-11ea-885b-3366a5696a30.png">

<img width="1029" alt="Screenshot 2020-03-18 at 14 15 19" src="https://user-images.githubusercontent.com/8842431/76970015-1f697c00-6923-11ea-9ad5-d0c25f82c76a.png">

**Comment by anikethsaha** [comment]
may be for page's content. You need to check it manually like with console.logs/debugger

**Comment by joetidee** [comment]
In the first example above, the <footer> is being added inside the H3 tag:

<img width="734" alt="Screenshot 2020-03-18 at 14 31 14" src="https://user-images.githubusercontent.com/8842431/76971541-3a3cf000-6925-11ea-9913-91c48e9a091c.png">

Whereas, in the second example above, the <footer> is (correctly) being added to the add of the article (before the pagination block):

<img width="504" alt="Screenshot 2020-03-18 at 14 34 23" src="https://user-images.githubusercontent.com/8842431/76971798-956ee280-6925-11ea-8853-91376ece3599.png">

**Comment by anikethsaha** [comment]
I think it might be cause of page content

**Comment by joetidee** [comment]
Ah, I added a newline to the end of the 'web/index.md' page and it now works. Is it a requirement of markdown files to have a newline at the end?

**Comment by anikethsaha** [comment]
>  Is it a requirement of markdown files to have a newline at the end?

I dont know, we are using markedjs to parsing and rendering markdown, so I guess you can ask this question in their repo as well are simply showing what's coming as an output of `markedjs`.

**Comment by joetidee** [comment]
Or, you could add a auto-add a newline before appending using the `hook.beforeEach` method.

**Comment by anikethsaha** [comment]
> Or, you could add a auto-add a newline before appending using the `hook.beforeEach` method.

yes. with plugin's hook you can. It depends on the different use cases so it is something which should be done by plugins


It looks like you got a workaround working for you. I am closing this issue. Please comment if you need some more clarification 👍
