### ISSUE TITLE
Search does not work on the home page

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1080]
When visiting the home page and typing in a word, the search does not show any results. The search works once in an article page.

**Comment by Koooooo-7** [comment]
could u give more details about it.

**Comment by joetidee** [comment]
It appears that the search mechanism does not work when on the home page (readme.md) - the type to search placeholder doesn't even show. When on any other page it works.

**Comment by sy-records** [comment]
is it that when you visit the home page you can't search for anything else, or is it that you can't search for readme.md's content?

**Comment by trusktr** [comment]
Please let us know how to reproduce. Do you have the code for your site?

**Comment by trusktr** [comment]
I think ombaiz on Discord may be having this issue. Can you check out his link and verify if it looks to be the same issue? 

Discord chat: https://discord.com/channels/713647066802421792/713647066802421795/721456182069559397

His website, http://54.37.231.32, seems to only have a home page. The behavior reported is that search is not working. Based on the reported issue here, it would seem that he is experiencing this problem (considering he has only a home page, there are no search results).

**Comment by anikethsaha** [comment]
I can confirm search is not working in homepage even in our docs site

**Comment by ixdarchitects** [comment]
May I suggest docsify team have a high level review of the search feature.

The search should be flexible enough to be place at different pages/levels:
- In the global _coverpage.md (or a custom coverpage.html) to search all content in the site
- If there are multiple folders/projects hosted in the /docs folder, we should be able to configure the search in the sidebar to only search content in the particular folder/project

**Comment by markbattistella** [comment]
I've got private facing docs site with this issue too - but our home page only is the `_coverpage`. Clicking "View Documentation" to jump to item 1 in the TOC the search doesn't show. A hard refresh shows it, but only then. I've tested the order of the scripts loading, but hasn't changed anything

**Comment by sy-records** [comment]
@markbattistella In [docsify.js.org](docsify.js.org), I can't reproduce the problem you're talking about.

**Comment by markbattistella** [comment]
@sy-records I made this repo: https://github.com/markbattistella/docsify-searchTest to show how I have it set up and the search doesn't auto load. I tried getting it working gh-pages but i couldn't get it working in the small amount of time :)

**Comment by sy-records** [comment]
@markbattistella Your problem is caused by your `docsify-autoheaders` plugin, Just remove the `scope`.

```
autoHeaders: {
    separator: 'decimal',
    levels: '3',
},
```

**Comment by joetidee** [comment]
Am I right in saying that the Search plugin only indexes links on pages you have already visited? In which case, it's a bit of a useless feature.
