### ISSUE TITLE
Can't Redirect to Heading Form like ## 1.1, ## 1.2, ..., etc.

### ISSUE THREAD

**Issue by integzz** [docsifyjs/docsify#1087]
#### What is current behaviour

Click Heading Form like ## 1.1, ## 1.2, ..., etc. on Sidebar, can't redirect to the contents

#### What is the expected behaviour

Redirect to Heading Form like 1.1, 1.2, ..., etc.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 13.7
- npm/yarn version: 
- Browser version:  Firefox
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
can you submit a reproducible sandbox ? we have  a demo sandbox in readme of this repo

**Comment by integzz** [comment]
Sorry for delayed response, I tried to use the sandbox, however, there is some new problem with the sidebar, plus I am a frontend novice and not familiar with the sandbox, so I just put this bug on hold.

**Comment by Koooooo-7** [comment]
thx for ur report .

Same issus as #1088.

**Comment by integzz** [comment]
Thank you, #1088 is exactly what I want to report.
