### ISSUE TITLE
Title begins with a number cannot click the sidebar jump, how to solve?

### ISSUE THREAD

**Issue by zerojs** [docsifyjs/docsify#1089]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
please translate it to english

**Comment by zerojs** [comment]
> please translate it to english

Title begins with a number cannot click the sidebar jump, how to solve?

**Comment by anikethsaha** [comment]
can you share a reproducible sandbox for this . we have a demo sandbox in the readme.
Also, is it working on docsify version `4.10.2` ?

**Comment by zerojs** [comment]
> can you share a reproducible sandbox for this . we have a demo sandbox in the readme.
> Also, is it working on docsify version `4.10.2` ?

Id starting with a number will not work?
my project working on docsify version `4.3.0`
![image](https://user-images.githubusercontent.com/38181072/77299249-23343e80-6d27-11ea-84e6-a606ed5ec2a0.png)

**Comment by anikethsaha** [comment]
> Id starting with a number will not work?

it should ,

**Comment by zerojs** [comment]
> > Id starting with a number will not work?
> 
> it should ,
I want to start the title with a number, so how do I use it? I remember it was ok。

In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F"

**Comment by anikethsaha** [comment]
its a bug if its not working . Need an investigation about it. 

Feel free to submit a fix .  It may take time for me as I am a bit busy with other stuff.

**Comment by zerojs** [comment]
> its a bug if its not working . Need an investigation about it.
> 
> Feel free to submit a fix . It may take time for me as I am a bit busy with other stuff.

Looking forward to your update！

**Comment by anikethsaha** [comment]
> Looking forward to your update！

Cant assure you anytime soon though

**Comment by Koooooo-7** [comment]
thx for ur report .

Same issus as #1088.
