### ISSUE TITLE
[DISCUSS] About how to resolve docsify links.

### ISSUE THREAD

**Issue by Koooooo-7** [docsifyjs/docsify#1093]
## Bug Report
Relative Issues/PRs :
1. Sidebar level link does not work if header starts with numbers.  #1088 #1087 #1089 
2. Deal with Docksify links format (https://github.com/docsifyjs/docsify/pull/1091#discussion_r396727010) 
#### Steps to reproduce
As I posted aboved.

#### What is current behaviour
1. render the all the links no matter what.
2. havnt deal with links in some cases.

#### What is the expected behaviour
Find a way to merge these  cases and make links render logic clearly.

**Comment by anikethsaha** [comment]
@Koooooo-7 can you update the issue if it still exists or not ?

**Comment by Koooooo-7** [comment]
> @Koooooo-7 can you update the issue if it still exists or not ?

it is just an issue to make us care about the potential links problems. if it is need to be solved soon, we can discuss on it again. 
So I just close this issue right now.
