### ISSUE TITLE
The first h1 header is ignored in sidebar

### ISSUE THREAD

**Issue by stoufa** [docsifyjs/docsify#1094]
## Bug Report
As the title suggests, the first h1 markdown header is ignored in sidebar.

#### Steps to reproduce
Let's say we have two h1 headers 'a' and 'b', for each one of them, we have three h2 sub-headers `a.1`, `a.2`, `a.3`, and `b.1`, `b.2`, `b.3` respectively. The output will be as if `a.1`, `a.2`, `a.3`, and `b` are h1 headers and `b.1`, `b.2`, `b.3` as h2 sub-headers.

#### What is current behaviour
In other words, the input is :
```
# a
## a.1
## a.2
## a.3
# b
## b.1
## b.2
## b.3
```
and the generated sidebar looks like the following :
```
# a.1
# a.2
# a.3
# b
## b.1
## b.2
## b.3
```
> a is ignored and all of its content (sub-headers) levels up!

#### What is the expected behaviour
The expected behavior is to have the same hierarchy as the original input.

#### Other relevant information
However, I have found a hack to fix this, just add an empty first header to replace the one ignored.
i.e. the input becomes :
```
# &nbsp;
# a
## a.1
## a.2
## a.3
# b
## b.1
## b.2
## b.3
```

- Your OS: `Ubuntu 18.04`
- Node.js version: `v8.10.0`
- npm/yarn version: `npm 6.12.0`
- Browser version: `Google Chrome 80.0.3987.132`
- Docsify version: `docsify-cli 4.4.0`
- Docsify plugins: `Copy to Clipboard + Language Highlight (Python) + Full Text Search`

#### Please create a reproducible sandbox 
I tried to reproduce the same case on codesandbox.io but I couldn't, this is an error related to their website not to docsify.

#### Mention the docsify version in which this bug was not present (if any)
I'm using one version only, the latest one.

**Comment by anikethsaha** [comment]
> I tried to reproduce the same case on codesandbox.io but I couldn't, this is an error related to their website not to docsify.

Can you explain this.

**Comment by stoufa** [comment]
@anikethsaha I get some errors when I try to fork the sandbox mentioned in the template. I tried my best to describe how to reproduce the same issue.

**Comment by anikethsaha** [comment]
> this is an error related to their website not to docsify.
its working fine from our end right cause our docs seems working fine and checked few other websites running docsify and seems to be working

**Comment by stoufa** [comment]
This is not my case !
![image](https://user-images.githubusercontent.com/11628585/77666837-bd8fbe80-6f81-11ea-98ce-9b5b7fcf528d.png)

**Comment by anikethsaha** [comment]
I guess after forking, try reloading the page

**Comment by stoufa** [comment]
It took more than a simple refresh, anyways, it's working now. The issue now is : we have a different environment in this sandbox ! And the same code that didn't work for me in working fine there ! Here's an animation of the output I get with and without the hack I spoke about.

![docsify bug | Peek 2020-03-26 18-39](https://user-images.githubusercontent.com/11628585/77678759-eae46880-6f91-11ea-8aca-3d3cf3de1867.gif)

**Comment by Koooooo-7** [comment]
I create a  initialization  docsify project (`docsify init ./docs`).    
and edit the README. md    
```md

# a
## a.1
## a.2
## a.3
# b
## b.1
## b.2
## b.3
```
the sidebar rendered correctly.    

so, I think u could create a simple demo likes this. 
if the bug is still reproducible, I guess there may have others configurations/content get it broken or environment problems.

**Comment by stoufa** [comment]
I managed to reproduce the same error, <a href="https://drive.google.com/drive/folders/1KixorxoBy_VojBrf1_SGcRA-Q0gTpoV3?usp=sharing" target="_blank">here's the link</a>.
Hope you find this helpful. 🙂

**Comment by h-hg** [comment]
I met the same problem.

The steps are follows:

```bash
docsify init .
```

The `README.md` is as follows

```markdown
# a
## a.1
## a.2
## a.3
# b
## b.1
## b.2
## b.3
```

The  `index.html` is as follows

```javascript
window.$docsify = {
    name: '',
    repo: '',
    loadSidebar: true,
    subMaxLevel: 6
}
```

The `_sidebar.md` is as follows

```markdown
- [start](README.md)
```

The sidebar is as follow
![example](https://user-images.githubusercontent.com/38984008/87437999-97ba2280-c621-11ea-8edb-2623ec9ca007.png)


Environment
- OS: win10 1909
- nodejs: v13.11.0
- browser: MS Edge 83.0.478.61 and IE 11
- docsify-cli: 4.4.1

**Comment by sy-records** [comment]
I think it's the right thing to do. The sidebar description should be the same as for h1.

**Comment by h-hg** [comment]
> I think it's the right thing to do. The sidebar description should be the same as for h1.

Thanks. I get it.

**Comment by glaucoleme** [comment]
The issue also happened with me. As @stoufa shown, adding the `# &nbsp;` before the first header hides the problem. 

**Your OS:** Ubuntu 18.04.5 LTS
**Node.js version:** v12.18.4
**npm/yarn version:** npm 6.14.6
**Browser version:** Edge Version 85.0.564.63 (Official build) (64-bit)
**Docsify version:** docsify-cli 4.4.1
**Docsify plugins:** none

**Comment by sy-records** [comment]
In most cases, we'll only have one h1 in a file, rather than multiple.

```markdown
<!-- docs/_sidebar.md -->

- Getting started

* [test](/)
```

```markdown
# a

## a.1

## a.2

## a.3

# b

## b.1

## b.2

## b.3
```

Here the `test` should be equal to `a`, so we omit the h1 rendering from the sidebar

![image](https://user-images.githubusercontent.com/33931153/94633856-18272000-0301-11eb-87d9-b1c455887e8b.png)

**Comment by glaucoleme** [comment]
Sorry @sy-records, I ignored your previous comment. If you consider [the top level header as a good practice](https://cirosantilli.com/markdown-style-guide/#top-level-header), that is the expected behaviour indeed. Thanks

**Comment by stellarkey** [comment]
If only one `h1` is permited to use in a single file, and the "AutoHeader" is enabled, then **we always starts with at least 2 `#`s**, which is real **wierd** comparing to normal markdown usage.

I encounteredd the same bug. And the rendering is unstable (sometimes it works, sometimes not).
