### ISSUE TITLE
Server Side Rendering appears to no longer work

### ISSUE THREAD

**Issue by tobyhede** [docsifyjs/docsify#1101]
#### Steps to reproduce
Follow the instructions on Server Side Rendering
https://docsify.js.org/#/ssr

#### What is current behaviour

Following the SSR instructions results in a blank page. 
It looks like the app and config are not being injected by the server.

Using the package.json configuration, I can get `docsify start` to run. 
It looks like there is also a bug in docsify-cli when using the config file `-c` option .

#### What is the expected behaviour

The content should be rendered into the appropriate areas in the HTML template marked by comments.

```
  <!--inject-app-->
  <!--inject-config-->    
```

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: OSX
- Node.js version: v12.13.1
- npm/yarn version: 6.12.1
- Browser version: Latest Chrome and Firefox
- Docsify version: docsify@4.11.3, docsify-cli@4.4.0
- Docsify plugins: None, default install

**Comment by anikethsaha** [comment]
can you share a reproducible repo ?

**Comment by tobyhede** [comment]
Sandbox is here - https://codesandbox.io/s/github/tobyhede/docsify-ssr

`docsify start . -c ssr.config.js` has an error. 

SSR Docs says "You can configure it in a special config file, or package.json."
So I used  `docsify start` with package.json.

But the injection doesn't happen.

**Comment by mattvb91** [comment]
Experiencing the same issue currently in particular with this https://github.com/docsifyjs/docsify/issues/704

**Comment by paulhibbitts** [comment]
Previous SSR code removed for upcoming v5 release, so closing issue.
