### ISSUE TITLE
Bugs in special character handling

### ISSUE THREAD

**Issue by CHU295** [docsifyjs/docsify#1103]
#### Steps to reproduce
When there is a special character in a title, the a tag will escape this character, but the key searched by the serach component will directly ignore it。

For example, now there is a title called 'developer's Guide', which will be converted to 'developer 39s guide', but in 'docsify. Search. Index', it will be converted to 'developers guide', The character ' is ignored

This causes the click search result to be unable to locate

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by CHU295** [comment]
This is the last bug I mentioned
Now I find this reason

https://github.com/docsifyjs/docsify/issues/1098

**Comment by CHU295** [comment]
And Chinese characters have the same problem

**Comment by anikethsaha** [comment]
Feel free to submit a fix

**Comment by Koooooo-7** [comment]
> Feel free to submit a fix

I remember it was working correctly about the  escape sequences  issues.
it seems refactoring problems.

**Comment by anikethsaha** [comment]
I think it was because I had to remove `css.escape` package in order to patch an immediate fix as `css.escape` was not bundling along with the other module during build using rollup. 
not sure ! forgot the context of this. 

@Koooooo-7 can you point me the issue/PR were it was fixed?

**Comment by Koooooo-7** [comment]
@anikethsaha  
I pulled the `v4.11.3` , it works correctly, I cant reproduce it right now. :sweat_smile:

**Comment by anikethsaha** [comment]
@Koooooo-7 thanks for the input.

@CHU295 can you mention which version you are on ? also try using `4.11.3`

**Comment by CHU295** [comment]
It's marked.js`s parsing rules that cause~@anikethsaha

**Comment by Koooooo-7** [comment]
so , what's ur version and trying to use v4.11.3 to make sure whether it is reproducible. 
if u have more useful information, u could show more details.
