### ISSUE TITLE
Nesting issue with more than 2 levels

### ISSUE THREAD

**Issue by woss** [docsifyjs/docsify#1104]
#### Steps to reproduce
I've made a repo that shows the issue. 

https://woss.io/docsify-nesting-issue/#/

#### What is current behaviour
the embedded files are not showing at all when nested and relativePath is true 

#### What is the expected behaviour

to show embedded files

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: not gonna happen
- Node.js version: irrelevant
- npm/yarn version: irrelevant
- Browser version: irrelevant
- Docsify version:  latest
- Docsify plugins: none

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by RayKimEX** [comment]
@anikethsaha Could you fix this issue?? i want to embed with nested files

**Comment by anikethsaha** [comment]
it seems there is already open/merged PR for this. (forgot which one.)

it will fixed in next release if i am not wrong 👍

**Comment by woss** [comment]
are you talking about this PR https://github.com/docsifyjs/docsify/pull/1076

**Comment by anikethsaha** [comment]
Not sure, I will check that soon.

**Comment by RayKimEX** [comment]
@anikethsaha Could you let me know for this updated news?
