### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by guiyomh** [docsifyjs/docsify#1107]
## Bug Report

when I run the command `docsify serve docs`
I have this error:

```bash
env: node\r: No such file or directory
```

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac Os 10.15
- Node.js version: 10.17
- npm/yarn version: yarn 1.22.4
- Browser version: ~
- Docsify version: 4.4.0
- Docsify plugins: []

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Trying to check on [this one](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo) on stackoverflow or asking help on documentation chat room is better .
