### ISSUE TITLE
mp3 embed

### ISSUE THREAD

**Issue by GerhardMes** [docsifyjs/docsify#1109]
hi there,

just playing around and embedding audio mp3 via 'include' function. Works perfect, but just one little suggestion or question.

Is there a way to include volume regulation too?

In my case, there isn't one. I have to use the volume control of my device.

I am trying to make something like an educational app. It would be perfect if someone knows how I could fix a video on top of the page and add a text-frame that goes down with a transcipt. Any idea to that?

thanks and cheers
Gerhard

**Comment by Koooooo-7** [comment]
I think it works as ur expected , maybe I need more details about ur needs. 

![176cd1c0d53d9c1d1e9b7404b76d41d68b4a5a766b1a536e14e2ff0c37428e6e 0](https://user-images.githubusercontent.com/33706142/78963738-f6579800-7b2a-11ea-9915-8b61f72ddcb0.jpg)

```
# Map3 Demo

[music](http:www.example/demo.mp3  ':include ')
<!--   you can insert the local file also. 
 [music](/media/demo.mp3  ':include ' )
 -->

> transcript

There is the transcript of the mp3 above.

```

**Comment by GerhardMes** [comment]
first, thanks for your response. For a second, after copying your code and adapting it to my needs, I had the volume control.
But after refreshing the localhost, it was gone again. Here is my line of code:

`[music](/_media/Audio_Lecture_4.mp3 ':include ')`
I have tried it with and without the foregoing backslash. Nothing changed.

![Bildschirmfoto 2020-04-10 um 09 51 04](https://user-images.githubusercontent.com/34518275/78974219-ca7be880-7b11-11ea-8870-a51c79da8216.png)

But thanks for helping me out. Happy Easter Weekend

**Comment by GerhardMes** [comment]
sorry guys. I restarted my iMac and everything is here as suggested.
Thanks and to all of you, Happy Easter

**Comment by Koooooo-7** [comment]
> sorry guys. I restarted my iMac and everything is here as suggested.
> Thanks and to all of you, Happy Easter

that's fine. :smile:  enjoy your day.
