### ISSUE TITLE
Refresh the service worker cache

### ISSUE THREAD

**Issue by ThomasSousa96** [docsifyjs/docsify#1113]
Hi, I'm using Service Worker on my project. I got the [documentation example](https://docsify.js.org/#/pwa?id=create-serviceworker) and edited it to show a message when a new version is available. The message is displayed and when I click in this message the page is reloaded. The problem is that after the reloading the page still use the old files.

See below my code:
* [Service worker](https://github.com/seudev/seudev-docs/blob/master/docs/sw.js) 
* [The registry function](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/_assets/js/service-worker-register.js#L31-L50)
* [The function that checks by updates](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/_assets/js/service-worker-register.js#L61-L88)
* [The hook that listen by updates](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/index.html#L96-L105)
* [The click message event](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/_assets/js/service-worker-register.js#L21-L23)
* [The skipWaiting event](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/sw.js#L44-L48)
[The reload event](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/_assets/js/service-worker-register.js#L37-L43)

I tried use a [cache name with a hash suffix](https://github.com/seudev/seudev-docs/blob/dda953165ca726fdeb08440db3e423c25d857589/docs/sw.js#L11) to each update (It will be create a empty cache for each different name), but the files still are loaded from cache.

How to resolve this problem?

**Comment by anikethsaha** [comment]
I don't think its related to docsify cause in docsify the service worker example is the general example available from google's docs with just a few comments and links added. 
I have very limited knowledge of digging in the service worker so U may be wrong.

I would recommend submitting this in StackOverflow cause it would increase visibility.
