### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by skmy93** [docsifyjs/docsify#1114]
#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by anikethsaha** [comment]
Please dont submit an issue with just one-word heading and empty template.
