### ISSUE TITLE
Image resize in % doesn't work anymore

### ISSUE THREAD

**Issue by costimuraru** [docsifyjs/docsify#1115]
## Bug Report
We're following the docsify documentation, which states that it's possible to resize an image using a percentage: https://github.com/docsifyjs/docsify/blob/develop/docs/helpers.md#resizing

#### Steps to reproduce

Use markdown to insert an image, with 50% width:
```
![My diagram](/_media/diagrams/sample_upstream_flow.png ':size=50%')
```
#### What is current behaviour

Notice the `width` is wrong. Instead of 50% it's just 50. Also the `%` seems to somehow be transferred to the `title` attribute:

```
<img src="/upstream-protocol/sample-app/_media/diagrams/sample_upstream_flow.png" 
  alt="My diagram" 
  title="%" 
  width="50" 
  height="50">
```

#### What is the expected behaviour
```
<img src="/upstream-protocol/sample-app/_media/diagrams/sample_upstream_flow.png" 
  alt="My diagram"
  width="50%">
```

#### Other relevant information

<img width="1075" alt="Screenshot 2020-04-13 16 18 11" src="https://user-images.githubusercontent.com/952836/79123253-67ed4b80-7da2-11ea-81c5-47c07e00cca3.png">

Could this be a parsing mardown issue? Perhaps here: https://github.com/docsifyjs/docsify/blob/master/src/core/render/utils.js#L6-L14 ?

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.11.3
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by costimuraru** [comment]
CC @anikethsaha, @QingWei-Li

**Comment by anikethsaha** [comment]
I think this https://github.com/docsifyjs/docsify/pull/1065 might fix the height issue.
And about the `%` issue, I do think there might be some bug with the extractor. 

could you try `![My diagram](/_media/diagrams/sample_upstream_flow.png ':size=50%x50%')` and check if the `%` issue still exists or not !

**Comment by Koooooo-7** [comment]
> I think this #1065 might fix the height issue.
> And about the `%` issue, I do think there might be some bug with the extractor.

 yep, I think it is the regex issues.
```js
...
.replace(/(?:^|\s):([\w-]+:?)=?([\w-]+)?/g, (m, key, value) => {
```
the `([\w-]+)`missed the `%`. and I checked `v4.11.0`,`v4.8.0`,`v4.6.8`, both have this problem  😅.
I fixed the regex 
```js
 .replace(/(?:^|\s):([\w-]+:?)=?([\w-%]+)?/
```
then, it works.
![image](https://user-images.githubusercontent.com/33706142/79129964-b9b0c880-7dd8-11ea-956f-350496e96511.png)

**Comment by anikethsaha** [comment]
@Koooooo-7 thanks a lot for investigating this ( as always 😄 )

Can you submit a PR with the fix and also we need to check if it's breaking something else or not,

**Comment by Koooooo-7** [comment]
> @Koooooo-7 thanks a lot for investigating this ( as always  )
> 
> Can you submit a PR with the fix and also we need to check if it's breaking something else or not,

yea, I m working on it. :hammer:

**Comment by costimuraru** [comment]
Thanks for the quick fix here, @Koooooo-7. And @anikethsaha for reviewing. You guys rock!

**Comment by cugxuan** [comment]
so great!
waiting for new release!
