### ISSUE TITLE
Inconsistent search and body rendering

### ISSUE THREAD

**Issue by sy-records** [docsifyjs/docsify#1118]
#### Steps to reproduce

```
## fatal error: 'openssl/ssl.h' file not found
```

#### What is current behaviour

![image](https://user-images.githubusercontent.com/33931153/79184061-bdc6ff80-7e45-11ea-8312-38517e4626d0.png)

The link when searching is `/question/install?id=fatal-error-opensslsslh-file-not-found`

![image](https://user-images.githubusercontent.com/33931153/79184422-a9373700-7e46-11ea-9351-c94542d6e3a7.png)

The link when body is `/question/install?id=fatal-error-39opensslsslh39-file-not-found`

![image](https://user-images.githubusercontent.com/33931153/79184438-b81de980-7e46-11ea-8a26-cad12c56aaac.png)

#### What is the expected behaviour

`/question/install?id=fatal-error-39opensslsslh39-file-not-found`

Or just keep it consistent

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
could u show me which version u work on?
it isn't reproducible now. 
they are both rendered to 
```html
/question/install?id=fatal-error-39opensslsslh39-file-not-found
```

**Comment by Koooooo-7** [comment]
@anikethsaha  could you investigate it also. we used the same `slugify` results render both the sidebar and title, if this issue exist , I guess there would have something broken we missed.

**Comment by anikethsaha** [comment]
@sy-records can you submit a reproducible sandbox for this

**Comment by sy-records** [comment]
Sorry, I will not use sandbox, I provided a test address. @anikethsaha @Koooooo-7 
https://sy-records.github.io/docsify-serach-test/

You can search `open`

![image](https://user-images.githubusercontent.com/33931153/79312571-a9603100-7f31-11ea-8e61-97c049e4f313.png)

![image](https://user-images.githubusercontent.com/33931153/79312609-b8df7a00-7f31-11ea-8e01-c314b258ccfe.png)

**Comment by Koooooo-7** [comment]
thx for ur report. 
It seems doesn't make the search broken, even though the different url showing. 
It needs investigation.

**Comment by sy-records** [comment]
But because of the different URLs, the corresponding IDs are also different. In this case, the jump cannot find the correct place.
Because the IDs are different, the corresponding anchor points are different, I think this is a bug.

**Comment by sy-records** [comment]
The problem may appear here. Use`slugify` to modify the `token.text` wrong.

https://github.com/docsifyjs/docsify/blob/39320bb3f4991b5b85ddf59876a1c51c1379a20b/src/plugins/search/search.js#L69

https://github.com/docsifyjs/docsify/blob/39320bb3f4991b5b85ddf59876a1c51c1379a20b/src/core/render/slugify.js#L10
