### ISSUE TITLE
Disable caching to get latest .md file

### ISSUE THREAD

**Issue by bilencekic** [docsifyjs/docsify#1119]
#### Steps to reproduce
Update an .md file and refresh the browser

#### What is current behaviour
.md file is read from the cache directly. As per network tab, it is retrieved from cache. On my local it works fine but in server always read from cache.

#### What is the expected behaviour
It should always read the latest .md file content in the server.

#### Other relevant information
maybe it is due to below code ? How to disable it ?
![image](https://i.imgur.com/6aNA59p.png)

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OS Catalina
- Node.js version: 
- npm/yarn version: 
- Browser version: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- Docsify version:  latest (4.11.3)
- Docsify plugins: Search, mermaid,emoji

**Comment by bilencekic** [comment]
sorry my bad
after adding below code, issue has been fixed;
```

  requestHeaders: {
    'cache-control': 'max-age=0',
  },
```

**Comment by shirleyman** [comment]
Does this mean I have to modify the source code to get this feature?

**Comment by sy-records** [comment]
@shirleyman you need update index.html, https://docsify.js.org/#/configuration?id=requestheaders
