### ISSUE TITLE
Side bar not showing sub sections

### ISSUE THREAD

**Issue by elmagrinmint** [docsifyjs/docsify#1122]
## Bug Report

Side bar does not always show sub sections for my pages

#### Steps to reproduce
Un able to reproduce

#### What is current behaviour
I have different pages in my side bar, some times the sub sections are visible. 

#### What is the expected behaviour

<img width="174" alt="Screenshot 2020-04-16 at 08 35 28" src="https://user-images.githubusercontent.com/52529310/79422475-3b614b80-7fbd-11ea-9934-5e33367ec42a.png">

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version:  
- npm/yarn version: 
- Browser version: Chrome
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by anikethsaha** [comment]
please mention the versions and submit a reproducible sandbox. it helps use investigating better. Also , share you docsify config
