### ISSUE TITLE
dont`t have other language doc , after version 4.7

### ISSUE THREAD

**Issue by loqhcn** [docsifyjs/docsify#1123]
dont`t have other language doc , after version 4.7

i want use Chinese doc

**Comment by Koooooo-7** [comment]
it is hard for us to make the documentation sync for other non-English docs after API changes or something stuff. 

and I hope there with have contributors to make it also.

**Comment by KyrieWang0410** [comment]
> dont`t have other language doc , after version 4.7
> 
> i want use Chinese doc

me too！！！

**Comment by vagra** [comment]
I update the ALL chinese translation to v4.11.3 .

see my PR.
https://github.com/docsifyjs/docs-zh/pull/19#issue-408684065

**Comment by Koooooo-7** [comment]
> I update the ALL chinese translation to v4.11.3 .
> 
> see my PR.

thx for ur contributions, we will check it soon. :+1:

**Comment by sy-records** [comment]
I've modified some, and you can modify the rest yourself...

**Comment by sy-records** [comment]
@anikethsaha @Koooooo-7 I have finished the review, are there any others?

**Comment by anikethsaha** [comment]
fine by me. 👍

**Comment by sy-records** [comment]
Okay, then I merged.
