### ISSUE TITLE
How to serve docsify from a subdirectory on an existing site?

### ISSUE THREAD

**Issue by wcarhart** [docsifyjs/docsify#1124]
## Bug Report
Can't serve docsify from a subdirectory. How would I serve docsify content when there is a directory between `docs/` and `index.html`?

#### Steps to reproduce
Visit https://wcarhart.github.io/docs/koi.

#### What is current behaviour
First off, thanks so much for docsify! Super awesome.

I doubt this is a bug, probably my own mistake. I am serving docsify from a subdirectory of a previously existing site, via GitHub Pages. As such, instead of having my docsify content `docs/index.html`, I have it in `docs/<project-name>/index.html`, where `<project-name>` is the name of my project.

It looks like my homepage renders fine, but docsify cannot find my `_sidebar.md` file. I've tried a number of different aliases and basePaths.

When I run the site locally via the docsify CLI, it is rendered fine.

Here is the deployed broken site: https://wcarhart.github.io/docs/koi/#/

Here is the code for the broken site: https://github.com/wcarhart/wcarhart.github.io/tree/master/docs/koi

#### What is the expected behaviour
I was expecting docsify to be able to serve my content from `docs/<project-name>/`.

#### Other relevant information
I have a couple of different projects I was hoping to create documentation for, using the pattern `https://domain.com/docs/<project-name>/`. You can see my initial draft at https://wcarhart.github.io, where there's a button to my first project on docsify, `koi`. My idea was to simply have a `docs/<project-name>` folder in the repository for each project, but perhaps there is a better way? Totally open to suggestions.

Here's what my `index.html` configurations looks like right now. Docsify has issues with `_/media/logo.png` and `_sidebar.md`.
```javascript
window.$docsify = {
  name: 'koi',
  repo: 'wcarhart/koi',
  homepage: 'overview.md',
  loadSidebar: true,
  logo: 'docs/koi/_media/logo.png',
  themeColor: '#9B59B6',
  notFoundPage: true,
  auto2top: true,
  autoHeader: false,
  subMaxLevel: 3,
  maxLevel: 4,
  copyCode: {
    buttonText : 'Copy',
    errorText  : 'Uh oh! Could not copy!',
    successText: 'Copied!'
  },
  search: {
    paths: 'auto',
    placeholder: 'Search',
    noData: 'No Results'
  },
  basePath: 'https://wcarhart.github.io/docs/koi/',
  alias: {
    '_sidebar.md': 'koi/_sidebar.md'
  }
}
```

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS, but issue exists when deployed to GitHub Pages
- Node.js version: v13.12.0
- npm/yarn version: npm 6.14.4, yarn 1.22.4
- Browser version: Chromium: 75.0.3770.142
- Docsify version: docsify-cli v4.4.0
- Docsify plugins: search, copyCode

#### Please create a reproducible sandbox 
Sorry, I couldn't recreate the issue here. You can see the issue in production at https://wcarhart.github.io/docs/koi/#/.

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by wcarhart** [comment]
Here's what my `index.html` configurations looks like right now. Docsify has issues with `_/media/logo.png` and `_sidebar.md`.
```javascript
window.$docsify = {
      name: 'koi',
      repo: 'wcarhart/koi',
      homepage: 'overview.md',
      loadSidebar: true,
      logo: 'docs/koi/_media/logo.png',
      themeColor: '#9B59B6',
      notFoundPage: true,
      auto2top: true,
      autoHeader: false,
      subMaxLevel: 3,
      maxLevel: 4,
      copyCode: {
        buttonText : 'Copy',
        errorText  : 'Uh oh! Could not copy!',
        successText: 'Copied!'
      },
      search: {
        paths: 'auto',
        placeholder: 'Search',
        noData: 'No Results'
      },
      basePath: 'https://wcarhart.github.io/docs/koi/',
      alias: {
        '_sidebar.md': 'koi/_sidebar.md'
      }
    }
```

**Comment by wcarhart** [comment]
This appears to have been some kind of routing issue with GitHub Pages, as I have switched to Netlify and am not experiencing this issue anymore: https://distracted-leakey-5bb864.netlify.app/docs/koi/#/

**Comment by NaffanDroo** [comment]
Did you try .nojekyll in the folder?
