### ISSUE TITLE
Markdown include not stripping YAML front matter

### ISSUE THREAD

**Issue by sytone** [docsifyjs/docsify#1129]
#### Steps to reproduce

1. Create a Markdown Page to view
2. Create a markdown page to include with a YAML header.
3. Add a link with the include tag to the page.
4. View the markdown page with the link and when the link I parsed the YAML header is also pulled through and rendered as markdown putting a line on the page followed by the YAML header information as test and then another line.

#### What is current behaviour

When the link I parsed the YAML header is also pulled through and rendered as markdown putting a line on the page followed by the YAML header information as test and then another line.

#### What is the expected behaviour

The markdown is rendered from the include should only have the markdown rendered and not the YAML front matter.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows
- Node.js version: NA
- npm/yarn version: NA
- Browser version: Edge and Chrome latest
- Docsify version: Latest (4.11.3)
- Docsify plugins: None

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-http-b695t)

**Comment by anikethsaha** [comment]
Thanks for the issue and filling the template and creating a repro sandbox. it helps a lot 🥇 

I can confirm this is a bug and should be fixed.
