### ISSUE TITLE
Skip coverpage for recurring issues

### ISSUE THREAD

**Issue by dellagustin-sap** [docsifyjs/docsify#1130]
## Feature request

I checked the documentation, open and closed issues and stackoverflow before reporting.

#### What problem does this feature solve?

Showing a coverpage for first time visitors is nice, but showing it to recurring visitors usually will not bring much value.

As a docsify based website owner, I would like to direct recurring visitors to some specific page.

#### What does the proposed API look like?

$docsify.coverpage could optionally accept an object with the following options:

```js
{
    skipRecurring: true, //boolean
    skipRecurringTo: '' // String, Defaults to README.md, page that will be shown on recurring visitors.
}
```
#### How should this be implemented in your opinion?

Some flag could be set on localStorage after the first visit, and checked on next visits.

#### Are you willing to work on this yourself?

Yes

**Comment by anikethsaha** [comment]
thanks for the issue. 
I don't think any other docs site generator supports this. (let me know if some other does)
consider the cover page as a landing page so I do think it should be visible every time someone visits your site.

**Comment by dellagustin-sap** [comment]
Hi @anikethsaha , thanks for your quick response.

I don't know if other site generators support this, not to my knowledge. I have used Jekyll and MkDocs int the recent past.

There a difference though, I don't usually consider the cover page as a landing page, but more as a Welcoming, non-overwhelming content, that directs visitors to the actual landing page, which in my case I consider to be the README.md, which very good for first time visitors.

I am speaking now more as a visitor that has to often visit the same page, then the maintainer of the page (which I also am).

**Comment by anikethsaha** [comment]
I would highly encourage if you can do this via plugins. cause we are kind of backing out from adding new enhancement as we already overshoot our claimed size (which is `21kb`). in the future. we will probably move out some core features to plugins.

**Comment by dellagustin-sap** [comment]
I will explore that idea, seems suitable.
Thanks for the advice.
I will close this issue, as there is nothing else to be done.
When I find a suitable solution I will post more information here, in case someone else finds it searching for the same topic.
