### ISSUE TITLE
the bug of Multiple covers ?

### ISSUE THREAD

**Issue by jerryc127** [docsifyjs/docsify#1132]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)

i have setting according the docs

![image](https://user-images.githubusercontent.com/16351105/80011643-b915e180-84fe-11ea-8377-4e2ce88742a1.png)

but when i change to /zh-cn/ , it not show the coverpage
![image](https://user-images.githubusercontent.com/16351105/80011349-57557780-84fe-11ea-9d9f-d66dbeecca30.png)
![image](https://user-images.githubusercontent.com/16351105/80011399-65a39380-84fe-11ea-8ddf-40f2bcee0491.png)

how can i solve it ?

and have a question
the docs show that run docsify serve and provide LiveReload to preview the website immediately。
but when i change the code , it nothing change. still need to run  docsify serve again and show the result

**Comment by sy-records** [comment]
A document site can have only one coverpage.
see https://docsify.js.org/#/cover?id=basic-usage

**Comment by jerryc127** [comment]
> A document site can have only one coverpage.
> see https://docsify.js.org/#/cover?id=basic-usage

but what meaning of multiple covers?
https://docsify.js.org/#/cover?id=multiple-covers

**Comment by sy-records** [comment]
I also encountered problems in the test a few days ago... 

But I had no problems with the test just now.

**Comment by jerryc127** [comment]
it is my website 
https://github.com/jerryc127/hexo-theme-butterfly-docs
https://docs.jerryc.me/#/

i have setting according the docs
you can see that  when i change to zh-cn, it not show the coverpage.

**Comment by sy-records** [comment]
You wrote it wrong... Fix jerryc127/hexo-theme-butterfly-docs#2

**Comment by jerryc127** [comment]
oh 
thx you
