### ISSUE TITLE
使用nginx部署的时候，具体文档的侧栏无法加载

### ISSUE THREAD

**Issue by darknoll** [docsifyjs/docsify#1133]
![](https://i.loli.net/2020/04/23/n7DSWaATkj8iJdN.png)

**Comment by vagra** [comment]
这可能是你把 docsify 放到网站的某个子目录下，而不是网站的根目录下了是吧？
而 index.html 中的 css 、 js 、 docs 等链接，都是用 / 开头的，也就是相对于网站根目录的，所以你找不到那些 css 、js 和 docs 。

解决办法：
修改 index.htm
```
<link rel="stylesheet" href="/themes/vue.css" title="vue">
<link rel="stylesheet" href="/themes/dark.css" title="dark" disabled>
<link rel="stylesheet" href="/themes/buble.css" title="buble" disabled>

window.$docsify = {
      basePath: '/docs/',
}

<script src="/lib/docsify.js"></script>
<script src="/lib/plugins/search.js"></script>
```

去掉 `/themes/...` `/lib/...` `/docs/` 开头的 `/` 即可，就是相对于当前文件夹的相对路径了。

**Comment by darknoll** [comment]
> 这可能是你把 docsify 放到网站的某个子目录下，而不是网站的根目录下了是吧？
> 而 index.html 中的 css 、 js 、 docs 等链接，都是用 / 开头的，也就是相对于网站根目录的，所以你找不到那些 css 、js 和 docs 。
> 
> > It may be that you place docsify into a subdirectory of your site, rather than the site's root directory.
> > in the index.html file, css, js and docs all begin with /, that is, relative to the site's root directory, so docsify can not find those css, js and docs.
> 
> Fix it：
> edit index.html
> 
> ```
> <link rel="stylesheet" href="/themes/vue.css" title="vue">
> <link rel="stylesheet" href="/themes/dark.css" title="dark" disabled>
> <link rel="stylesheet" href="/themes/buble.css" title="buble" disabled>
> 
> window.$docsify = {
>       basePath: '/docs/',
> }
> 
> <script src="/lib/docsify.js"></script>
> <script src="/lib/plugins/search.js"></script>
> ```
> 
> change to:
> 
> ```
> <link rel="stylesheet" href="themes/vue.css" title="vue">
> <link rel="stylesheet" href="themes/dark.css" title="dark" disabled>
> <link rel="stylesheet" href="themes/buble.css" title="buble" disabled>
> 
> window.$docsify = {
>       basePath: 'docs/',
> }
> 
> <script src="lib/docsify.js"></script>
> <script src="lib/plugins/search.js"></script>
> ```

![](https://i.loli.net/2020/04/24/XF73B69lJovZkyC.png)

**Comment by sy-records** [comment]
提供一个复现环境吧... 或者可以访问的地址

**Comment by vagra** [comment]
用浏览器的 F12 调试，看网络界面，哪个请求报 404 ，就是找不到这个文件，说明它的路径是错的。

**Comment by Aaxom** [comment]
希望可以加一个build功能，全部打包成标准的html、css、js文件，不然nginx部署有各种问题（无法获取md类型文件、侧边栏不会向上寻找，这些我都遇到了），根本无法实现生产用途。

**Comment by sy-records** [comment]
这是你配置问题，我用nginx跑文档已经很久了。下个大版本会有生成静态文件的考虑。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aaxom <notifications@github.com&gt;
发送时间: 2020年10月4日 23:21
收件人: docsifyjs/docsify <docsify@noreply.github.com&gt;
抄送: 沈唁 <52o@qq52o.cn&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[docsifyjs/docsify] 使用nginx部署的时候，具体文档的侧栏无法加载 (#1133)





 
希望可以加一个build功能，全部打包成标准的html、css、js文件，不然nginx部署有各种问题（无法获取md类型文件、侧边栏不会向上寻找，这些我都遇到了），根本无法实现生产用途。

**Comment by yelingchen** [comment]
// 添加alias配置防止侧边栏消失
      alias: {
        '/.*/_sidebar.md': '/_sidebar.md'
      },
