### ISSUE TITLE
click left sidebar, then refresh the page, lost the sync scroll.

### ISSUE THREAD

**Issue by vagra** [docsifyjs/docsify#1136]
#### Steps to reproduce

1. open a page like https://docsify.js.org/#/configuration

2. click a sub-sidebar link (the toc of current document), or click a heading in the main content

3. using F5, refresh the current page

#### What is current behaviour

the page lost sync scroll. 
when you scroll the main page, the sidebar could not sync scroll.

#### What is the expected behaviour

 the sidebar sync scroll always.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by vagra** [comment]
if I don't click the left sidebar item, when refresh the page using F5, I always sync scroll.

**Comment by vagra** [comment]
see this code in scroll.js
```
export function scrollActiveSidebar(router) {

  const path = router.getCurrentPath();
  console.log(path);  // log info for test
  dom.off('scroll', () => highlight(path));
  dom.on('scroll', () => highlight(path));

}
```

if I don't click the links at main content or side bar, the path is :
```
/docs/pagename
```

if I clicked the links at main content or side bar, the path is:
```
/docs/pagename?id=anchorid
```

but in the `function highlight(path) `, does not handle the `id` in `path`.

**Comment by sy-records** [comment]
@vagra Can you give me your contact information? wechat or email?
