### ISSUE TITLE
 mermaid Can't renderer

### ISSUE THREAD

**Issue by kobojp** [docsifyjs/docsify#1137]
Where is the problem

![105](https://user-images.githubusercontent.com/22941674/80198228-5897b900-8652-11ea-95ef-011cbe03520c.jpg)

![107](https://user-images.githubusercontent.com/22941674/80198243-5e8d9a00-8652-11ea-95df-a4c740b4596a.jpg)

![image](https://user-images.githubusercontent.com/22941674/80198851-3eaaa600-8653-11ea-95df-1ac0f1bc7503.png)

**Comment by sy-records** [comment]
Maybe js is not loaded.
```
<script src="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
```

**Comment by kobojp** [comment]
Thank you so much

**Comment by sy-records** [comment]
@anikethsaha @kobojp This can be closed.
