### ISSUE TITLE
when using relativePath: true, links on the sidebar are always relative to the current page 

### ISSUE THREAD

**Issue by dellagustin** [docsifyjs/docsify#1139]
## Bug Report

this is a duplicate of #925, that was closed automatically.

#### Steps to reproduce

I have prepared an example here: https://dellagustin-sap.github.io/docsify-relative-path-bug-report/#/

Click first on _Subpage1 - Absolute_ (on the sidebar), then on _Subpage1 - Relative_

#### What is current behaviour

A 404 page is shown

#### What is the expected behaviour

Subpage 1 should be shown

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 home
- Node.js version: N/A
- npm/yarn version: N/A
- Browser version: Google Chrome 80.0.3987.163
- Docsify version: 4.11.3
- Docsify plugins: none

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

https://dellagustin-sap.github.io/docsify-relative-path-bug-report/#/

**Comment by dellagustin** [comment]
I have considered whether this behavior was intended to cover some specific scenario, but could not think of any in which it would be beneficial.

I have browsed the code, the link rendered uses the current route to resolve relative links: https://github.com/docsifyjs/docsify/blob/b2e6123980e98c75a6a6e6cb1f366b19e9856c13/src/core/render/compiler/link.js#L20

It has no access to current file for the sidebar (I suppose this is also true for the navbar).
The only place where this information is available seems to be https://github.com/docsifyjs/docsify/blob/develop/src/core/fetch/index.js#L8

I could not think of an easy solution.
There are many layers between where the information is available and where it is used.

I have considered the following:

1. Modiy `loadNested` also pass down the current path to the next callback (maybe as a 3rd parameter, or enriching the section parameter, as it is a dictionary.
2. Pass the current path to _renderSidebar and _renderNav
3. Extend the `HashHistory` router to return the current path (of sidebar or navbar) on `getCurrentPath` 
4. Instatiate a different compiler to use for redering sidebar and navbar, that would use as router the new extended `HashHistory`

I did not check yet how to create automated tests for this.

**Comment by anikethsaha** [comment]
Thanks for the detailed issue. 💯 

If I am not wrong, when you are in `subpage1 (absolute)` , you click on the `subpage1 (relative)` and its searching for the page in that directory instead of from root . right ?

if this is, then its the intended behavior as sidebar is always at root (of the current folder) so the base path will be the current path. if you want to go up one directory in order to render that page you need to give related path from where the sidebar is.

**Comment by dellagustin** [comment]
Hi @anikethsaha 

> If I am not wrong, when you are in subpage1 (absolute) , you click on the subpage1 (relative) and its searching for the page in that directory instead of from root . right ?

Right, if I understood that correctly.

To give more details:
In my example, if you are at https://dellagustin-sap.github.io/docsify-relative-path-bug-report/#/subpages/subpage1 (route is `/subpages/subpage1`, you will get here from `/` by clicking either the absolute or relative link), and then you click in the relative link, it will link to https://dellagustin-sap.github.io/docsify-relative-path-bug-report/#/subpages/subpages/subpage1

Now, in my example the sidebar markdown file is always at root (not of the current folder, but https://dellagustin-sap.github.io/docsify-relative-path-bug-report/sidebar.md) - and that is why I think that the links on the sidebar should be resolved relative to where the sidebar file was found.

About:
> as sidebar is always at root (of the current folder)

I am not sure what you mean with _always_ here, because `loadNested` will recursively search for the sidebar up the path structure: https://docsify.js.org/#/more-pages?id=nested-sidebars
> If the current directory doesn't have _sidebar.md, it will fall back to the parent directory.

**Comment by anikethsaha** [comment]
> > as sidebar is always at root (of the current folder)

`loadNested` ? did you mean `loadSidebar`

> I am not sure what you mean with _always_ here, because `loadNested` will recursively search for the sidebar up the path structure: https://docsify.js.org/#/more-pages?id=nested-sidebars

sorry, I thought you had the aliases setup to fallback to root.

this needs investigation. I will check once again. 


cc @docsifyjs/reviewers , thoughts ?

**Comment by dellagustin** [comment]
> `loadNested` ? did you mean `loadSidebar`
No actually meant this function: https://github.com/docsifyjs/docsify/blob/b2e6123980e98c75a6a6e6cb1f366b19e9856c13/src/core/fetch/index.js#L8

**Comment by anikethsaha** [comment]
ok cool, I will check that soon for sure 👍 .

**Comment by CxRes** [comment]
I think I can solve this issue. My strategy is to pass a `isParent` property to the `next` function in `loadNested` if it is invoked a second time which is passed to `_renderSidebar` and then `compiler.sidebar`. Now ideally I should be able to ask the compiler to append '../' to each link or I can mutate paths from _sidebar.md to append '../'. 

```js
  function loadNested(path, qs, file, next, vm, first) {
    path = first ? path : path.replace(/\/$/, '');
    path = getParentPath(path);

    if (!path) {
      return;
    }

    get(
      vm.router.getFile(path + file) + qs,
      false,
      vm.config.requestHeaders
    ).then(
      next,
      function (_) { return loadNested(path, qs, file, (r) => next(r, true), vm); });
  }

  ...

        var fn = function (result, isParent) {
          this$1._renderSidebar(result, isParent);
          cb();
        };

        // Load sidebar
        loadNested(path, qs, loadSidebar, fn, this$1, true);
      
  proto._renderSidebar = function(text, isParent) {
     ...
     this._renderTo('.sidebar-nav', that.compiler.sidebar(result, maxLevel, isParent));
     ...
  }

Compiler.prototype.sidebar = function sidebar (text, level, isParent) {
  ...
  if (text) {
      html = this.compile(text, isParent && {baseUrl: '../'}); // using this to modify marked.setOptions
  }
  ...
```


An alternative could be to pass the `path` from `loadNested` and use it to build absolute urls before passing it to the compiler. 

But I have a couple of questions:
1) How do I ask marked to append `../` to links. Adding `baseUrl` does not seem to work. 
2) How do I get a handle to `relativePath` in `compiler.sidebar`.

**Comment by sy-records** [comment]
I tried it and I don't think it's a problem.

no get 404

![image](https://user-images.githubusercontent.com/33931153/89286045-1a178e80-d684-11ea-9b73-ecbfd09587c4.png)

The two files in your sidebar should both use absolute paths.
```
- A section
    - [Subpage1](/subpages/subpage1.md) - Absolute
    - [Subpage1](/subpages/subpage1.md) - Relative
```

**Comment by wizardforcel** [comment]
I have another idea: Once the program reads the toc (`loadSidebar`)， process every link into the absolute path.

And then they have no problem, according to @sy-records .

**Comment by MrBlenny** [comment]
I was having this issue but was able to resolve it for now by writing the `_sidebar.md` in html instead of markdown.

i.e.
```
    - [Subpage1](/subpages/subpage1.md)
    - [Subpage2](/subpages/subpage2.md)
```

becomes:
```
    - <a href="#subpages/subpage1">Subpage1</a>
    - <a href="#subpages/subpage2">Subpage1</a>
```

note, `#` is added and `.md` is removed.

**Comment by trusktr** [comment]
I too have been bitten by this. This will be officially solved in https://github.com/docsifyjs/docsify/issues/1684 with a new option (for backwards compatibility, so that existing options like `relativePath` work the same).
