### ISSUE TITLE
Link to page breaks scroll

### ISSUE THREAD

**Issue by I-Valchev** [docsifyjs/docsify#1141]
#### Steps to reproduce
`A.md` is a page long enough to force a scrollbar. At the end of that page, I create a link to `B.md` as follows:
`[B](/b_in_folder/B.md)`

#### What is current behaviour

When page B loads, it loads as far down the page as I was on `A.md`.

#### What is the expected behaviour

Going to `B.md` I should be at the top of the page.

#### Other relevant information

- [ x ] Bug does still occur when all/other plugins are disabled?

- Your OS:
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by dellagustin** [comment]
Have you checked https://docsify.js.org/#/configuration?id=auto2top ?

**Comment by I-Valchev** [comment]
Oh right! Yes that fixed it. Thanks @dellagustin

**Comment by dellagustin** [comment]
Glad to help.
