### ISSUE TITLE
{docsify-updated} not work ?

### ISSUE THREAD

**Issue by jerryc127** [docsifyjs/docsify#1142]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)

when i checking in localhost, it work
![image](https://user-images.githubusercontent.com/16351105/80313163-d3600000-881b-11ea-85c0-1892c752584d.png)
when i upload to github, and it not work
![image](https://user-images.githubusercontent.com/16351105/80313175-eb378400-881b-11ea-9977-8ac544ed4f00.png)

how to solve?

it is my docsify github https://github.com/jerryc127/hexo-theme-butterfly-docs

**Comment by anikethsaha** [comment]
please fill the issue template

**Comment by sy-records** [comment]
Maybe it is the `cdn` cache, try to visit after you set the `hosts` locally.

**Comment by jerryc127** [comment]
still not work
i do not how to solve

**Comment by sy-records** [comment]
I'm sure it's your caching problem, I tried to deploy it using github page and they showed normal.

You can also try it.

![image](https://user-images.githubusercontent.com/33931153/80688102-e3b6fa00-8afd-11ea-9dfa-f8dba3a0e146.png)

**Comment by baicaihenxiao** [comment]
I have the same problem.
Every time I push new commits to github. {docsify-updated} in all pages is changed to the time of the latest push time.

**Comment by sy-records** [comment]
Please submit a new issue and fill the issue template.

**Comment by sy-records** [comment]
Please submit a new issue and fill the issue template. @baicaihenxiao

**Comment by realzsy** [comment]
@jerryc127 你好，最后这个问题解决了吗？我也是本地显示，上传以后不显示。
