### ISSUE TITLE
官方文档中文版404！！！

### ISSUE THREAD

**Issue by ZainIoT** [docsifyjs/docsify#1143]
## 且官方文档除英文版之外，全都不能访问。

**Comment by sy-records** [comment]
https://docsify.js.org/#/zh-cn/ 不能访问吗？

**Comment by vagra** [comment]
https://raw.githubusercontent.com/docsifyjs/docs-zh/master/README.md

用浏览器的F12调试，发现这个链接被墙了。

**Comment by vagra** [comment]
所有的以 //raw.githubusercontent.com/ 开头的链接都被墙了。

之前的版本404吗？

**Comment by vagra** [comment]
docsify.js.org 上的 index.htm 也需要更新一下。

**Comment by HerbertHe** [comment]
可以在gitee上gitee page托管一份的吧

**Comment by sy-records** [comment]
gitee pages自定义域名是收费的吧？
文档部署用的是master，现在dev分支修改了，应该等下次发布版本就会正常...

**Comment by HerbertHe** [comment]
> gitee pages自定义域名是收费的吧？
> 文档部署用的是master，现在dev分支修改了，应该等下次发布版本就会正常...

可以做个跳转emmm

**Comment by sy-records** [comment]
@ZainIoT https://sy-records.github.io/docsify-cn/#/ 可以暂时使用这个，下次发布版本以后用https://docsify.js.org/#/zh-cn/ 就可以了
