### ISSUE TITLE
how to know navigation have been fully loaded?

### ISSUE THREAD

**Issue by jerryc127** [docsifyjs/docsify#1153]
## Feature request

Dynamic change the link in nav ？

#### Are you willing to work on this yourself?

Dynamic change the link in nav ？

I want to Dynamic change the link in navigation。

so i put in hook.doneEach to call the function
but it error ,`Uncaught TypeError: Cannot set property 'href' of null`
it seen like cannot get the `document.querySelector('.app-nav>ul>li:last-child>ul>li:first-child>a')`
the navigation have not been fully loaded.

i try to add window.onload , it work but just one time, when click anoter page, it not run the function.

how to solved?
how to check the  navigation have been fully loaded ?
![image](https://user-images.githubusercontent.com/16351105/80563357-7338ac00-8a1d-11ea-9173-a02da3926053.png)

**Comment by anikethsaha** [comment]
try `hook.ready` instead.
