### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by jerryc127** [docsifyjs/docsify#1154]
#### Steps to reproduce

add the darkmode button

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
https://docs.jerryc.me/src/bottom.js
I create the dark mode button,
it work fine.
but i check the console, it error show Uncaught TypeError: Cannot read property 'tagName' of null ?
what problem ? but the function is work fine.
![image](https://user-images.githubusercontent.com/16351105/80681303-fb3cb580-8af2-11ea-9268-c1dc54e78654.png)

**Comment by anikethsaha** [comment]
can you mention how you added the dark mode. 

also, please submit a reproducible sandbox

**Comment by jerryc127** [comment]
https://github.com/jerryc127/hexo-theme-butterfly-docs/blob/master/src/bottom.js
https://github.com/jerryc127/hexo-theme-butterfly-docs/blob/master/src/bottom.js
