### ISSUE TITLE
Will docsify support .ipynb files?

### ISSUE THREAD

**Issue by Jerrywang959** [docsifyjs/docsify#1155]
## Feature request

just use .ipynb files to create site

#### What problem does this feature solve?

To create site via jupyter files, it doesn't work well to just use `jupyter nbconvert --to html` or `jupyter nbconvert --to markdown` and put it in the right place. 

If converting to markdown, there are some bugs in katex plugins and others. If converting to html,  docsify can't find its `h1,h2,h3,h4,h5,h6` to create table of content.

#### What does the proposed API look like?

None.

#### How should this be implemented in your opinion?

The simplest way is to support `h1,h2,h3,h4,h5,h6` in html.

The best way is to support .ipynb file to create site, but this might be complex

#### Are you willing to work on this yourself?

Alough I have some willing, my ability disagrees. I am still an undergrade in finance. I just can use html, css and javascript but don't know its principle. Docsify is easy to use, so I choose it. Maybe what I can do is to donate little money. Before I open this issue, I find pelican which supports ipynb files but it's not easy to use and not beautiful compared to docsify. 

My English is not vey good. Hope you could understand me.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

docsify  needs markdown files as a source to render them in runtime. It can use `.html` to show the page as well. 

I am not sure what is `.ipynb` but as far as docsify is a concern if you have `.md` as a source, you are good to go.

**Comment by Jerrywang959** [comment]
Thank you.

.ipynb file is [jupyter](https://jupyter.org/) notebook file. We use it for interactive computing across dozens of programming languages, usually in data science. It is essentially a file in json format. It contains input and output (includes the data of the image, not the external link of the picture) in a json file. 

Currently, we could use some python command to convert .ipynb file to html or markdown. But it just didn't work very well with docsify, such as oversized images and spacing. 

And this is somewhat verbose. For example, if we write a file named "test1.ipynb" and convert it to "test1.md". Then we have two files for a subpage. And once I want to edit it. First I edit test1.ipynb. Then type `jupyter nbconvert --to markdown test1.ipynb`. And then type `docsify serve`.

However, if it is integrated in docsify, we could just type  `docsify serve` to build a document and don't generate markdown files. This is similar to that docsify convert markdown files to html files but  put html files in another folder rather than the folder contains markdown files.

Having written so much, I hate that I am not able to write javascript. Maybe this function contradicts the original intention of docsify

**Comment by anikethsaha** [comment]
> This is similar to that docsify convert markdown files to html files but put html files in another folder rather than the folder contains markdown files.

docsify converts markdow content to HTML in runtime. 

> However, if it is integrated in docsify, we could just type docsify serve to build a document and don't generate markdown files.

IMO, you need some pre-build script like to run that before `docsify serve`. 

Make use of [execs](https://www.npmjs.com/package/execa), you can run commands in this. 
run the `jupyter nbconvert --to markdown test1.ipynb` first and then `docsify serve`. 
all async . 

We cant do this because it's not in the scope of this package.

**Comment by Jerrywang959** [comment]
OK. Thank you very much. I will try.

**Comment by AntHubTC** [comment]
Hello, friend! I'm from China.You can refer to my method:
Add HTML iframe tags in markdown and use the official online rendering service provided by Judge Notebook.
<iframe style="min-height:999px" width="100%" scrolling="no" title="Zdog trefoil" src="https://nbviewer.org/github/AntHubTC/AntHubTC.github.io/blob/master/NumPy/jupterDoc/base.ipynb" frameborder="no" loading="lazy" allowtransparency="true" allowfullscreen="true"></iframe>

For usage cases, please refer to: https://anthubtc.github.io/NumPy/#/base
