### ISSUE TITLE
{docsify-updated} cannot show as expected in GitHub pages

### ISSUE THREAD

**Issue by baicaihenxiao** [docsifyjs/docsify#1157]
#### Steps to reproduce
I add this script to index.html so that {docsify-updated} can be shown at the bottom of every pags.

```javascript
hook.beforeEach(function(content) {
  return content + '\n\n----\n\n' + '<p style="color: inherit; font-weight: normal; text-decoration: none; color: #828282;">Last updated <b>{docsify-updated}</b></p>';
});
```

#### What is current behaviour
It works well at my local computer, that is, the file updated at 04.22.2020 will show 04.22.2020,  the file updated at 05.04 will show 05.04. However, when I made another commit while not modify these two files at 05.05.2020，and push the new commit to GitHub, all pages depolyed in GitHub pages show 05.05.2020 at bottom. Local docsify pages still work well and show 04.22 and 05.04.

#### What is the expected behaviour
{docsify-updated} shows the same behaviour at both the local and github pages environment

---

Maybe this problem is not created by docsify, because it works at my local computer. Is it true that github modify all the files even my new commit only contains one single file?

**Comment by sy-records** [comment]
Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by JingqingLin** [comment]
> 
> 
> Please create a reproducible sandbox
> 
> [![Edit 307qqv236](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/307qqv236)
> 
> Or github repo address...

Hi, I have the same problem and I create a repo on gitee.

Repo address: https://gitee.com/JingqingLin/docsify-test
Gitee Pages address:  https://jingqinglin.gitee.io/docsify-test

The [first page](https://jingqinglin.gitee.io/docsify-test/#/first) was updated on 2020/06/02 20:42 and the [second page](https://jingqinglin.gitee.io/docsify-test/#/second) was updated on 2020/06/02 20:45, but all pages was show 2020/06/02 20:45.

**Comment by sy-records** [comment]
Can you try to run on a server without a CDN? I think this is still a caching problem. @JingqingLin

**Comment by JingqingLin** [comment]
> 
> 
> Can you try to run on a server without a CDN? I think this is still a caching problem. @JingqingLin

I put it on [VPS](http://117.78.4.128:9999/#/first), and the time is right.

If I deploy it on GitHub Pages, does `{docsify-updated}` show file modification time or show commit time?

**Comment by sy-records** [comment]
@JingqingLin You can try it use github pages.

gitee:
![image](https://user-images.githubusercontent.com/33931153/83582325-cf8a7080-a573-11ea-9837-94d8a290ef91.png)

vps:

![image](https://user-images.githubusercontent.com/33931153/83582410-f9439780-a573-11ea-8305-d8a7ca4dc618.png)

**Comment by JingqingLin** [comment]
> 
> 
> @JingqingLin You can try it use github pages.
> 
> gitee:
> ![image](https://user-images.githubusercontent.com/33931153/83582325-cf8a7080-a573-11ea-9837-94d8a290ef91.png)
> 
> vps:
> 
> ![image](https://user-images.githubusercontent.com/33931153/83582410-f9439780-a573-11ea-8305-d8a7ca4dc618.png)

I put it on [GitHub Pages](https://jingqinglin.github.io/docsify-test/#/first), `{docsify-updated}` shows commit time. But all files also show the same time. Is there any way to solve this problem?

**Comment by sy-records** [comment]
There doesn't seem to be a good solution. 😅
Get the `last-modified` value, but both the github page and the gitee page are cached release times, so they are consistent.
@anikethsaha Do you have any ideas?

**Comment by anikethsaha** [comment]
I forgot the context of this issue. I will check this soon.

**Comment by yzhang-gh** [comment]
I did a little search and found this, [Last Modified Dates for GitHub Pages Jekyll Posts](https://ryanfb.github.io/etc/2020/04/27/last_modified_dates_for_github_pages_jekyll_posts.html).

Basically, it uses GitHub API `https://api.github.com/repos/{owner}/{repo}/commits?path={path}` to get the metadata. I have checked and it does work as described (just type the url in the browser and you get a JSON array).

Now the problem is how to extract `path` from the parameter `url` here.

https://github.com/docsifyjs/docsify/blob/75c72e917bdacbf70aae124f812edcefc651a5ab/src/core/fetch/ajax.js#L61

For me it is simply taking the string after `yzhang-gh/{repo}/`. But I'm not sure whether we need to deal with other cases like custom domain.

**Comment by wallena3** [comment]
Same problem. Any progress?

**Comment by teckbond** [comment]
I have the same problem.
Every time I push new commits to github. {docsify-updated} in all pages is changed to the time of the latest push time.

but localhost the time is ok.

**Comment by sy-records** [comment]
Thank you @yzhang-gh for your comment https://github.com/docsifyjs/docsify/issues/1157#issuecomment-685443988

I provide some code for interested users to create a plugin.

Take docsify's repository as an example

```js
  window.$docsify = {
    plugins: [
      function (hook, vm) {
        hook.beforeEach(function (html) {
          date_url = 'https://api.github.com/repos/docsifyjs/docsify/commits?per_page=1&path=' + vm.config.basePath + vm.route.file;
          fetch(date_url)
            .then((response) => {
              return response.json();
            })
            .then((commits) => {
              var modified = commits[0]['commit']['committer']['date'].slice(0, 10);
              document.getElementById('last-modified').textContent = "Last Modified: " + modified;
            });
          return (
            html +
            '\n\n----\n\n' +
            '<span id="last-modified"></span>'
          );
        });
      }
    ]
  };
```

![image](https://user-images.githubusercontent.com/33931153/127762868-fa261aca-76cf-40ff-9bbc-525e7482a1ab.png)

**Comment by rxmapple** [comment]
> Thank you @yzhang-gh for your comment [#1157 (comment)](https://github.com/docsifyjs/docsify/issues/1157#issuecomment-685443988)
> 
> I provide some code for interested users to create a plugin.
> 
> Take docsify's repository as an example
> 
> ```js
>   window.$docsify = {
>     plugins: [
>       function (hook, vm) {
>         hook.beforeEach(function (html) {
>           date_url = 'https://api.github.com/repos/docsifyjs/docsify/commits?per_page=1&path=' + vm.config.basePath + vm.route.file;
>           fetch(date_url)
>             .then((response) => {
>               return response.json();
>             })
>             .then((commits) => {
>               var modified = commits[0]['commit']['committer']['date'].slice(0, 10);
>               document.getElementById('last-modified').textContent = "Last Modified: " + modified;
>             });
>           return (
>             html +
>             '\n\n----\n\n' +
>             '<span id="last-modified"></span>'
>           );
>         });
>       }
>     ]
>   };
> ```
> 
> ![image](https://user-images.githubusercontent.com/33931153/127762868-fa261aca-76cf-40ff-9bbc-525e7482a1ab.png)

try dev a plugin, see :https://github.com/rxmapple/docsify-last-modified

**Comment by rxmapple** [comment]
HI ，this is a demo plugin:
https://github.com/rxmapple/docsify-last-modified
