### ISSUE TITLE
How to generate the files for docsify?

### ISSUE THREAD

**Issue by skeddles** [docsifyjs/docsify#1160]
I can't find anything in the documentation about how to actually generate the documentation to use with docsify (meaning generating it from comments in code). Is there a specific package that's recommended that works well with docsify?

**Comment by anikethsaha** [comment]
you need to use markdown file for content. you cant generate from comments cause if we not focusing on API docs.

**Comment by Koooooo-7** [comment]
I guess u may need this one [swagger](https://github.com/swagger-api/swagger-ui).

**Comment by skeddles** [comment]
> you need to use markdown file for content. you cant generate from comments cause if we not focusing on API docs.

I don't expect this library to generate the files for me, I was hoping you would have some recommendations of other packages to use to make the MD files somewhere, since it seems like a pretty common use case.
