### ISSUE TITLE
Emoji `:+1:` not rendering 

### ISSUE THREAD

**Issue by ppipada** [docsifyjs/docsify#1162]
## Bug Report
When using `:+1:` in markdown the corresponding thumbs up is not rendering.

#### Steps to reproduce
Add `:+1:` in markdown and `docsify serve docs`

#### What is current behaviour
The string `:+1:` is displayed as is in the rendered page. 

#### What is the expected behaviour
The emoji for thumbs up( :+1: ) should be shown.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: MacOS Catalina
- Node.js version: v13.3.0
- npm/yarn version: v6.14.4
- Browser version: Chrome v81.0.xxx
- Docsify version: latest at `cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js`
- Docsify plugins: emoji

#### Please create a reproducible sandbox 

[![Sandbox](https://codesandbox.io/s/snowy-cookies-f7ipv?file=/index.html](https://codesandbox.io/s/snowy-cookies-f7ipv?file=/index.html)

#### Mention the docsify version in which this bug was not present (if any)
NA

**Comment by anikethsaha** [comment]
use `:thumbsup:` instead .

**Comment by ppipada** [comment]
@anikethsaha Got it. But `:+1:` is a standard shortcode used for thumbs up. Github markdown does support it. Any specific reason this is not supported?

**Comment by anikethsaha** [comment]
In emoji plugin we are hitting Github's  service for emoji rendering, I do think that `+` is getting encoded to `%2B` and not able to get resolved. 

need to take a look. 


may be we should change `+1` to `thumbsup` in the plugin and same for `-1` 🤔

**Comment by ppipada** [comment]
`:-1:` also has the same issue. Added this to sandbox.

**Comment by anikethsaha** [comment]
yup, we can change them to `thumbsup` and `thumbsdown` in the plugin.

**Comment by axiiomatic** [comment]
can i work on this?

**Comment by anikethsaha** [comment]
sure , go ahead 👍

**Comment by axiiomatic** [comment]
Hello @anikethsaha I'm new to the codebase, can you guide me?

**Comment by anikethsaha** [comment]
sure. let me know if you have any question.
