### ISSUE TITLE
Support Custom component

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1163]
Solution A:

---
```text
<!-- component-name -->
...
<!---->
```
---

Solution B:

---
```text
:::component-name
...
:::
```
---

Solution C:

---
```text
<docsify name='component-name' attr=''>
...
</docsify>
```
---

**Comment by trusktr** [comment]
What's the motivation here? Was there another issue describing this with more detail? (I converted the 5.0 board's card into this issue, but we can close this if there's already another issue)

**Comment by anikethsaha** [comment]
I am not sure about this. was it mentioned in v5 roadmap issue ?

I think we can close this. it was never in the roadmap.

cc @trusktr

**Comment by trusktr** [comment]
It was a simple card that I found inside `5.0!` project, then I converted it into an issue.

Yeah, it can wait. Was there a PR relating to this?

**Comment by anikethsaha** [comment]
I dont think so 👍
