### ISSUE TITLE
externalLinkRel not working if externalLinkTarget: '_blank'

### ISSUE THREAD

**Issue by denydias** [docsifyjs/docsify#1183]
## Bug Report

Re. #917 / #914, when `externalLinkTarget: '_blank'` and `externalLinkRel: 'noopener'`, href should be:

```html
<a href="https://outthere.com" target="_blank" rel="noopener">
```

but it's being generated as:

```html
<a href="https://outthere.com" target="_blank">
```

#### Steps to reproduce

1. Add an external link to a markdown file:

    ```
    [Out There](https://outthere.com)
    ```

1. Add this do `window.$docsify`:

    ```
    externalLinkTarget:  '_blank',
    externalLinkRel: 'noopener'
    ```

#### What is current behaviour

Links are generated without `rel="noopener"`. Example:

```html
<a href="https://outthere.com" target="_blank">
```

#### What is the expected behaviour

Links should have `rel="noopener"`. Example:

```html
<a href="https://outthere.com" target="_blank" rel="noopener">
```

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: GNU Linux
- Node.js version: none
- npm/yarn version: none
- Browser version: Chromium 81.0.4044.138
- Docsify version: 4.11.3
- Docsify plugins: docsify-copy-code, external-script, search, zoom-image, prism-bash, prism-json, prism-markdown, docsify-tabs

#### Please create a reproducible sandbox 

[![Edit angry-pasteur-414ut](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-pasteur-414ut)

#### Mention the docsify version in which this bug was not present (if any)

Not tested in other versions.

### PS: add to showcase

I've just published a brand new website of my company made entirely with docsify. I would appreciate to have it listed in the [showcase](https://docsify.js.org/#/awesome?id=showcase). The entry might look like:

```markdown
- [eDok](https://www.edok.com.br/) - A safe, full featured ECM (Electronic Content Management) for the paperless business.
```

**Comment by anikethsaha** [comment]
This seems like a bug. 



> ### PS: add to showcase
> I've just published a brand new website of my company made entirely with docsify. I would appreciate to have it listed in the [showcase](https://docsify.js.org/#/awesome?id=showcase). The entry might look like:
> 
> ```gfm
> - [eDok](https://www.edok.com.br/) - A safe, full featured ECM (Electronic Content Management) f
> ```

Submit a PR in [awesome-docsify](https://github.com/docsifyjs/awesome-docsify)

**Comment by denydias** [comment]
> Submit a PR in [awesome-docsify](https://github.com/docsifyjs/awesome-docsify)

Done [here](https://github.com/docsifyjs/awesome-docsify/pull/88). Thanks for the heads up.

**Comment by anikethsaha** [comment]
This has been removed somehow in this commit https://github.com/docsifyjs/docsify/commit/724ac024ddfc28e93d8b5dd909e722747286fa00#diff-d73f215ac772d2673dd8c51f24976e4eL256

Thanks for pointing. It will be fixed soon

**Comment by denydias** [comment]
Glad to help.
