### ISSUE TITLE
Change font size globally

### ISSUE THREAD

**Issue by mafanwei** [docsifyjs/docsify#1196]
## Feature request
 change font size globally

#### What problem does this feature solve?
In a website for some special people.

#### What does the proposed API look like?
```js
font-size = 7;
```

#### How should this be implemented in your opinion?
I'm not a web developer, but I don't think this will be difficult.

#### Are you willing to work on this yourself?
I'm afraid I can't.

**Comment by anikethsaha** [comment]
you can use custom styles for this.

**Comment by ianjennings** [comment]
@anikethsaha, I think this can be closed

**Comment by anikethsaha** [comment]
Thanks @ianjennings for reminding. 


@mafanwei answer here https://github.com/docsifyjs/docsify/issues/1196#issuecomment-633683423
