### ISSUE TITLE
[build] convert external dependencies (missing dependencies) into Rollup errors instead of warnings.

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1210]
Rollup by default treats missing dependencies as "external" and will only output a warning to the console instead of an error (working as intended).

We can make it throw an error for our use case.

See: https://github.com/rollup/rollup/issues/1906#issuecomment-561055996

**Comment by mohammedsahl** [comment]
I'd like to work on this. How would you suggest going about with testing? Can you tell me of a way to reproduce the missing dependencies warning. @trusktr
