### ISSUE TITLE
Sidebar: Overlapped by cover page, toggled by screen width shortening

### ISSUE THREAD

**Issue by mohammedsahl** [docsifyjs/docsify#1213]
## Bug Report

When the screen width gets shorter than 768px some unusual UI updates take place. 

#### Steps to reproduce

This [video](https://youtu.be/V47A5XUsrzQ) better demonstrates the conditions needed to reproduce this
Posting screenshots would clog this issue 😅 

#### What is current behavior

- The sidebar is positioned under the cover page UI elements
- The side bar toggles on when shortening the width

#### What is the expected behavior

- The side bar should overlap the cover screen when the sidebar-toggle-button is pressed. 
- Shortening the screen width must not cause the sidebar must not toggle on

#### Other relevant information

- Your OS: 
- Node.js version: v13.11.0
- npm/yarn version: 6.13.7
- Browser version: 83.0.4103.97
- Docsify version: 4.4.1 (CLI version)

**Comment by anikethsaha** [comment]
Thanks for the detailed report. 

I appreciate your efforts in submitting a video of the bug 😃 ,  but those might take a long time for you. 
for repro examples, you can simply write the steps or you can submit a code sandbox link as it will take less time. 

No need to change this one, as it is pretty clear from the video 😄 .


This is a bug, Feel free to submit a PR.  👍

**Comment by mohammedsahl** [comment]
It's a relatively small change. However I was wondering if the "sidebar toggling when shortening" fix should also be added to this commit.
