### ISSUE TITLE
Unable to use search plugin.

### ISSUE THREAD

**Issue by hpeixoto** [docsifyjs/docsify#1214]
#### Steps to reproduce
Accessing this url: http://54.37.231.32/
I am not able to use the search plugin. There is no data in the localstorage key on the webbrowser.

#### What is current behaviour
no data in the localstorage key on the webbrowser

#### What is the expected behaviour
Save the data in the broswer storage

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 12.16.0
- npm/yarn version: 6.4.15
- Browser version: Brave version 1.9 chromium 81.0.4044.138
- Docsify version: 
- Docsify plugins: search

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/hpeixoto/docogt)

#### Mention the docsify version in which this bug was not present (if any)
4.11.3

**Comment by sy-records** [comment]
You need to fill out the `_sidebar.md`. see https://docsify.js.org/#/more-pages?id=sidebar

![image](https://user-images.githubusercontent.com/33931153/84558777-bb125900-ad67-11ea-989d-3c8a0189a62c.png)
