### ISSUE TITLE
add tests!

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1217]
This is a meta issue. We should put some focus on stabilizing the source by adding unit and e2e tests. Test infrastructure is already in place thanks to @anikethsaha.

We can create separate issues for testing specific parts, and assign to ourselves so other will know what to work on without duplicating efforst.

**Comment by anikethsaha** [comment]
Having some more unit tests, integration tests would be great. 
I think the current setup for unit tests are not working completely to test all parts. We need to check that.
