### ISSUE TITLE
issue triage

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1218]
There are a bunch of issues that we should triage and prioritize. Normally we don't need to make meta issues like this one, but wanted to get it on people's radar. We should go through issues and label them and place them onto a project board (and the order they appear on the project board can indicate priority).

**Comment by jhildenbiddle** [comment]
From Discord thread:

> I am definitely in favor of cleaning up the projects though. Here are some suggestions:
> 
>- Use a consistent name for version-based projects. We currently have "4.x" and "5.0!". My vote would be for "4.x" and "5.x", using milestones to target minor or point releases if necessary (otherwise it's just extra work to manage this meta data).
>- Triage issues from "Issues" project, move to 4.x or 5.x project or close the issue, then remove the "Issues project.
>- Triage ideas from "Ideas" project, create issues as needed, delete cards, then delete the "Ideas" project.
>- Create a "Triage" project and use project-bot or a GitHub action to automatically add new issues and PRs to this project for easier review.
> 
> The end result would be three projects: "4.x", "5.x" and "Triage". I'm happy to handle these changes if the team agrees. Comments/feedback welcome.

When this work is complete the new Triage project should make working with issues much easier. Aside from that, perhaps we could ask maintainers to take a look at the Triage project and contribute where they can on a specific day each week (or whatever schedule we come up with).

Thoughts?

**Comment by anikethsaha** [comment]
> When this work is complete the new Triage project should make working with issues much easier. Aside from that, perhaps we could ask maintainers to take a look at the Triage project and contribute where they can on a specific day each week (or whatever schedule we come up with).
> 
> Thoughts?

Yea, make sense

**Comment by jhildenbiddle** [comment]
Closing this issue since Projects have been updated and the triage is underway.
