### ISSUE TITLE
mobile site scrolls sideways now

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1219]
## Bug Report

The mobile site scrolls horizontally a little bit. (This is not published yet)

The current live site at docsify.js.org does not have this bug yet.

#### Steps to reproduce

go to mobile mode and try scrolling horizontally:

#### What is current behaviour

![scroll-sideways](https://user-images.githubusercontent.com/297678/84561257-c3cf4480-acff-11ea-8749-2ed35fba1a8e.gif)

#### What is the expected behaviour

does not scroll sideways:

![no-scroll-sideways](https://user-images.githubusercontent.com/297678/84561262-cb8ee900-acff-11ea-80c9-d099cf9b60a6.gif)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Linux
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: develop
- Docsify plugins: whatever the docsify site has

#### Please create a reproducible sandbox 

https://docsify-preview-git-fork-mlh-fellowship-1213-fix-sidebar-toggle.docsify-core.vercel.app/#/

**Comment by anikethsaha** [comment]
Can we fix this in https://github.com/docsifyjs/docsify/pull/1215 itself ?

**Comment by jhildenbiddle** [comment]
Strange. I'm not seeing this behavior on iPhone (XS Max) or iPad.

Which device(s) are you testing on?

**Comment by mohammedsahl** [comment]
> Can we fix this in #1215 itself ?

Yeah definitely. I have a few questions though. Was this caused after merging in #1215 in anyway? And what device is this problem occurring on? I've tested all the ones Chrome devtools has to offer

![image](https://user-images.githubusercontent.com/32067562/84566686-3280c200-ad41-11ea-9a3b-b4f449ecfda1.png)

**Comment by jhildenbiddle** [comment]
Possibly related (since I'm not seeing this scroll issue either): https://github.com/docsifyjs/docsify/pull/1215#issuecomment-643677786

**Comment by trusktr** [comment]
> Which device(s) are you testing on?

Chrome mobile emulation (in Linux) but not on Android. Hmmmm...

> Was this caused after merging in #1215 in anyway?

I don't think it was.

**Comment by jhildenbiddle** [comment]
FWIW, I'm not seeing this behavior on iOS (real device) or the Chrome emulator.

@trusktr -- Are you looking at docsify.js.org (v4.11.4)? I ask because the screenshots show 4.11.3.

**Comment by trusktr** [comment]
At the moment I'm not seeing this on docsify.js.org.
