### ISSUE TITLE
regression: hamburger menu icon not visible on mobile until after scrolling a little

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1223]
## Bug Report

Regression: the mobile menu is out of view by default now

#### Steps to reproduce

Visit a docsify site on mobile.

#### What is current behaviour

On the latest vercel preview that I grabbed from #1215, https://docsify-preview-p88m1zgcc.vercel.app, I am not able to see the hamburger menu on mobile unless I scroll:

![menu-hidden](https://user-images.githubusercontent.com/297678/84630122-51e23100-aea0-11ea-83d3-b4b5390dc9c7.gif)

#### What is the expected behaviour

The menu should be visible I think, like it is on docsify.js.org currently.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: develop
- Docsify plugins:

**Comment by mohammedsahl** [comment]
Is this still an issue after #1215? We decided not to translate the cover page hence zoom should be disabled. If required I can work on copying the current "sidebar and content" behavior onto the coverpage such that nothing is rendered beyond the viewport
@trusktr

**Comment by trusktr** [comment]
I believe this is a different issue: at the bottom left corner, the hamburger menu icon isn't visible until I scroll the page up.

**Comment by jhildenbiddle** [comment]
@trusktr --

I'm not seeing this behavior on docsify.js.org on an iPhone, Chrome Dev Tools, or Safari's Responsive Design Mode. Can you verify if this is still an issue?

**Comment by paulhibbitts** [comment]
Re-tested with Android Phone, iPhone, and Safari Responsive Design Mode, so closing issue - please feel free to re-open if issue is still seen.
