### ISSUE TITLE
英文分号会被渲染成图片

### ISSUE THREAD

**Issue by jrmaker** [docsifyjs/docsify#1231]
"10:00:00" 启动服务查看时，英文分号部分显示一个英文小图片，谷歌浏览器会有该问题，在火狐浏览器中，中间两个00 位置会偏下

**Comment by jrmaker** [comment]
该问题存在markdown表格中

**Comment by jrmaker** [comment]
在markdown的表格中，

**Comment by jrmaker** [comment]
|参数|说明|
|:--|:--|
|startTime|"10:00:00"|

“10:00:00” 在谷歌浏览器中，第一个英文分号会被渲染成小图片

版本

**Comment by anikethsaha** [comment]
Please translate to English.

**Comment by sy-records** [comment]
把`:00:`当成图片渲染了，你这种情况可以使用\`或者`&#58;`来转义`:`

```markdown
|startTime|10&#58;00:00|

|startTime|`10:00:00`|
```


请用英文提问。

**Comment by jrmaker** [comment]
think you

**Comment by jrmaker** [comment]
Thank you

**Comment by jrmaker** [comment]
Thank you
