### ISSUE TITLE
how to change entry file (index.html)?

### ISSUE THREAD

**Issue by wangck-uhome** [docsifyjs/docsify#1239]
for some reasons , I have to change entry file, for explem doc.html

**Comment by anikethsaha** [comment]
Please Fill the template

**Comment by sy-records** [comment]
`index.html` is the general sense of "home", if you need to modify, you can deploy in the VPS, modify the `index`

https://docsify.js.org/#/deploy?id=vps

```
  location / {
    alias /path/to/dir/of/docs/;
    index doc.html;
  }
```
