### ISSUE TITLE
how to set the width of table's cell?

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#1242]
#### What problem does this feature solve?

I want to set the with of table's cell, for beautiful

#### What does the proposed API look like?

the minimum with is equal to the second row‘s ’----‘ with at least

#### How should this be implemented in your opinion?

set the minimum with as the  second row‘s ’----‘ with

#### Are you willing to work on this yourself?
no, I'm not

**Comment by Koooooo-7** [comment]
Docsify render the md files in a normal way.
Maybe u can search for the method to set the width of table cell in md or adding ur customized styles for the table cell elements.
