### ISSUE TITLE
Some Website Links Redirect To 404 Not Found Page

### ISSUE THREAD

**Issue by aemmadi** [docsifyjs/docsify#1244]
## Bug Report
Links on website give a `404 Not Found Error`

#### Steps to reproduce
The links I found that have the issue:

[https://docsify.js.org/#/contributing](https://docsify.js.org/#/contributing)

[https://docsify.js.org/#/license](https://docsify.js.org/#/license)

#### What is current behaviour
Renders the `404 Not Found` page.

#### What is the expected behaviour
Render the appropriate page (i.e Contributing.md and License.md)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 10.16.0
- npm/yarn version: 6.9.0
- Browser version: Chrome 83
- Docsify version: 4.11.3
- Docsify plugins: N/A

#### Please create a reproducible sandbox 
Error is directly in production website [https://docsify.js.org](https://docsify.js.org/)
[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
Not sure.

**Comment by Koooooo-7** [comment]
thx for ur report!
it seems our put wrong links on the docs.

**Comment by sy-records** [comment]
Fixed via https://github.com/docsifyjs/awesome-docsify/commit/3dd0a5ae51ab4263e53bfdcb796faa471550f0c0
