### ISSUE TITLE
how to hide the scroll bar

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#1245]
#### What problem does this feature solve?

the default with of scroll bar is wide, It's ugly

#### What does the proposed API look like?

hide the scroll bar or set the with to 0

#### How should this be implemented in your opinion?

gei me a config arg to hide the bar or set the with

**Comment by anikethsaha** [comment]
You can do that using a custom css.

**Comment by tonglei100** [comment]
> I dont think we can implement from our side as support for the scrollbar styling in IE11 is not solid as of now I guess.
> 
> Thanks

I open the site in Chrome or EDGE, it's scrollbar also with :(

**Comment by anikethsaha** [comment]
can you explain, I didnt get you

**Comment by tonglei100** [comment]
the browser‘s scrollbar is width, look the picture right, I want it litter like the sidebar's scrollbar, thank you!  


![scroll](https://user-images.githubusercontent.com/530089/85807286-08d58b00-b784-11ea-9bd8-8f7e33806b27.png)
