### ISSUE TITLE
Need a "back to top" button

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#1246]
#### What problem does this feature solve?

My pages is so longer, I hope have a button back to top

#### How should this be implemented in your opinion?

a button on the right bottom

**Comment by Koooooo-7** [comment]
I know a 3rd part plugins of docsify ([docsify-scroll-to-top](https://github.com/zhengxiangqi/docsify-scroll-to-top#readme)) which will add a `Top` button to back top..
I guess it can help u for now.

**Comment by tonglei100** [comment]
thank you
