### ISSUE TITLE
The sidebar's maxLevel is not show

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#1248]
#### Steps to reproduce

I set as this:      
maxLevel: 4,
subMaxLevel: 3,

when I click the level 3 title, look at  https://report.sweeter.io/#/latest/Baidu?id=baidu-1

#### What is current behaviour

the level 4 is not show

#### What is the expected behaviour

the level 4 title is show

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
you need set `subMaxLevel` to `4`.

`maxLevel` takes effect when you don't set `_sidebar.md`

**Comment by tonglei100** [comment]
> you need set `subMaxLevel` to `4`.
> 
> `maxLevel` takes effect when you don't set `_sidebar.md`

其实我是想像 docsify 官网那样，默认只展示到3级标题，当点击3级标题时，该3级标题下面的4级标题才展示出来；如果再点其他1~3级标题时，刚才展开的4级标题会收起。我看官网就是这么配置的，但是 我就是不行呢

**Comment by sy-records** [comment]
你的baidu就等于配置项这一层。

**Comment by tonglei100** [comment]
OK，明白了，谢谢:)

**Comment by tonglei100** [comment]
@sy-records 借楼请教一个问题，插件 [Zoom image](https://docsify.js.org/#/zh-cn/plugins?id=%e5%9b%be%e7%89%87%e7%bc%a9%e6%94%be-zoom-image) 该如何配置图片的默认显示尺寸呢？

现在图片正常展示的还是比较大，我想以很小的缩略图来显示，用户点击后才放大展示

期待回复，谢谢~

**Comment by sy-records** [comment]
https://docsify.js.org/#/zh-cn/helpers?id=%e5%9b%be%e7%89%87%e5%a4%84%e7%90%86
