### ISSUE TITLE
How to get lastUpdated date of page?

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1266]
## Bug Report
I am trying to display the lastupdate time on each page. However, the lastupdated time o all pages is the same, even though I just updated one of them. 

#### Steps to reproduce
I am using this to get the time:

```
...
hook.beforeEach(function(html) {
  return addLastUpdatedPlaceholder(html);
});

hook.afterEach(function(html, next) {
  const plugins = [insertLastUpdated];
  const finalHtml = plugins.reduce((accHtml, plugin) => plugin(accHtml), html);
  next(finalHtml);
});
...

function addLastUpdatedPlaceholder(html) {
    var footer = [
        '\n<footer class="last-updated">',
        `<small>__lastupdated__</small>`,
        '</footer>'
    ].join('');
    return html + footer;
}

function insertLastUpdated(html) {
    return html.replace(/__lastupdated__/, `Page last updated: ${window.$docsify.lastUpdated}`);
}
```

#### What is current behaviour
Displaying same time on all pages.

#### What is the expected behaviour
Display time of when page was last updated.

#### Other relevant information

- [ x] Bug does still occur when all/other plugins are disabled?

- Your OS: OSX
- Node.js version: 10.15.3 
- npm/yarn version: 6.4.1
- Browser version: Chrome 83
- Docsify version: 4.4.0
- Docsify plugins: Custom

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by anikethsaha** [comment]
docsify doesnt support that officially. may be there are some plugins out there I am not aware of that.

What I can suggest is to hit the github API and get the latest commit and use that commit date ?

**Comment by joetidee** [comment]
I think this did it:

```
function addLastUpdatedPlaceholder(html, lastUpdated) {
    var footer = [
        '\n<footer class="last-updated">',
        `<small>Page last updated: ${lastUpdated}</small>`,
        '</footer>'
    ].join('');
    return html + footer;
}
```

As per, https://github.com/docsifyjs/docsify/blob/314e2d9d39a024270403a42eb19bd98e6cce8d17/docs/write-a-plugin.md

**Comment by sy-records** [comment]
The reason for displaying the same time is because the acquisition is the time of the last deployment.

When deploying with github pages, the header information is updated to the same time for all pages in one deployment.

Similar issues: #1157 #1142

**Comment by sy-records** [comment]
you can use `{docsify-updated}`

for example :

```javascipt
window.$docsify = {
  plugins: [
    function(hook, vm) {
      hook.beforeEach(function(html) {
        return (
          html +
          '\n----\n' +
          'Last modified {docsify-updated} ' 
        );
      });
    }
  ]
};
```

However, if you deploy using a github page, you usually get the same time.

**Comment by Immortalt** [comment]
> you can use `{docsify-updated}`
> 
> for example :
> 
> ```
> window.$docsify = {
>   plugins: [
>     function(hook, vm) {
>       hook.beforeEach(function(html) {
>         return (
>           html +
>           '\n----\n' +
>           'Last modified {docsify-updated} ' 
>         );
>       });
>     }
>   ]
> };
> ```
> 
> However, if you deploy using a github page, you usually get the same time.

I used your method but I did't see the time on the page.
It's just empty.
https://immortal-blog.github.io/#/devops/create-a-private-ubuntu-mirror
