### ISSUE TITLE
Restore codefund plugin to plugin list.

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1268]
The issue it had with IE 11 is fixed: https://github.com/njleonzhang/docsify-plugin-codefund/issues/6

But if any plugin has browser compatibility issue, perhaps we shouldn't remove it. After all we aren't testing all of them. We should state that third party plugins come with no Docsify guarantees.

**Comment by anikethsaha** [comment]
codefund has been shutdown. the plugin will become non functional soon. So I guess it wont make sense to add again as the service itself is shutdown.

**Comment by trusktr** [comment]
> codefund has been shutdown


oooh, I didn't realize that part! :) There was no point in fixing it then. :laughing:
