### ISSUE TITLE
Add docsify-plugin-carbon support for carbon ads

### ISSUE THREAD

**Issue by waruqi** [docsifyjs/docsify#1275]
I written a docsify plugin for carbon ads, you can try it instead of codefund.

https://github.com/waruqi/docsify-plugin-carbon

# docsify-plugin-carbon

A plugin to make you easy to join up [Carbon](https://www.carbonads.net/)

# Usage

```
<script src="//cdn.jsdelivr.net/npm/docsify-plugin-carbon@1.0.0/index.min.js"></script>
```

```
window.$docsify = {
  plugins: [
    // change to your Carbon property id
    DocsifyCarbon.create('CE7I52QU', 'xmakeio')
  ]
}
```

# Sample

[xmake.io](https://xmake.io/#/getting_started)

![](https://cdn.jsdelivr.net/gh/waruqi/docsify-plugin-carbon@master/sample.png)

**Comment by anikethsaha** [comment]
THanks a lot for the plugin.

We have decided to not go with ads in our docs as of now. You can submit PR in the `awesome-docsify` repo to add a link to your plugin.

**Comment by waruqi** [comment]
Ok, thanks!

**Comment by waruqi** [comment]
https://github.com/docsifyjs/awesome-docsify/pull/103  I have submited a pr.
