### ISSUE TITLE
Will valine support it?

### ISSUE THREAD

**Issue by zygds** [docsifyjs/docsify#1310]
#### What problem does this feature solve?
Will valine support it?
#### What does the proposed API look like?
https://valine.js.org/

**Comment by anikethsaha** [comment]
Please give some more info

cc @Koooooo-7 @sy-records

**Comment by zygds** [comment]
Comment system
valine

**Comment by zygds** [comment]
Can you support it

**Comment by sy-records** [comment]
Looks like `Gitalk`, currently does not support `valine`

**Comment by anikethsaha** [comment]
@zygds  Feel free to make a custom plugin for this and add a link to `awesome-docsify` repo. 

Looking forward for this. 

Thanks

**Comment by zygd-s** [comment]
I won't, so I asked the government to make this one, because gittalk has a requirement for links, and the length is limited to 50，tks very much
