### ISSUE TITLE
Add SSR option or independent script  file!

### ISSUE THREAD

**Issue by ghost** [docsifyjs/docsify#1312]
## Feature request
Add SSR option or independent script  file!

#### What problem does this feature solve?
Solve the problems left by the history of SSR mode

#### What does the proposed API look like?
1.  👉 Automatically generate toc and add it to the existing sidebar instead of overwriting
2.  👉 Switching support for the sidebar
3.  👉 The rest of the script content is recommended to be closed

#### How should this be implemented in your opinion?
Need your help!

#### Are you willing to work on this yourself?
Yes!

**Comment by Koooooo-7** [comment]
sounds cool, waiting for your contribution. :+1:

**Comment by saowang** [comment]
Next SSR: 

Use jekyll to support search data and sidebar ...!

**Comment by saowang** [comment]
:+1:  https://rundocs.github.io/jekyll-theme-docsify/
