### ISSUE TITLE
markdown mermaid

### ISSUE THREAD

**Issue by zygds** [docsifyjs/docsify#1314]
![image](https://user-images.githubusercontent.com/50038957/88657267-3ce5f800-d104-11ea-8a1d-993cf52e1bbb.png)
please add this

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/88657943-3a37d280-d105-11ea-8c68-4efe2c7b7793.png)

**Comment by sy-records** [comment]
Please follow the template for questions and use English.
