### ISSUE TITLE
Request to support markdown Mermaid

### ISSUE THREAD

**Issue by zygds** [docsifyjs/docsify#1316]
## Feature request
Request to support markdown Mermaid
#### What problem does this feature solve?
Solve the problem that the browser cannot view the preview of markdown Mermaid

#### What does the proposed API look like?

Compatible support

#### How should this be implemented in your opinion?

Need your help!

#### Are you willing to work on this yourself?
No,Because I don't know the web

This is WEB using Mermaid
![](https://user-images.githubusercontent.com/50038957/88657267-3ce5f800-d104-11ea-8a1d-993cf52e1bbb.png)
This is typora using Mermaid
![](https://user-images.githubusercontent.com/50038957/88657943-3a37d280-d105-11ea-8c68-4efe2c7b7793.png)

**Comment by sy-records** [comment]
see https://docsify.js.org/#/markdown?id=supports-mermaid

**Comment by sy-records** [comment]
Need to load `mermaid.min.js` before `window.$docsify`, Error messages can be viewed in the console tool.
