### ISSUE TITLE
Request to repair PC style

### ISSUE THREAD

**Issue by zygds** [docsifyjs/docsify#1317]
#### Steps to reproduce
Request to repair PC style
Auto shrink table

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
no, I can`t

![image](https://user-images.githubusercontent.com/50038957/88660468-576ea000-d109-11ea-89d4-deb3c77923dd.png)
![image](https://user-images.githubusercontent.com/50038957/88660474-5a699080-d109-11ea-96c6-be2adeb1f3b1.png)

**Comment by sy-records** [comment]
Please follow the template to ask questions and check your theme style.
