### ISSUE TITLE
test: discord webhook

### ISSUE THREAD

**Issue by sy-records** [docsifyjs/docsify#1326]
#### Steps to reproduce

test: discord webhook

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Sorry to interrupt. It's just a test.

**Comment by anikethsaha** [comment]
No issue @sy-records , feel free to carry on with your tests
