### ISSUE TITLE
the search plug can't work at all

### ISSUE THREAD

**Issue by turtlekey** [docsifyjs/docsify#1327]
## Bug Report
- the search plug can't work at all, maybe because I set up the *index.html* manuall, instead of `docsify-cli`
- some issues about this problem are not helpful for me

#### Steps to reproduce
- all has been done according to [the guide](https://docsify.js.org/)

#### What is current behaviour
- there is no valid localstorage content in browser, but has two keys:
  - `"enabledExtension": "csineneo-lang-traditional-chinese"`
  - `"welcomeHidden": "true"`

#### What is the expected behaviour
- appear valid localstorage content in browser and make the search plug work

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: `centos-release-7-8.2003.0.el7.centos.x86_64`
- Node.js version: **no use**
- npm/yarn version: **no use**
- Browser version: `chrome 84.0.4147.105`
- Docsify version: **unknown, set up manually** 
- Docsify plugins: **only** `plugins/search.min.js`

#### Please create a reproducible sandbox 
the `codeSandbox` is [here](https://codesandbox.io/s/billowing-thunder-wp7j0)

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
per to your information， it is hard to know where the problem is.
can you provide your configurations/files or `CodeSandbox` to make it reproducible ?

and I recommend you use the docsify-cli instead of creating initial the files manually.

**Comment by turtlekey** [comment]
> per to your information， it is hard to know where the problem is.
> can you provide your configurations/files or `CodeSandbox` to make it reproducible ?
> 
> and I recommend you use the docsify-cli instead of creating initial the files manually.

**Comment by turtlekey** [comment]
> per to your information， it is hard to know where the problem is.
> can you provide your configurations/files or `CodeSandbox` to make it reproducible ?
> 
> and I recommend you use the docsify-cli instead of creating initial the files manually.

**Thanks for your reply!**
- Now I have created a `CodeSandbox` about this problem, click [here](https://codesandbox.io/s/billowing-thunder-wp7j0), you can find the `search plug` can't work.
- Besides, I also tried to create the initial files by `docsify-cli`, but there are some errors as following:
```bash
/usr/lib/node_modules/docsify-cli/node_modules/update-notifier/index.js:74
                        (async () => {
                               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/docsify-cli/bin/docsify:5:24)
```
- So where is the problem from? And what shoud I do?

**Comment by Koooooo-7** [comment]
@turtlekey  
thx for ur details.
According to the sandbox configurations, u need remove the `path`, cuz u defined the search path is empty.
and ur test titles r `### title` which have the depth is 3.

suggest:

```
search:{
path: [ ] , //  remove this
depth: 2 // make it bigger than 2
}
```

**Comment by Koooooo-7** [comment]
About the `docsify-cli`, trying to update the node version and install the latest cli again. waiting for the feedback here.

**Comment by turtlekey** [comment]
> About the `docsify-cli`, trying to update the node version and install the latest cli again. waiting for the feedback here.

**^GREAT and WONDERFUL^, this problem has been resolved with your help, thanks so much!** 
I think there are some points about  `search plug`  the newbies(just like me) should be careful, as following:
- It is so easy and convenient to create the initial files manually, a working configure about `seach plug` is like
```javascript
<script>
        window.$docsify = {
        loadSidebar: true,
        subMaxLevel: 6,
        maxLever: 6,
        //auto2top: true,
        //search: 'auto',
        search: [
            '/websites/engine',
            '/websites/work-design',
            ],
        search: {
            maxAge: 86400000,
            //paths: [],
            placeholder: 'please search',
            noData: 'please replace your keyword',
            depth: 6,
            }
        }
    </script>
......
<script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
```
- The version of `npm` should not be too old. In my case, the version `3.10.10` can't work, but the version `6.14.6` work well.

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/89165796-a73ae480-d5ab-11ea-98cc-c60737a45851.png)
These are the three search configurations, you just need to choose one.

**Comment by turtlekey** [comment]
> ![image](https://user-images.githubusercontent.com/33931153/89165796-a73ae480-d5ab-11ea-98cc-c60737a45851.png)
> These are the three search configurations, you just need to choose one.

Ok, got it. I'm just a newbie for programming, and now I wonder whether we can count the search results, locate them, and highlight them in `content box` , not `search box`, just like the `find mode` in `vim`. Waiting for reply.

**Comment by sy-records** [comment]
No support, you can use ctrl+f to search the current page.

**Comment by turtlekey** [comment]
> No support, you can use ctrl+f to search the current page.

It's a way, but I want to make others use. Thank you anyway.
