### ISSUE TITLE
can't get Element by javascript

### ISSUE THREAD

**Issue by turtlekey** [docsifyjs/docsify#1333]
## Bug Report
I just want to get an element by the function `document.querySelector("aside.sidebar")` with js, but I found that neither with an outside `index.js` or directly embedding it in `index.html`, it can't work, just return `null` or `undefined`, and other functions like `document.getElementsByClassName` and  `document.getElementsByTagName` can't work either. I also changed the squence of all scripts in `index.html`, but it failed.  However, these functions work well in the console of Chrome. So where is the problem from, and what should I do?

attached my `index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- Theme: Simple -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple.css">
    <link rel="shortcut icon" href="/static/index.ico">
    <script>
    !function () {
            var width = window.outerWidth;
            if (width > 900) {
                var head = document.head;
                var css = document.createElement("link");
                css.setAttribute("rel","stylesheet");
                css.setAttribute("href","/static/index.css");
                head.appendChild(css);
            }
        }()
    </script>
</head>
<body>
    <div id="app"></div>
    <script>
        window.$docsify = {
        loadSidebar: true,
        subMaxLevel: 6,
        maxLever: 6,
        }
    </script>
<script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0"></script>
</body>
</html>
```
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: `win10`
- Node.js version: `manually`
- npm/yarn version: `manually`
- Browser version: `Google Chrome | 84.0.4147.105`
- Docsify version: `manually`
- Docsify plugins: `none`

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by anikethsaha** [comment]
Thanks for the issue

This is because those are not yet mounted when the script is being run. You can use the docsify hooks to work with them 
like `ready` hook
[refer more here](https://docsify.js.org/#/write-a-plugin)

**Comment by turtlekey** [comment]
> Thanks for the issue
> 
> This is because those are not yet mounted when the script is being run. You can use the docsify hooks to work with them
> like `ready` hook
> [refer more here](https://docsify.js.org/#/write-a-plugin)

Thanks for reply. Here is another question is that how to make anchor for each subtitle in the `_sidebar`, it looks like some easy ways exists in `docsify`, but I have not found out.

**Comment by sy-records** [comment]
> Thanks for reply. Here is another question is that how to make anchor for each subtitle in the `_sidebar`, it looks like some easy ways exists in `docsify`, but I have not found out.

The anchor is added automatically, you can also specify the id. https://docsify.js.org/#/helpers?id=customise-id-for-headings

**Comment by trusktr** [comment]
@turtlekey Closing this as it isn't a feature request or bug, but feel free to discuss if you still need help. Also a better place to chat about help may be on our Discord chat server: https://discord.gg/3NwKFyR

**Comment by trusktr** [comment]
If you want to manipulate DOM after it is rendered, you will need the `doneEach` hook. That will be called once all the markdown is converted into elements in the DOM.
