### ISSUE TITLE
how to make anchor for  markdown-section

### ISSUE THREAD

**Issue by turtlekey** [docsifyjs/docsify#1334]
## Bug Report
Maybe there are some ways inside `docsify` to make anchor, can someone tell me?
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by anikethsaha** [comment]
use javascript and docsify plugin hooks for that

**Comment by turtlekey** [comment]
> use javascript and docsify plugin hooks for that

got it, thank you very much!
