### ISSUE TITLE
Broken display URL's in headers

### ISSUE THREAD

**Issue by arjun-1** [docsifyjs/docsify#1353]
## Bug Report
Going from 4.11.4 to 4.11.5 we noticed that the display of our auto generated changelogs in the sidebar changed .

#### Steps to reproduce
Use Docsify 4.11.5 or higher. Use a sidebar backed by for example the following markdown
```
### [1.2.1](https://github.com) (2020-08-24)

## [1.2.0](https://github.com) (2020-08-21)


### Features

* feature a

## [1.1.0](https://github.com) (2020-07-24)


### Features

* feature b

### [1.0.35](https://github.com) (2020-06-24)


```

#### What is current behaviour
The listing of headers is malformed. Also the links are no longer working in the sidebar:
![Screenshot from 2020-08-24 11-57-27](https://user-images.githubusercontent.com/8102654/91031545-06b36f80-e601-11ea-9342-d70a398b316c.png)

#### What is the expected behaviour
Proper listing of the changelog, with working links in the sidebar

![Screenshot from 2020-08-24 11-57-11](https://user-images.githubusercontent.com/8102654/91031556-0a46f680-e601-11ea-8daf-edc69babed6c.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 18.04.5 LTS
- Node.js version: v12.16.1
- npm/yarn version: 1.22.4
- Browser version: 84.0.4147.135
- Docsify version: 4.11.5
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
4.11.4

**Comment by sy-records** [comment]
Thank you for your feedback, we are aware of this issue and will fix it in the next version!

You can use the lower version for now, Or if you can build it yourself, you can use the code in #1336 to build it.

 fixed via #1336

**Comment by adrianbj** [comment]
I am also seeing this here: https://adrianbj.github.io/TracyDebugger/#/debug-bar

How far away do you think a fix will be? Thanks.

**Comment by adrianbj** [comment]
Maybe this isn't related to the issue I am seeing, but it hasn't fixed the issue I noted above.

**Comment by sy-records** [comment]
@adrianbj well, I see you used img, I'll see how to fix it later.

**Comment by adrianbj** [comment]
@sy-records - thanks for looking into it - not sure when it stopped working properly - it was OK for many years.

**Comment by sy-records** [comment]
@adrianbj done.

**Comment by adrianbj** [comment]
Thanks @sy-records - let's hope it is merged soon so that this is actually fixed on sites using docsify.

**Comment by adrianbj** [comment]
@sy-records - any word on when a new version might be released so that this fix is actually applied to everyone's doc sites?

**Comment by sy-records** [comment]
@adrianbj I'm not sure, but I've created a nightly version and you can use this https://github.com/sy-records/docsify-nightly

**Comment by adrianbj** [comment]
Thanks @sy-records - that's really helpful and everything is working with your bugfix.

Just a quick note that you omitted the `/lib/` component for the path to the theme css file in the usage example in the Readme. It seems to me that you'd want to point users to the minified version inside `/lib/`, or am I missing something?

Thanks again!

**Comment by sy-records** [comment]
Both are fine, I copied them from the document... https://docsify.js.org/#/quickstart?id=manual-initialization
