### ISSUE TITLE
请帮忙看看问题，谢谢~

### ISSUE THREAD

**Issue by heyuhang21** [docsifyjs/docsify#1354]
你好，比如我按您的方式在gitee配置了目前非常正确，但是我出现了一个问题就是
我第一次点击图标登录，他会弹出授权信息等一系列，或者直接跳转到码云里，然后通过QQ登录再回调到页面首页中，那我这个时候退出登录(因为我的第三方信息我保存到了redis里)清空了redis里的数据，当我再次点击gitee图标登录的时候，他不会再出现授权的框了，直接就返回主页面了，这个时候我的疑问就来了，万一用户这个时候想要再换一个授权账号应该怎么办呢？难道要用户F12去清空缓存吗，我比较菜，问一下~

**Comment by sy-records** [comment]
你的问题和docsify无关。

**Comment by saowang** [comment]
呃呃呃呃呃！

在 2020年8月25日，下午3:43，沈唁 <notifications@github.com> 写道：

﻿

Closed #1354<https://github.com/docsifyjs/docsify/issues/1354>.
