### ISSUE TITLE
Cannot read property 'level' of undefined

### ISSUE THREAD

**Issue by jesobreira** [docsifyjs/docsify#1356]
#### Steps to reproduce

Run the following README.md:

```README.md
# Heading 1

Test

## Heading 2

### Heading 3A

Lorem ipsum

#### Heading 4A

##### Heading 5A

Lorem ipsum

### Heading 3B

Lorem ipsum

#### Heading 4B <!-- {docsify-ignore} -->

##### Heading 5B

Lorem ipsum
```

#### What is current behaviour

The sidebar does not show up and the console shows:

```

```docsify.min.js:1 Uncaught TypeError: Cannot read property 'level' of undefined
    at $n.sidebar (docsify.min.js:1)
    at Vn.Xn._renderSidebar (docsify.min.js:1)
    at Vn.Pn (docsify.min.js:1)
    at docsify.min.js:1
    at o (docsify.min.js:1)
    at B (docsify.min.js:1)
    at t (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
    at docsify.min.js:1
```

#### What is the expected behaviour

Sidebar shows up

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS Catalina
- Node.js version: 12.18.3
- npm/yarn version: 6.14.6
- Browser version: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- Docsify version: 4.11.6
- Docsify plugins: none

#### Please create a reproducible sandbox 

[![Code Sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-cdn-16042)

**Comment by sy-records** [comment]
I can't reproduce your question.

The `README.md` will not show up in the sidebar, you need to add `- [README](README.md)` to `_sidebar.md`

![image](https://user-images.githubusercontent.com/33931153/91239595-90cf1580-e772-11ea-9daa-b78b32e0698a.png)

**Comment by sy-records** [comment]
https://github.com/docsifyjs/docsify/issues/1355#issuecomment-680351473 As with this one, you need to add configuration items.

```
Cannot read property 'level' of undefined
```
This is an exception message that we can optimize

**Comment by jesobreira** [comment]
I'm not using a custom _sidebar.md, rather I'm trying to use the auto-generated table of contents. Does it make any difference?

**Comment by sy-records** [comment]
No problem, here's a bug.
