### ISSUE TITLE
Cannot read property 'indexOf' of undefined 

### ISSUE THREAD

**Issue by virain** [docsifyjs/docsify#1363]
## Bug Report
Error configuring SSR

Cannot read property 'indexOf' of undefined 

- Your OS: 
- Node.js version: v10.22.0
- npm/yarn version:  6.14.6
- Browser version:  edge
- Docsify version:  4.4.1
- Docsify plugins:  none

**Comment by sy-records** [comment]
There is something wrong with ssr now. 🤣

**Comment by virain** [comment]
> ssr 现在出了问题。🤣

/(ㄒoㄒ)/~~   Can't it be fixed? 😭

**Comment by sy-records** [comment]
It should be fixed, but we don't know when...

Maybe it'll be fixed by #1311.

**Comment by virain** [comment]
Can it be released in the next version?
Waiting for V5 is too long.....

**Comment by mattvb91** [comment]
Experiencing the same issue currently.

**Comment by ngthtung** [comment]
+1, I cannot use SSR because same problem _Cannot read property 'indexOf' of undefined_ 😢

**Comment by trusktr** [comment]
Hello! It will be fixed in #1227.

**Comment by trusktr** [comment]
> Can it be released in the next version?
> Waiting for V5 is too long.....

Yes, it's coming soon, in v4

**Comment by jhildenbiddle** [comment]
Closing as SSR is deprecated for v5.
