### ISSUE TITLE
Support Vue3

### ISSUE THREAD

**Issue by nichtich** [docsifyjs/docsify#1364]
#### What problem does this feature solve?

Docsify does not work with Vue3 because in Vue3 there is no global app. This results in error

> Uncaught TypeError: window.Vue is not a constructor

#### What does the proposed API look like?

When using Vue3, you have to manually initialize a Vue instance because no default instance is created.

It would also be possible to create a default instance with Vue3 but I need to configure my own instance anyway.

#### How should this be implemented in your opinion?

Add an additional condition `Vue.version.split(".")[0]<=2` and don't [call `Vue().$mount`](https://github.com/docsifyjs/docsify/blob/1a945d445a636d778b242f9d74af4f72c7d89e16/src/core/render/index.js#L60) if it is false.

#### Are you willing to work on this yourself?

I can provide a pull request if the proposed solution is ok to you.

**Comment by jhildenbiddle** [comment]
Fixed in #1271

**Comment by jhildenbiddle** [comment]
@nichtich --

Added in #1271. Updated docs are available here: https://github.com/docsifyjs/docsify/blob/develop/docs/vue.md
