### ISSUE TITLE
Sidebar incorrect parsing

### ISSUE THREAD

**Issue by adonis-lau** [docsifyjs/docsify#1368]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS Big Sur
- Node.js version: none
- npm/yarn version: none
- Browser version: chrome 85.0.4183.83
- Docsify version: 4.11.4 & 4.11.6
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Please follow the template for questions.

**Comment by sy-records** [comment]
You need to create the `_sidebar.md` file.

see https://docsify.js.org/#/more-pages?id=sidebar
