### ISSUE TITLE
Ability to disable the showing of the navigation bar on the cover

### ISSUE THREAD

**Issue by kennykantisiri** [docsifyjs/docsify#1375]
## Feature request
Ability to disable the showing of the navigation bar on the cover

#### What problem does this feature solve?
This feature request makes it so users have the ability to be able to not show the navigation bar on the cover, and have it only show on the normal pages.

**Comment by jhildenbiddle** [comment]
This issue has been addressed by PR #2469. The changes will be available when Docsify v5 is released.

Once v5 is release, this issue can be resolved by modifying the following theme property:

```css
:root {
  --z-cover: 20;
  --z-app-nav: 10;
}
```

Note that this solution will work best when `onlyCover` is `true`. When `false`, the sidebar navigation will only be visible after navigating to a page and hiding the cover page.
