### ISSUE TITLE
Folders seems to be not working after multiple clicks in sidebar navigation links

### ISSUE THREAD

**Issue by ArjunDandagi** [docsifyjs/docsify#1377]
## Bug Report
Folders seems to be not working after multiple clicks in sidebar
#### Steps to reproduce
[Repo](https://github.com/arjundandagi/devopsnotes/docs)
[live site link](https://arjundandagi.github.io/devopsnotes) 

click multiple times on "Software Packaging" in the sidebar 
it works for the first time 
fails in subsequent clicking ( it is appending my folder name second time , which is causing the issue)

#### What is current behaviour

click multiple times on "Software Packaging" in the sidebar 
it works for the first time 
fails in subsequent clicking ( it is appending my folder name second time , which is causing the issue)

#### What is the expected behaviour

any number of time i click the sidebar link , it should take me to relevant page

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: N/a , i am directly editing in github pages 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version:  not mentioned ( cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js ) 
- Docsify plugins: docsify-darklight-theme

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
I visit ur site, I cant reproduce it, could plz provide more details and some pics about it? thx.
