### ISSUE TITLE
A cross-origin url  on _coverpage file cannot be redirected to if "routerMode" is set to "history"

### ISSUE THREAD

**Issue by BeamerIsHere** [docsifyjs/docsify#1379]
#### Steps to reproduce
Set these lines in index.html

      window.$docsify = {
        //...
        loadSidebar: true,
        routerMode: 'history',
        coverpage: true,
        onlyCover: true,

Then use any other doman URLs in _coverpage file, See below...

  ```<a href="https://rstudio.com/auth-sign-in">Login</a><br />```

#### What is the current behavior

when clicking on the link on the cover page there is no response, while checking the browser console getting the following error.

Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://rstudio.com/auth-sign-in' cannot be created in a document with origin 'https://datatools.inhouse.com' and URL 'https://datatools.inhouse.com/'.
    at https://cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js:1:93866

#### What is the expected behavior

Redirect to the mentioned web page directly.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
 Using the docsify index.html file in an apache container, the apache server serves the web site. 

- Docsify version: 
  Using "src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js" " in the index page. I believe this will use the latest version of docsify.
- Have you seen this issue with other docsify projects?
  Yes, see #1046 @Koooooo-7 @anikethsaha 

- Docsify plugins: 
1. search.min.js
1. docsify-plugin-flexible-alerts
1. mermaid.js

#### Mentioned ```index.html``` and ```_coverpage``` files are in the below repository. Please check it.

[Git repo](https://github.com/BeamerIsHere/docsify_bug1)

**Comment by Siddhu1096** [comment]
I'm also facing the same issue.

**Comment by vergilcw** [comment]
Yes, I have noticed this issue as well--I use some custom html in my coverpage, and standard html anchor links do nothing when you click on them, if router mode is set to "history".  The same links work fine in "hash" routing mode.

It looks like another Docsify user may have solved this with a custom plugin, but I'm not sure if it is possible to generalize: https://github.com/ml5js/ml5-library/pull/985
https://github.com/ml5js/ml5-library/pull/985/commits/f5ba5d7c8f793ca83660e1087061964156f0488c

**Comment by Koooooo-7** [comment]
Thx for ur report.
Actually, we support this case but we hvnt document  it yet, cuz we dont wanna users force to define the specific cross origin urls with ` <a>` tag links ( we prefer to recommend use the md synax).
Absolutely, you can use the same way as @vergilcw  mentioned in docsify configurations.  you can defined all the cross origin links below, and I think it will works as u expect.
```js
window.$docsify = {
  crossOriginLinks:[
      "https://rstudio.com/auth-sign-in",
   ],
};

```

**Comment by BeamerIsHere** [comment]
@Koooooo-7 Thank you for the solution, I tried the same and it worked as expected.

I've solved the issue differently using href attribute '"target="_blank'. See below. 

<a href="https://rstudio.com/rsc/connect/#/login/" **_target="_blank"_**>

Adding the  '"target="_blank' with the URL solved the issue by opening it in a different browser tab.

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Thank you for the solution, I tried the same and it worked as expected.

Aha, no problem.

> I've solved the issue differently using href attribute '"target="_blank'. See below.
> 
> <a href="https://rstudio.com/rsc/connect/#/login/" **target="_blank"_**>
> 
> Adding the '"target="_blank' with the URL solved the issue by opening it in a different browser tab.

Cool.
