### ISSUE TITLE
Avoiding emoji transform of colons using __colon__ is undocumented and buggy

### ISSUE THREAD

**Issue by atuttle** [docsifyjs/docsify#1380]
## Bug Report
Today I saw in #742 that  supposedly you can use `__colon__` to insert colons that won't be used to transform into an emoji, as when e.g. `:smile:` would become `😄` .

Firstly, if this is intended to be a supported work-around, it should be documented. It is not mentioned at all in the docsify documentation. Secondly, it is not working correctly.

#### Steps to reproduce

```
$ echo '# foo:bar:baz\nfoo bar baz!\n\n\n# foo__colon__bar__colon__baz\nhere we go again' > src/test.md
$ docsify serve src
$ open http://localhost:3000/#/test
```

#### What is current behaviour

https://codesandbox.io/s/wizardly-noyce-44rr6?file=/README.md

Note that the first example displays correctly in the sidebar but incorrectly in the content, and the second example displays incorrectly in the sidebar but correctly in the content. 🤦 

![image](https://user-images.githubusercontent.com/46990/94882419-f9767580-0435-11eb-900a-b2c6cecbd46f.png)

#### What is the expected behaviour

If `__colon__` is the preferred way of avoiding the emoji transform, it should be rendered as a `:` in both the sidebar and the content consistently.

As I was typing up this bug report I thought to try `&#58;` and that does seem to work. You might want to consider adopting that as the preferred approach. I included it in my code sandbox.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OSX 10.14.5
- Node.js version: 14.10.1
- npm/yarn version: 6.14.8
- Browser version: N/A
- Docsify version: 4.4.1 (I see more recent versions on github, but none later than 4.4.1 published to npm)
- Docsify plugins: none

#### Please create a reproducible sandbox 

https://codesandbox.io/s/wizardly-noyce-44rr6?file=/README.md

#### Mention the docsify version in which this bug was not present (if any)

n/a only tried latest from npm

**Comment by sy-records** [comment]
First, you need to load the emoji plugin. https://docsify.js.org/#/plugins?id=emoji

**Comment by atuttle** [comment]
That does seem to work, thank you.
