### ISSUE TITLE
More comprehensive SEO optimization support

### ISSUE THREAD

**Issue by yl-yue** [docsifyjs/docsify#1387]
### What problem does this feature solve?
1. 更全面的SEO解决方案描述(SSR、SSG、通过简单配置)
2. 文档嵌入支持（由于docsify是单页面的，想依托于docsify构建个人网站，必须添加更多元素，如：网站首页、博客专栏等）

-

1. More comprehensive SEO solution description (SSR,SSG,Or simple configuration).
2. Document embedding support (since Docsify is single-page, if you want to build a personal website based on Docsify, you must add more elements, such as website homepage, blog column, etc.)

### How should this be implemented in your opinion?
可以考虑在docsify文档中的“指南”导航区域加一块SEO专题说明，描述目前已支持的SEO方案特点与使用教程。

Consider adding an SEO topic description to the "Guide" navigation area of your Docsify document, describing the features of the currently supported SEO solutions and tutorials for using them.

### Are you willing to work on this yourself?
I don't think I have enough JS and Docsify knowledge to develop these feature. But I can (beta) test it!

**Comment by sy-records** [comment]
> More comprehensive SEO solution description (SSR,SSG,Or simple configuration).

The SSR now has known bugs, we'll try to fix it.

For better SEO, static HTML generation will be implemented in the v5 version. #136

> Document embedding support (since Docsify is single-page, if you want to build a personal website based on Docsify, you must add more elements, such as website homepage, blog column, etc.)

I think this should be made possible by the theme

**Comment by yl-yue** [comment]
@sy-records 多谢提示，我尝试下通过导航栏构建出一个多页的文档。

**Comment by yl-yue** [comment]
It is suggested to add an SEO optimization special description in the document @sy-records

**Comment by sy-records** [comment]
We're not SEO experts.

**Comment by yl-yue** [comment]
> We're not SEO experts.

What I want to express is that Docsify currently has those SEO configuration and related schemes, you can list a sidebar file to explain, for example, SSR is currently supported.
I'm sorry for the misunderstanding caused by my unclear expression.

**Comment by sy-records** [comment]
https://docsify.js.org/#/ssr
