### ISSUE TITLE
Sidebar not work if direct page not found

### ISSUE THREAD

**Issue by ngthtung** [docsifyjs/docsify#1394]
#### Steps to reproduce
1: Access link: https://docsify.js.org/#/cvasda ( of course, this page is not found )

#### What is current behaviour

Docsify return page not found but sidebar not work ( not get content )

![image](https://user-images.githubusercontent.com/43090730/95813596-6d702200-0d42-11eb-90ad-2e9a0899fc63.png)

#### What is the expected behaviour

Docsify return page not found and sidebar have data.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Direct access to the wrong page address makes no sense

**Comment by ngthtung** [comment]
Yah, its maybe make no sense for developer, but user - who don't have any knowledge about technical will make confuse because they don't see sidebar to redirect to right address.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

It is working fine in our [docs](https://docsify.js.org/#/quickstartv). Please check your docsify config and project structure

**Comment by sy-records** [comment]
> Thanks for the issue.
> 
> It is working fine in our [docs](https://docsify.js.org/#/quickstartv). Please check your docsify config and project structure

There is a problem, the sidebar does not display when accessing a non-existent address

**Comment by ngthtung** [comment]
I already try this [link](https://docsify.js.org/#/quickstartv): but it not work ( sidebar still empty )
![image](https://user-images.githubusercontent.com/43090730/95815025-08b6c680-0d46-11eb-95cb-17761fff53d5.png)

**Comment by ngthtung** [comment]
> > Thanks for the issue.
> > It is working fine in our [docs](https://docsify.js.org/#/quickstartv). Please check your docsify config and project structure
> 
> There is a problem, the sidebar does not display when accessing a non-existent address

Is it a bug or a feature? When the sidebar does not display when accessing a non-existent address

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/95815663-bd091a80-0d4f-11eb-8be5-303e00e5e932.png)

You can set the `notFoundPage` option to work.

**Comment by ngthtung** [comment]
Actually, I'm using options notFoundPage but it not work ( i'm using homepage and basePath )

**Comment by sy-records** [comment]
You don't have a sidebar on this one, how do you load it? 

The requested file does not exist, so the sidebar is not generated automatically.

**Comment by ngthtung** [comment]
Thank you @sy-records , I found out the problem, when use basePath is my local backend => it's not work, but when I use basePath is raw.githubusercontent.com/xxxx/yyyy => it works.
