### ISSUE TITLE
Search not working picking up links in nav

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1401]
#### Steps to reproduce
See code below

#### What is current behaviour
On the home page, the search is not returning any results.

#### What is the expected behaviour
Search follows the links in the `<nav>` tag and creates the search index.

#### Other relevant information

- [ x] Bug does still occur when all/other plugins are disabled?

- Your OS: MacOSx
- Node.js version: 10.22.0
- npm/yarn version: 6.14.6
- Browser version: Chrome 86.0.4240.80
- Docsify version: 4.4.1
- Docsify plugins: search

#### Please create a reproducible sandbox 

**index.html**
```
...
<body>
<nav>
  <a href="#/new-starter-guide/index">New Starter Guide</a>
  <a href="#/web/index">Web</a>
  <a href="#/mobile/index">Mobile</a>
  <a href="#/conversational/index">Conversational</a>
  <a href="#/backend/index">Backend</a>
  <a href="#/production-engineering/index">Production Engineering</a>
</nav>
  <div id="app"></div>
  <script>
    window.$docsify = {
      ...
      search: {
        maxAge: 86400000, // Expiration time, the default one day
        paths: 'auto',
        placeholder: 'Type to search',
        noData: 'No Results!',
        // Headline depth, 1 - 6
        depth: 6,
        hideOtherSidebarContent: false, // whether or not to hide other sidebar content
        namespace: 'shopping-platforms',
      }
   }
<script>
...
```

**Comment by sy-records** [comment]
Yes, it's just navigation, not a sidebar.

The search will only look in the sidebar. https://docsify.js.org/#/more-pages?id=sidebar

**Comment by joetidee** [comment]
It is not obvious from the documentation that this is its limitation.

How would you suggest I resolve this issue? I tried using javascript to copy the HTML form the `<nav>` block to the sidebar using a couple of hooks, but this didn't seem to work (the HTML was copied but the search plugin wasn't picking up the links) - maybe a timing issues in that the search plugin does it's indexing before the HTML was copied over.

**Comment by sy-records** [comment]
First, you need to set `loadSidebar` to true

Create the `_sidebar.md`

```markdown
* [New Starter Guide](new-starter-guide.md)
* [Web](web.md)
......
```

**Comment by joetidee** [comment]
@sy-records Yeah, was hoping not to have to enter the same links in two separate locations. So, wondered if there was a way to automate the copying of the links to the sidebar. Else, maybe include an option in search config to state an array of css classes to look for on the page to create the search index from.
