### ISSUE TITLE
search accents marks

### ISSUE THREAD

**Issue by EloFran** [docsifyjs/docsify#1405]
## Feature request
It posible that search plugin ignore accents marks (tildes) ?
  
#### What problem does this feature solve?
id like that the words with accents to be the same with out accents.

#### What does the proposed API look like?
In the Spanish lenguage is important write accents, but in the search, the peoples does not usually add them.

#### How should this be implemented in your opinion?
adding some kind of routine that ignores accents in vowels: á é í ó ú
for example: **artículo** or **articulo** to be the same

#### Are you willing to work on this yourself?
yes

**Comment by sy-records** [comment]
I test can search for content, what are you referring to?

![image](https://user-images.githubusercontent.com/33931153/97958248-cbdf6c00-1de7-11eb-8bad-d31542d66e90.png)

**Comment by EloFran** [comment]
yes its correct, but if you search without "accent" it should find it anyway. In Spanish a lot of peoples no using accents in their search.

![image](https://user-images.githubusercontent.com/37640520/98157256-62d82100-1ed9-11eb-82b5-35661191f028.png)

**Comment by sy-records** [comment]
Okay, I misread it, you need to ignore accent...

But I don't think it's necessary, because it's two different letters.

![image](https://user-images.githubusercontent.com/33931153/98183368-f85bcb00-1f42-11eb-9edc-97b2fef2e123.png)

**Comment by StephaneG31** [comment]
I have the same problem with French.

**Comment by EloFran** [comment]
In Spanish there are words that have or do not have an accent depending on the context, but if you are looking for only the word it should appear in all its contexts. If we add that people in search engines do not use accents, they are usually ignored, because for example Google, you find it both with and without it.

**Comment by sy-records** [comment]
@EloFran @StephaneG31 Hello, do you have any comments on the results of such a search? Do I need to show accents in the results?
 
![image](https://user-images.githubusercontent.com/33931153/103127490-fbff0900-46cc-11eb-877e-cee72da72e39.png)

![image](https://user-images.githubusercontent.com/33931153/103127496-04efda80-46cd-11eb-8242-274b06b437ef.png)

**Comment by StephaneG31** [comment]
It's better to have accent in the result but if it's too complicated it's acceptable.

Moreover (but it's not the same problem, maybe I have to open an other issue) in the result pane, html is sometimes displayed (in the capture you can see the ' character displayed with ...9; in the expression "Let's".)

**Comment by sy-records** [comment]
Yes, I know the problem
