### ISSUE TITLE
Sidebar has special character when config header as a link.

### ISSUE THREAD

**Issue by ngthtung** [docsifyjs/docsify#1406]
#### Steps to reproduce

First , add Link as a Header.
Config subMaxLevel is 3

We will get content in sidebar here:
![image](https://user-images.githubusercontent.com/43090730/96851190-f5140a00-1481-11eb-90d5-f9c6151fdf68.png)

Link demo: https://codesandbox.io/s/eager-tree-gqhzr?file=/index.html

#### What is current behaviour

In sidebar, we got character ">

#### What is the expected behaviour

In sidebar, dont render ">

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
fixed #1336
