### ISSUE TITLE
Make the GitHub Repo Link Dynamic 

### ISSUE THREAD

**Issue by TiKevin83** [docsifyjs/docsify#1417]
## Feature request

Instead of just linking to the root of a GitHub repository, change the link so it takes you to the specific markdown file source for that page

#### What problem does this feature solve?

A new user to GitHub might not understand how to find the wiki page they were reading if they wanted to go suggest an edit

#### What does the proposed API look like?

Either a change to the behavior of 'repo' or a new option 'dynamicRepo' for this feature

#### How should this be implemented in your opinion?

changing the generated src of the GitHub icon

#### Are you willing to work on this yourself?

Could help if pointed to the relevant areas of the code. I imagine this wouldn't be too complicated because the system already has to be tracking down the source markdown URL of a page and should be able to translate that directly to a link to the source code to output into the generated markup.

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/97956691-4908e200-1de4-11eb-8f23-167097ca1476.png)
