### ISSUE TITLE
sideBar rendering error

### ISSUE THREAD

**Issue by lxhyl** [docsifyjs/docsify#1426]
#### Steps to reproduce
my sideBar is auto generate,
if title is a link, the  sideBar will render error

i use script to  ntroduce docsify
<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>

#### What is current behaviour
![image](https://user-images.githubusercontent.com/41041503/99019660-c75d4500-2597-11eb-9472-9abe3f7465ac.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: win10 chrome
- Node.js version:  
- npm/yarn version: 
- Browser version:   86.0.4240.198
- Docsify version:   always new 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by lxhyl** [comment]
add a current behaviour  pic

![image](https://user-images.githubusercontent.com/41041503/99020592-e78e0380-2599-11eb-85ae-1d1274a9c8be.png)

**Comment by sy-records** [comment]
fixed via #1336
