### ISSUE TITLE
alias is not working

### ISSUE THREAD

**Issue by macrozone** [docsifyjs/docsify#1436]
#### Steps to reproduce

define alias described like in https://docsify.js.org/#/configuration?id=alias

do a link in a md file using an alias path

#### What is current behaviour

the alias is ignored, you will get linked to a local path

#### What is the expected behaviour

it should resolve the alias

#### Other relevant information

- Your OS:  macOs
- Node.js version:  12.13.1
- npm/yarn version: 
- Browser version: chrome
- Docsify version: 4.11.6
- Docsify plugins: none

#### Please create a reproducible sandbox 

See https://codesandbox.io/s/jolly-joliot-jzzwx

**Comment by sy-records** [comment]
It will look for the corresponding md file.

![image](https://user-images.githubusercontent.com/33931153/100814858-94fb8500-347d-11eb-9d1c-400e153e5d2f.png)

You can use it like this

```
"/foo": "https://raw.githubusercontent.com/docsifyjs/awesome-docsify/master/README.md"
```

**Comment by macrozone** [comment]
ok i interpreted it differently. i solved it by using 

```
 plugins: [
        function (hook, vm) {
          hook.beforeEach((markdown) => {
            console.log(markdown)
            const result = markdown.replace(/]\(\/\/myspecialpath\//g, `](${"https://external-url.com"/*"http://localhost:3000"*/}/examples/`)
            return result
          })
        }
      ],
```
