### ISSUE TITLE
How to delete carbon ads

### ISSUE THREAD

**Issue by pilotpanda** [docsifyjs/docsify#1437]
Hello, 

How I can delete Carbon Ads from docsify?

I try when delete Carbon Ads the site is broken

Thank You

**Comment by sy-records** [comment]
What do you mean? Can carbon ads be removed from docsify.js.org?

**Comment by pilotpanda** [comment]
Hi, 

I mean this https://prnt.sc/vuuflp when im forking master branch the ads always show, How can i remove the ads?

Thank You

**Comment by sy-records** [comment]
What is the link you are visiting?

**Comment by pilotpanda** [comment]
Hi, 

This is the link that i visiting : https://pilotpanda.github.io/docsify/#/

Thank You

**Comment by sy-records** [comment]
remove `docsify-plugin-carbon`. 

 please use the official website. https://docsify.js.org
