### ISSUE TITLE
Markdown link bug in navbar

### ISSUE THREAD

**Issue by jcayzac** [docsifyjs/docsify#1438]
## Bug Report

This markdown link:

```md
- [:jp:&#x3009;:us:](/ "English")
```

…has a correct `title="English"` when used in a page, but has `title="〉"` when used in the navbar document.

#### Steps to reproduce

Use the markdown link above in a navbar.

#### What is current behaviour

The generated link has `title="〉"`.

#### What is the expected behaviour

The generated link has `title="English"`.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS Catalina
- Browser version: Chrome 86
- Docsify version: 4.11.6

#### Link for repro

[![Link for repro](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dank-frog-g4tx0)

**Comment by sy-records** [comment]
I don't understand what you mean, can you create a sandbox or provide a reproducible address?

**Comment by jcayzac** [comment]
> I don't understand what you mean, can you create a sandbox or provide a reproducible address?

The link to the code sandbox is in the issue?

**Comment by sy-records** [comment]
Sorry, I didn't see that you had created.

I feel like it should have been fixed, You can use this to try.

```html
<script src="//docsify-preview.now.sh/lib/docsify.js"></script>
```

**Comment by jcayzac** [comment]
Confirmed it's fixed using the same sandbox code https://codesandbox.io/s/magical-faraday-37q2g
Thanks!
I see the fix is several months old: any chance for a new v4 release soon?

**Comment by sy-records** [comment]
We will release as soon as possible.
