### ISSUE TITLE
Scroll section by section

### ISSUE THREAD

**Issue by ngthtung** [docsifyjs/docsify#1439]
#### What problem does this feature solve?

Currently if want go to the next page, we have to click section in sidebar, but i wanna scroll section by section. How can I do that ?

It similar like https://github.com/imyelo/docsify-pagination , but user just scroll and scroll.

**Comment by sy-records** [comment]
You can go to this plugin to make a request, it may be easier to implement.

**Comment by ngthtung** [comment]
> You can go to this plugin

Give me a link to go to plugin.

**Comment by sy-records** [comment]
https://github.com/imyelo/docsify-pagination

**Comment by ngthtung** [comment]
ok, thank you @sy-records

**Comment by ngthtung** [comment]
Hey @sy-records , is there any public api about fetch data of docsify ?

**Comment by sy-records** [comment]
only these, see https://docsify.js.org/#/write-a-plugin
