### ISSUE TITLE
Code sections using ```sh...``` are not aligned properly when there's more than 4 leading spaces.

### ISSUE THREAD

**Issue by ak2766** [docsifyjs/docsify#1440]
## Bug Report
Code sections using ```sh...``` are not aligned properly when there's more than 4 leading spaces.

#### Steps to reproduce
1. Create an MD file with at least 2 levels of depth as shown below:
<pre>
### Verify Federation Settings

* SAML 2.0 Federation Verification Process
  * To verify that the domain has been federated with the correct information, execute the following command:

    ```sh
    Get-MsolDomainFederationSettings -DomainName DOMAIN
    ```
  * You should see output similar to below:

    ```sh
    ActiveLogOnUri                         : https://DOMAIN/SERVICENAME/ecp     
    DefaultInteractiveAuthenticationMethod :                                        
    FederationBrandName                    : DOMAIN                               
    IssuerUri                              : https://DOMAIN/SERVICENAME         
    LogOffUri                              : https://DOMAIN/SERVICENAME/logout  
    MetadataExchangeUri                    :                                        
    NextSigningCertificate                 :                                        
    OpenIdConnectDiscoveryEndpoint         :                                        
    PassiveLogOnUri                        : https://DOMAIN/SERVICENAME/qr_login
    SigningCertificate                     : <base64 encoded certificate>           
    SupportsMfa                            :                                        
    ```
</pre>

#### What is current behaviour
The current behaviour can best be detailed via a screenshot of the result of the above code.  The code sections (1) are aligned, but the colons are misaligned (2):
![Selection_00975](https://user-images.githubusercontent.com/6629646/101143309-d00edb80-366a-11eb-96ae-073753013253.png)

#### What is the expected behaviour
In the above image, I added a vertical red line (2) to help bring out the expected behaviour which is to have all colons properly aligned.

If I modify the markdown in step 1 above to look like below, I get the desired effect of having all colons properly aligned (2), but then my code sections do not line up (1):

<pre>
### Verify Federation Settings

* SAML 2.0 Federation Verification Process
  * To verify that the domain has been federated with the correct information, execute the following command:

    ```sh
    Get-MsolDomainFederationSettings -DomainName DOMAIN
    ```
  * You should see output similar to below:

```sh
ActiveLogOnUri                         : https://DOMAIN/SERVICENAME/ecp     
DefaultInteractiveAuthenticationMethod :                                        
FederationBrandName                    : DOMAIN                               
IssuerUri                              : https://DOMAIN/SERVICENAME         
LogOffUri                              : https://DOMAIN/SERVICENAME/logout  
MetadataExchangeUri                    :                                        
NextSigningCertificate                 :                                        
OpenIdConnectDiscoveryEndpoint         :                                        
PassiveLogOnUri                        : https://DOMAIN/SERVICENAME/qr_login
SigningCertificate                     : base64 encoded certificate           
SupportsMfa                            :                                        
```
</pre>

This works for alignning the colons (2) but then misaligns the code sections (1):
![Selection_00977](https://user-images.githubusercontent.com/6629646/101143699-5cb99980-366b-11eb-95cb-b94ee9e80a01.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 20.04.1 LTS
- Node.js version: v12.20.0
- npm/yarn version: 6.14.8
- Browser version: Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Docsify version: docsify-cli version 4.4.2
- Docsify plugins: Default (what was installed during install of docsify)

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)
The same issue is present in the sandbox: https://n3sq6.csb.app/#/?id=verify-federation-settings

#### Mention the docsify version in which this bug was not present (if any)
This is my first time using `docsify` so **no** historical data available.

**Comment by sy-records** [comment]
This should be a `marked` problem, I'll check later

**Comment by sy-records** [comment]
you can add this css to index.html

```css
.markdown-section ul {
    word-spacing: unset;
}
```

![image](https://user-images.githubusercontent.com/33931153/101474070-95b47f80-3985-11eb-9aa7-830cc8dd412e.png)

**Comment by ak2766** [comment]
So sorry.  Forgot to comeback here and report the suggestion by @sy-records resolved the issue.
