### ISSUE TITLE
Does not automatically generate a left-hand directory

### ISSUE THREAD

**Issue by xmuli** [docsifyjs/docsify#1444]
#### Steps to reproduce

Probably shouldn't ask questions here, but it might be hard to get a reply on gitter, so I took the liberty of asking here.

docsify looks beautiful for the first time; ready to deploy it as one of my content documents.

However, it has the disadvantage of not being able to automatically generate a left-hand directory (consisting of all *.md filenames in a given folder); it seems to be possible only through [docsify.js.org](https://docsify.js.org/#/zh-cn/configuration?id=). fallbacklanguages) `loadSidebar: true` Manually manage directories with all file names, which is a pain in the ass.

I can't find any plugins with this feature in the plugin list. Still not provided? Or is there a better solution?

#### What is current behaviour

Does not automatically generate a left-hand directory (consisting of all *.md file names in a given folder)

#### What is the expected behaviour

Hopefully, the left-hand directory (consisting of all *.md file names in a given folder) will be generated automatically.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: UOS v20

- Node.js version: v10.23.0

- npm/yarn version: 

  ```bash
  cnpm@6.1.1 (/home/xmuli/.config/nvm/versions/node/v10.23.0/lib/node_modules/cnpm/lib/parse_argv.js)
  npm@6.14.9 (/home/xmuli/.config/nvm/versions/node/v10.23.0/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
  node@10.23.0 (/home/xmuli/.config/nvm/versions/node/v10.23.0/bin/node)
  npminstall@3.28.0 (/home/xmuli/.config/nvm/versions/node/v10.23.0/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
  prefix=/home/xmuli/.config/nvm/versions/node/v10.23.0 
  linux x64 5.7.7-amd64-desktop 
  registry=https://r.npm.taobao.org
  ```

- Browser version: 

- Docsify version: 4.4.2

- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)

**Comment by sy-records** [comment]
Yes, it is not now automatically generated. see #1290
