### ISSUE TITLE
Docs Button Edit Document Support Multiple Language

### ISSUE THREAD

**Issue by Anilople** [docsifyjs/docsify#1448]
#### What problem does this feature solve?

Support different language on button `Edit Document`

![image](https://user-images.githubusercontent.com/15523186/101980099-fa315080-3c9d-11eb-88f4-19b32c89d2cf.png)

#### What does the proposed API look like?

None.

#### How should this be implemented in your opinion?

Resolve the value of variable `editHtml` in
https://github.com/docsifyjs/docsify/blob/bc3350f6e6bfe670c95569b4e9c51321f5c7dbb9/docs/index.html#L176

Determine which text should show base on `vm.route.file`.

#### Are you willing to work on this yourself?

I can have a try. But I am not familar with frontend.

**Comment by sy-records** [comment]
It doesn't feel like it makes much sense to do this, and the corresponding links are correct.

**Comment by Koooooo-7** [comment]
Simple way is changing it based on the router in this plugin script.

```js
               // default content
               let content = "Edit Document"
               // the mapping for routers and multi languages
               let m = new Map();
               m.set("/zh-cn/", "编辑文档");
               m.set("/es/", "Edit Document");
               m.forEach(function (val, key) {
                  // find the matched content
                  if(window.location.href.indexOf(key) !== -1){
                       content = val
                   }
               });
            
               var editHtml = '[:memo: '+ content +'](' + url + ')\n'
```

**Comment by sy-records** [comment]
you can use https://github.com/njleonzhang/docsify-edit-on-github
