### ISSUE TITLE
SSR Always throw http404 and typeerr

### ISSUE THREAD

**Issue by NaiveTomcat** [docsifyjs/docsify#1450]
#### Steps to reproduce

```sh
npm start
```

With the documented settings

#### What is current behaviour

Throw typeerr from node_modules/docsify-server-renderer/build.js:267:27

#### What is the expected behaviour

Serve the server side rendered site properly

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Linux 5.9.13-arch1-1
- Node.js version: v15.3.0
- npm/yarn version: npm 7.0.5
- Browser version: Chromium 87.0.4280.88 Arch Linux
- Docsify version: 4.4.2
- Docsify plugins: Docsify Search, Click to copy, themeable

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Thank you for your feedback, this is a known issue and will probably be fixed in #1227

**Comment by paulhibbitts** [comment]
Previous SSR code removed for upcoming v5 release, so closing issue.
