### ISSUE TITLE
Deep linking breaks scrolling when sharing

### ISSUE THREAD

**Issue by johndcarmichael** [docsifyjs/docsify#1452]
#### Steps to reproduce
- Generate a site from a single readme file.
- Click on a link in the sidebar nav
- After the page has scrolled into position the url will have the anchor in the url
- share this url
- when the recipient opens the link, the scroll to anchor is broken

#### What is current behaviour
Scroll is broken and the link is injected as a header at the top of the page

#### What is the expected behaviour
It scrolls to the link as normal

#### Other relevant information
Using the latest code from the CDN

#### Please create a reproducible sandbox 
here is an example share with the anchor pulled to the top and the page not scrolling:
- https://johndcarmichael.github.io/boats/#/?id=pickprops

here is the index it is read from on the gh-pages branch: https://github.com/johndcarmichael/boats/blob/gh-pages/index.html

**Comment by sy-records** [comment]
Please remove the `autoHeader: true,`

**Comment by pcothenet** [comment]
Hi team,

We have a similar issue. Navbar links work correctly when clicking on the navbar link, but referencing the link gets the user to the wrong place on the doc.
`auoHeader` was not activated. We tried setting to false (or true), no change.
We tried disabling different themes and plugins one-by-one and it does not seem to help either.

Any advice here?

**Comment by sy-records** [comment]
Thank you for your feedback. @pcothenet
What version are you using? Can the issue be reproduced in [docsify.js.org](https://docsify.js.org)?

**Comment by pcothenet** [comment]
Loading from cdn at https://unpkg.com/docsify/lib/docsify.min.js (so looks like 4.12.0).

I cannot reproduce on docsify.js.org (https://docsify.js.org/#/language-highlight gets me to the right place).

The site is behind login, here's a quick video though: https://www.loom.com/share/07a771cf778e4b1381687f783a454f42

**Comment by sy-records** [comment]
This seems to be related to the theme

**Comment by pcothenet** [comment]
@sy-records thanks for your quick return.

I removed the themes and all plugins and still encounter the same issue.

**Comment by pcothenet** [comment]
It looks like it could be some sort of race condition.

**Comment by sy-records** [comment]
Please provide a reproducible sandbox.
