### ISSUE TITLE
Incompatible with bootstrap

### ISSUE THREAD

**Issue by Banyc** [docsifyjs/docsify#1453]
#### Steps to reproduce

1. Clone this [repo](https://github.com/SciSharp/tensorflow-net-docs/tree/e72a8df8828f6bcc1ed5301fad81a5cf7f76d9fa) .
1. Go to the branch `e72a8df8828f6bcc1ed5301fad81a5cf7f76d9fa`.
1. `docsify serve docs`.
1. Click the title that has subtitles in the sidebar twice.

#### What is current behaviour

When clicking the title that has subtitles in the sidebar twice, the title will disappear.

#### What is the expected behaviour

The title that was clicked should not disappear.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Banyc** [comment]
Forgot to mention that the bootstrap is introduced in file `index.html`.

**Comment by sy-records** [comment]
`collapse` class name conflict.

You can add this css to index.html

```css
.collapse:not(.show) {
    display: unset!important;
}
```
