### ISSUE TITLE
Some of the Docsify docs do not load

### ISSUE THREAD

**Issue by zvictor** [docsifyjs/docsify#1462]
## Bug Report

I can't access some of the docsify docs. It seems that bigger pages fail to load.

#### Steps to reproduce

1. Visit https://docsify.js.org/#/configuration?id=themecolor

#### What is current behaviour

I see only the sidebar and a blank page in the main panel, nothing else.
The console shows:

![image](https://user-images.githubusercontent.com/181076/103381208-69ef6a00-4aeb-11eb-9a97-d078fede48c4.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS:  MacOs
- Node.js version: irrelevant
- npm/yarn version: irrelevant
- Browser version: Chrome 87.0.4280.88 and Safari 14.0 (15610.1.28.1.9, 15610)
- Docsify version: 🤷‍♀️
- Docsify plugins: 🤷‍♀️

**Comment by sy-records** [comment]
Thank you for your feedback. You should now be able to access it normally

**Comment by zvictor** [comment]
Thank you! Just for curiosity, how did it get fixed?

**Comment by sy-records** [comment]
Yesterday I merged an error commit into the master branch...😅
