### ISSUE TITLE
search not find result

### ISSUE THREAD

**Issue by lxhyl** [docsifyjs/docsify#1464]
#### Steps to reproduce

just try to search

#### What is current behaviour

can't find result
![image](https://user-images.githubusercontent.com/41041503/103392464-01d76d00-4b59-11eb-98c7-b78c470f1814.png)

#### What is the expected behaviour

have this word. but not find.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  windows 10
- Node.js version: 12.18.3
- npm/yarn version: 6.14.6
- Browser version: 87.0.4280.88
- Docsify version: 4.11.6
- Docsify plugins: search

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by lxhyl** [comment]
utl:  lxhyl.cn

**Comment by lxhyl** [comment]
url:  lxhyl.cn

**Comment by sy-records** [comment]
You need to create a `_sidebar.md` file and write the corresponding information, for example https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/_sidebar.md

**Comment by trusktr** [comment]
Really gotta improve search. We will add a CLI command that can generate the search results for the whole site. A search index.

**Comment by sy-records** [comment]
Yes, I made half of it. it's not finished yet.
