### ISSUE TITLE
External links do not have target=_blank attribute

### ISSUE THREAD

**Issue by Fab1en** [docsifyjs/docsify#1467]
## Bug Report
When using `homepage` to point to an external file, the default configuration automatically adds `rel="noopener"` and `target="_blank"` attributes to external links. But then, DOMPurify sanitizer removes the `target` attribute as it is not in the white list. This completely prevent the opening of external links in `history` router mode.

#### Steps to reproduce
Just point to an external file as your homepage : 
```js
window.$docsify = {
      homepage: 'https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/README.md',
}
```

#### What is current behaviour
generated HTML for external link is missing "target" attribute :
```html
<li>Support server-side rendering (<a rel="noopener" href="https://github.com/docsifyjs/docsify-ssr-demo">example</a>)</li>
```

#### What is the expected behaviour
target attribute should be present
generated HTML for external link is missing "target" attribute :
```html
<li>Support server-side rendering (<a rel="noopener" target="_blank" href="https://github.com/docsifyjs/docsify-ssr-demo">example</a>)</li>
```

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.11.6
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Fab1en** [comment]
I was able to remove this bug by adding the `target` attribute to DOMPurify white list : 
```js
DOMPurify.sanitize(html, {ADD_ATTR: ['target']})
```

**Comment by jhildenbiddle** [comment]
Confirmed `target="_blank"` added to external links on `develop` branch.
