### ISSUE TITLE
how to support $$

### ISSUE THREAD

**Issue by rpig** [docsifyjs/docsify#1474]
I want to support like$\sqrt{x^{2}}$

**Comment by sy-records** [comment]
Please explain in full.

**Comment by Koooooo-7** [comment]
I guess u wanna support the math stuff, u can use this plugin [docsify-katex](https://github.com/upupming/docsify-katex).

**Comment by trusktr** [comment]
Yep, also Markdown is just HTML with extra syntax, you can use any web libraries you desire just like in any HTML file. Choose any library, import the script, and use it.
