### ISSUE TITLE
Search doesn't index

### ISSUE THREAD

**Issue by nkavian** [docsifyjs/docsify#1478]
#### Steps to reproduce

Create three MD files, enable the sidebar, enable search, and observe that search doesn't work.

https://codesandbox.io/s/fervent-almeida-1p5us?file=/index.html

#### What is current behaviour

docsify.search.index only contains content for a.md and b.md/c.md was not parsed into the index:

````
{
"/a":{"#/a?id=hn2":{"slug":"#/a?id=hn2","title":"HN2","body":"HN3\nHello A"}},
"/b":{},
"/c":{}
}
````

Using Chrome incognito is even worse, not even a.md is searchable.

#### What is the expected behaviour

The index should properly contain all pages to be able to perform a search.

#### Other relevant information

- [X] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac / Chrome
- Docsify version: latest
- Docsify plugins: search.min.js

#### Please create a reproducible sandbox 

https://codesandbox.io/s/fervent-almeida-1p5us?file=/index.html

#### Mention the docsify version in which this bug was not present (if any)

N/A

**Comment by sy-records** [comment]
You need to add a title. see https://codesandbox.io/s/modest-pike-ehdh9

```markdown
## Hello B

```java
public interface Foo { }
```
```

**Comment by nkavian** [comment]
That does work around the issue sometimes, but not all the time. I won't be able to use autoHeader.

For example, if I want my page to look like this (search works, but then I can't use autoHeader):

````
# Page Title

This is some description. A long paragraph.
````

If I use autoHeader, then my page would start like this (search doesn't work):

````
This is some description. We assume autoHeader added the # Title. A long paragraph.
````

So compatibility with autoHeader is an issue. Overall however, there should not be a dependency between a page/section title versus the search indexing. All page content should be able to be indexed. Can you consider this a bug and fix it? This will be very counter intuitive for other people and they won't know that search isn't truly working for all of their content.

**Comment by sy-records** [comment]
Thank you for your feedback, I will check it as soon as possible

**Comment by Jir4** [comment]
It's still not possible to find something in a list : https://codesandbox.io/s/sparkling-cdn-v87gl

For example you can search "object" on your sandbox and on mine.

**Comment by sy-records** [comment]
https://codesandbox.io/s/modern-wind-hm6wn

@Jir4 Your problem will be fixed in the next version

![image](https://user-images.githubusercontent.com/33931153/106974886-74f38500-6790-11eb-9a03-b86e039d25eb.png)

**Comment by gyhyfj** [comment]
怎么设置，都搜不到README.md以外的内容

**Comment by Jir4** [comment]
> https://codesandbox.io/s/modern-wind-hm6wn
> 
> @Jir4 Your problem will be fixed in the next version
> 
> ![image](https://user-images.githubusercontent.com/33931153/106974886-74f38500-6790-11eb-9a03-b86e039d25eb.png)

https://github.com/docsifyjs/docsify/pull/1361 i guess 

Didn't search enough sorry.

Any release date planned ?

**Comment by gyhyfj** [comment]
search still not work
