### ISSUE TITLE
Remove hash # symbol from URLs?

### ISSUE THREAD

**Issue by shawaj** [docsifyjs/docsify#1479]
## Feature request

It's it possible to remove the # from the URLs?

Like https://helium.nebra.com/#/indoor-hotspot/overview change to https://helium.nebra.com/indoor-hotspot/overview ?

#### What problem does this feature solve?

Better looking URLs

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

Simple config change

#### Are you willing to work on this yourself?

Yes but don't know if I have the ability.

**Comment by sy-records** [comment]
you can see #235

**Comment by shawaj** [comment]
@sy-records it doesn't seem to provide a solution?

**Comment by sy-records** [comment]
https://github.com/docsifyjs/docsify/issues/235#issuecomment-322960245

**Comment by shawaj** [comment]
What is HTML5 history API?

And does it cause any other problems with the setup if using github pages?

**Comment by Koooooo-7** [comment]
> What is HTML5 history API?
> 
> And does it cause any other problems with the setup if using github pages?

The `#` makes the hash router.
History model uses `history.pushState` to change urls, it like the normal urls without `#`.
This model needs a server to avoid `404` error on flushing page, so ,u cant use it on `github pages`.
More details see [HTML5 History Mode](https://router.vuejs.org/guide/essentials/history-mode.html).

**Comment by shawaj** [comment]
Thanks @Koooooo-7 very helpful. So must use a different server not github pages?

**Comment by shawaj** [comment]
All sorted thanks @Koooooo-7 @sy-records https://helium.nebra.com/
