### ISSUE TITLE
how to use diff 

### ISSUE THREAD

**Issue by calmchang** [docsifyjs/docsify#1480]
#### Steps to reproduce
```
~~~diff
- old code
+ new code
~~~
```

not work!

**Comment by sy-records** [comment]
see https://github.com/markedjs/marked/issues/1741

**Comment by Koooooo-7** [comment]
Using the `prismjs` to decorate the `code block`.
you can just import this
 ` <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-diff.min.js"></script>`
 to use the `diff`.


![diff](https://user-images.githubusercontent.com/33706142/105477655-1d0f4580-5cdd-11eb-855d-c248302e981f.png)
