### ISSUE TITLE
Navbar cannot always show if it's written in solo `.md` file 

### ISSUE THREAD

**Issue by gyhyfj** [docsifyjs/docsify#1494]
## Bug Report
Navbar can be always showed only if we design it in `index.html`  rather than solo `.md` file

#### Steps to reproduce
If we creat the Navbar in the `_navbar.md` file and set `loadNavbar: true`&&`onlyCover: true` in `index.html`, then when we open the coverpage in browser, the Navbar won't be there unless we go into the document and return back to the coverpage

**Comment by sy-records** [comment]
I don't understand what you mean, is it possible to create reproducible sandboxes?
