### ISSUE TITLE
HOMEPAGE `docsify.js.org` not showing up normally

### ISSUE THREAD

**Issue by pythonokai** [docsifyjs/docsify#1497]
## Bug Report

HOMEPAGE `docsify.js.org` not showing up normally

#### Steps to reproduce

Enter `docsify.js.org`, and navigate to `https://docsify.js.org/#/configuration` from sidebar, and then content is gone just a blank.

#### What is current behaviour

Some pages are blank.

#### What is the expected behaviour

Show up the content which associate to sidebar headers.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Thanks for your feedback, I tested it.

It was found to be because of a CDN problem, so we wait for it to refresh tomorrow and it should be back

**Comment by jhildenbiddle** [comment]
Working as expected now.
