### ISSUE TITLE
Search index does not expire in dev?

### ISSUE THREAD

**Issue by cottrell** [docsifyjs/docsify#1508]
I have been having trouble getting the search index to refresh quickly in dev. It *does* refresh if you wait long enough. I have set maxAage quite low. 

I noticed this in the code and am wondering if this actually fails to work when you refresh (i.e. it keeps pushing the fresh date into the future)

```
function saveData(maxAge, expireKey, indexKey) {
  localStorage.setItem(expireKey, Date.now() + maxAge);
  localStorage.setItem(indexKey, JSON.stringify(INDEXS));
}
```

**Comment by sy-records** [comment]
if you use services like GitHub pages, you need to consider caching issues.

**Comment by cottrell** [comment]
It seems to be sporadic as I couldn't reproduce it yesterday. One thing I did was a add a button to delete and a button to log the localstorage cache on a config page somewhere.

My use case is to just always run it in dev mode (live reload) and never deploy it. I am also not using the live reload port so have to manually reload the page. I don't think that should affect cache invalidation but not sure.

**Comment by sy-records** [comment]
You can observe whether the timestamp corresponding to the `expireKey` has changed
