### ISSUE TITLE
README.md vs readme.md

### ISSUE THREAD

**Issue by gadhagod** [docsifyjs/docsify#1512]
#### What problem does this feature solve?

When having a file called `readme.md`, `docsify serve` works perfectly, but when I deployed on GitHub pages, it did not work, because it needed to be `README.md`. If running locally works but not on GitHub pages, it can be very confusing as to why this is happening.

#### What does the proposed API look like?

Sorry, not sure what should go here.

#### How should this be implemented in your opinion?

Maybe tolerate both `readme.md` and `README.md`?

#### Are you willing to work on this yourself?

yes!

**Comment by sy-records** [comment]
you maybe need setting homepage, see https://docsify.js.org/#/configuration?id=homepage

**Comment by gadhagod** [comment]
Thanks for the link @sy-records! I actually opened this because I thought if `readme.md` would work with `docsify serve`, it should work with GH pages, but that was not the case.

**Comment by sy-records** [comment]
Can work after setup.

![image](https://user-images.githubusercontent.com/33931153/108164187-462fc400-712b-11eb-9ef2-1ef335a24f2a.png)
![image](https://user-images.githubusercontent.com/33931153/108164150-36b07b00-712b-11eb-92af-e2a0cdda61c0.png)

This should be related to GitHub pages.

![image](https://user-images.githubusercontent.com/33931153/108164276-711a1800-712b-11eb-97d6-edc63ee2d883.png)
