### ISSUE TITLE
Search is KO with IE11

### ISSUE THREAD

**Issue by StephaneG31** [docsifyjs/docsify#1526]
When an IE11 user try to search in docsfy with IE11, there's an JS error and the search doesn't work.
![image](https://user-images.githubusercontent.com/4253015/110303692-f857fe80-7ffa-11eb-937c-5eed0a66fed0.png)

**Comment by sy-records** [comment]
Have you tried this?

![image](https://user-images.githubusercontent.com/33931153/110304400-869da600-8036-11eb-8f45-54e1f095d007.png)

```html
<script src="//polyfill.io/v3/polyfill.min.js?features=String.prototype.normalize"></script>
```

see https://docsify.js.org/#/plugins?id=full-text-search

**Comment by StephaneG31** [comment]
The problem seems to be here :
https://github.com/docsifyjs/docsify/blob/0f3211ee77303f8f1c2e40ed5221ed9d8a988d81/src/plugins/search/component.js#L141
In our case $appName is null. Is it possible to juste add an if begind to test the presence of this object ?

**Comment by sy-records** [comment]
Can you provide a reproducible sandbox?

**Comment by StephaneG31** [comment]
you can try here : https://www.audiowebconference.orange-business.com/help/manual/#/

**Comment by StephaneG31** [comment]
If I remove the "n.classList.remove('hide')" it works but I think it's better to do an if check

**Comment by sy-records** [comment]
Can you use this for testing?

```html
<script src="https://docsify-preview-git-fork-sy-records-fix-1526-docsify-core.vercel.app/lib/docsify.js"></script>
<script src="https://docsify-preview-git-fork-sy-records-fix-1526-docsify-core.vercel.app/lib/plugins/search.js"></script>
```

**Comment by StephaneG31** [comment]
> Can you use this for testing?
> 
> ```
> <script src="https://docsify-preview-git-fork-sy-records-fix-1526-docsify-core.vercel.app/lib/docsify.js"></script>
> <script src="https://docsify-preview-git-fork-sy-records-fix-1526-docsify-core.vercel.app/lib/plugins/search.js"></script>
> ```

I this it on my DEV ENV and it works!

**Comment by sy-records** [comment]
Thank you for your feedback
