### ISSUE TITLE
js package 'npm/docsify@4' cause sidebar could not be hide and navbar could not be appear 

### ISSUE THREAD

**Issue by BackMountainDevil** [docsifyjs/docsify#1533]
## Bug Report

1. The sidebar could not be clicked to hide. If clicked, nothing happen.   
2. Though navbar which has been added, it will not appear in the web.  

#### Steps to reproduce

```bash
sudo pacman -S nodejs  npm
sudo npm i docsify-cli -g
docsify init docs
docsify serve docs
```

All code could be fetch [here](https://github.com/BackMountainDevil/projectdemo/tree/9b597b1382b882729facba7ffb4724a0026f0690)

#### What is current behaviour

Fine. Because I know what cause that. This is the [soution](https://github.com/BackMountainDevil/projectdemo/commit/36e3916881539e03cd622fc8e56ce949435dda26)

How I find the solution? Use firefox + F12 to Inspect Element of the hide button in the sidebar. Then delete this will work fine  

`<script src="//cdn.jsdelivr.net/npm/docsify@4"></script>`

#### What is the expected behaviour

Is is a bug of npm package?  Or just my pc problem?

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?  
No plugins..

- Your OS: Linux arch 5.10.16-arch1-1
- Node.js version:  v15.11.0
- npm/yarn version: 7.6.1
- Browser version: Firefox 86.0 x64
- Docsify version: 4.4.2
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/maybe-tdu67)

**Comment by sy-records** [comment]
I tested it and found no problems.
Can you provide some more information? For example, screenshots or video recordings

**Comment by sy-records** [comment]
Thank you for your feedback, the problem is that you have loaded the same js file twice.

```html
  <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
```

Just one is all you need
