### ISSUE TITLE
A no existing id will make plugin stop work.

### ISSUE THREAD

**Issue by wellcomez** [docsifyjs/docsify#1537]
#### Steps to reproduce
http://127.0.0.1:3000/#/quickstart?id=06798c67-ac22-41c2-bcd1-cdc102dc4924

If id doesn't  exist on page ,
`
  function scrollIntoView(path, id) {
    if (!id) {
      return;
    }
    var topMargin = config().topMargin;
    var section = find('#' + id);  <<<<<< this function will throw exception 
    section && scrollTo(section, topMargin);

    var li = nav[getNavKey(path, id)];
    var sidebar = getNode('.sidebar');
    var active = find(sidebar, 'li.active');
    active && active.classList.remove('active');
    li && li.classList.add('active');
  }
`
#### What is current behaviour
   var section = find('#' + id);   will throw exception
   
   After exception happened , docsify's plugin loading procedure will stop and any other plugins will have no chance to be excuted.
#### What is the expected behaviour

add try catch to make work flow continue even an exception happened

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
It is not so clear to me, I mean why there is a non-exist id here? all the id should be rendered based on ur files.

**Comment by wellcomez** [comment]
> It is not so clear to me, I mean why there is a non-exist id here? all the id should be rendered based on ur files.

for example http://192.168.2.5:8080/#/README?id=usage usage is existed id 
If change `usage` to usagexxxxxxx which  doesn't exist on pag and open  http://192.168.2.5:8080/#/README?id=usagexxxxxxx , an exception will cause 3rd party plugin which `use  hook.doneEach(function () {});` have no chance to be excuted.

**Comment by wellcomez** [comment]
如果随便搞一个不存在的id放到id=后面，就会触发异常。如果插件是在doneEach中做初始化的将没有机会执行初始化 函数。
另外插件注册的流程，缺少一套接口和规范。导致多个插件的注册产生兼容性问题

**Comment by Koooooo-7** [comment]
I see.but it makes no sense to support an non exist id.
 and I test it on our [site](https://docsify.js.org/), there is no exception, I guess it's the plugin's issue.

and for the steps of registering plugins, we may document it more details in the future.
