### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'docsify.search.index' exceeded the quota.

### ISSUE THREAD

**Issue by wellcomez** [docsifyjs/docsify#1538]
## Bug Report
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'docsify.search.index' exceeded the quota.
#### Steps to reproduce

All documents size exceeds 400MB  . exceeded the quota error will occur

#### What is current behaviour
```
JSON.stringify(INDEXS).length
14474634
```

#### What is the expected behaviour

You can compact storage

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
yea,AFAIK there is an issues about the `LocalStorage` limitation( about 5MB), we will refine it in future. 
related #1400 。
