### ISSUE TITLE
how to add newline in code block markdown?

### ISSUE THREAD

**Issue by heart-er** [docsifyjs/docsify#1543]
## Bug Report
insert newline failed in code block;

#### Steps to reproduce
```
var a = 1;

var b = 2;
```
#### What is current behaviour
current result is : var a = 1;var b = 2;

#### What is the expected behaviour
expected result: 

var a = 1;
var b = 2;

#### Other relevant information

- Your OS:  macOS 11.0.1
- Node.js version: 10.19.1
- npm/yarn version: 6.13.4
- Browser version: 89.0.4389.90
- Docsify version:  4.4.3
- Docsify plugins:  4.4.3

**Comment by sy-records** [comment]
I don't have a reproduction problem, can you provide a sandbox?

![image](https://user-images.githubusercontent.com/33931153/112078823-0f315000-8bba-11eb-854c-60309532276d.png)

````
```
var a = 1;

var b = 2;
```
````
