### ISSUE TITLE
markdown toc not jump in body

### ISSUE THREAD

**Issue by max-young** [docsifyjs/docsify#1545]
## Bug Report

[table of content] in markdown, click,  not jump 

#### Steps to reproduce

toc in markdown, content is:
```
- [Preface](#preface)
- [1. Introduction](#1-introduction)
```
if section not have number, it can jump in body and sidebar.
if have number, it can jump in sidebar, but can't jump in body
href in body is "...1introduction", but href in sidebar is "..._1introduction", have a underline_ before "1inttroduction"

in my editor, markdown preview can jump

#### What is current behaviour

can't jump in body

#### What is the expected behaviour

href in body and sidebar should be same, and can jump

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS
- Node.js version: 11.22.0
- npm/yarn version: 7.6.3
- Browser version: chrome 89.0.4389.90
- Docsify version: 4.4.3
- Docsify plugins: docsify-footer

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Yes, the id you fill in needs to be the same as the one generated by docsify

**Comment by Joyyuezhao** [comment]
the same issue, when content is start with numbers, Docsify can't jump to the corresponding place. **However, in Typora when pressing ctrl and clicking at the same time, it can reach the right place.** I think the response action of Docsity should be the same as the mainstream markdown Editor.
