### ISSUE TITLE
C++ syntax highlighting error

### ISSUE THREAD

**Issue by jiongjarjar** [docsifyjs/docsify#1546]
#### Steps to reproduce
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/components/prism-cpp.js"></script>

#### What is current behaviour
docsify@4:1 Uncaught TypeError: Cannot set property 'class-name' of undefined
    at Object.extend (docsify@4:1)
    at prism-cpp.js:5
    at prism-cpp.js:56

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 x64
- Node.js version: v11.15.0
- npm/yarn version: 6.14.8
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
This seems to be an issue with PrismJS, you can submit an issue to them 

https://github.com/PrismJS/prism/issues/new/choose

![image](https://user-images.githubusercontent.com/33931153/112240113-ac57bb80-8c82-11eb-9261-d4c5b4b4f28b.png)
![image](https://user-images.githubusercontent.com/33931153/112240127-b37ec980-8c82-11eb-8f24-9484b625c8a5.png)
