### ISSUE TITLE
search.js v4.12.1 Cross-Site Scripting 

### ISSUE THREAD

**Issue by Ares-X** [docsifyjs/docsify#1549]
##### 1. create a simple docsify project
file tree
```
.
├── README.md
├── _sidebar.md
├── index.html
└── test
    └── xss.md
```
index.html
```
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>test</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify/lib/themes/vue.css">
  <link rel="stylesheet" href="/css/sidebar.css">
</head>
<body>

  <div id="app"></div>

  <script>
    window.$docsify = {
      loadSidebar: true,
      homepage: './README.md',
      alias:{
        '/.*/_sidebar.md': '/_sidebar.md',
      },
      autoHeader: true,
      auto2top: true,
      search: {
        noData: {
          '/': 'No results!'
        },
        paths: 'auto',
        placeholder: {
          '/': 'Search'
        },
        hideOtherSidebarContent: true,
        depth: 1
      },
      name: 'test',
    }
  </script>

  <script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.js"></script>

</body>
</html>
```

xss.md

```
# xss test

    xss"><img src=1 onerror=alert(1)><"
```

_sidebar.md

```
- Test
  - [xss](./test/xss.md)
```

##### 2. start a http server

![image](https://user-images.githubusercontent.com/30471149/113081487-57c8b900-920b-11eb-8099-d71c6ea61f0b.png)
![image](https://user-images.githubusercontent.com/30471149/113082103-6fed0800-920c-11eb-84cc-e11057ddba33.png)

when user search  something near XSS payload and the javascript which should rendering as markdown will be execute

##### 3. input `x` in search filed

![image](https://user-images.githubusercontent.com/30471149/113081528-6d3de300-920b-11eb-8a75-320d058e59a9.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  Mac OS
- Node.js version:  v12.19.0
- npm/yarn version: 
- Browser version: 
- Docsify version:  4.12.1
- Docsify plugins: search.js

#### Please create a reproducible sandbox 

https://xl9pw.csb.app/

**Comment by sy-records** [comment]
You should not write the wrong content... 

docsify does not filter errors content in the body.

**Comment by Ares-X** [comment]
4 space or one tab for Code Blocks  is a standard markdown syntax 

```
# title

    code

```

i don't think this is a wrong content

**Comment by sy-records** [comment]
Okay, I tested it without spaces...

```
xss"><img src=1 onerror=alert(1)><"
```

**Comment by Ares-X** [comment]
with out Code Blocks syntax markdown will rendering code as html 
The problem comes from the search plug didn't appropriate encode Code Blocks and let `"` escaped
![image](https://user-images.githubusercontent.com/30471149/113257644-7b6c2c00-92fd-11eb-8c5a-bb8a3d49971b.png)
![image](https://user-images.githubusercontent.com/30471149/113257760-a35b8f80-92fd-11eb-9ad5-6e7320a98611.png)

**Comment by sy-records** [comment]
Yes, here's what I removed, I'm revisiting
