### ISSUE TITLE
':include' not working in Docsify 4.12.1

### ISSUE THREAD

**Issue by wangmeng1991** [docsifyjs/docsify#1555]
> ![image](https://user-images.githubusercontent.com/33443928/114673724-14a53480-9d39-11eb-823b-90ef2d973cb6.png)
>
![image](https://user-images.githubusercontent.com/33443928/114673799-2a1a5e80-9d39-11eb-8417-356def9ea742.png)

> 
> Details:
> 
> * OS: macOS 11.2.3
> * Node.js version: 15.14.0
> * npm version: 7.8.0
> * Browser version: chrome 89.0.4389.114
> * Docsify version: 4.12.1
>

**Comment by sy-records** [comment]
Please use single quotes

```
[video](./test.mp4 ':include :type=video')
```

**Comment by trusktr** [comment]
Will be fixed by #1598
