### ISSUE TITLE
Sidebar category does not show the first subtitle sometimes

### ISSUE THREAD

**Issue by ShXDler** [docsifyjs/docsify#1556]
#### Steps to reproduce

Use the docsify-sidebar-collapse plugin.

#### What is current behaviour

![图片](https://user-images.githubusercontent.com/50830775/114855365-78525f00-9e18-11eb-80c2-b351ba00f4a1.png)
The sidebar category does not show the first subtitle correctly in some articles. As the picture shows, '1.文章简介' as the first level title is supposed to appear. However, the sidebar only shows the subtitles under '1.文章简介', e.g. '1.1 xxx' and '1.2 xxx'. I am not sure whether it is due to my inappropriate operations or a bug.

#### What is the expected behaviour

The first subtitle is correctly shown.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 
- npm/yarn version: 
- Browser version:  It seems to appear in Firefox and Microsoft Edge and other browsers.
- Docsify version: 
- Docsify plugins: docsify-sidebar-collapse

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
You should go to the docsify-sidebar-collapse repository and submit the [issue](https://github.com/iPeng6/docsify-sidebar-collapse/issues/new)
