### ISSUE TITLE
Broken Images, Aws Amplify

### ISSUE THREAD

**Issue by aeweda** [docsifyjs/docsify#1557]
#### Steps to reproduce

Following Documentation Steps to deploy docsify to AWS Amplify

#### What is current behaviour

Works fine locally, doesn't work on Amplify, images are returned with a `content-type: text/html`

#### What is the expected behaviour

after adding the following rewrite rules, images are expected to load properly
| Source address | Target address | Type          |
|----------------|----------------|---------------|
| /<*>.md        | /<*>.md        | 200 (Rewrite) |
| /<*>.png       | /<*>.png       | 200 (Rewrite) |
| /<*>           | /index.html    | 200 (Rewrite) |

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: `Linux`
- Node.js version: `14.16.0`
- npm/yarn version: `6.14.11`
- Browser version: `Chrome 88`
- Docsify version: `4.4.3`
- Docsify plugins: `no-plugins`

#### Sandbox Attached

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/docsify-amplify-bug-s44wd)

#### Mention the docsify version in which this bug was not present (if any)
not sure if it's just related to docsify or amplify x docsify

**Comment by Koooooo-7** [comment]
It is the our doc about [how to deploy on AWS](https://docsify.js.org/#/deploy?id=aws-amplify). it should add the redirect rules.
I wonder if it works when u fellow the steps of the docs eventually. thx.

**Comment by aeweda** [comment]
> It is the our doc about [how to deploy on AWS](https://docsify.js.org/#/deploy?id=aws-amplify). it should add the redirect rules.
> I wonder if it works when u fellow the steps of the docs eventually. thx.

I'm not saying it's not your in documentation, I'm saying I followed your documentation to the letter with the latest inclusion of those rewrite rules & despite that all that, the images are still broken on amplify

**Comment by Koooooo-7** [comment]
> > It is the our doc about [how to deploy on AWS](https://docsify.js.org/#/deploy?id=aws-amplify). it should add the redirect rules.
> > I wonder if it works when u fellow the steps of the docs eventually. thx.
> 
> I'm not saying it's not your in documentation, I'm saying I followed your documentation to the letter with the latest inclusion of those rewrite rules & despite that all that, the images are still broken on amplify

I see， could u provide ur site or the `relative path` of those broken images to make sure whats wrong there.

**Comment by aeweda** [comment]
You can find that in the codesandbox sample attached to the issue, if you push that example to amplify the images will break, including the logo image defined in the `index.html`

**Comment by aeweda** [comment]
@Koooooo-7 you can go ahead and close this one, the fix for anyone who stumbles upon this was to remove `historymode` from `index.html`

**Comment by Koooooo-7** [comment]
> @Koooooo-7 you can go ahead and close this one, the fix for anyone who stumbles upon this was to remove `historymode` from `index.html`

yea. thx for ur feedback.
