### ISSUE TITLE
Not playable video after setting width

### ISSUE THREAD

**Issue by GABAnich** [docsifyjs/docsify#1558]
## Bug Report

```markdown
[Example](_media/actions_example.mp4 ':include :type=video width=100%')
```

![image](https://user-images.githubusercontent.com/26234053/115070225-51ba2400-9efd-11eb-893b-127abfd1e90c.png)

#### Steps to reproduce

```markdown
[Example](_media/actions_example.mp4 ':include :type=video width=100%')
```

#### What is current behaviour

The video is not playable

#### What is the expected behavior

The video should be playable with width 100%

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 18.04.5 LTS (Bionic Beaver)
- Node.js version: v12.13.1
- npm/yarn version: yarn -v:  1.22.5 
- Browser version: Google Chrome Version 89.0.4389.82 (Official Build) (64-bit)
- Docsify version: 4.4.3
- Docsify plugins:     <script src="//cdn.jsdelivr.net/npm/prismjs@1.23.0/components/prism-graphql.min.js"></script>

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by GABAnich** [comment]
Seems once we setup video attributes like `width` default attribute `controls` disappears

It works with these code:

```markdown
[Example](_media/actions_example.mp4 ':include :type=video width=100% controls')
```

**Comment by GABAnich** [comment]
Take look at https://github.com/docsifyjs/docsify/blob/c24f7f6f0b87a87f6dd3755f69eb0969ebb029c9/src/core/render/compiler.js#L37

Once any attribute is set, `controls` will be replaced

**Comment by Koooooo-7** [comment]
thx for ur report ! it seems should be refine.
when the `title` is not empty, the `controls` would be removed.
you can use the `[Example](_media/actions_example.mp4 ':include :type=video controls width=100%')` to add the `controls` manually for now.
