### ISSUE TITLE
Dedicated Sticky TOC (Table of Contents) on Right Side

### ISSUE THREAD

**Issue by htakemoto** [docsifyjs/docsify#1560]
## Feature request

I would like to see a sticky TOC on dedicated right side section rather than putting inside the left sidebar as it is difficult to navigate with a lot of contents.

#### What problem does this feature solve?

Sticky TOC is becoming popular on Doc (i.e https://docs.docker.com/get-started/). Other doc framework such as Docusaurus also has this feature by default. It is more natural to see TOC on right side rather than side bar combined with navigation links.

#### What does the proposed API look like?

We can possibly incorporate docsify-plugin-toc plugin<br>
https://github.com/justintien/docsify-plugin-toc<br>

#### How should this be implemented in your opinion?

I believe we can fully borrow the idea from the plugin above<br>
Demo: https://blog.jiapan.tw/ops/cloud/README

#### Are you willing to work on this yourself?

No

**Comment by sy-records** [comment]
Merge this plugin into docsify, its way is also plugin, why not just use it?

**Comment by htakemoto** [comment]
I feel this is an essential feature considering the UX trend across many doc pages. It took me a long time to implement it into my project. The essential level is similar to search, disqus and emoji. I strongly believe this feature also attracts new users. I hope to see this feature as a part of default plugins.

**Comment by sy-records** [comment]
cc @docsifyjs/reviewers

**Comment by Koooooo-7** [comment]
Thx for ur good suggestion. :+1:
We may plan to move out all of the plugins out of our main repo and place to something like `official recommend plugins` and integrate to `cli` in the future. 
I suppose u could add this `docsify-plugin-toc` plugin to our [awesome-docsify](https://github.com/docsifyjs/awesome-docsify) list for sharing with more users , TIA. 
BTW: that's a nice blog tho.

**Comment by stigmollerhansen** [comment]
Fully agree on this. The ability to toggle a theme-responsive sticky auto-generated TOC on the right side would be a much appreciated addition to Docsify. Unfortunately I don't have the tech skills to offer to work on implementing this feature.

**Comment by trusktr** [comment]
This already works as a plugin, I don't think there is a need to make it part of Docsify. We should make sure we don't break Docsify APIs so that plugins like docsify-plugin-toc will continue to work.

However we can definitely add it to the `awesome-docsify` list (PR welcome!).

Any ideas on how we can improve the left-side sidebar to make that easier, instead of duplicating content?
