### ISSUE TITLE
sidebar relative path issues

### ISSUE THREAD

**Issue by wizardforcel** [docsifyjs/docsify#1569]
#### Steps to reproduce

1.  set `relativePath` as `true`

2.  set `loadSidebar` as `SUMMARY.md`

3. create `path/to/doc1.md` and `path/to/doc2.md`

3.  write the link `path/to/doc2.md` to `SUMMARY.md`

4.  access `#/path/to/doc1`

#### What is current behaviour

the sidebar link is `#/path/to/path/to/doc2`

#### What is the expected behaviour

the sidebar link should be `#/path/to/doc2`

The sidebar and article come from different sources, so have different base pathes.

The base path of all sidebar links should be `dirname($docsify.loadSidebar)`, not `dirname(location.hash)`.

#### Other relevant information

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.11.6
- Docsify plugins:

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
