### ISSUE TITLE
Need a function or plugin to to display the commit date for each md file

### ISSUE THREAD

**Issue by Immortalt** [docsifyjs/docsify#1572]
#### What problem does this feature solve?
I use docsify as my blog, but I can't see each post's date.
Are there any way to meet this requirement?

#### What does the proposed API look like?
Automatically generate or caculate the create time for each md file,
 and display on the web.

#### How should this be implemented in your opinion?
Like a build-in config to open this function on, or a plugin.
The cli or plugin can fetch the create date and edit date from the git commit log and calculate every time we committing local doc to the Github. The date can be stored in the MD file in a specific style, or it can be stored in a separate file and read by js.

#### Are you willing to work on this yourself?
I'm not sure if I am able to write and achieve this function.

**Comment by sy-records** [comment]
see https://docsify.js.org/#/configuration?id=formatupdated
