### ISSUE TITLE
The formatUpdated config doesn't display any thing

### ISSUE THREAD

**Issue by Immortalt** [docsifyjs/docsify#1573]
## Bug Report
You can see in this page's code:
https://github.com/immortal-blog/immortal-blog.github.io/blob/main/docs/index.html
and you can see that all pages don't have update time:
https://immortal-blog.github.io/#/golang/migrate-mgo-to-qmgo
I added the config as the doc mentioned,
```
window.$docsify = {
                formatUpdated: '{YYYY}-{MM}-{DD}',
```
but I still can't see any change in my blog. There is no time.
(I'm sure that I cleaned the cache before refreshing the page)
#### Steps to reproduce
1. Create a Github Page using docsify like https://immortal-blog.github.io/#/, or you can just fork this git.
2. Add the config option: formatUpdated: '{YYYY}-{MM}-{DD}'.
3. Clean the browser cache and refresh the Github Page.

#### What is current behaviour
Nothing changed.
There is no update time on the page.

#### What is the expected behaviour
There is an update time on the page.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 20.04 LTS
- Node.js version: v14.16.1
- npm/yarn version: 7.12.0
- Browser version: Firefox 88.0.1 x64
- Docsify version: 4.4.3
- Docsify plugins: disabled all

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
you need add `{docsify-updated}`


```diff
    window.$docsify = {
        formatUpdated: '{YYYY}-{MM}-{DD}',
        name: 'Immortal Blog',
        repo: '',
        auto2top: true,
        coverpage: true,
        loadSidebar: true,
        maxLevel: 4,
        subMaxLevel: 2,
+        plugins: [
+            function(hook, vm) {
+                hook.beforeEach(function(html) {
+                    return (
+                        html +
+                        '\n----\n' +
+                        'Last modified {docsify-updated}'
+                    );
+                });
+            }
+        ]
+    }
```

**Comment by Immortalt** [comment]
> ```diff
> +        plugins: [
> +            function(hook, vm) {
> +                hook.beforeEach(function(html) {
> +                    return (
> +                        html +
> +                        '\n----\n' +
> +                        'Last modified {docsify-updated}'
> +                    );
> +                });
> +            }
> +        ]
> ```

It seems that the problem solved. Thanks!
But I think docsify's doc needs to add this info, otherwise other user will also meet this problem and waste some time again and again.

**Comment by Immortalt** [comment]
> you need add `{docsify-updated}`
> 
> ```diff
>     window.$docsify = {
>         formatUpdated: '{YYYY}-{MM}-{DD}',
>         name: 'Immortal Blog',
>         repo: '',
>         auto2top: true,
>         coverpage: true,
>         loadSidebar: true,
>         maxLevel: 4,
>         subMaxLevel: 2,
> +        plugins: [
> +            function(hook, vm) {
> +                hook.beforeEach(function(html) {
> +                    return (
> +                        html +
> +                        '\n----\n' +
> +                        'Last modified {docsify-updated}'
> +                    );
> +                });
> +            }
> +        ]
> +    }
> ```

It seems that the problem solved. Thanks!
But I think docsify's doc needs to add this info, otherwise other user will also meet this problem and waste some time again and again.

**Comment by sy-records** [comment]
Here's an example https://github.com/docsifyjs/docsify/blob/develop/docs/write-a-plugin.md#edit-button
