### ISSUE TITLE
Code, Commands Copy Button

### ISSUE THREAD

**Issue by Siddhant-K-code** [docsifyjs/docsify#1575]
## Feature request
We Can add a Copy button to the right side of, ( like GitHub did it ) 

![image](https://user-images.githubusercontent.com/55068936/118633702-5f5e1480-b7ef-11eb-9abf-ef758c15bbb6.png)

#### What problem does this feature solve?
It will help users to copy & useCode Snippets or terminal Commands.

#### What does the proposed API look like?
Returning a Copy Snippet Button.

#### How should this be implemented in your opinion?
Just a Simple button to Copy.

#### Are you willing to work on this yourself?
Yes

**Comment by sy-records** [comment]
see https://docsify.js.org/#/plugins?id=copy-to-clipboard
