### ISSUE TITLE
Access docsify-demo-box-vue according to the example, but it does not display correctly

### ISSUE THREAD

**Issue by awzks1314** [docsifyjs/docsify#1583]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by jhildenbiddle** [comment]
This is a plugin-specific issue. Please create the issue within the [docsify-demo-box-vue](https://github.com/njleonzhang/docsify-demo-box-vue) repo.
