### ISSUE TITLE
Search plugin has collisions despite using different namespaces

### ISSUE THREAD

**Issue by AlCalzone** [docsifyjs/docsify#1591]
#### Steps to reproduce
We have two repositories under the same org, both with a Docisify documentation. In the past we've set the `namespace` option to avoid collisions in the search result, but it seems that isn't working reliably.

#### What is current behaviour
When switching from the [first project's documentation](https://zwave-js.github.io/zwavejs2mqtt/#/) to the [second project's](https://zwave-js.github.io/node-zwave-js/#/), the search still returns results for the first project, resulting in a 404:
https://github.com/zwave-js/node-zwave-js/issues/2868

#### What is the expected behaviour
Both documentations to have their separate search index

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: not relevant
- Node.js version: not relevant
- npm/yarn version: not relevant
- Browser version: Firefox 89.0
- Docsify version: 4.12.1
- Docsify plugins: Search

#### Please create a reproducible sandbox 

See description of current behavior.

#### Mention the docsify version in which this bug was not present (if any)

Don't know

**Comment by sy-records** [comment]
I submitted PRs to you. https://github.com/zwave-js/zwavejs2mqtt/pull/1356 https://github.com/zwave-js/node-zwave-js/pull/2877

`namespace` needs to be in `search`

```html
 search: {
    namespace: 'zwavejs2mqtt',
},
```
