### ISSUE TITLE
Unable to scroll in the coverpage and there are two search boxes

### ISSUE THREAD

**Issue by zzsqwq** [docsifyjs/docsify#1593]
#### Steps to reproduce
My code is at https://github.com/zzsqwq/zs_docsify

And I deployed it on https://zzsqwq.github.io/zs_docsify/

You can browse online or use `git clone` and `docsify serve docs` to reproduce this problem

You can click `Getting Read` to enter the homepage

There is a reproducible sandbox , you can reproduce this problem easily

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-shadow-fb44r)

#### What is current behaviour
1 . When I set `onlycover` to `false`, there is still looks like only the coverpage, that is, I can't scroll down the page with the mouse
2. There will be two search boxes on the homepage, and they will work at the same time
3. I can't collapse the sidebar
4.  When I use python or `docsify serve` in `docsify-cli` to start the server or deploy it in `Apache`,`Github Pages`,`Nginx`, the above problems will occur, but if I use `clion` to start the server, the above problems will not occur
#### What is the expected behaviour
1. The cover can scroll normally
2. There is only one search bar
3. You can collapse the sidebar

Looking forward to your reply! Thanks!
#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS:  Ubuntu 18.04.5
- Node.js version:  14.17.1
- npm/yarn version:  npm 6.14.13
- Browser version: chrome 91.0.4472.101
- Docsify version:  4.4.3
- Docsify plugins: search

**Comment by sy-records** [comment]
Just keep a docsify@4 or docsify.min.js

https://github.com/zzsqwq/zs_docsify/blob/main/docs/index.html#L26

```diff
-  <script src="docsify-js/docsify@4"></script>
  <script src="docsify-js/docsify.min.js"></script>
```
