### ISSUE TITLE
embed quotes bug

### ISSUE THREAD

**Issue by luwol03** [docsifyjs/docsify#1597]
#### Steps to reproduce
1. Create empty docsify project
2. Add following to one markdown file
  ```markdown
  [gist: script.js](https://gist.githubusercontent.com/anikethsaha/f88893bb563bb7229d6e575db53a8c15/raw/script.js ":include :type=code")
  ```
3. See not renderd embed 

#### What is current behaviour

Embedded gist will not be renderd.

#### What is the expected behaviour

Embedded gist should be renderd.

#### Other relevant information

This is not working because the type of quotes are not supported. The default prettier configuration changes the `''` to  `""`. And if you have auto format toggled on, you're not be able to save the file working.

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: any os
- Node.js version: any nodejs version
- npm/yarn version: any yarn/npm version
- Browser version: any browser and version
- Docsify version: 4.12.1
- Docsify plugins: none

#### Please create a reproducible sandbox 

[![Edit docsify-template-forked-zlwql](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/docsify-template-forked-zlwql)

**Comment by trusktr** [comment]
Asper conversation at https://discord.com/channels/713647066802421792/719155521109884978/855738415399043082, double quotes don't work, but single quotes do. I haven't tried this particular feature to confirm, but I imagine there's an easy fix for it.
