### ISSUE TITLE
flaky tests

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1602]
The tests seem to be flaky for some reason. I re-ran the tests in https://github.com/docsifyjs/docsify/pull/1598 like 5+ times, and could not get them to pass. Each time, a different test failed.

cc @jhildenbiddle Any ideas?

**Comment by jhildenbiddle** [comment]
@trusktr --

I'm seeing the same behavior when testing locally. The first time I ran all tests everything passed without issue. The second time a failure occurred in `test/e2e/index-file.test.js`. I can confirm, however, that skipping the tests in `index-file.test.js` resulted in five test runs without a single failure. I haven't spent a ton of time on this, but Playwright is providing useful information to help track down the issue:

<img width="620" alt="CleanShot 2021-06-26 at 17 39 14@2x" src="https://user-images.githubusercontent.com/442527/123527487-9f919c00-d6a5-11eb-8368-ffc1143bfe7b.png">

It's clear from the text in the error that when this test fails, the content being loaded into `#main` is from `plugins.md` and not `README.md` as expected. Why? Not sure yet, but this gives us a place to start.

More to come...

**Comment by jhildenbiddle** [comment]
Addressed in #1736
