### ISSUE TITLE
Fix the navigation bar and add the back to top button

### ISSUE THREAD

**Issue by dbses** [docsifyjs/docsify#1612]
#### What problem does this feature solve?

Click the navigation bar when browsing documents.

**Comment by trusktr** [comment]
Why is this closed? I think feature request should be triaged, and at least a message before closing.

**Comment by trusktr** [comment]
@dbses Can you expand? Seems a back-to-top button can be added as a non-breaking option.

**Comment by sy-records** [comment]
You can use the [Pagination](https://github.com/imyelo/docsify-pagination) plugin. see https://docsify.js.org/#/plugins?id=pagination

**Comment by dbses** [comment]
> You can use the [Pagination](https://github.com/imyelo/docsify-pagination) plugin. see https://docsify.js.org/#/plugins?id=pagination

It doesn't work when I haven't set the property `loadsidebar: true`. The content of the article is more important to me than the sidebar.

**Comment by sy-records** [comment]
If you don't use `loadSidebar` then it won't know where your next post is.

Your idea should be to add a `nav` for setting the corresponding post address; so you need to go back to the top.

**Comment by trusktr** [comment]
Also, [docsify-scroll-to-top](https://www.npmjs.com/package/docsify-scroll-to-top)
