### ISSUE TITLE
I am writing a plugin that support image caption, but when it serves with docsify, only even order image works correctly

### ISSUE THREAD

**Issue by Joaxin** [docsifyjs/docsify#1613]
#### Steps to reproduce

The key code is here
```js
                hook.beforeEach(function (content) {
                    let mark_imgReg = /!\[(?<alt>[^\]]*)\]\((?<filename>.*?)(?=\"|\))(?<title>\".*\")?\)/g;
                    let mark_img = content.match(mark_imgReg);
                    if (mark_img) {
                        mark_img.forEach(function (item, idx) {
                            console.log(item, idx)
                            let match = mark_imgReg.exec(item);
                            console.log(match)
                            if (match) {
                                if (match.groups.alt) {
                                    content = content.replace(item, `<figure>
<img src="${match.groups.filename}" width="100%" alt="${match.groups.alt}" title = "${match.groups.title}">
    <figcaption>${match.groups.alt}</figcaption>
</figure>`)
                                } else {
                                    content = content.replace(item, `<figure>
<img src="${match.groups.filename}" width="100%" alt="${match.groups.alt}" title = "${match.groups.title}">
</figure>`)
                                }
                            }
                        })
                    }
                })
```

#### What is current behaviour

See screenshots, only even order image works correctly 
![](https://i.postimg.cc/Y2br26pK/image.png)

#### What is the expected behaviour

All images work correctly 

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows_NT 10.0.19041 win32 x64
- Node.js version: 16.1.0
- npm/yarn version: 7.11.2
- Browser version: Version 91.0.4472.114 (Official Build) (64-bit)
- Docsify version: 4.12.1
- Docsify plugins:  None, I create a project without any plugins the problem still happens.

**Comment by Koooooo-7** [comment]
Hi. 
IMO, It is not our side problem.
When you change to rematch a new string by `exec()`, you need reset the `lastIndex` manually.
```js
                            console.log(item, idx)
                            let match = mark_imgReg.exec(item);
                            console.log(match)
                            mark_imgReg.lastIndex = 0
```

FYI.  [Finding successive matches](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#finding_successive_matches)
