### ISSUE TITLE
Sidebar not being displayed and search not working when deployed to GitHub Pages

### ISSUE THREAD

**Issue by reymon359** [docsifyjs/docsify#1623]
## Bug Report

The sidebar dissapears and the search stops working when deploying to GitHub Pages

I already submitted an issue in the plugin repo https://github.com/iPeng6/docsify-sidebar-collapse/issues/29, however I decided to submit it here too in case someone can help 😄 

#### Steps to reproduce

- Have a look at this repo and clone it https://github.com/reymon359/collman-fruits-example
- run `docsify serve docs` to see how it works locally
- check https://reymon359.github.io/collman-fruits-example/#/ to compare how the issue is happening there and not locally

#### What is current behaviour

The sidebar is not being displayed when deployed to Github Pages

<img width="536" alt="129520874-3405f26f-0c64-4f02-84b5-8faa0562f3d1" src="https://user-images.githubusercontent.com/31936665/129545451-28f9e5dc-bc78-4796-844a-573bf0d15f2e.png">

However it works locally 

<img width="396" alt="129521254-01705fc6-c261-4456-add8-af125dc9964b" src="https://user-images.githubusercontent.com/31936665/129608234-f3d3ca69-33d7-449a-abbd-82ff446a77b7.png">

#### What is the expected behaviour

The sidebar should appear when deployed to GitHub Pages the same way it works locally

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?
- Your OS: macOS version 10.15.4 (19E266)
- Node.js version: v14.17.4
- npm/yarn version: 6.14.14 / 1.22.4
- Browser version: Brave
- Docsify version: 4
- Docsify plugins: search, docsify-sidebar-collapse, docsify-themeable, docsify-pagination, zoom-image

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collman-fruits-example-vrfut)

**Comment by sy-records** [comment]
You need to set the [basePath](https://docsify.js.org/#/configuration?id=basepath)

```markup
basePath: '/docsify-sidebar-collapse/',
```

**Comment by reymon359** [comment]
Hi there @sy-records!

Thank you for the suggestion. I tried adding the `basePath: '/docsify-sidebar-collapse/',` to the `window.$docsify `
 object in the repo https://github.com/reymon359/collman-fruits-example `index.html` file, but it didn't work. 🤔 

I had a proper look at the docs and tried these too(without success):
- [adding `basePath: '/',`](https://github.com/reymon359/collman-fruits-example/commit/657ccf49ed719478dfd01fbd3b116efaa9bd886f ) 
- [adding `basePath: '/docsify-sidebar-collapse/',`](https://github.com/reymon359/collman-fruits-example/commit/99c77124925efa3d18d4c411a4e8fe457880289f ) 
- [adding `relativePath: true,`](https://github.com/reymon359/collman-fruits-example/commit/702be61faa1ea78319667bae5af1d4d83f8e6290) 
- [adding `basePath: '/collman-fruits-example/',`](https://github.com/reymon359/collman-fruits-example/commit/84df9e7b40ce984b245637f77120031029a3a7e0 ) 

In the end this one worked. However, I feel it is a bit unnecessary to add the full raw URL path.
- [adding `basePath: 'https://raw.githubusercontent.com/reymon359/collman-fruits-example/master/docs/',`](https://github.com/reymon359/collman-fruits-example/commit/cd36463fc85c57dc4d5eb23570ee4dd3dc06bd89 ) 

Thank you again for the help and have a great day full of meat 🍖 !  😄

**Comment by SumithChandran** [comment]
This method is ok if the git repo is publicly accessible. If its in an organization and is private it wont work. That's what happened to me.

I too faced the same issue of blank sidebar. After a quick inspect of webpage in chrome I found that when page is hosted, _sidebar.md was facing a fall back issue since it was loaded from each level directory.

The fix that worked for me was to use [Nested  Sidebar](https://docsify.js.org/#/more-pages?id=nested-sidebars).
I just added alias with the intex.html and my issue got fixed. 

`<script>
  window.$docsify = {
    loadSidebar: true,
    alias: {
      '/.*/_sidebar.md': '/_sidebar.md'
    }
  }
</script>`

Please try and see if this works

**Comment by jellehak** [comment]
I also found that gh-pages is not serving the `_sidebar.md` file for some reason. Perhaps it is ignoring files that start with an `_` ?

**Comment by ThomasThelen** [comment]
Can calso onfirm that adding `.nojekyll`to the project root solves this problem
