### ISSUE TITLE
sidebar-toggle-button is invisible on Safari on small screen

### ISSUE THREAD

**Issue by kopylovvlad** [docsifyjs/docsify#1632]
## Bug Report

Hello. I use docsify 4.4.3 and noticed a bug on Safari 13.1.3. sidebar-toggle-button is invisible on Safari if the screen is less then 760px. On Opera 74.0.3911.75 and Safari 14.1.2 it works.

Here is a link to a screenshot:
https://www.dropbox.com/s/ta3ct4rekiz2al9/docsifyjs_sidebar_bug.png?dl=0

#### Steps to reproduce

1. Run `docsify init ./docs`
2. Open `docs/index.html` file and add `loadSidebar: true`
3. Create `_sidebar.md` file with content.
4. Run `docsify serve ./docs`
5. Open Safari 13.1.3
6. Make your screen smaller

- Your OS: MacOs Catalina 10.15.7
- Browser version: Safari 13.1.3
- Docsify version:  docsify-cli 4.4.3

**Comment by sy-records** [comment]
I wasn't able to reproduce your question

![image](https://user-images.githubusercontent.com/33931153/132087199-f1a99654-a9e8-449e-9fd5-648f28e63009.png)

**Comment by kopylovvlad** [comment]
Thank you very much for your quick answer. Have you tried to reproduce it on desktop Safari? 🤔 Because I had problem only on desktop.

If you can't reproduce it maybe there is something wrong with my machine and you can close the issue.. But I'm glad that on Safari 14.1.2 it works. 😃

**Comment by kopylovvlad** [comment]
And have you tried to reproduce the bug by creating new docsify app from the scratch?

**Comment by sy-records** [comment]
I tried it and still no problem

![image](https://user-images.githubusercontent.com/33931153/132087654-77637d82-0e54-48a1-ae43-435dc2abbb81.png)

**Comment by kopylovvlad** [comment]
Ok. Thanks for your help. Maybe one of Safari's extensions does it.
