### ISSUE TITLE
Can the cover can be fixed?

### ISSUE THREAD

**Issue by 9uest** [docsifyjs/docsify#1637]
I want to fix the cover. Is there any way?

**Comment by 9uest** [comment]
Can you customize the CSS of each cover?

**Comment by sy-records** [comment]
What's wrong with the cover? You can use css to optimize

**Comment by 9uest** [comment]
I don't want the cover to slip
I do not like this
I want to fix the cover, what should I configure?
![444](https://user-images.githubusercontent.com/11766504/134268196-c4a25192-3b57-48c2-b0c6-9c26b12acc17.gif)

**Comment by sy-records** [comment]
see https://docsify.js.org/#/configuration?id=onlycover

**Comment by 9uest** [comment]
thx
