### ISSUE TITLE
how to change url from  http://{ip}:{port}/#/    to    http://{ip}:{port}/document

### ISSUE THREAD

**Issue by LFDwater** [docsifyjs/docsify#1642]
i want to change url from  http://{ip}:{port}/#/    to    http://{ip}:{port}/document
and my settings as follows:
```
 window.$docsify = {
      routerMode: 'history',
      name: '',
      repo: '',
      notFoundPage: true,
      alias: {
        '/document': '/'
      },
    }
```
but when i visit http://{ip}:{port}/document ，a problem show   GET Error /document

**Comment by sy-records** [comment]
see https://github.com/docsifyjs/docsify/issues/720
