### ISSUE TITLE
Docs(docx, xlsx...) download from docsify server change and can not be open correct.

### ISSUE THREAD

**Issue by Chernfalin** [docsifyjs/docsify#1658]
## Bug Report
Docs(docx, xlsx...) download from docsify server can not be open correct, change link from markdown to html5 download link work fine.
#### Steps to reproduce
Put some file to docsify server, such as a docx file, use markdown link for download, such as :
\[a docx file](./folder/file.docx)
Downloaded this docx file frome the link, the file content change and can not be open by office word.
Change the markdown link to html5 stye, such as:
\<a href='ip:port/file.docx' download>file\</a>(must include "download")
It have no any problem.

#### What is current behaviour
docx/xlsx file download frome docsify broke(file size bigger than the raw).

#### What is the expected behaviour
Just download and don't change the file content.

#### Other relevant information

- Your OS:
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.12.1
- Docsify plugins:

**Comment by sy-records** [comment]
Thank you for your feedback. But I tested it and got a different result. I use chrome for testing.

```
[a docx file](../resource/test.docx)

<a href='http://localhost:3000/resource/test.docx' download>file</a>
```

use markdown, got 404. 

use html5, normal download.

use html5, no download: 

```
<a href='http://localhost:3000/resource/test.docx'>file</a>
```

It is also a normal download. 

You can create a reproducible sandbox or repo, complete the issue template for the current issue.

**Comment by Chernfalin** [comment]
> Thank you for your feedback. But I tested it and got a different result. I use chrome for testing.
> 
> ```
> [a docx file](../resource/test.docx)
> 
> <a href='http://localhost:3000/resource/test.docx' download>file</a>
> ```
> 
> use markdown, got 404.
> 
> use html5, normal download.
> 
> use html5, no download:
> 
> ```
> <a href='http://localhost:3000/resource/test.docx'>file</a>
> ```
> 
> It is also a normal download.
> 
> You can create a reproducible sandbox or repo, complete the issue template for the current issue.

Download is ok, my problem is the downloaded file is corrupted, file size changed.
raw file size: 914k
use markdown: 1.6m
use html, normal download: 914k ok
use html, no download: 1.6m
Can you open the downloaded docx file?

**Comment by sy-records** [comment]
yes.

You can create a reproducible sandbox or repo.

**Comment by Chernfalin** [comment]
Change chrome to another browser solved this problem.
My chrome installed many plugins.
Maybe a certain doc plugin cause this problem.
thx all the same.
