### ISSUE TITLE
Navigation does not work when Google Translate is activated

### ISSUE THREAD

**Issue by atrolex** [docsifyjs/docsify#1665]
## Bug Report
If I use this button to translate the content
![image](https://user-images.githubusercontent.com/33658481/142181599-df6c724e-02bf-4e98-930a-4a0958a33f78.png)
this anchor navigation doesn't work:
![image](https://user-images.githubusercontent.com/33658481/142181916-ad0b0635-bd9a-44bb-80d9-379a9a168246.png)

#### Steps to reproduce
1) Chick on the translate button in chrome
2) Try to use the navigation items in the sidebar here: https://docsify.js.org/#/configuration?id=hidesidebar
or here: https://help.atrocore.com/#/

Only anchor navigation is affected. Navigation through different pages works as expected.

#### What is current behaviour
Click on some anchor navagation item, nothing happens.

#### What is the expected behaviour
I expect the page to be scrolled to the proper header.

#### Other relevant information
Tried to switch off all the modules, not helped.

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 
Check your own documentation
[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
latest

**Comment by 4lexo** [comment]
Bug is also available if google translate is added to the documentation directly:
![image](https://user-images.githubusercontent.com/33658481/144756194-894ef488-d954-4944-84e7-4affac36802d.png)

**Comment by sy-records** [comment]
Thank you for your feedback, the problem does exist.

Feel free to submit a PR.

**Comment by jhildenbiddle** [comment]
Confirmed working on https://docsify.js.org/ using Chrome 126.
