### ISSUE TITLE
Wrong path for the images in html tags

### ISSUE THREAD

**Issue by ruanqizhen** [docsifyjs/docsify#1674]
#### Steps to reproduce
My md file is in folder "mypage.com/docs/"
for this tag ```<img src="images/image360.png" style="width:2.39426in;height:0.70169in" />```
I expected to get a image link as "mypage.com/docs/images/image360.png"

#### What is current behaviour
Docsify got an image path as "mypage.com/images/image360.png"

#### What is the expected behaviour
I expected to get a image link as "mypage.com/docs/images/image360.png"

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
This is the correct parsing behavior

**Comment by ruanqizhen** [comment]
> This is the correct parsing behavior

I don't think so, all other parsers like GitHub, GitBook, use the folder of current md doc as base path for the image.  Only Docsify use page root as the path page.   This is also inconsistent with Docisy itself,  because image markdown code use  the folder of current md doc as base path.

**Comment by sy-records** [comment]
Your index.html is in the docs directory, not the parent

**Comment by ruanqizhen** [comment]
> Your index.html is in the docs directory, not the parent

My index.html is in the root directory, not in docs directory.

**Comment by sy-records** [comment]
Provide a reproducible sandbox or repo

**Comment by sy-records** [comment]
When you use html style, you need to set routerMode to `history`, but this will cause access exceptions when you deploy using GitHub pages.

**Comment by ruanqizhen** [comment]
> When you use html style, you need to set routerMode to `history`, but this will cause access exceptions when you deploy using GitHub pages.

So, Docsify will not support html style that deployed on GitHub Pages, correct?
