### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by loungkayewechat** [docsifyjs/docsify#1677]
#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

#### Mention the docsify version in which this bug was not present (if any)
[github-issue-templates-master.zip](https://github.com/docsifyjs/docsify/files/7646417/github-issue-templates-master.zip)

**Comment by loungkayewechat** [comment]
[github-issue-templates-master (1).zip](https://github.com/docsifyjs/docsify/files/7646424/github-issue-templates-master.1.zip)

**Comment by sy-records** [comment]
Please follow the template to submit an issue
