### ISSUE TITLE
Front-matter broken. Also add documentation

### ISSUE THREAD

**Issue by Kikobeats** [docsifyjs/docsify#168]
No idea what is the purpose of this plugin

**Comment by QingWei-Li** [comment]
Actually I have not any idea what this plugin can do 😂

**Comment by jrappen** [comment]
https://github.com/egoist/docute/blob/0096fc1327b695f810ea652cb0adbe0c1cddccec/src/views/Page.vue#L273-L288

It overrides page attributes as far as I can tell.

**Comment by cgatian** [comment]
This is used to remove the front matter section that is located at the top of technical markdown documentation.

```
---
Title: XXX
Ref: 123
Authors: Some Guy
Created: 2018-05-24
---
```

**Comment by jthegedus** [comment]
Just having come across this myself, how are the attributes from the front-matter used by Docsify? Are the attributes used at all by the core, or are they simple extracted to then be used by other plugins after the fact?

**Comment by trusktr** [comment]
> Just having come across this myself, how are the attributes from the front-matter used by Docsify? Are the attributes used at all by the core, or are they simple extracted to then be used by other plugins after the fact?

I think it just strips them based on the comment above.

**Comment by trusktr** [comment]
Re-opening, this should be documented.

**Comment by thomascatlee** [comment]
Still no document about front-matter.
And [https://docsify.js.org/#/embed-files?id=markdown-with-yaml-front-matter](url) gave a wrong example, in which the front-matter plugin didn't work.
![image](https://github.com/docsifyjs/docsify/assets/484823/58262cff-54f2-42d8-baad-6351a259c767)

**Comment by trusktr** [comment]
Oh, yeah, that's broken! Anyone have time to fix this one?
