### ISSUE TITLE
Many CSS and JS suddenly failed

### ISSUE THREAD

**Issue by youthlql** [docsifyjs/docsify#1682]
![$4Y5`OD4VD6MZ@RLRLNYMO2](https://user-images.githubusercontent.com/49017153/144733530-7f92bf10-7d50-4ac6-bde3-c01fcd7e62cf.png)
I didn't move anything. I've been visiting well before. Today, it suddenly failed

**Comment by trusktr** [comment]
@youthlql Hi, what's the URL that is not working? Can't see anything in the screenshot

**Comment by youthlql** [comment]
<link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/prism.css">
  
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">

  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
  
  <script src="//unpkg.com/prismjs/components/prism-java.js"></script>
  
  <script src="https://cdn.bootcss.com/docsify/4.5.9/plugins/search.min.js"></script>
  
  <script src="//unpkg.com/docsify-copy-code"></script>
  
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
  
  <script src="//unpkg.com/docsify/lib/plugins/emoji.js"></script>
  
  <script src="//unpkg.com/docsify-count/dist/countable.js"></script>


I think unpkg.com is blocked in my area
![image](https://user-images.githubusercontent.com/49017153/144735916-64c4a829-4cae-4229-a077-e8436d6916c9.png)

**Comment by youthlql** [comment]
```
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/prism.css">
  <!--主题-->
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
  <!--Java代码高亮-->
  <script src="//unpkg.com/prismjs/components/prism-java.js"></script>
  <!--全文搜索,直接用官方提供的无法生效-->
  <script src="https://cdn.bootcss.com/docsify/4.5.9/plugins/search.min.js"></script>
  <!-- 复制到剪贴板 -->
  <script src="//unpkg.com/docsify-copy-code"></script>
  <!-- 图片缩放 -->
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
  <!-- 表情 -->
  <script src="//unpkg.com/docsify/lib/plugins/emoji.js"></script>
  <!-- 字数统计 -->
  <script src="//unpkg.com/docsify-count/dist/countable.js"></script>

**Comment by sy-records** [comment]
This is a problem with your local network. You can use https://cdn.jsdelivr.net/npm/docsify@4/

**Comment by trusktr** [comment]
Yeah, working for me. It is blocked in your area for some reason. Here's the alternative CSS URL for example: https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css

Does that work for you?

**Comment by youthlql** [comment]
It is ok now
