### ISSUE TITLE
relative paths of links in sidebar should be relative to the sidebar file

### ISSUE THREAD

**Issue by ruanqizhen** [docsifyjs/docsify#1684]
## Bug Report

The relative path should always based on the file that quote it. 

For example, the path (foo) in file bar.md should always point to the foo.md file that in the same folder of bar.md.  
But the current mechanism of relative path is based on the current url.  That means if the current url is in folder xxxx, the  (foo) in file bar.md file will point to the foo.md in folder xxxx.  
That means the relative will never work if you have a sidebar with multiple layer of documents.

I hope this could be fixed in the next docsify version.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
Hello @ruanqizhen What you described seems to be what the doc says:

https://docsify.js.org/#/configuration?id=relativepath

Can you make a reproduction?

**Comment by ruanqizhen** [comment]
> Hello @ruanqizhen What you described seems to be what the doc says:
> 
> https://docsify.js.org/#/configuration?id=relativepath
> 
> Can you make a reproduction?

The current implementation only consider a single base path for relative paths.    
My point is that when there are 2 md files loaded, one sidebar, and one content md, the relative paths in the sidebar md and the content may need different base path, one should based on the sidebar md, the other should based on the content md file.

**Comment by ruanqizhen** [comment]
Just use the case in the document:
.
└── docs
    ├── README.md
    ├── guide.md
    └── zh-cn
        ├── README.md
        ├── guide.md
        └── config
            └── example.md

Suppose there is a single sidebar file for all the md files listed here, with the current relative path mechanism, there is not way to make the links in sidebar point to the right files.

**Comment by ruanqizhen** [comment]
Found a workaround:  I'm using absolute path in sidebar file, and using relative path in other files now.

**Comment by trusktr** [comment]
I see what you're saying: yeah, links in sidebar should be relative to the sidebar file. That would be most intuitive.

**Comment by mike-potter** [comment]
I am also very interested in this functionality.  In my use case I have a top-level "portal" docsify site that brings in several other project docsify sites as subfolders.  Each of the projects has their own _sidebar.  But when used in the portal, the links in the project sidebars no longer work because it's using the main top-level folder instead of looking relative to the folder containing the sidebar.

**Comment by mike-potter** [comment]
It's possible that using `relativePath: true` helps with this, if all of the sub-projects are also configured for this.

**Comment by mike-potter** [comment]
Nope, that doesn't work either.  If the projects have subfolders, then once a page in the subfolder is loaded, the other pages in the sidebar no longer work as they use the new subfolder as the relative path.  So still can't find a way to basically embed one docsify site within another.

I agree with the OP that the links in the sidebar should be relative to the location of the _sidebar file.  Using `relativePath` just makes them relative to the current path, which changes once you are in a subfolder.

**Comment by trusktr** [comment]
Yeah, it's a bit counterintuitive right now.

For backwards compat, I believe we need a new option for this (`false` by default). It will override `relativePath` for the sidebar.

Perhaps named like `sidebarLinksRelativeToSidebarFile`? Any other naming ideas?

The docs need more clarity here too.

**Comment by trusktr** [comment]
Closed https://github.com/docsifyjs/docsify/issues/1139 in favor of this one.

cc @CxRes (since you were interested in trying to solve it with that code mod you made in the other issue, open to a PR)

**Comment by hexus** [comment]
How about `relativeSidebarPaths`?

**Comment by hamishwillee** [comment]
Is there any approximate ETA on this or plugin that could be tried to get the functionality in the meantime? 

This will make multi-lingual and multi version libraries very much easier to create, and remove the limitations where you're forced to have your content for translations in different repositories.

**Comment by hamishwillee** [comment]
@chenGit1763113879QQ Not as far as I know. The workaround I use (not in production) is described here: https://evilmartians.com/chronicles/easy-multi-language-multi-version-documentation-with-docsify-git-and-github-actions

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
