### ISSUE TITLE
rename "master" branch to "main"

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#1690]
Ever since the 2020 protests in U.S. regarding racial issues, there has been a push in the tech world to eliminate any and all discriminatory wording. For example "master"/"slave" terminology. To avoid having master/slave terminology, many projects have renamed "master" to "main". Other things to look out for, for example, include re-naming "whitelist"/"blacklist" to allow/deny, etc.

**Comment by Koooooo-7** [comment]
No offense, IMO the branch name is just a branch name, conventional rules.
Lots of projects keep the master, such as `linux`.
We need not to do extra effort on it.

**Comment by trusktr** [comment]
It's fine, but in the U.S.A. there are many new opinions around this. Even when you make a new repo in GitHub with default content (f.e. README) it defaults to `main` now.

I'm in favor of avoiding conflict (no matter how small) by moving to words that have less possible negative association.

**Comment by trusktr** [comment]
@Koooooo-7 No offense taken. Don't worry, I am open to opinions.

> just a branch name, conventional rules.

Thoughtful/social libs are updating their conventions. For example, these ones are on `main` already:

- https://github.com/facebook/react
- https://github.com/babel/babel
- https://github.com/webpack/webpack
- https://github.com/solidjs/solid

**Comment by trusktr** [comment]
I pushed a new `main` branch. It is not set to default yet. This isn't something we can make a pull request for, so if two other maintainers upvote (please do, support social goodness) then let's toggle the setting.

If a name is just a name and you really don't care about it, then no harm upvoting.

**Comment by trusktr** [comment]
Oh, I forgot, `develop` is the "default" branch already, which is good. The proposal is to merge releases to `main`.

**Comment by Koooooo-7** [comment]
Definitely, we can find lots of projects change them to `main`, and we can find lots of projects keep the `master` too. 
It depends on their members' decisions as well.
THB, it doesn't matter whether the name is `master` or `main`, but I think this is an unnecessary change.(I m a lazy guy, Lol.)


> I'm in favor of avoiding conflict (no matter how small) by moving to words that have less possible negative association.

About the `Conflict`, I fully understand what you afraid about :P ,hmmmmmmm,If the conflict were possible, we could make this change......

Yea, we should always be nice.

**Comment by trusktr** [comment]
https://github.com/docsifyjs/docsify/wiki/Release/_compare/5540c31777c5831262e1833b4e86e437787ec03b...915c2fa4b15dddd4ecf52f9581e64d54f4a02013
