### ISSUE TITLE
The menu positional fault

### ISSUE THREAD

**Issue by lxhyl** [docsifyjs/docsify#1691]
#### Steps to reproduce
 When i use this css. In mobile. The menu positional fault. It should  fixed in page.but now you must scroll to bottom to find meun
```
  <style>
    * {
      filter: grayscale(100%);
      -webkit-filter: grayscale(100%);
      -moz-filter: grayscale(100%);
      -ms-filter: grayscale(100%);
      -o-filter: grayscale(100%);
    }
  </style>
```

#### What is current behaviour

meun position fault

#### What is the expected behaviour

meun fixed in page

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version:  Newest
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
That only changes the color, so I don't see how that would be possible.

Please make a reproduction to help us help you.

**Comment by trusktr** [comment]
The issue template gives you a codesandbox where you can paste your code, or you can poste a link to a GitHub repo with steps to run it.
