### ISSUE TITLE
Missing navbar with only coverpage

### ISSUE THREAD

**Issue by CxRes** [docsifyjs/docsify#1696]
#### Steps to reproduce

1. Set a navbar `loadnavbar: "_nav.md"`.
2. Set `onlyCover: true`

#### What is current behaviour

The navbar is missing on first navigation to the page.

#### What is the expected behaviour

The navbar should exist unless set to false.

#### Other relevant information

If you go to an internal page and and 

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 x64
- Node.js version: 14.17.5
- npm/yarn version: 6.14.14
- Browser version: Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
- Docsify version: 4.12.1
- Docsify plugins: NA

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

Sandbox link: https://codesandbox.io/s/elated-sound-6s1rq

**Comment by trusktr** [comment]
@CxRes can you please provide a working reproduction? See the codesandbox link above.

**Comment by trusktr** [comment]
Wait, nvm, i see the second link. The first one pointed to the default sandbox.

**Comment by trusktr** [comment]
In your reproduction, there is no buttons on the cover page to go to any other page. I believe the expectation is that you will link to a page, then you will see a navbar on that page. Or no?

Does this work on any other sites?

If not, this may be a feature request. We could add an option to show navbar on cover-only pages (defaulting to false to be backward compatible).

PRs welcome!

**Comment by CxRes** [comment]
@trusktr I added a button in the reproduction. There is no effect.

This is not a feature request! It is a BUG!!!

**Comment by trusktr** [comment]
I'm not sure if this ever worked. I tried [searching github for "onlyCover true"] and you can see there are only 5 results and they have a typo (`onlycover` instead of `onlyCover`).

We should have this ability regardless if its a bug or not. Interested to make a PR?

**Comment by trusktr** [comment]
pull request: https://github.com/docsifyjs/docsify/pull/1706

**Comment by jhildenbiddle** [comment]
Confirmed working as expected on `develop`.
