### ISSUE TITLE
Jumping to a specific place of a different page doesn't work

### ISSUE THREAD

**Issue by rahjuu** [docsifyjs/docsify#1698]
#### Steps to reproduce
1. Add an anchor (id="test") in page A.
2. Create a link in page B: [Here is the Link](path of page A#test)
3. Click the link in page B

#### What is current behaviour
Jump to the top of page A

#### What is the expected behaviour
Should jump to the place where the anchor was added

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Win 11
- Node.js version: 14.16.0
- npm/yarn version: npm: 6.14.11
- Browser version: Chrome 96.0.4664.110 (Official Build) (64-bit)
- Docsify version: 4.4.3
- Docsify plugins: <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/sidebar.min.css" />
  <script src="//cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by paulhibbitts** [comment]
Tested with the following with Docsify release v4.13.1 (see below) and now works as expected so closing issue.

Page A. [Here is the Link](page-b#test)
Page B. .... <p id="test">This is the paragraph I want to link to.</p> ...
