### ISSUE TITLE
[markdown] An exception occurred while parsing ```javascript``` 

### ISSUE THREAD

**Issue by wgplt** [docsifyjs/docsify#1705]
#### Steps to reproduce

Codes like this:

![image](https://user-images.githubusercontent.com/54103241/147737001-199342fa-9238-4665-8069-5c07aa7f4300.png)

#### What is current behaviour

![image](https://user-images.githubusercontent.com/54103241/147737015-1954af69-8acb-4d90-ae94-e304a4ab3ef2.png)

#### What is the expected behaviour

![image](https://user-images.githubusercontent.com/54103241/147737201-3e071762-d95d-4440-8134-922a55c98d6b.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS:  centos 3.10.0-957.27.2.el7.x86_64
- Node.js version: node-v15.5.0-linux-x64
- npm/yarn version:  npm@8.3.0
- Browser version: 
- Docsify version:  docsify-cli 4.4.3
- Docsify plugins:  Zoom image、ocsify-copy-code

**Comment by trusktr** [comment]
Looks like GitHub does it fine. 

- foo
```js
One two

Three four
```

Maybe a bug in the markdown renderer,

**Comment by paulhibbitts** [comment]
Looks like as of Docsify v4.13.1 this is still an issue, as shown below.

<img width="763" alt="2024-03-16_15-25-54" src="https://github.com/docsifyjs/docsify/assets/1812771/610f1f3c-2b85-4426-8a97-5f2ed98a2975">

**Comment by sy-records** [comment]
You can modify the usage:

````markdown
- text

```javascript
console.log('hello world')

console.log('hello world')
```
````

<img width="336" alt="image" src="https://github.com/docsifyjs/docsify/assets/33931153/8d6a2438-5c12-494d-99ea-f2f3c07291ed">
