### ISSUE TITLE
C++ Hightlight With Prism

### ISSUE THREAD

**Issue by sivanWu0222** [docsifyjs/docsify#1708]
#### Steps to reproduce
1. create a markdown file and write the content according to image ![dOQIg7](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/dOQIg7.png)
2. write the content to index.html according to image: ![Kpbjkb](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/Kpbjkb.png)

**c and go hightlight plugin could work correcly, but c++ doesn't**

#### What is current behaviour

![AOcenk](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/AOcenk.png)
#### What is the expected behaviour
expect to highlight my cpp code correctly!

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: mac os 10.15.7
- Node.js version: 14.15.1
- npm/yarn version: 6.14.13
- Browser version: chrome 96.0.4664.110 (x86_64)
- Docsify version: 4.4.2
- Docsify plugins: prism

#### Please create a reproducible sandbox 
[my sandbox](https://codesandbox.io/s/exciting-bartik-jezv1?file=/code.md)
[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
Hello! For help, please use [Discussions](https://github.com/docsifyjs/docsify/discussions). Better to keep issues for known bugs or feature requests (discussion is better if you're not sure of a bug of if a feature exists).

Make sure you load `prism-cpp.min.js` into your page, then use ```` ```cpp ````.

- https://docsify.js.org/#/ssr?id=custom-template
- https://prismjs.com/#supported-languages
