### ISSUE TITLE
Is there a way or plugin for embed an office file in the page

### ISSUE THREAD

**Issue by chinajuanbob** [docsifyjs/docsify#1717]
#### What problem does this feature solve?
Want to embed an office file in the page, e.g. word, pptx, ...

#### What does the proposed API look like?
There is a PDF plugin that is very useful

#### How should this be implemented in your opinion?
Maybe a js script w/ demo

#### Are you willing to work on this yourself?
Not sure.

**Comment by trusktr** [comment]
It is possible to embed Google Docs. See "embed" here:

https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform%3DDesktop

As for converting to Docsify format, we would need to find a doc to markdown converter

**Comment by trusktr** [comment]
If you paste the embed code for a google doc (link in previous comment), you should get a similar result, as a workaround. You just have to upload docs to Google Docs first.

**Comment by trusktr** [comment]
I think the workarounds are good enough, especially saving/printing to PDF. Just use that method.
