### ISSUE TITLE
default behavoir should not be to emojify all, including non-emojis

### ISSUE THREAD

**Issue by ChoKaPeek** [docsifyjs/docsify#1721]
## Bug Report

Any couple of colons gets emojified.

#### Steps to reproduce

- have a md containing the following:

`Namespace::SubNameSpace::Class hh:mm:ss :one::two:`

#### What is current behaviour

It will  create a string like this:

> Namespace:<img class="emoji" src="https://github.githubassets.com/images/icons/emoji/SubNameSpace.png alt="SubNameSpace" />:Class hh<img class="emoji" src="https://github.githubassets.com/images/icons/emoji/mm.png alt="mm" />ss <img class="emoji" src="https://github.githubassets.com/images/icons/emoji/unicode/0031-20e3.png?v8" alt="one" /><img class="emoji" src="https://github.githubassets.com/images/icons/emoji/unicode/0032-20e3.png?v8" alt="two" />

#### What is the expected behaviour

This:

> Namespace::SubNameSpace::Class hh:mm:ss <img class="emoji" src="https://github.githubassets.com/images/icons/emoji/unicode/0031-20e3.png?v8" alt="one" /><img class="emoji" src="https://github.githubassets.com/images/icons/emoji/unicode/0032-20e3.png?v8" alt="two" />

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.12.2
- Docsify plugins: emoji.js

**Comment by sy-records** [comment]
see https://docsify.js.org/#/configuration?id=noemoji
