### ISSUE TITLE
Automatic generation of page index in Sidebar at runtime

### ISSUE THREAD

**Issue by paulhibbitts** [docsifyjs/docsify#1735]
#### What problem does this feature solve?
When using Docsify to quickly put together a smaller collection of MD pages the creation, and then updating, of the Sidebar can be additional effort with little benefit

#### How should this be implemented in your opinion?
This issue has been discussed before (i.e. https://github.com/docsifyjs/docsify/issues/1290), and the ordering of pages often comes up. As described in issue #1290 a default sort on MD file name looks promising. This would give user control of the sort order, and likely support using numerical prefixes to help auto-sort pages. For example, 01-Chapter 1, 02-Chapter 2, etc.

Might this be able to be created as a Plugin?

#### Are you willing to work on this yourself?
Unfortunately I do not have the needed developer skills but I'd be more than happy to help test, share ideas, etc.

**Comment by trusktr** [comment]
Hey @paulhibbitts, thanks for the idea, although static websites can't inspect files from a server, so this is not possible as a runtime thing for static web sites without support from a server that exposes an API endpoint for the client to receive specific information.

In #1290 I linked to the CLI feature @sy-records added recently for generating a sidebar. To automate this, someone can run it manually, or they can run it in a GitHub action, etc.
