### ISSUE TITLE
Support relativePath link set linkTarget

### ISSUE THREAD

**Issue by bilibiliou** [docsifyjs/docsify#1750]
Hi
When I read the  docs of "Set target attribute for link" https://docsify.js.org/#/helpers?id=set-target-attribute-for-link 
I try a relative path to jump

```
[demo](/docs/front_end/summery_of_experience/data_use/assets/demo/index.html ':target=_blank')
```

but It be compiled as
```
<a href="/docs/front_end/summery_of_experience/data_use/assets/demo/index.html">demo</a>
```
It is not my expectation.

After then, I read the source code: "src\core\render\compiler\link.js" line 22
I discover that `docsifyjs` didnt support relative path linkTarget custom

so I make the issue in order to discuss the problem

thx

**Comment by Koooooo-7** [comment]
Thx for ur report. 
Unfortunately, docsify doesn't support the relative target config for now. 
I think we may have an update on it asap. :)

**Comment by bilibiliou** [comment]
Okay, thx ur reply and support
I can use the absolute link instead now. 
hope you have a nice day :)
