### ISSUE TITLE
A Visual Studio Code Dark Theme

### ISSUE THREAD

**Issue by BoomProj** [docsifyjs/docsify#1755]
#### What problem does this feature solve?
I have made a Visual Studio Code Dark Style Theme, is there someone need ?

#### Are you willing to work on this yourself?

![vuiot-dark](https://github.com/BoomProj/docsify/blob/develop/docs/_images/vuiot-dark.png)

**Comment by sy-records** [comment]
You can submit to awesome-docsify.

see https://github.com/docsifyjs/awesome-docsify#themes
