### ISSUE TITLE
mustache does not work in navbar

### ISSUE THREAD

**Issue by DanielYWoo** [docsifyjs/docsify#1759]
#### Steps to reproduce
- create a nav bar with variables
- check the nav bar

#### What is current behaviour
- variables is not replaced by mustache

#### What is the expected behaviour
- variables should be replaced by mustache

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OSX
- Node.js version: N/A
- npm/yarn version: N/A
- Browser version: Chrome 97.0.4692.99 (Official Build) (x86_64)
- Docsify version: CDN latest
- Docsify plugins: mustache

#### Please create a reproducible sandbox 

[code sandbox demo](https://codesandbox.io/embed/sparkling-voice-kmibcc?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Koooooo-7** [comment]
Hi. By default, there is no support for `mustache`. As per the `docsify-mustache` plugin you mentioned in sandbox, I think u need make an issue there instead.

**Comment by DanielYWoo** [comment]
thanks. Will do.
