### ISSUE TITLE
No homepage loaded for the others lang with path `/lang`

### ISSUE THREAD

**Issue by initdc** [docsifyjs/docsify#1762]
## Bug Report

1. No homepage loaded for the others lang with path `/lang`
2. img in `.md` ,same format but one of them not working
3. When click lang switcher, it alway goto homepage, not the related doc with other lang

#### Steps to reproduce

https://docsify.js.org/#/zh-cn

https://mirr.one/#/zh-cn
> scroll down

#### What is current behaviour

404

#### What is the expected behaviour

show the README.md as index

https://docsify.js.org/#/zh-cn/
https://mirr.one/#/zh-cn/

#### Other relevant information

1. src: https://github.com/initdc/mirr-docsify

2. with another problem of markdown img path
website host on @netlify

check at here: 
- [path for en](https://github.com/initdc/mirr-docsify/commit/aa8b322e28f6415a0c355897a4942f8c93b34285#diff-5c5673893e9673f3386e027650f7f42053b73393c5441b23d7ce45e7d1962595L51)
- [path for zh-CN](https://github.com/initdc/mirr-docsify/blob/master/lang_i18n/zh-CN/media/backblaze-b2.md?plain=1#L51)

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS:  macOS 10.13.6
- Node.js version: 16.14.0
- npm/yarn version: 12
- Browser version: Chrome
- Docsify version: @4
- Docsify plugins: search

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi, I'm wondering you already know the `/zh-cn` and the `/zh-cn/` issue to land the index page. 👍
