### ISSUE TITLE
Did not load homepage in router mode history and subdirectory

### ISSUE THREAD

**Issue by rottmann** [docsifyjs/docsify#1763]
#### Steps to reproduce

Settings
```
homepage: "index.md"
relativePath: false
routerMode: history
basePath: /test/
```
Open the doc `http://localhost:9000/test/`

#### What is current behaviour

It did not load `/test/index.md` it try to load `/test/test/README.md`

Aliases not work with homepage file too.

#### What is the expected behaviour

Load index.md

#### Other relevant information

- Docsify version: https://cdn.jsdelivr.net/npm/docsify@4

**Comment by Koooooo-7** [comment]
Currently, the whole site is only one `homepage`, which means there is no other homepage in `subdirectory`.
If you wanna have a default index page in `subdirectory`, it is `README.md` in the `subdirectory` by default.

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
