### ISSUE TITLE
search搜索中文显示的title未解码

### ISSUE THREAD

**Issue by shenxiang216** [docsifyjs/docsify#1769]
# 我已经定位到了bug所在位置
* src/plugins/component.js    -> 159行
* 推荐改为<h2>${decodeURI(post.title)}</h2>

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Please follow the template for questions.

Please create a reproducible sandbox.

**Comment by Tajang-ctf** [comment]
可我是windows本地引用的搜索插件，也出现了这个问题该怎么解决？
