### ISSUE TITLE
can't completely display the content

### ISSUE THREAD

**Issue by WittonBell** [docsifyjs/docsify#1777]
## Bug Report

Docsify sometimes can't completely display the content on the left side of the page.

![image](https://user-images.githubusercontent.com/8215947/159417797-1aa9a35f-8f9f-4e4e-80b2-83b8cb544c91.png)

visit https://wittonbell.github.io/ to see.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version:  chrome latest
- Docsify version: latest
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
You use a lot of plugins, which can lead to style overrides.

You need to change it to 80% by css

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/33931153/159427627-febf9c82-2760-458c-a79c-9c60136320b9.png">

**Comment by WittonBell** [comment]
ok, thanks.
