### ISSUE TITLE
Why can't I add a footnote?

### ISSUE THREAD

**Issue by ersrohu** [docsifyjs/docsify#1779]
## Bug Report

I can't add the footnotes, like this[^1].

[^1]: Test of a footnote.

- My OS: Windows
- Node.js version: ?
- npm/yarn version: ?
- Browser version: MS Edge Current
- Docsify version: Current
- Docsify plugins: None

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Thanks for your feedback, please see #1628
