### ISSUE TITLE
Head Style Tag didn't load

### ISSUE THREAD

**Issue by ersrohu** [docsifyjs/docsify#1783]
## Bug Report

I wanted to add some style to my document, then I input this to the `index.html`.
```html
<head>
  <!--The above is omitted-->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
  <style type="text/css">
    p {
      text-indent: 2em;
    }
  </style>
```
But it didn't make text indent.

What's the matter? Why?

I can't understand.

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 11
- Node.js version: ?
- npm/yarn version: ?
- Browser version: MS Edge Current
- Docsify version: Current
- Docsify plugins: None

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
I can't reproduce the problem you mentioned.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/33931153/161051596-ce3c19f2-c180-494f-8cd1-3a7c78bbd814.png">

**Comment by ersrohu** [comment]
Oh... But here...

![image](https://user-images.githubusercontent.com/102342661/161060074-b5e31e2c-1de3-4ee6-b805-e022b7de86dd.png)

![image](https://user-images.githubusercontent.com/102342661/161060332-fc8e58a4-1f64-4445-b49b-69cc47b93fd9.png)

So I have to use the 2 full-width spaces (&#x3000;, &amp;#x3000) to make indent.

I think that it has produced by GitHub Pages, or because I'm in Chinese Mainland, then...

Wait, I've put the `index.html` in the `zh-cn` folder, has it caused by this?

You can look at these file and check the problems below: 

* [The Problem file `index.html`](https://github.com/ersrohu/mingyues-daily-life/blob/main/zh-cn/index.html)
* [Markdown files example](https://github.com/ersrohu/mingyues-daily-life/blob/main/zh-cn/part1/chapter1.md)

**Comment by sy-records** [comment]
You only added it in zh-cn/index.html, which is normal when using zh-cn as an entry.

```
cd zh-cn/
docsify serve .
```

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/33931153/161062506-f81d7197-5a99-4f15-9755-cf92f10fc9fa.png">

**Comment by ersrohu** [comment]
But I want to let the /zh-cn/ become a **child folder**, not main folder, the main folder is en-us. Hmm, has this caused by "fallbackLanguages", its value is: `["en","zh-cn"]` .

**Comment by sy-records** [comment]
you should add it to /index.html and handle the style according to the language.

**Comment by ersrohu** [comment]
> you should add it to /index.html and handle the style according to the language.

It doesn't give attention to the `/zh-cn/index.html`, sure?

How to do this? Add the `"fallbackLanguages": ["en","zh-cn"]`? Or, what code should I add?

Or use below?

```html
<style type="text/css>
/* I don't want the English text indents, I **only** want the Chinese text indents.*/
/* But this is not very good, because when I use below: */
/*
<p class="zh-cn">**内容**</p>
*/
/* It won't render the markdown text. */
    p .zh-cn{
    text-indent: 2em; 
}
</style>
```

So, what can I do?
