### ISSUE TITLE
how do we fix nav bar at the top to remain fixed?

### ISSUE THREAD

**Issue by Srikanthholo** [docsifyjs/docsify#1785]
I was trying to fix the navbar on the top, please let me know how to fix it?

**Comment by sy-records** [comment]
Hi, there. i'm not sure what question you are talking about? Can you explain it in full?

**Comment by Srikanthholo** [comment]
![image](https://user-images.githubusercontent.com/101865042/161724369-4f10479e-6515-4da7-a194-ec9ba776e68f.png)

This picture will explain, i want a nav bar on top always.

**Comment by sy-records** [comment]
You can use css to control this.
```css
.app-nav {
    position: fixed;
}
```
