### ISSUE TITLE
我每点一个目录页，都会报404

### ISSUE THREAD

**Issue by shenxiang216** [docsifyjs/docsify#1786]
## Bug Report
每次点击一个sidebar目录，都会抛出404错误

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Please follow the template for questions.
