### ISSUE TITLE
Strange bug on nested side bar host on cloudflare pages

### ISSUE THREAD

**Issue by help-14** [docsifyjs/docsify#1793]
#### Steps to reproduce

Host a simple page with nested side bar. Click on nested link.

<img width="379" alt="Screen Shot 2022-04-25 at 11 10 19 AM" src="https://user-images.githubusercontent.com/574357/165019477-f2dab4b0-5d2a-4a07-9b75-0e1f690de0f5.png">
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/574357/165019496-eb54ba50-1466-4ec6-aa1d-367c7f5b5522.png">

#### What is current behaviour

Side bar disappeared and show loading.

#### What is the expected behaviour

It working fine when using Github page, but something happend and my github action isn't running anymore so I moved to cloudflare pages.

#### Other relevant information

Check it here: https://magma.help14.com/#/getting-started

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version:  16
- npm/yarn version: 
- Browser version: chrome 100
- Docsify version: v4
- Docsify plugins: none

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
cloudflare pages will not respond to 404, you can add an alias to solve this problem

```markup
      alias: {
        '/.*/_sidebar.md': '/_sidebar.md'
      },
```
