### ISSUE TITLE
vue docs click  BUTTON cant alert 'message'

### ISSUE THREAD

**Issue by ecitlm** [docsifyjs/docsify#1794]
## Bug Report
website https://docsify.js.org/#/zh-cn/vue  ，vue demo cant run，click  BUTTON cant alert 'massage'
```
{
  data() {
    return {
      message: 'Hello, World!'
    };
  },
  methods: {
    hello() {
      alert(this.message);
    }
  },
}
```
```
<button @click="hello">Say Hello</button>
```
![image](https://user-images.githubusercontent.com/15050326/165772398-c4330aca-cb2c-4d38-bae5-4bd457a081fd.png)

**Comment by sy-records** [comment]
Hi, @jhildenbiddle 
Is this a problem caused by loading Markdown files via remote?

**Comment by jhildenbiddle** [comment]
@sy-records --

I don't believe so. If you look at the Chinese translation vs the English version of the [Vue Compatibility](https://docsify.js.org/#/vue) page you'll notice that almost none of the `<output>` blocks render as expected except for this one:

<img width="660" alt="CleanShot 2022-05-01 at 17 21 29@2x" src="https://user-images.githubusercontent.com/442527/166166876-73698497-2408-407d-bb43-c687aef92abf.png">

The fact that this one block renders properly means that Vue is working, but the console indicates that it's throwing errors:

<img width="574" alt="CleanShot 2022-05-01 at 17 27 28@2x" src="https://user-images.githubusercontent.com/442527/166167035-d56b4fd0-5cbb-4d2a-ae8b-bb2763bec7b7.png">

An easy way to troubleshoot would be to checkout the [docs-zh](https://github.com/docsifyjs/docs-zh) repo, serve is locally on a different port (which is the same as serving it from a different domain), change the alias your local docisfy `index.html` to point to the local docs-zh repo, and try to find the issue.

**Comment by sy-records** [comment]
Thank you for your reply. I'll try to find the problem later.

**Comment by sy-records** [comment]
Hi @ecitlm 
I think this should be a fixed problem, wait for the next version release and then it will be normal.
I use [docsify-nightly](https://github.com/sy-records/docsify-nightly) test is normal.

```diff
+   <script src="//cdn.jsdelivr.net/gh/sy-records/docsify-nightly/lib/docsify.min.js"></script>
-   <script src="//cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
```

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/33931153/166171126-400dcab9-919e-4d63-a86b-ebd4cb6cb68c.png">
