### ISSUE TITLE
Search plugin did not load when setting onlyCover to true

### ISSUE THREAD

**Issue by yequanrui** [docsifyjs/docsify#1797]
#### Steps to reproduce

1. set onlyCover to true
2. enter from the cover to the home page
3. search plugin did not load
![image](https://user-images.githubusercontent.com/26866409/167669851-5c2fbc9a-bde1-4385-b35d-57ae78f76701.png)
4. but search plugin will load when i reload the home page
![image](https://user-images.githubusercontent.com/26866409/167669511-10b1c72d-81f1-4d7e-a760-fdb2c81fe6bd.png)

#### What is current behaviour

The search plugin did not load

#### What is the expected behaviour

The search plugin should be loaded

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows11
- Node.js version: 16.14.0
- npm/yarn version: 6.14.16
- Browser version: Edge 101.0.1210.39
- Docsify version: 4.12.2
- Docsify plugins: search

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
No reproduction of the issue.
