### ISSUE TITLE
external links don't work in history router mode

### ISSUE THREAD

**Issue by 6ecuw** [docsifyjs/docsify#1803]
#### Steps to reproduce

1. Set `routerMode` to `history`.
2. Create mailto link with `<my@mail.com>`, or any external link.
3. Click on rendered link.

#### What is current behaviour

Crashes with error:

```
SecurityError
Failed to execute 'replaceState' on 'History': A history state object with URL 'mailto:my@email.com' cannot be created in a document with origin 'https://kc32ry.csb.app' and URL 'https://kc32ry.csb.app/'.
```

#### What is the expected behaviour

Native behaviour

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS Catalina, version 10.15.7
- Node.js version: 16.13.2
- npm/yarn version: npm v8.1.2
- Browser version: Google Chrome 100.0.4896.127
- Docsify version: 4.12.2
- Docsify plugins: -

#### Please create a reproducible sandbox 

[![Edit immutable-sunset-kc32ry](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-sunset-kc32ry)

Live example: https://docs.lume.io/

**Comment by trusktr** [comment]
Indeed, non-docsify links (external links) are currently not working in history router mode. We need to fix this and add tests.

**Comment by trusktr** [comment]
I found the issue. It happens when `externalLinkTarget: '_self'` is specified. Fix WIP
