### ISSUE TITLE
‘formatUpdated’ didn't work when deployed

### ISSUE THREAD

**Issue by pfeak** [docsifyjs/docsify#1813]
## Bug Report

When deploying docs via `netlify`, it is found that when using `formatUpdated`, `{docsify-updated}` is not rendered as expected.
Local testing does not have this problem.

#### Steps to reproduce

add `formatUpdated` to the `windows.$docsify`

```
window.$docsify = {
  coverpage: false,
  loadSidebar: false,
  loadNavbar: false,
  formatUpdated: "{MM}/{DD} {HH}:{mm}"
};
```

add  `{docsify-updated}`  to `README.md` file

```
# Home

This is Home Page.

> Last Modified {docsify-updated}
```

#### What is current behaviour

`{docsify-updated}` is rendered as expected

#### What is the expected behaviour

`{docsify-updated}` is not rendered as expected

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows10
- Node.js version: v12.16.1
- npm/yarn version: 6.13.4
- Browser version: Chrome(102.0.5005.63)
- Docsify version: 4.4.4
- Docsify plugins: None

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-frost-syhtpv)

#### Mention the docsify version in which this bug was not present (if any)

Local test or manual deployment on vps.

**Comment by sy-records** [comment]
Check for the presence of last-modified in the response header
<img width="658" alt="image" src="https://user-images.githubusercontent.com/33931153/171791944-250f8912-b7a4-4a72-9f09-0f609d3c5356.png">

**Comment by pfeak** [comment]
screenshot taken from here https://codesandbox.io/s/romantic-frost-syhtpv

![ERV`G3GSDSOTJ S)C3~761B](https://user-images.githubusercontent.com/30229826/171793100-9060521b-bc29-45c6-8516-fa078f509fab.png)

![SW_NU$ YU%G`R7AVRG`S`07](https://user-images.githubusercontent.com/30229826/171793111-81852eb5-a05b-4bf7-8009-f43f3e10b38c.png)

**Comment by pfeak** [comment]
the same as `netlify`.

**Comment by sy-records** [comment]
Your md file does not have a `last-modified` header

**Comment by pfeak** [comment]
Thanks a lot for your answer.
So how can I solve this problem through the settings when deploying `docsfiy` to `netlify` or `CodeSandbox`?

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-frost-syhtpv)

**Comment by sy-records** [comment]
I'm not sure about netlify and CodeSandbox, but if you're using GItHub Pages, take a look at https://github.com/docsifyjs/docsify/issues/1157#issuecomment-890467244
