### ISSUE TITLE
Failed to load remaining requests correctly when trying to load more than 255 documents

### ISSUE THREAD

**Issue by LiarOnce** [docsifyjs/docsify#1818]
#### Steps to reproduce

Create and load documents over 2000.

#### What is current behaviour

When I try to load more than 255 documents, the remaining documents, including pictures, cannot be loaded, and the error `net::ERR_INSUFFICIENT_RESOURCES` is returned. 

However, after manually refreshing the page, the page is normal, but the same error is returned on all other pages.
![image](https://user-images.githubusercontent.com/11171892/173360918-98dd345b-b51f-4e9a-9c94-f43ef3993529.png)

#### What is the expected behaviour

Render OK

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 11 22000.675
- Node.js version: 16.15.1
- npm/yarn version: 8.11.0 (npm)
- Browser version: Microsoft Edge 102.0.1245.39
- Docsify version: 4.12.2
- Docsify plugins: 
  - search
  - docsify-sidebar-collapse
  - docsify-footer
  - docsify-copy-code

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Can you provide a reproducible repo?

**Comment by LiarOnce** [comment]
Repo: https://github.com/GamemakerChina/GMS2_Manual_RoboHelp/tree/markdown

**Comment by LiarOnce** [comment]
@Koooooo-7 
I have removed it but the problem still persists.
The current temporary solution is to configure `_sidebar.md` separately for the part with the most content

**Comment by sy-records** [comment]
Try to use Nginx, docsify-cli may not load so many files.
