### ISSUE TITLE
I set hideSidebar: true，but it do not work. Sidebar can not hide.

### ISSUE THREAD

**Issue by wardseptember** [docsifyjs/docsify#1819]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Plz fill the tpl and  create a reproduce case in Sandbox better.
