### ISSUE TITLE
Emoji parsing should exclude URLs

### ISSUE THREAD

**Issue by socsieng** [docsifyjs/docsify#1823]
## Bug Report

Parsing of `:emojis:` should exclude URLs as this causes URLs in the following format render invalid HTML:

```
[link](https://link.com/:smile:/index)
```

Note that in my use case, I am also using other `:emojis:` so I can't set `noEmoji: true` in config.

Happy to contribute a fix if this bug is accepted.

#### Steps to reproduce

Example: https://codesandbox.io/s/brave-margulis-tw5t2b?file=/index.html

#### What is current behaviour

Invalid HTML is rendered:

```
<a alt="smile" src="https://github.githubassets.com/images/icons/emoji/smile.png" href="https://link.com/&lt;img class=">/index" target="_blank"  rel="noopener"&gt;link</a>
```

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2647062/174975972-36e2ca3e-1fc8-4fb7-a100-a9180cd3b377.png">

#### What is the expected behaviour

Rendered HTML should produce something like:

```
<a href="https://link.com/:smile:/index" target="_blank"  rel="noopener">link</a>
```

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS
- Node.js version:
- npm/yarn version: 
- Browser version: Safari 15.5
- Docsify version: 4
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-margulis-tw5t2b?file=/index.html)

**Comment by sy-records** [comment]
Thank you for your feedback.

Have you tried #1746?

**Comment by socsieng** [comment]
I've tried with `nativeEmoji: true` and it still suffers from the same problem: https://codesandbox.io/s/practical-borg-nb3vdl?file=/index.html

**Comment by jhildenbiddle** [comment]
@socsieng --

Ideally, docsify should handle this for you. If you're up for creating the PR, that would be great as I'm not sure I'll have the bandwidth anytime soon.

If you need a quick fix, you can just manually encode any portion of a URL that requires it (like a string matching the double-colon emoji pattern). You can do this using an online [encode/decode tool](https://www.urlencoder.org) or with the console in your browser's dev tools:

```js
encodeURIComponent(':smile:')
```

```markdown
[link](https://link.com/%3Asmile%3A/index)
```
