### ISSUE TITLE
Scroll only half page

### ISSUE THREAD

**Issue by 1049451037** [docsifyjs/docsify#1826]
## Bug Report

Our page only scroll half after clicking `Get Started`.

https://thudm.github.io/SwissArmyTransformer

#### Steps to reproduce

Open our page. Click Get Started.

#### What is current behaviour

Scroll only half page.

#### What is the expected behaviour

Scroll full page.

#### Other relevant information

- Your OS: Github Pages

**Comment by sy-records** [comment]
You have too little content on your page.
