### ISSUE TITLE
Scroll only half page (Not because of too little content!)

### ISSUE THREAD

**Issue by 1049451037** [docsifyjs/docsify#1827]
## Bug Report

Our page only scroll half after clicking `Get Started`.

https://thudm.github.io/SwissArmyTransformer

#### Steps to reproduce

Open our page. Click Get Started. Here is the source code: https://drive.google.com/file/d/1CGdFa4nPZaj8Hwz4dE9uGdwe27lXaFfW/view?usp=sharing

#### What is current behaviour

Scroll only half page. I have tried to add more content, but still scroll half page!!!!

#### What is the expected behaviour

Scroll full page.

#### Other relevant information

- Your OS: Github Pages

**Comment by sy-records** [comment]
Have you tried expanding your readme content?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/33931153/175897930-adc1f958-c5f5-422d-9fa1-ec38c3ad7aa4.png">

**Comment by 1049451037** [comment]
I have pasted the code link above. https://drive.google.com/file/d/1CGdFa4nPZaj8Hwz4dE9uGdwe27lXaFfW/view?usp=sharing

**Comment by 1049451037** [comment]
It works! Thank you so much!
