### ISSUE TITLE
When is version 5.0 coming?

### ISSUE THREAD

**Issue by sunchaser-lilu** [docsifyjs/docsify#1828]
## Bug Report

When is version 5.0 coming?

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi. Thx for the regard to the V5.
We wanna have the V5 as well.
Unfortunately, as you can see, we still remain lots bugs and issues which we need take and resolve before we release a brand new V5. Instead, we are working on a steady V4x first rn.

We are moving on. 😃
