### ISSUE TITLE
Scala prism bug

### ISSUE THREAD

**Issue by hagay3** [docsifyjs/docsify#1830]
#### Steps to reproduce
Add scala prism to `index.html`
```
<script src="//cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-scala.min.js"></script>
```

Add to readme the following scala code
```scala
import skuber._
import skuber.json.format._
val k8s = k8sInit
val patchStr="""{ "spec": { "replicas" : 1 } }"""
val stsFut = k8s.jsonMergePatch(myStatefulSet, patchStr)
```

#### What is the current behaviour
1. Errors in chrome console
```
docsify@4:1 Uncaught TypeError: Cannot set properties of undefined (setting 'triple-quoted-string')
    at Object.extend (docsify@4:1:69345)
    at prism-scala.min.js:1:39
extend @ docsify@4:1
(anonymous) @ prism-scala.min.js:1
```
2. No syntax highlighting for scala

#### What is the expected behaviour

Syntax highlighting

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac
- Node.js version: v14.17.2
- npm/yarn version: 6.14.13
- Browser version: Chrome, Version 103.0.5060.53 (Official Build) (x86_64)
- Docsify version: 4.4.4
- Docsify plugins: prism scala

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currying-architecture-gr3emx)

It looks like here prism offers how to solve the issue
https://github.com/PrismJS/prism/issues/3458

**In case adding both java & scala prism scripts, it solves the issue.**

**Comment by sy-records** [comment]
usage:

```html
    <script src="//cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-java.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-scala.min.js"></script>
```

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/33931153/176985651-326742c9-1832-4af1-8888-ebb391484689.png">
