### ISSUE TITLE
Loading Mermaid plugin is slow

### ISSUE THREAD

**Issue by zhoufupeng** [docsifyjs/docsify#1832]
Add Mermaid and the plugin:
```
<script src="//unpkg.com/mermaid/dist/mermaid.js"></script>
<script src="//unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js"></script>
<script>mermaid.initialize({ startOnLoad: true });</script>
```

mermaid.js  file is large，3.36MB

Just a few The mermaid is used in the MD file. Please find the optimization method. Thank you

**Comment by sy-records** [comment]
It's not as big as you make it out to be.

You can try other CDN sources, slow loading may be a network problem.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/33931153/177910449-77005624-3a66-4684-a085-387dd71dead7.png">
