### ISSUE TITLE
Select last sidebar sub-item on scroll reach bottom

### ISSUE THREAD

**Issue by GCSBOSS** [docsifyjs/docsify#1837]
#### What problem does this feature solve?
Scrolling a page all the way to the bottom does not activate the last sub-item on sidebar when the section is somewhat short.

![image](https://user-images.githubusercontent.com/11818414/178483773-0759341a-d3b4-4453-b5f9-6dc71b14dadc.png)

#### What does the proposed API look like?
No API needed

#### How should this be implemented in your opinion?
Not sure how the code works, but there might already be a scroll hook to select the current active sub-menu. Just add in there that if it reached bottom, must select the last item.

On `src/core/event/scroll.js` file. `highlight()` function. After this:

```js
  if (!last) {
    return;
  }
```

Around line 63, add:

```js
  const maxTop = doc.scrollHeight - doc.clientHeight;
  if(top >= maxTop)
    last = anchors.pop();
```

Might work.

#### Are you willing to work on this yourself?
Possibly.

**Comment by jhildenbiddle** [comment]
New scroll behaviors integrate on `develop`. Will be released with v5.
