### ISSUE TITLE
Chinese links to official website documents 404

### ISSUE THREAD

**Issue by yangsenlin01** [docsifyjs/docsify#1843]
#### What is current behaviour
![image](https://user-images.githubusercontent.com/47729081/180611599-2ab67a5f-9513-4aec-98c8-ffebef70acf5.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
This should be the problem of your own network, can not get to the markdown content, so it shows 404.
