### ISSUE TITLE
underline and bold

### ISSUE THREAD

**Issue by Erimus-Koo** [docsifyjs/docsify#1846]
#### Steps to reproduce
```
「<u>**中文内容**</u>」
「<u>**中文**内容</u>」
「<u>中**文内**容</u>」
「<u>中文**内容**</u>」
「**<u>中文内容</u>**」
「**<u>中文</u>内容**」
「**中<u>文内</u>容**」
「**中文<u>内容</u>**」
```

#### What is current behaviour
![](https://user-images.githubusercontent.com/17139670/181592328-151e7500-22fa-4163-a2db-8a941a493f52.png)

#### What is the expected behaviour
`「<u>**中文内容**</u>」`
display same style to
`「**<u>中文内容</u>**」`

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: latest (//unpkg.com/docsify/lib/docsify.min.js)
- Docsify plugins: 

#### Please create a reproducible sandbox 

HERE IS A SAMPLE 👇👇👇
[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-shockley-1kq13f)

**Comment by jhildenbiddle** [comment]
Tested and verified expected behavior on `develop` branch. Likely fixed by updating our [marked](https://github.com/markedjs/marked) dependency.

<img src="https://github.com/docsifyjs/docsify/assets/442527/6c513c1f-56cd-4921-9f6d-3fa297cb9d26" height="200">
