### ISSUE TITLE
Embed files with .html makes the page auto scroll to where the embed .html at.

### ISSUE THREAD

**Issue by diazynez** [docsifyjs/docsify#1857]
#### Steps to reproduce

Anyway do it, it will happen. 

#### What is current behaviour

Embed files with .html makes the page auto scroll to where the embed .html at.
But sometimes the page will auto scroll back to top.

#### What is the expected behaviour

Scrolling to the embed .html will never happen.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 Enterprise Edition 21H2
- Node.js version: v16.15.1
- npm/yarn version: 8.11.0
- Browser version: Google Chrome 105.0.5195.19 dev
- Docsify version: 4.12.2
- Docsify plugins: search, docsify-copy-code, docsify-pagination, prism-actionscript

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Can you provide a reproducible sandbox or repo?

**Comment by diazynez** [comment]
I tried it just now. There is no such problem in the sandbox. The .html I embedded contains the <input> with autofocus, which should be caused by this property. Sorry for the inconvenience.

**Comment by sy-records** [comment]
ok, thanks for your feedback
