### ISSUE TITLE
How can you seriously label this 'a feature' – it should be an option.

### ISSUE THREAD

**Issue by blaasvaer** [docsifyjs/docsify#1861]
You've put this: 'No statically built html files' under the Features listing.

Generally a feature is the capability of DOING something – not the opposite, NOT doing something.

Now, this seems like a bummer to me, since a lot of people are actually asking for this feature. And why not simply make it an option since you already generate the markup anyway – simply save it to files?

Maybe you should consider this more important than:  feat: Emoji build (#1766)?

Just a suggestion ...

**Comment by trusktr** [comment]
Hi, thanks for the valid input, but not for the [condescension](https://en.wiktionary.org/wiki/condescension). You can also easily make a PR in order to make a suggestion.

**Comment by trusktr** [comment]
And sidenote, we've been thinking about how to implement SSR and SSG for a while now.
