### ISSUE TITLE
Page interior tracing points do not jump

### ISSUE THREAD

**Issue by lwh-0739** [docsifyjs/docsify#1869]
The sidebar renders the content title and click Not Jump to the stroke position

environment：
npm：8.9.0
node.js：environment
docsify：4.12.2

![image](https://user-images.githubusercontent.com/53554356/186554321-db668e8f-028a-4e7f-90ee-ccfbabfdc1ed.png)

**Comment by Koooooo-7** [comment]
Hi,  could u check the console output and provide a demo repo to reproduce this ?

**Comment by lwh-0739** [comment]
Console No log,and This is a local service that is currently inaccessible to the outside world.
Provide an example where the same problem occurs locall
[tmp.zip](https://github.com/docsifyjs/docsify/files/9442879/tmp.zip)
y

**Comment by lwh-0739** [comment]
I'm sorry I didn't reply until now. Something's been going on.

**Comment by lwh-0739** [comment]
Cause of the problem has been found:
~~~html
<style type="text/css">
	.content {
		overflow: auto;
	}
  </style>
~~~
Remove it and the jump will work.

**Comment by lwh-0739** [comment]
resolved
