### ISSUE TITLE
Custom heading anchors could match the rest of the world

### ISSUE THREAD

**Issue by hamishwillee** [docsifyjs/docsify#1871]
#### What problem does this feature solve?

Markdown does not have a standard format for defining a custom heading anchor format. I see from [this doc](https://docsify.js.org/#/helpers?id=customise-id-for-headings) that docsify allows this with:

```
### Hello, world! :id=hello-world
```

First time I've seen this format. Would it make sense to add this far more common format "as well"?

```
## Hello, world! {#hello-world}
```

This allows things like working with pandoc for pdfs, and easier migration for anyone who wants to use docsify.

#### What does the proposed API look like?

NA

#### How should this be implemented in your opinion?

No

#### Are you willing to work on this yourself?

No

**Comment by Koooooo-7** [comment]
Hi @hamishwillee .
In docsify, almost configs are config/format like `:config='xxxxx '`, we don't support `#` to follow the markdown anchor syntax for now.

**Comment by hamishwillee** [comment]
Thanks @Koooooo-7 , I understand that :-)

The main reason to consider adopting markdown conventions is that many people host on github, and have large established documentation libraries. The closer you are to convention, the more likely people are to use the system.

Personally this case is not a "deal breaker" as I could pre-process the markdown in a hook to fix up the link syntax.

**Comment by Koooooo-7** [comment]
Hi @hamishwillee.
I see, If you wanna pre-process the md content before docsify handle it, you can use this hook [`hook.beforeEach()`](https://docsify.js.org/#/write-a-plugin?id=write-a-plugin) to do the trick. e.g.
```js
hook.beforeEach(function (markdown) {
              // convert the {#hello-world} to   :id=hello-world
              content = markdown.replace(/\s*{#([\w-]*)}/, " :id=$1")
              return content
    })
```

**Comment by hamishwillee** [comment]
Thanks. The point I'm trying to make is inventing your own syntax for this kind of thing doesn't help docsify. Another good example is notes - I like your syntax, but github had a better one.

I do like docsify. If you can fix up image loading from aliases and relative links in sidebars I'll be using it.

**Comment by Koooooo-7** [comment]
I understand that you may want have a more common syntax to render things like the sort of defacto-standard . 
IMO, for a real LTS project, things is not that idealized. We r not a brand new project, we should take care of those breaking changes avoid breaking exist things for users.

Personally, I think we wont replace/refactor all the docsify syntax for now, maybe it would have  plugins or adaptors in the future.

**Comment by hamishwillee** [comment]
Thanks. Closing - made my point :-)
