### ISSUE TITLE
Can I import docsify as a vue component into the VUE project?

### ISSUE THREAD

**Issue by dongrixinyu** [docsifyjs/docsify#1875]
## Feature request
I have already write a website using vue. 
and now I wanna insert some sub pages with markdown formats.
So I am comfused if docsify could be imported into a vue component, thus being added to a vue project?

**Comment by mitchell-b-chelin** [comment]
@dongrixinyu it is just JavaScript. i do not see any reason why it cant be.

Q: What problem does this feature solve?
A: for me? none, but it could be useful

Q: What does the proposed API look like?
A: unsure, props or require options pass through.

Q: How should this be implemented in your opinion?
A: unsure, perhaps as a module or package to be loaded via npm and required in vue main.js file.

Q: Are you willing to work on this yourself?
A: Perhaps, is there a big need for it?

**Comment by dongrixinyu** [comment]
Thank you.
I find that `marked` seems suitable for me and nailed it.
It seems like that `docsify` provides a whole set of structures and not that easy to be imported into vue.
