### ISSUE TITLE
Add option to break line with single newline character

### ISSUE THREAD

**Issue by scruel** [docsifyjs/docsify#1882]
#### What problem does this feature solve?
I am using Typora for editing Markdown files, but docsify renders a different effect than Typora about line breaks.
Write one newline character, docsify will parse it as a soft line break rather than a hard line break, however, for two newline characters, docsify will parse them as two hard line breaks, just like other editors.
For daily usage, there is no reason for using soft line break, consider we can just type "space" to do this, and like many other editors docsify doesn't follow the [commonmark spec](https://spec.commonmark.org/0.28/#hard-line-breaks) to support rare used syntax either.
So I wonder if there is anything I can do to achieve this by "[Markdown configuration](https://docsify.js.org/#/markdown)" or can you add this as a feature? Thanks!

Code:
```
Break line by two or more spaces and newline charactor:
line1  
line2

Break line by one newline charactor:
line1
line2

Break lines by two or more newline charactors:
line1

line2



Break lines by two or more newline charactors:

line1

line2



No need to fully support the spec:
line1\ line2
line1  line2
```

Typora(Github also rendered md files like this):
![image](https://user-images.githubusercontent.com/16933298/190627022-29ab5fe8-319f-47e5-b181-e4438fb06795.png)

docsify:
![image](https://user-images.githubusercontent.com/16933298/190626996-02d98611-1cae-40e5-b59a-d8a33ba41684.png)

#### How should this be implemented in your opinion?
Add a custom option.

#### Are you willing to work on this yourself?
No

**Comment by scruel** [comment]
Temporary method:
```
          hook.beforeEach(function(content) {
            return content.replaceAll(/(?!^)\n/gm, '  \n');
          });
```

**Comment by scruel** [comment]
Temporary work around:
```
hook.beforeEach(function(content) {
  return content.replaceAll(/(?!^)\n(?!\n)/gm, '  \n');
});
```

**Comment by Koooooo-7** [comment]
Hi. @scruel .
Plz add this config and have a try.
```
window.$docsify = {
  markdown: {
    breaks: true,
  }
}
```

**Comment by scruel** [comment]
It works, thanks!
