### ISSUE TITLE
Bold text not rendered correctly

### ISSUE THREAD

**Issue by scruel** [docsifyjs/docsify#1888]
#### Steps to reproduce
```
**test)**test
```

#### What is current behaviour
Bold text not rendered correctly.

#### What is the expected behaviour
Render `test)` as bold text.

#### Other relevant information
- [x] Bug does still occur when all/other plugins are disabled?
Related to: https://github.com/docsifyjs/docsify/issues/1071

- Your OS: Windows
- Node.js version: 16.17.0
- npm/yarn version:  8.19.2
- Browser version: latest
- Docsify version: latest(from cdn)

#### Please create a reproducible sandbox 

[![Edit dreamy-bessie-honvrx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-bessie-honvrx)

**Comment by Koooooo-7** [comment]
Hi @scruel .
I m not quite sure where the certain problem is,  since I test here  is the same result.
```
**test)**test
```
**test)**test

If you wanna wrapper it as bold, currently the workaround is using the html tag intead.
```
<b>test)</b>test
```
<b>test)</b>test

**Comment by jhildenbiddle** [comment]
Not sure what the issue is, but since this is an issue with the [marked](https://github.com/markedjs/marked) (the markdown parser we use) I recommend opening an issue there instead.

Until this gets fixed, @Koooooo-7's suggestion is probably the best option.
