### ISSUE TITLE
Spaces not rendered correctly

### ISSUE THREAD

**Issue by scruel** [docsifyjs/docsify#1889]
#### Steps to reproduce
```
long-text:option: 1
option:                2
first-option:         3
```

#### What is current behaviour
Empty spaces lost after rendered page.

#### What is the expected behaviour
Keep spaces within text.

#### Other relevant information
- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows
- Node.js version: 16.17.0
- npm/yarn version:  8.19.2
- Browser version: latest
- Docsify version: latest(from cdn)

**Comment by Koooooo-7** [comment]
Hi @scruel .
Normally, markdown is used to generate html, and html collapses white spaces by default. 
So, you should wrapper them in specific tags. besides, use  either ` &nbsp;   &ensp;  or  &emsp;` instead of space characters is fine too.
