### ISSUE TITLE
Comments line should not be ignored to support plugins

### ISSUE THREAD

**Issue by scruel** [docsifyjs/docsify#1890]
#### Steps to reproduce
```
> l
>
> <!-- <div>test</div> -->
>
> <!-- <div>test</div> -->d
>
> a
>
> <!-- <div>test</div> -->
>
> <!-- <div>test</div> -->d
>
> l
>

<!-- <div>plugin convert comments</div> -->
<!-- <div>plugin convert comments</div> -->
```

#### What is current behaviour
quote block ignored comments, this result of above code is rendered to:
```
<blockquote>
<p>l</p>
<!-- <div>test</div> -->
<!-- <div>test</div> -->d
<p>a</p>
<!-- <div>test</div> -->
<!-- <div>test</div> -->d
<p>l</p>
</blockquote>
```

#### What is the expected behaviour
Expected to:
```
<blockquote>
<p>l</p>
<p><!-- <div>test</div> --></p>
<p><!-- <div>test</div> -->d</p>
<p>a</p>
<p><!-- <div>test</div> --></p>
<p><!-- <div>test</div> -->d</p>
<p>l</p>
</blockquote>
```

And plugins like docsify-latex and docsify-tabs should be able to get line breaks as normal text.

#### Other relevant information
- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows
- Node.js version: 16.17.0
- npm/yarn version:  8.19.2
- Browser version: latest
- Docsify version: latest(from cdn)

#### Please create a reproducible sandbox 

[![Edit funny-firefly-58h39c](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-firefly-58h39c)

**Comment by scruel** [comment]
What I mean is wrapper the line to <p> </p>, rather than leave it blank, I don't want you show those comments for users.
```
> <!-- <div>test</div> -->d
> <!-- <div>test</div> -->d

<!-- <div>plugin convert comments</div> -->d
<!-- <div>plugin convert comments</div> -->
```

**Comment by scruel** [comment]
And what about this:
```
d<!-- ->
x<!-- ->
```

Will get:
```
d<!– -> x<!– ->

**Comment by Koooooo-7** [comment]
> What I mean is wrapper the line to
> 
> , rather than leave it blank, I don't want you show those comments for users.
> ```
> > d
> > d
> 
> d
> d
> ```

I m not fully aware what you meat about the `blank` and show the `comments` for users...
the `<!-- <div> this is html content </div> -->` is not showing indeed.
and docsify does't render it either.

**Comment by Koooooo-7** [comment]
> And what about this:
> 
> ```
> d<!-- ->
> x<!-- ->
> ```
> 
> Will get:
> 
> ```
> d<!– -> x<!– ->
> ```

As I mentioned, the md render to html, it will align to the html syntax as well.

**Comment by Koooooo-7** [comment]
And I think it is X-Y problem here rn. 
Could u plz provide some screenshots or live samples to clarify what ur assumption is.

**Comment by scruel** [comment]
> > And what about this:
> > ```
> > d<!-- ->
> > x<!-- ->
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will get:
> > ```
> > d<!– -> x<!– ->
> > ```
> 
> As I mentioned, the md render to html, it will align to the html syntax as well.


And it breaks what you said before, "the `<!-- -->` is the valid comment tag in both markdown and html".
Users now can the comments, because `<` is escaped to `&lt;`.

**Comment by Koooooo-7** [comment]
Hi, @scruel .
It is `<!-- comment -->` , not  `<!--  comment  -> `,  the double `-` in the end.

IMHO, it is literally expected behavior about the `comments` render result you mentioned. 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/33706142/191403583-8338e748-34b7-439c-85ea-78a1cb324d20.png">

**Comment by scruel** [comment]
Oops, I made a mistake, it's related to another issue, I will add more info into that one, Thanks.
