### ISSUE TITLE
markdown network image dont display?

### ISSUE THREAD

**Issue by chengkanghua** [docsifyjs/docsify#1925]
#### Steps to reproduce

test.md
-------------------------------
## route命令

route程序对内核的IP选路表进行操作。它主要用于通过已用ifconfig(8)程序配置好的接口来指定的主机或网络设置静态路由。
路由概念：
计算机之间的数据传输必须经过网络，网络可以直接连接两台计算机，或者通过一个一个的节点构成。
路由器理解为互联网的中转站，网络中的数据包就是通过一个一个路由器转发到达目的地。

![](https://cdn.nlark.com/yuque/0/2021/png/194754/1610857066266-ae4b2ec7-dd1b-4051-9f4b-b0ba657eb0a2.png#align=left&display=inline&height=554&margin=%5Bobject%20Object%5D&originHeight=554&originWidth=1180&size=0&status=done&style=none&width=1180)
----------------------
this is demo , 

#### What is current behaviour
```bash
cd docs
docsify serve .
```

#### What is the expected behaviour
in browser show imags

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: ubunt1804
- Node.js version: v14.21.1
- npm/yarn version: 6.14.17
- Browser version: Google Chrome   97.0.4692.71（正式版本） (x86_64)
- Docsify version:  //cdn.jsdelivr.net/npm/docsify@4
- Docsify plugins: 

#### Please create a reproducible sandbox 
https://codesandbox.io/s/modest-jackson-tw0d99?file=/README.md
[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)
[]()#### Mention the docsify version in which this bug was not present (if any)

**Comment by sy-records** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/33931153/201007216-fe898f6e-3859-4932-b974-9d9675b25c27.png">
