### ISSUE TITLE
GitHub Pages does not work with ./docs folder

### ISSUE THREAD

**Issue by shinokada** [docsifyjs/docsify#1936]
## Bug Report

GitHub page does not work with ./docs folder.  

#### Steps to reproduce

I followed the [doc](https://docsify.js.org/#/deploy).
When I add index.html in the root, it works. But when I add it to the docs folder and select `main branch /docs` folder as my GitHub Pages source, it returns 404.

#### What I tried

1. I added `homepage` but the result is the same.

```
...
homepage: 'https://raw.githubusercontent.com/shinokada/svelte-heros-v2/main/README.md'
...
```

2. I added .nojekyll file.

But the result is the same.

3. I added `basePath` but the result is the same.

```
<script>
  window.$docsify = {
    subMaxLevel: 1,
    maxLevel: 3,
    auto2top: true,
    repo: 'shinokada/svelte-heros-v2',
    routerMode: 'history',
    basePath: 'https://raw.githubusercontent.com/shinokada/svelte-heros-v2/main/docs/',
    homepage: 'https://raw.githubusercontent.com/shinokada/svelte-heros-v2/main/README.md'
  };
</script>
```

#### What is current behaviour

[demo](https://shinokada.github.io/svelte-heros-v2/)

404 - Not found

![image](https://user-images.githubusercontent.com/147320/207158065-206a7778-5e09-4dc9-98c3-93f88081161d.png)

GitHub page deployment shows no problem.

![image](https://user-images.githubusercontent.com/147320/207159544-09fa82a8-928b-4e3b-87d8-a86740886059.png)

#### What is the expected behaviour

Showing the docs.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
You'll need to place a .nojekyll file in the deploy location (such as /docs or the gh-pages branch)

**Comment by shinokada** [comment]
I have it.
It seems like I need to place README.md in the docs folder.
I think having two README.md files are not nice.
Adding followings works localhost but not GitHub Pages.

```
homepage: 'https://raw.githubusercontent.com/shinokada/svelte-heros-v2/main/README.md'
```

So at the moment I keep two README files in the root and docs folder.
It will be nice to have a command to copy root/README.md to docs/README.md

```
docsify cp
```

Is there such a command?

**Comment by sy-records** [comment]
In fact, if you put the readme in the docs directory, GitHub will display it properly without adding two readme.

**Comment by shinokada** [comment]
Thanks. I didn't know that GitHub can display README file from docs folder.

**Comment by shinokada** [comment]
NPM page won't show docs/README.md. 
How to show it?
