### ISSUE TITLE
Internal link problem with GitHub Pages

### ISSUE THREAD

**Issue by shinokada** [docsifyjs/docsify#1938]
## Bug Report

I placed `icon-list.md` in the docs folder.
And I add a link in the README.md:

```
[Icon names](./icon-list.md)
// I also tried this
[Icon names](icon-list.md)
```

The my GitHub page URL is `https://shinokada.github.io/my-repo-name`. But the link leads to `https://shinokada.github.io/icon-list` and this returns 404.

I'm expecting the link to be `https://shinokada.github.io/my-repo-name/icon-list`.

**Comment by sy-records** [comment]
Can you provide your configuration items? `window.$docsify`

Maybe you need to set the `basePath`

**Comment by shinokada** [comment]
I moved all the files to the root dir and it is working.
Thanks for your help.
