### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by shinokada** [docsifyjs/docsify#1947]
#### Steps to reproduce

The search function works localhost but not GitHub pages.

[My GitHub page](https://shinokada.github.io/teffects/)

#### What is current behaviour

On the GitHub pages, it shows No Results!.

#### What is the expected behaviour

It shows search results.

#### Other relevant information

My docsify code:

```
window.$docsify = {
      maxLevel: 4,
      auto2top: true,
      repo: 'shinokada/teffects',
      routerMode: 'history',
      ga: 'G-B4WX2V302K',
      search: 'auto',
      // search: [
      //   '/',            // => /README.md
      // ],

      // complete configuration parameters
      search: {
        maxAge: 180000,
        paths: 'auto',
        placeholder: 'Type to search',
        noData: 'No Results!',
        // Headline depth, 1 - 6
        depth: 3,
        hideOtherSidebarContent: false, // whether or not to hide other sidebar content
      },
    };
```

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @shinokada , It works fine to me on the site ur mentioned.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/33706142/210398974-7e53c234-5fc2-4226-9adf-de21cff585f3.png">

**Comment by shinokada** [comment]
Thanks. I think GitHub pages sometimes takes time to update.
