### ISSUE TITLE
coverage missing on GitHub Pages

### ISSUE THREAD

**Issue by zhang-yuanye** [docsifyjs/docsify#1964]
I cloned a Docsify templete-repo and set up GitHub Pages, but the coverage is not showing.

Coverage is showing correctly on local sever (Docsify serve)

to reproduce:
https://github.com/zhang-yuanye/docsify-templete.git

GitHub Pages for the repo above:
https://zhang-yuanye.github.io/docsify-templete/#/

**Comment by sy-records** [comment]
you need create `.nojekyll` file
see https://github.com/MichaelCurrin/docsify-js-template/tree/master/docs
