### ISSUE TITLE
使用感受，反馈以下几个问题

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [docsifyjs/docsify#1980]
[存在问题](https://boxtrade.github.io/docsify_sample/#/README?id=%e5%ad%98%e5%9c%a8%e9%97%ae%e9%a2%98)

    天下没有免费的午餐，好用的后台评论 几乎不存在！
    gittalk 认证接口问题 不好用；
    页面加载缓慢
    好多页面一下加载很多 md ，文件，用户体验差
    google 字体下载？？ 默认不行吗
    希望能越来越好 ！！！

**Comment by sy-records** [comment]
大部分都是插件，不是核心功能。
google依赖可以换镜像加载，也可以放本地。
