### ISSUE TITLE
Search doesn't work for Tibetan

### ISSUE THREAD

**Issue by ngawangtrinley** [docsifyjs/docsify#1986]
## Bug Report

Docsify search doesn't work for Tibetan language ([Tibetan Unicode block](https://en.wikipedia.org/wiki/Tibetan_(Unicode_block))). 

#### Steps to reproduce

1. Add a Tibetan string such as `བཀྲ་ཤིས་བདེ་ལེགས་ཤོག` in a document
2. Search for a substring of said text such as `བཀྲ་` or `ཤིས` or `བཀྲ་ཤིས་`

#### What is current behaviour

1. Add a Tibetan string such as `བཀྲ་ཤིས་བདེ་ལེགས་ཤོག` in a document

![image](https://user-images.githubusercontent.com/17675331/216928090-5320caad-f79f-4f03-aca2-2b1e3ed50459.png)

2. Search for a substring of said text such as `བཀྲ་` or `ཤིས` or `བཀྲ་ཤིས་`
![image](https://user-images.githubusercontent.com/17675331/216928298-97581f9a-a49b-4186-9b15-cdb46c2d61d2.png)

#### What is the expected behaviour

A search result is expected, such as:
![image](https://user-images.githubusercontent.com/17675331/216928872-bfbd5ce8-a8fa-45de-8b16-88c6c0381013.png)

...or like the search in MKDocs:
![image](https://user-images.githubusercontent.com/17675331/216929026-8c5e602b-bbd5-45c1-94a3-928bfb648148.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows
- Node.js version: 
- npm/yarn version: 
- Browser version: Chrome, Version 109.0.5414.120 (Official Build) (64-bit)
- Docsify version: 4.13.0
- Docsify plugins: search.min.js

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @ngawangtrinley , I can not reproduce it, could u provide more details about it?

<img width="627" alt="image" src="https://user-images.githubusercontent.com/33706142/217169148-b3765d63-7baa-4c0c-b515-1f0dcbfca105.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/33706142/217169275-498673aa-b166-42c1-a4f8-906f3839591d.png">

**Comment by ngawangtrinley** [comment]
@Koooooo-7 I did more testing and it started working after a few builts. It's either that the index isn't refreshed at each build or that it is cached in my browser and only gets replaced after a few times. In practice it means that the only issue left is that there's a bit of lag between what was added and what can be searched. 

It's not a big problem so I'll close this issue. Thanks for looking into it!

**Comment by Koooooo-7** [comment]
Hi @ngawangtrinley , yes, we store the index in `localStorage` for caching, if you wanna test it locally, normally you should alway open a new incognito window since it will have a new localStorage init.

**Comment by ngawangtrinley** [comment]
That makes a lot of sense. 

It is a bit confusing in a few cases like the one I faced or in the opposite when you delete a page and the search still finds its content.

**Comment by Koooooo-7** [comment]
> That makes a lot of sense.
> 
> It is a bit confusing in a few cases like the one I faced or in the opposite when you delete a page and the search still finds its content.

If the user always open this browser, I should say yes. but it's can't not to handle it since it's store in the browser. If not to use this cache is fine but it will issue the performance since the search index need generate everytime u do the search. it's a balance.
