### ISSUE TITLE
 subdirectory  _sidebar.md uses an absolute path, which is very awkward

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [docsifyjs/docsify#1989]
> I am also very interested in this functionality. In my use case I have a top-level "portal" docsify site that brings in several other project docsify sites as subfolders. Each of the projects has their own _sidebar. But when used in the portal, the links in the project sidebars no longer work because it's using the main top-level folder instead of looking relative to the folder containing the sidebar.

Is this fixed?
When I read the official documentation, I also found that the subdirectory uses an absolute path, which is very awkward!!
Like what

> https://github.com/docsifyjs/docs-zh/edit/master/_sidebar.md
``` [快速开始](zh-cn/quickstart.md)```
it can't work in your own warehouse ;

page 404 
https://github.com/docsifyjs/docs-zh/blob/master/zh-cn/quickstart.md

https://github.com/docsifyjs/docsify/edit/develop/docs/_sidebar.md
```   - [Quick start](quickstart.md) ```

_Originally posted by @chenGit1763113879QQ in https://github.com/docsifyjs/docsify/issues/1684#issuecomment-1426120196_

**Comment by Koooooo-7** [comment]
plz do not delete the issue tpl.
