### ISSUE TITLE
image url error when deploy docsify on sub folder with nginx

### ISSUE THREAD

**Issue by wxh0402** [docsifyjs/docsify#1995]
#### Steps to reproduce

code link:https://gitee.com/dcalc/dnfcalculating_110/tree/master/docs
nginx set:
![image](https://user-images.githubusercontent.com/50483907/220286402-b893d925-1386-4e06-96fd-7daea03f81f6.png)
![image](https://user-images.githubusercontent.com/50483907/220283538-41b47498-b751-47ba-ab50-e25384b92ef3.png)

web link:  https://dcalc.cn/USERMANUAL

#### What is current behaviour

I use the same path to show image,but only can get on cover.
![image](https://user-images.githubusercontent.com/50483907/220286711-89c02f09-57da-42fd-94bf-26ef783316d3.png)
![image](https://user-images.githubusercontent.com/50483907/220286796-11dbb586-1816-41ad-8175-b62453008228.png)

![image](https://user-images.githubusercontent.com/50483907/220284973-3903086f-399c-4061-900d-218534041b9f.png)
**When i copy the img floder to root path or add /docs to image path ,/USERMANUAL can get image correctly.**

#### What is the expected behaviour

get the img correctly

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: Windows Server 2022 Datacenter
- npm/yarn version: 
- Browser version: 
- Docsify version: newset
- Docsify plugins: 
- nginx version:1.22.1

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @wxh0402 , the `img` path in ur doc is `/img/xxx.jpg`, it gonna search on the root folder based on ur nginx server.
And I think it maybe issue with the config `relativePath: true`, the workaround is that you need have a `rewrite` config in ur nginx based on path or suffix.

**Comment by wxh0402** [comment]
Thank you
