### ISSUE TITLE
Upon invoking "Copy to Clipboard" button, the Screen reader is not announcing the success message "Copied". 

### ISSUE THREAD

**Issue by msftedad** [docsifyjs/docsify#1997]
#### Steps to reproduce
1.Navigate to this link [First Level Child (zorana-jankovic.github.io)](https://zorana-jankovic.github.io/example/#/start)
2.Turn on screen reader.
3.Tab navigate to the "Copy to Clipboard" button and invoke it.
4.Observe that screenreader is announcing the success message copied/not.

#### What is current behaviour
Upon invoking "Copy to Clipboard" button, the Narrator is not announcing the success message "Copied".

#### What is the expected behaviour

Upon invoking "Copy to Clipboard" button, the Narrator should announce the success message "Copied".
Note: Issue occurs in NVDA, JAWS also

#### Other relevant information

- Your OS: OS build (22621.1265)
- Browser version: Version 110.0.1587.50 (Official build) (64-bit)
- NVDA version: 2022.3.2
- JAWS version: 2023.2212.23 ILM

https://user-images.githubusercontent.com/93735775/221094529-44517d34-f0e4-4815-bdb2-5897525b4485.mp4

**Comment by sy-records** [comment]
I did not reproduce your problem and I use Chrome.

If you can reproduce it stably, you can submit the issue to [docsify-copy-code](https://github.com/jperasmus/docsify-copy-code/issues)

![image](https://user-images.githubusercontent.com/33931153/221129268-4c6f8d4b-5bc1-4dad-a812-32a3d8097876.png)

**Comment by msftedad** [comment]
Hi sy-records,

We have tested in the following environment :
Chrome Version 110.0.5481.177 (Official Build) (64-bit)

**Comment by sy-records** [comment]
Sorry, I didn't notice the screen reader. You can submit an issue to the plug-in, which may not be supported.

**Comment by msftedad** [comment]
Hi sy-records,
Could you please share us the repo for Plug-in to address this issue. Thanks

**Comment by sy-records** [comment]
https://github.com/jperasmus/docsify-copy-code

**Comment by msftedad** [comment]
Thanks for the update.
