### ISSUE TITLE
Not able to access a page directly using its URL

### ISSUE THREAD

**Issue by shinokada** [docsifyjs/docsify#2004]
#### Steps to reproduce

[My docs](https://flowbite-svelte-blocks.codewithshin.com/) has `_sidebar.md` and navigation works. However when I use the direct URL, for example, [this page](https://flowbite-svelte-blocks.codewithshin.com/account-recovery) shows 404.

When I refresh the page after navigating a page also show 404.

#### What is current behaviour

It shows 404, File not found.

#### What is the expected behaviour

It should show the page.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @shinokada , it seems the github-page related issue, could u plz share us your github pages settings detail ?

**Comment by shinokada** [comment]
Thank you for your reply.
The following image shows all GitHub Pages config.

![image](https://user-images.githubusercontent.com/147320/226171324-efd8480b-819e-44c6-8189-031f68c0054f.png)

**Comment by trusktr** [comment]
Hello! Don't use `routerMode: 'history'` unless you know how to configure your server (GitHub Pages in this case) to serve URLs from a single index.html file. Use `routerMode: 'hash'` (or remove the option, that's the default value).

To serve regular URLs with GitHub pages from a single index file, see here: https://github.com/rafgraph/spa-github-pages
