### ISSUE TITLE
Can docsify support hash tag like <a href="#part1">Part 1</a> inside content page at right side? 

### ISSUE THREAD

**Issue by weixuezhang** [docsifyjs/docsify#2005]
#### Steps to reproduce

Create a test html page and add it to right side with docsify. In the test file, add a hash tag, such as: <a href="#part1">Part 1</a>, inside this page, add a html element <div id="part1"> This is the title of Part 1 </div>, then go to browser, click "Part 1" hash tag. 

#### What is current behaviour
Browser shows body content of index.html.

#### What is the expected behaviour
It's expected that browser scroll to "This is the title of Part 1" of the test page.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @weixuezhang , what means the html page of docisfy? IIUC, if you wanna add hashtag/anchor into a markdown page and jump inside the same page between titles, you can mark the anchor using `[content](#title-anchor)` directly. i.e.
```md
# Title here

some content...

## Second

some content too ...

## Other

wanna jump to [second](#second) now.

```

**Comment by trusktr** [comment]
Yep, that's the way.
