### ISSUE TITLE
Access results in a blank page

### ISSUE THREAD

**Issue by ShutterZor** [docsifyjs/docsify#2013]
#### Steps to reproduce

I deployed the local project to a GitHub repository and used the pages service and bound it to my own domain. The project has been working for a while, but I noticed today that the pages are blank when I visit them.

My page is: https://shutterzor.cn/stata-tutorial/

#### What is current behaviour

All blank now.

#### What is the expected behaviour

The expected behaviour is to be able to display web resources properly.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?
I do not use other plugins.
- Your OS: Windows11
- Node.js version: v18.14.1
- npm/yarn version: 9.3.1
- Browser version: Microsoft Edge Version 111.0.1661.62 (official version) (64-bit)
- Docsify version: 4.4.4
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/33931153/229734516-6a5f183a-d226-4a44-b3ef-89f1181c80fb.png">
