### ISSUE TITLE
Why cannot I visit your website?

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [docsifyjs/docsify#2014]
## Bug Report
![image](https://user-images.githubusercontent.com/60914359/229834068-84f61fbc-ad93-4b52-8994-8bdb82d638e3.png)

#### Steps to reproduce

visit https://docsify.js.org/

My local server also broke down.
![image](https://user-images.githubusercontent.com/60914359/229834299-3add0a22-c378-4b20-b56a-4cac2d79c347.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
Works for me. Are you in China or some country outside the U.S.A.? You may have been blocked by your internet service provider, or something, and may need to use a Proxy. Maybe @Koooooo-7 or @sy-records can recommend what to do.

**Comment by Koooooo-7** [comment]
Hi @S-N-O-R-L-A-X , I think it maybe the temporary net issue since we deploy it on github pages... As @trusktr said,  you may need some proxy stuff to make it if you are in some places with net block.

**Comment by sy-records** [comment]
see https://github.com/docsifyjs/docsify/discussions/1806

**Comment by S-N-O-R-L-A-X** [comment]
> Works for me. Are you in China or some country outside the U.S.A.? You may have been blocked by your internet service provider, or something, and may need to use a Proxy. Maybe @Koooooo-7 or @sy-records can recommend what to do.

Yes, I am in China, but I tried VPN and it still couldn't work.

**Comment by S-N-O-R-L-A-X** [comment]
> Hi @S-N-O-R-L-A-X , I think it maybe the temporary net issue, it's lagging... As @trusktr said, you may need some proxy stuff to make it if you are in some places with net block. Instead, you can try to visit the https://docsifyjs.org , our mirror site host by @sy-records as well.

That website is accessible. but the content is different.
