### ISSUE TITLE
Mermaid diagram not rendering properly 

### ISSUE THREAD

**Issue by SumithChandran** [docsifyjs/docsify#2015]
## Bug Report
I am facing problem with mermaid rendering.
When I click on another page in the sidebar the diagrams are not rendering.

#### Steps to reproduce
I am attached a zip file that replicate my issue 
[mermaid_diagram_not_loading.zip](https://github.com/docsifyjs/docsify/files/11159344/mermaid_diagram_not_loading.zip)

#### What is current behaviour
The mermaid diagram will not render when I change page in sidebar to Guide.
It will only load when I refresh the page.

#### What is the expected behaviour
Should be rendered without a refresh

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by SumithChandran** [comment]
@paulhibbitts,
Thanks. This script fixed the issue.

**Comment by Leward** [comment]
Hello, @corentinleberre kindly made [a PR to address the issue](https://github.com/Leward/mermaid-docsify/pull/32). 

You should be able to try and close this issue if that works for you @SumithChandran
