### ISSUE TITLE
Cover page doesn't display on translated pages

### ISSUE THREAD

**Issue by adamlui** [docsifyjs/docsify#2018]
#### Steps to reproduce

1. Create a translation subdir w/ `_coverpage.md`
2. Add navbar that links to translation
3. Visit page
4. Click translation link

#### What is current behaviour

Translated cover page doesn't appear

#### What is the expected behaviour

Translated cover page appears

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 18.15.0
- npm/yarn version: 9.5.0 
- Browser version: Firefox 111.0
- Docsify version: 4.13.0
- Docsify plugins: None

#### Please create a reproducible sandbox 

The codesandbox.io site keeps giving error when I try to upload files (https://github.com/chatgptjs/chatgpt.js/tree/main/docs)

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi  @adamlui . Have you config it as per to the [cover docs](https://docsify.js.org/#/configuration?id=coverpage) ? since I check your repo `index.html`, it seems only enable the cover page.

**Comment by adamlui** [comment]
@Koooooo-7 thank you you are great!
