### ISSUE TITLE
How to Customize the name of index.html

### ISSUE THREAD

**Issue by Haoshouquan** [docsifyjs/docsify#2039]
I want to customize the name of  index.html

for example:My html name is user-helper.html,i want to see content when open user-helper.html

Please help me how can i do. Thanks

**Comment by manthanindane** [comment]
you can customize the name of your Docsify index file. To do this, you will need to specify the name of your HTML file in the Docsify configuration. Here are the steps:

Create your HTML file with your desired name, for example, "user-helper.html".
In the <head> section of your HTML file, add a script tag to load Docsify's JavaScript library, and configure it as follows:

`<head>
  <script>
    window.$docsify = {
      loadSidebar: true,
      loadNavbar: true,
      homepage: 'README.md'
    }
  </script>
  <script src="//unpkg.com/docsify@latest/docsify.min.js"></script>
</head>
`

In the configuration object (window.$docsify), add a property named entry, and set its value to the relative path of your HTML file. For example:

`<head>
  <script>
    window.$docsify = {
      loadSidebar: true,
      loadNavbar: true,
      homepage: 'README.md',
      entry: 'user-helper.html'
    }
  </script>
  <script src="//unpkg.com/docsify@latest/docsify.min.js"></script>
</head>
`

Save and deploy your HTML file to your web server or GitHub Pages.

now, when you open the URL of your HTML file, Docsify will load and parse your Markdown files and display them as a website. In this case, the URL would be 
http://yourdomain.com/user-helper.html or
https://yourusername.github.io/your-repo/user-helper.html if you're using GitHub Pages.

**Comment by sy-records** [comment]
yeah, you only need change `index.html` to `user-helper.html`.
