### ISSUE TITLE
Code snippets not properly indented if included in numbered lists w/o empty newline

### ISSUE THREAD

**Issue by adamlui** [docsifyjs/docsify#2057]
## Bug Report

When code snippets are included in numbered lists without an empty newline separating numbered heading & snippet, indents become single spaces:

> ![image](https://user-images.githubusercontent.com/10906554/236442890-7ee819dd-ae75-4a1a-81d8-38f2438b9d7c.png)

#### Steps to reproduce

In the doc, write a code snippet after numbered item without using an empty newline:

``````markdown
4. In scripts that use `chatgpt.js` (foreground or background), structure like so:
```js
(async () => {
    const { chatgpt } = await import(chrome.runtime.getURL('lib/chatgpt.js'));    
    // Your code here...
})();
```
``````

#### What is current behaviour

4-space indents in code block become 1-space

#### What is the expected behaviour

4-space indents remain 4-space

#### Other relevant information

The bug is live @ https://chatgpt.js.org

While inserting an empty newline between the numbered item & the code block restores proper indentation, it strangely removes the vertical gap between the two when rendered, so omitting empty newline is less unpleasing aesthetically (relative to whole site vs. merely code blocks being off)

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 18.15.0
- npm/yarn version: 9.5.0
- Browser version: Firefox 111.0
- Docsify version: 4.13.0
- Docsify plugins: 

#### Please create a reproducible sandbox 

The codesandbox.io site keeps giving error when I try to upload files (https://github.com/chatgptjs/chatgpt.js/tree/main/docs)

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @adamlui , IIUC, it seems the md parser default syntax , either in github comments. i.e
- `1-space`
```
4. In scripts that use `chatgpt.js` (foreground or background), structure like so:
```js
(async () => {
    const { chatgpt } = await import(chrome.runtime.getURL('lib/chatgpt.js'));    
    // Your code here...
})();
```
**Result** 
4. In scripts that use `chatgpt.js` (foreground or background), structure like so:
```js
(async () => {
    const { chatgpt } = await import(chrome.runtime.getURL('lib/chatgpt.js'));    
    // Your code here...
})();
```
--- 
- `4-space`
```
4.    In scripts that use `chatgpt.js` (foreground or background), structure like so: 
```js
(async () => {
    const { chatgpt } = await import(chrome.runtime.getURL('lib/chatgpt.js'));    
    // Your code here...
})();
```
**Result** 
4.    In scripts that use `chatgpt.js` (foreground or background), structure like so:
```js
(async () => {
    const { chatgpt } = await import(chrome.runtime.getURL('lib/chatgpt.js'));    
    // Your code here...
})();
```

**Comment by adamlui** [comment]
Hey @Koooooo-7 I tested your theory and added 4 spaces after `4.` but it still displays as 1-space indent:

![image](https://user-images.githubusercontent.com/10906554/236777193-4d626369-fef9-47aa-aca5-77e72431a1f0.png)

**Comment by Koooooo-7** [comment]
> Hey @Koooooo-7 I tested your theory and added 4 spaces after `4.` but it still displays as 1-space indent:
> 
> ![image](https://user-images.githubusercontent.com/10906554/236777193-4d626369-fef9-47aa-aca5-77e72431a1f0.png)

Yep. I meant that it seems the parser common behavior in both docsify and github as I pasted above, they have the same render result which make the 4 spaces to 1.

If you wanna keep the `4-spece`, the `&emsp` could be a workaround.

**Comment by adamlui** [comment]
@Koooooo-7 where should I insert the `&emsp`?

**Comment by Koooooo-7** [comment]
I checked the [Markdown style guide](https://google.github.io/styleguide/docguide/style.html#nested-list-spacing), the `4-spaces` way sounds tricky.

**Comment by Koooooo-7** [comment]
> @Koooooo-7 where should I insert the `&emsp`?

Normally, it should be in the html content. but in the case you mentioned, it seems not work :(.
I suppose that you may need adjust your content to match the common parser rules.

**Comment by adamlui** [comment]
> Yep. I meant that it seems the parser common behavior in both docsify and github as I pasted above, they have the same render result which make the 4 spaces to 1.

Actually your pastes render properly in GitHub as 4-space:

![image](https://user-images.githubusercontent.com/10906554/236977514-aee909a2-b176-4323-94be-2b2578e0173a.png)
![image](https://user-images.githubusercontent.com/10906554/236977535-2ce54076-dd30-4dee-8dca-4eb6b1cb5034.png)

Only in Docsify do code blocks without vertical space between numbered item & code block as described do they become 1-space:

![image](https://user-images.githubusercontent.com/10906554/236978195-0492691b-f692-415b-bbfc-04561542efca.png)

_Source: https://chatgpt.js.org/#/?id=-chrome_

On GitHub, this same markdown results in 4-space:

![image](https://user-images.githubusercontent.com/10906554/236978339-6712b69d-0533-4f15-ad04-dbaad7206b99.png)

_Source: https://github.com/chatgptjs/chatgpt.js#-chrome_

The reason this glitch is occurring, the logic in Docsify that strips extra whitespace to uniformly indent numbered items is not accounting for code blocks like GitHub does (so it needs to add a condition only if backticks aren't detected)

**Comment by adamlui** [comment]
(it probably happens to quotations too so `>` should also be added to condition)

**Comment by Koooooo-7** [comment]
Hi @adamlui ,  I final understand this now. gonna take a look on it !

**Comment by adamlui** [comment]
It does properly indent when newline is added, but the gap between numbered heading and code block shrinks, so it doesn't look right is why I sacrificed and let just one code block look weird. Do you know when marked.js will be upgraded?

**Comment by Koooooo-7** [comment]
> It does properly indent when newline is added, but the gap between numbered heading and code block shrinks, so it doesn't look right is why I sacrificed and let just one code block look weird. Do you know when marked.js will be upgraded?

Actually, we do discuss on the marked.js upgrade stuff and I already merge it #1993. But it may broken the support for `IE11` since marked.js drop IE11... so...I m not sure when we have a clear plan when/how to release this changes.
