### ISSUE TITLE
code block is broken by list

### ISSUE THREAD

**Issue by LiJohnson** [docsifyjs/docsify#2100]
## Bug Report

a list item with code block and code block has a blank line
[codesandbox](https://codesandbox.io/s/practical-cherry-9rg23v?file=/README.md)

#### Steps to reproduce

here is markdown code 
<img width="321" alt="image" src="https://github.com/docsifyjs/docsify/assets/2616788/a0603bcf-cb79-4f02-99b8-4e2b8444875d">

- list 1
```js
let a = 1
let b = 2
console.log(a +b)
```
- list 2
```js
let a = 1
let b = 2
// blank line

console.log(a +b)
```

#### What is current behaviour

<img width="591" alt="image" src="https://github.com/docsifyjs/docsify/assets/2616788/b41f4384-f68c-42f0-ab03-57c90a6580f4">

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
use
````
- list 1

```js
let a = 1;
let b = 2;
console.log(a + b);
```

- list 2

```js
let a = 1;
let b = 2;
// blank line

console.log(a + b);
```

````

**Comment by LiJohnson** [comment]
> use
> 
> ```
> - list 1
> 
> ```js
> let a = 1;
> let b = 2;
> console.log(a + b);
> ```
> 
> - list 2
> 
> ```js
> let a = 1;
> let b = 2;
> // blank line
> 
> console.log(a + b);
> ```
> ```

if leave a  blank line alter list item, code block will not intdent . [preview here](https://9rg23v.csb.app/#/no-indent)
![image](https://github.com/docsifyjs/docsify/assets/2616788/32db556d-e73d-4b4c-a08e-61d7730639be)
