### ISSUE TITLE
4.13 and 4.12, a label discrepancy

### ISSUE THREAD

**Issue by chaoweiyi** [docsifyjs/docsify#2110]
#### Steps to reproduce

- [link](/assets/demo.html ':ignore :target=_blank')

4.12 open new page
4.13 current page, but normal after F5

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
I don't know what you mean at all, your issue description is very vague, and your link doesn't go anywhere. Please open a new issue with a good description and problem reproduction steps.
