### ISSUE TITLE
Seems Gtag not working

### ISSUE THREAD

**Issue by darhanger** [docsifyjs/docsify#2111]
## Bug Report
Seems new gtag not working. 
#### Steps to reproduce
Instal Gtag
https://github.com/darhanger/rotations/blob/main/docs/index.html#L42 - seems all correct. 

#### What is the expected behaviour
With old ga script and tags all work. 

#### Other relevant information

- Your OS: Win 11
- Browser version: Chrome Last
- Docsify version: Last
- Docsify plugins: //cdn.jsdelivr.net/npm/docsify/lib/plugins/gtag.min.js

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by jimaek** [comment]
There is no such file in the NPM package https://cdn.jsdelivr.net/npm/docsify/lib/plugins/

**Comment by sy-records** [comment]
We haven't released a new version yet. So you can't use //cdn.jsdelivr.net/npm/docsify/lib/plugins/gtag.min.js

you can try https://cdn.jsdelivr.net/gh/sy-records/docsify-nightly@master/lib/plugins/gtag.min.js
