### ISSUE TITLE
CSS Style code improvements

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#2112]
This is a new issue to track the improvements to the CSS styling system. This will likely be a major version bump on its own eventually, but first we can see if there's a way we can deprecate existing style vars for a while before we remove them in a major bump.

- [ ] Prefix all Docsify CSS variables with `--docsify-`. For example, `--theme-color` should be `--docsify-theme-color`, or even better `--docsify-accent-color`.
- [ ] Deprecate old variables, but keep them around for back compat for a while.
  - We can, for example, map a new `--docsify-accent-color` variable to the existing `--theme-color` once we deprecate it, then eventually we remove `--theme-color` and use `--docsify-accent-color` directly.
  - We can write a script that checks style sheets for deprecated variables, and warns in console.
- [ ] Let's update styling code so that [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable) implementation becomes simpler, if possible. (cc @jhildenbiddle) 
- [ ] ...

**Comment by anniepauline** [comment]
I'd like to work on it.Is it up for grabs?
