### ISSUE TITLE
Sex

### ISSUE THREAD

**Issue by DJKStyles** [docsifyjs/docsify#2119]
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by trusktr** [comment]
Yes, but not here.
