### ISSUE TITLE
Support for sidebar items pointing to multiple different domains?

### ISSUE THREAD

**Issue by palypster** [docsifyjs/docsify#214]
I can see in the documentation that it's possible to set basePath to some URL (typically Github's repo). With this option I am able to load current version of my .md files directly from the repo. But what if I have several .md files in multiple repositories I want to point to? This does not work:
```
<!-- _navbar.md -->

- Getting started
  - [Introduction](README.md)
  - [Components](https://raw.githubusercontent.com/QingWei-Li/docsify/master/README.md)
```

**Comment by meganhkelley** [comment]
@palypster did you ever figure this out, or did docsify ever add support this functionality?

**Comment by palypster** [comment]
I don't know. I quit using docsify, sorry.
