### ISSUE TITLE
Docsify Can`t Load JavaScript And CSS Style Sheet in Chinese Mainland

### ISSUE THREAD

**Issue by AkarinLiu** [docsifyjs/docsify#2159]
## Bug Report
![image](https://github.com/docsifyjs/docsify/assets/58081491/1e229e4d-6203-44cc-957e-efd7aff8be2b)

#### Steps to reproduce
1. Access My Build Website
2. Discover Some Assets Can`t Load in Chinese Mainland
3. "Clash For Windows" Software at "Rule" mode Can Load it
#### What is current behaviour
Timeout, and Same as "Clash For Windows" Software at "Direct" mode 
#### What is the expected behaviour
Can 100% Access My Document Site.
#### Other relevant information
JS Deliver Is not reliable at Chinese Mainland Network, please to consider using [CDNJS](https://cdnjs.com) by Cloudflare, of Given user Choose CDNJS or JS Deliver at Docsify Cli.

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 11
- Node.js version: v16.20.1
- npm/yarn version: 9.8.1
- Browser version: 115.0.1901.188
- Docsify version: 4.x
- Docsify plugins: ![image](https://github.com/docsifyjs/docsify/assets/58081491/fb694ab2-dd61-47ef-b73f-2c0c2f4649c5)

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lively-grass-plpq5p?file=/index.html)

**Comment by sy-records** [comment]
Thank you for your feedback, but we are not responsible for our users' networks.

I think users can choose the CDN they want to use themselves, or save it locally.

For docsify-cli feature request, I think it's good that you can submit it to https://github.com/docsifyjs/docsify-cli/issues . If I have time, I will implement it.
