### ISSUE TITLE
我按照文档配置出现了好多的问题！（I have many problems according to the document configuration!）

### ISSUE THREAD

**Issue by triggergun** [docsifyjs/docsify#2172]
配置是没有问题。是环境问题吗。
我用的node版本是14.17.0。

The environment of node is 14.17.0

问题。（quesition）
1、loadNavbar设置为true，他在页面不显示。
2、显示的内容无法滚动，我加了个overflow：auto；后在pc有滚动，在移动端不滚的展示内容。

loadNavbar Don't display on page.
The displayed content cannot be scrolled.
I‘m after add overflow,don't showing on page.

[我的问题源码：](https://gitee.com/ground-gun/gunblog)

**Comment by Osman2726** [comment]
@$#@_&-!))/';?5_3$content/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app.md
