### ISSUE TITLE
Feature request: Improve Positioning of the Hamburger Menu on Mobile

### ISSUE THREAD

**Issue by RitaDee** [docsifyjs/docsify#2205]
#### Problem or desire

The hamburger menu is positioned at the bottom of the page in mobile view:

![44474F6F-69CA-4912-BE71-3BDFEE8EE256](https://github.com/open-sauced/intro/assets/106407013/7718508f-c994-4a57-9b77-fe9de6715578)

<img width="341" alt="image" src="https://github.com/docsifyjs/docsify/assets/106407013/de66fc72-ffd9-4ba8-8ff2-385fb481f2d4">

#### Steps to reproduce

1. Visit https://intro.opensauced.pizza/ on mobile.

#### Proposal

IMHO I suggest it should be fixed at the top. 

### Reasons:
- For easy navigation.
- For visibility(Newcomers might find it difficult to locate the hamburger menu as I did and this is because most people are used to top positioned menu).

#### Implementation

This request is generated from the issue: https://github.com/open-sauced/intro/issues/31

**Comment by Koooooo-7** [comment]
Hi @RitaDee , this is more like the personal style stuff here, I think we won't change the default behavior in docsify for now.
Maybe we could raise a config such as `sidebar position` [top, bottom, middle] or something in the furture.

And for the requirement you mentioned here, I think you can use this [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/#/) to achieve it, especially the [simple-dark](https://jhildenbiddle.github.io/docsify-themeable/#/themes?id=simple-dark) based on the style of ur neat site.

**Comment by jhildenbiddle** [comment]
This issue has been addressed by PR #2469. The changes will be available when Docsify v5 is released.

The new default sidebar position is in the middle of the left edge of the screen (red arrow). Docsify v5's new custom theme properties and optional class names make it easy to reposition the toggle (green arrows), change the toggle icon, change the colors, etc.

<img src="https://github.com/user-attachments/assets/316b1eff-10f6-4243-9b3d-ac7e8bb6e1dd" width="300">
