### ISSUE TITLE
switch from live-server to five-server

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#2218]
I've been having issues with `live-server` lately (in other projects): it is sometimes flaky, and sometimes the network connection is really slow, especially in **Windows PowerShell**. `live-server` hasn't been updated in a while, so it seems that something has changed in my system that somehow affects `live-server`.

There's a newer package called `five-server` (a **f**ork of l**ive-server**) that is a drop-in replacement for it, plus new features, and it has been working great without any issues.

**Comment by Koooooo-7** [comment]
Hi Joe,  you mean this one https://github.com/yandeu/five-server ?
It seems not very active for now. I suppose that we could hold migrate to it later when it is stable.

**Comment by jhildenbiddle** [comment]
My vote would be to replace live-server with [BrowserSync](https://browsersync.io) since we are already using it for our test environment. It supports all of the niceties of `live-server` and then some. It is also actively maintained.
