### ISSUE TITLE
Accessibility - hidden anchors are still tabbable

### ISSUE THREAD

**Issue by kburk1997** [docsifyjs/docsify#2225]
#### Steps to reproduce

1. Go to [develop preview](https://docsify-preview.vercel.app/#/)
2. Press Tab key to move to next focusable element on the page
3. Repeat step 2 until "Edit document" link is focused
#### Current behaviour
Sidebar items remain in the tab order regardless of whether the menu is open or closed.
Screen recording with keystrokes:

https://github.com/docsifyjs/docsify/assets/11298269/1431c518-df88-4776-8d2e-a56b553f583f

#### Expected behaviour
Hidden sidebar items are not tabbable when closed. 
Sidebar items are tabbable when the sidebar is open.

#### Other relevant information

- Docsify version: latest

- [x] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue): n/s

**Comment by jhildenbiddle** [comment]
Thanks for creating the issue, @kburk1997!

I've created a draft PR here: #2265. In that PR you will find a preview link which will allow you to review the changes:

![CleanShot 2023-10-17 at 08 59 27@2x](https://github.com/docsifyjs/docsify/assets/442527/7e4bf479-b02c-46c3-8e98-a99ffefa1ae5)

Before I mark this PR as ready for review by the maintainers, I would love to get your thoughts and/or feedback.

Thanks!
