### ISSUE TITLE
Can docsify set up lazy loading for article markdown files

### ISSUE THREAD

**Issue by javastacks** [docsifyjs/docsify#2236]
#### Problem or desire

I have thousands of markdown files, it will send thousands of request for all markdown files in _sidebar.md file when loading the _sidebar.md file, which leads to a slow response.

#### Proposal

Can docsify set up lazy loading for markdown links in the _sidebar.md file, so that markdown files are only requested when the link is clicked.

Or are there any alternative ways to disabled this feature?

#### Implementation

I have no idea, thanks.

**Comment by sy-records** [comment]
It also saves the index to the localStorage if you use search.

**Comment by sy-records** [comment]
If you don't need to search, you can use `routes`. see https://docsify.js.org/#/configuration?id=routes

```
        routes: {
            '/(.+)': function (route, matched, next) {
                fetch('https://example.com/' + route + '.md', {
                    headers: {
                    }
                })
                    .then(response => response.text())
                    .then(data => {
                        next(data);
                    })
                    .catch(function (err) {
                        next('!> Get content failed.');
                    });
            },
        },
```

**Comment by sy-records** [comment]
Don't add `.md` to _sidebar.md and it should work. I have a site that uses it that way.

```
  - Name
    - [Foo](foo)
    - [Bar](bar)
```

**Comment by sy-records** [comment]
I tested it using docsify's repo with no problems, please remove the search plugin.

> Btw, there is also no need to configure routes

```
- Getting started

  - [Quick start](quickstart)
  - [Writing more pages](more-pages)
  - [Custom navbar](custom-navbar)
  - [Cover page](cover)

- Customization

  - [Configuration](configuration)
  - [Themes](themes)
  - [List of Plugins](plugins)
  - [Write a Plugin](write-a-plugin)
  - [Markdown configuration](markdown)
  - [Language highlighting](language-highlight)
  - [Emoji](emoji)

- Guide

  - [Deploy](deploy)
  - [Helpers](helpers)
  - [Vue compatibility](vue)
  - [CDN](cdn)
  - [Offline Mode (PWA)](pwa)
  - [Embed Files](embed-files)

- [Awesome docsify](awesome)
- [Changelog](changelog)
```

**Comment by trusktr** [comment]
Downside of removing search plugin is visited pages will not be searchable.

Maybe we should add an option for search plugin to index only visited pages (not ideal, but maybe more desirable than nothing?).

Also in the future we will have a command line to generate search index ahead of time, instead of at runtime in the browser.
