### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by zjzjzjzj1874** [docsifyjs/docsify#2268]
大家好，我今天遇到一个问题，当我访问'https://my-domain.com/page',发生了301重定向，我的协议和端口都被修改成这样了：'http://my-domain.com:8080/page/'.添加'/'是我需要的，但是我要保证协议和端口不变化，要如何配置呢？

--------- 
Translate into English:
Hello everyone, I encountered a problem today when I visited ' https://my-domain.com/page A 301 redirect occurred, and my protocol and port have been modified as follows: http://my-domain.com:8080/page/ Adding '/' is what I need, but I need to ensure that the protocol and port remain unchanged. How do I configure it?

**Comment by sy-records** [comment]
This doesn't seem to be a docsify issue, depending on the web server you're using.
