### ISSUE TITLE
Feature: navigation keyboard bindings/shortcuts

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#2278]
## Feature request

Improve accessibility by implementing keyboard bindings/shortcuts for common navigation actions.

Linked PR: #2279

#### Proposal

Provide the following navigation keyboard bindings/shortcuts for all docsify sites by default:

1. Toggle the sidebar menu
2. Move focus on the main content area
3. Move focus to the search field (and toggle sidebar if necessary)

Because all three of the above shortcuts are associated with DOM elements, keyboard binding hints can be provided to the user by hovering (via `title` attribute) or focusing (via `aria-keyshortcuts` attribute) on each associated element (sidebar toggle button, the "Skip to main content" element from #2253, and the search input field).

#### Optional

Allow custom keyboard binding functions to be defined as part of the docsify configuration. Docsify will handle capturing these keyboard shortcuts and invoking the associated function.

#### Example Implementation

```js
window.$docsify = {
  keyBindings: {
    // Example: Docsify default shortcut
    'toggleSidebar': {
      binding: 'alt+t',
      label: 'Toggle sidebar menu',
      callback(e) {
          const toggleElm = document.querySelector('.sidebar-toggle');

          if (toggleElm) {
            toggleElm.click();
            toggleElm.focus();
          }
      },
    },
    // Example: Plugin custom shortcut
    'myPlugin': {
      binding: 'alt+ctrl+shift+meta+a',
      label: 'Do a plugin thing',
      callback(e) {
        // ...
      },
    },
  }
}
```

Disable key bindings:

```js
window.$docsify = {
  keyBindings: false,
}
```

#### Links

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-keyshortcuts

**Comment by trusktr** [comment]
I've implemented this recently in an app. Custom key bindings don't need to be Docsify specific, and it can be a standalone library.

Docsify could have its own bindings made with it, and we can turn it on/off, but if someone want their own bindings they just use the lib:

```js
import {Actions} from 'foo-actions-lib'

new Actions({
  target: document, // default
  actions: {
    // ... similar type of config object ...
  }
})
```

And *then* if users want to map actions to Docsify functions, they can call `docsifyInstance.openMenu()`, `closeMenu()`, etc

If we implement it that way, we could the decide if it is really worth adding a $docsify config for actions, which would itself just be a tiny plugin to pass it along to a `new Actions`.


---

Also I'd like to abstract Docsify's layout into templates that can be swapped out. Perhaps a totally different menu system in a new template would have its own key bindings, so this could be a feature specific to each eventual template, unless we restrict the template system to always accepting only content, sidebar, and menu replacements, then we control them all the same way.

```html
<docsify-app>
  <my-sidebar slot="sidebar"></my-sidebar>
  <my-body slot="content"></my-body>
  <!-- etc -->
</docsify-app>
```

Where each slotted element receives the content to render for each part of the site. Or fully replaced:

```html
<docsify-app replace="my-full-template"></docsify-app>
```

where it accepts a custom element to fully replace the template with, or something (just random ideas at this point, but the idea is making alternative Docsify themes possible (not just CSS themes, but alternative DOM too)).

Hard to tell exactly how both of these ideas play well together ATM.

---

Do you have examples of this in other doc sites?

**Comment by jhildenbiddle** [comment]
Appreciate the feedback, @trusktr. I'm not sure I'm following though. Hopefully what follows will help clarify...

Keyboard shortcuts improve accessibility for users navigating sites with a keyboard and/or assistive devices. Many popular websites and applications offer them:

- Facebook ([details](https://www.facebook.com/help/156151771119453))
- Twitter ([details](https://help.twitter.com/en/using-x/how-to-post))
- YouTube ([details](https://support.google.com/youtube/answer/7631406?hl=en))
- Jira ([details](https://www.facebook.com/help/156151771119453))
- Trello ([details](https://trello.com/shortcuts))
- GitHub ([details](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts))
- [Reddit](https://www.reddit.com) (press `?` for shortcut menu)

Other documentation generators like [GitBook](https://docs.gitbook.com), [Docusaurus](https://docusaurus.io/docs), and [Starlight](https://starlight.astro.build/getting-started/) offer a keyboard shortcut for the search field. These sites, like Docsify, would also benefit from additional shortcuts like the ones I've proposed above. Try navigating between pages on any of these sites using just the keyboard and this will quickly become apparent.

With that said, there are really two things to discuss for this feature request...

---

### 1. Should Docsify provide keyboard shortcuts for site visitors?

I believe the answer is "yes". I view this as a non-controversial feature that aligns with other accessibility-related work being done (#2253, #2254, #2264, #2265, #2269).

Users will need to be made aware of these shortcuts. I propose we accomplish this by:

- Adding the [`aria-keyshortcuts`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-keyshortcuts) attribute to appropriate elements
- Adding keyboard shortcut combinations to element `title` attributes (visible on hover)

---

### 2. Should Docsify provide the ability to easily create custom keyboard shortcuts?

This is where I believe further discussion is warranted.

My initial thought is that this would be useful mostly for plugin authors. Yes, plugin authors can implement keyboard shortcuts on their own already, but standardizing and simplifying how shortcuts are implemented and ensuring that Docsify knows about and handles them properly offers real-world advantages. For example:

- Simplified DX for plugin authors
- Less code coming over the wire, to maintain, and for plugin authors to write
- Reduced risk of implementation conflicts/issues from multiple plugins
- Improved UX by offering an auto-generated Reddit-style shortcut menu via `?` shortcut (possible because all shortcuts are handled by Docsify)

FWIW, Docusaurus has an [open RFC](https://github.com/facebook/docusaurus/issues/3020) for something similar. It hasn't seen much activity since 2021, but I wanted to share it to demonstrate that others have had similar ideas and believed it would be useful.

**Comment by paulhibbitts** [comment]
Thanks for the issue/ping @jhildenbiddle and sharing your thoughts @trusktr ! While I do not have any specific accessibility-focused feedback (I am learning more as I go...) the recent accessibility PR's of @jhildenbiddle have highlighted to me as well the importance of keyboard shortcuts in relation to making Docsify more accessible for everyone. Additional default keyboard shortcuts would be a valuable addition for me, esp. my audience of open educators/publishers.

**Comment by jhildenbiddle** [comment]
@vhscom --

The work has been completed but not yet released. You can review the feature via the docsify develop branch [preview](https://docsify-preview.vercel.app/preview/).
