### ISSUE TITLE
An exception occurs when Katex inline formula contains subscripts

### ISSUE THREAD

**Issue by LzcGeorge** [docsifyjs/docsify#2286]
My text is `字母：$a$  , $c$ 和 $n_0 $ , $n_0 +$`
But $n_0$ shows wrongly, Why is there an extra scroll wheel below this?

![](https://gcore.jsdelivr.net/gh/lzcgeorge/imagebed@main/20231021163955.png)

How to remove the roller below?
Thanks .

**Comment by Koooooo-7** [comment]
Hi @LzcGeorge , could you plz provide an reproduce sample on it ? 

FYI, I test it locally.
```md
# Test
My text is 字母：$a$  , $c$ 和 $n_0 $ , $n_0 +$
```

<img width="497" alt="image" src="https://github.com/docsifyjs/docsify/assets/33706142/d8872569-6448-4d20-95bd-dace214e57a5">

**Comment by LzcGeorge** [comment]
Hi @Koooooo-7,Thank you for your help.
I checked my JavaScript file again and found the source of my issue.

At fist，my js file like that
```
<script src="//cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css" />
<script src="//cdn.jsdelivr.net/npm/docsify-latex@0"></script>
```
Most of the cases are showing normal behavior, but there is an issue occurring like this.

Now ，I change it and it works！

```
<script src="//cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css" />
<script src="//cdn.jsdelivr.net/npm/marked@4"></script>

<!-- CDN files for docsify-katex -->
<script src="//cdn.jsdelivr.net/npm/docsify-katex@latest/dist/docsify-katex.js"></script>
```

Thanks!

**Comment by Koooooo-7** [comment]
no prob.
