### ISSUE TITLE
Feature: Change 'X' button style 

### ISSUE THREAD

**Issue by singodiyashubham87** [docsifyjs/docsify#2287]
#### Problem or desire

The size of the 'x' button near the search should have to be a little larger to be more consistent with the UI

#### Proposal

I will either scale it up a little bit or change the whole icon itself.

#### Implementation

To implement this, I'll change the styling of the button.

![image](https://github.com/open-sauced/intro/assets/93720428/d5c5e888-2c86-4de2-b02a-2e11bc72d34e)

**Comment by Koooooo-7** [comment]
Hi @singodiyashubham87 , It seems not our official style, do you use some theme or custom styles?
If you could provide a demo site/codebase would be better.

**Comment by jhildenbiddle** [comment]
This issue has been addressed by PR #2469. The changes will be available when Docsify v5 is released.

![CleanShot 2024-07-19 at 11 43 04@2x](https://github.com/user-attachments/assets/fed99bb8-f845-410a-a3d4-ac08698bd60c)
