### ISSUE TITLE
Husky no longer working after update back in April

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#2292]
Back in April we updated Husky from v3 to v8 due to Dependabot.

- #2029 

This broke our workflow: the git commit hook is no longer installed on a fresh clone with `npm install`, so we no longer run lint on commit.

Latest Husky requires manually installing hooks with `npx husky install`.

They recommend that the `prepare` script can be used to automate this for `npm install`. But then it runs at random other times like any time the package is being packed, f.e. during publish.

We can, however, make `npx husky install` be optional: the contributing guide can recommend it as a convenience for pre-pull-request time saving. I like making it opt-in, and those who don't want it can rely on pull request builds or running command manually. Wdyt?

**Comment by trusktr** [comment]
cc @Koooooo-7

**Comment by Koooooo-7** [comment]
Yea,  I have to say the `github actions` is the `final gateway` for lint check for now.
I gonna update the contributing guide on this.
And I will try to find a more convenient way in further instead of contributors notice the lint issue after creating PRs.

**Comment by Koooooo-7** [comment]
Put some docs for usage reminder.
[`migration from v4-`](https://typicode.github.io/husky/migrating-from-v4.html)
['.husky/pre-commit' hook not set as executable](https://github.com/typicode/husky/issues/1177)
