### ISSUE TITLE
[DOCS] Add a CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [docsifyjs/docsify#2293]
#### Problem or desire

The repository looks incomplete because of the missing CODE_OF_CONDUCT.md file to specify the rules and regulations to follow while contributing to the repository, I want to add that file to the repo.

#### Proposal

Add CODE_OF_CONDUCT file to the repository which guidelines.

Kindly assign me this issue.

**Comment by CBID2** [comment]
Can I be assigned to this @Koooooo-7? It’s be a month since this issue has been published.

**Comment by Koooooo-7** [comment]
Hi @singodiyashubham87 , @CBID2 .
TBH, I think this file is not necessary since we have the full sites/docs to guide how to use and contribute to docsify.
Thx for your mentions.

**Comment by paulhibbitts** [comment]
Thanks to @sy-records there is now a Code of Conduct in place for the entire Docsify project https://github.com/docsifyjs/.github/blob/main/CODE_OF_CONDUCT.md. Thank you @singodiyashubham87 @CBID2 for raising this issue!
