### ISSUE TITLE
markdown table 

### ISSUE THREAD

**Issue by wjzxc123** [docsifyjs/docsify#2301]
![image](https://github.com/docsifyjs/docsify/assets/32690579/16af131d-bd42-4894-83ce-60d19b572e5b)

![image](https://github.com/docsifyjs/docsify/assets/32690579/d4f0f046-ec75-4470-9b4d-6917879b45b8)

表格内会出现表头字段，为什么会这样？这是个bug吗

**Comment by sy-records** [comment]
Not reproducing your problem.

```
|| 字段 | 类型 | 长度 | test
----|----|----|----|---
1 | mode | int |  | 1
2 | http | array |  | 1
```

<img width="336" alt="image" src="https://github.com/docsifyjs/docsify/assets/33931153/0b95c7aa-9c61-4530-aa30-8f46005373d0">

----

To submit an issue, please use English and send the content in text, not images.

**Comment by wjzxc123** [comment]
> Not reproducing your problem.
> 
> ```
> || 字段 | 类型 | 长度 | test
> ----|----|----|----|---
> 1 | mode | int |  | 1
> 2 | http | array |  | 1
> ```
> 
> <img alt="image" width="336" src="https://user-images.githubusercontent.com/33931153/281599006-0b95c7aa-9c61-4530-aa30-8f46005373d0.png">
> To submit an issue, please use English and send the content in text, not images.


I have discovered that this issue arises when using **docsify-themeable**.

**Comment by sy-records** [comment]
cc @jhildenbiddle
