### ISSUE TITLE
Incorrect name and no state is defined for the ‘Hamburger’ menu button.

### ISSUE THREAD

**Issue by msftedad** [docsifyjs/docsify#2308]
#### Steps to reproduce

1. Open the URL: [PWABuilder - Packaging for the Google Play Store](https://docs.pwabuilder.com/#/builder/android) in browser.
2. Turn on the narrator through Ctrl+ Windows+ Enter key.
3. Navigate to the hamburger menu through tab key.
4. Observe the issue.

#### Current behaviour
Incorrect name and no state are defined for the ‘Hamburger’ menu button, Screen reader is only announcing as ‘Menu button.

**Attachments:**

<img width="957" alt="Incorrect name and no state is defined for the ‘Hamburger’ menu button (2)" src="https://github.com/docsifyjs/docsify/assets/93735775/777516e2-e7a2-4c04-9ebb-ab020966740a">

https://github.com/docsifyjs/docsify/assets/93735775/441887f2-5c74-48ad-80ce-8ad04e2971ed

#### Expected behaviour

Proper name and state should be defined for the ‘Hamburger’ menu button.Screen reader should announce as ‘Hamburger menu’ button 'collapsed’ when it is in collapsed state and expanded when it is in expanded state.

#### Other relevant information

- Docsify version: 4.4.4

- [ X] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue): NA

#### Please create a reproducible sandbox
(https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)](https://docs.pwabuilder.com/#/)

#### Mention the docsify version in which this bug was not present (if any)
NA

**Comment by paulhibbitts** [comment]
Thanks very much for reporting this issue @msftedad . Re: un-merged PR #2304 might it still be possible to consider the status 'collapsed' and 'expanded' to the aria-labels for the hamburger menu element @jhildenbiddle ? 

Perhaps another option instead of using a UI element name (which might not be familiar to all users) something more action-related like "Expand sidebar, button" and "collapse Sidebar, button" might be label options to consider?

**Comment by jhildenbiddle** [comment]
Fixed via #2254.

These updates will be available in the next release. Until then, you can verify the changes by visiting the [develop branch preview](https://docsify-preview.vercel.app/).
