### ISSUE TITLE
Google indexing issue

### ISSUE THREAD

**Issue by dobromir-hristov** [docsifyjs/docsify#231]
Hey is anyone else having google indexing issues? 
A library of mine, [palettify](https://dobromir-hristov.github.io/palettify/#/) is not crawled beyond the first page at all. Google page render just renders the upper top half of the page and thats it.

I tried with the new noty docs and its pretty much the same. 

I am not using the html5 history mode, but I could change if that was the problem, but I dont think so.

**Comment by fkorotkov** [comment]
Seems it's just a problem of how docsify renders stuff. I believe Google Crawler doesn't execute JS.

For example there is only [one Google Search result for docsify](https://www.google.com/search?q=site:docsify.js.org).

**Comment by jthegedus** [comment]
Has anyone determined if this is because of the `routerMode`?

**Comment by Chocobozzz** [comment]
(sorry for the message on this old issue, but this could help)

> Has anyone determined if this is because of the routerMode?

Yes it is. In the default router mode, google indexed only 1 page. With `routerMode: 'history'`, now Google indexes all our doc pages.

You can use this function in the `plugins` config to make a (little bit dirty) redirection from old URLs to new URLs:

```
        function (hook) {
          hook.doneEach(function() {
            const current = window.location.hash

            if (current.startsWith('#/')) {
              window.location.href = current.replace(/^#\//, '/')
            }
          })
        }
```

**Comment by ASaiAnudeep** [comment]
@Chocobozzz I have updated the routerMode to 'history' but google is still not able to index the site. I have also added the sitemap.xml. Still no luck.

**Docs**: https://pactumjs.github.io/
**Code**: https://github.com/pactumjs/pactumjs.github.io
