### ISSUE TITLE
Position error when returning to home page from navbar

### ISSUE THREAD

**Issue by sy-records** [docsifyjs/docsify#2319]
## Bug Report

Position error when returning to home page from navbar.

#### Steps to reproduce

![image](https://github.com/docsifyjs/docsify/assets/33931153/24855544-c470-4833-8810-b666c7732887)

![image](https://github.com/docsifyjs/docsify/assets/33931153/5e73c967-2787-4196-837f-a862cbab1223)

#### Current behaviour

The homepage is half displayed.

#### Expected behaviour

The homepage show all.

**Comment by jhildenbiddle** [comment]
Note: Occurs on the current develop branch [preview](https://docsify-preview.vercel.app/preview/), not on [docsify.js.org](https://docsify.js.org/).
