### ISSUE TITLE
在gitee上 点击目录上 跳转失败

### ISSUE THREAD

**Issue by 2579902254** [docsifyjs/docsify#2326]
## Bug Report

url：https://ma-xinhui.gitee.io/xlzl/#/Python/01.python%E5%9F%BA%E7%A1%80
![image](https://github.com/docsifyjs/docsify/assets/86905386/7fc1bea6-147a-4339-b0cc-a051d3b20461)

#### Steps to reproduce

1.进入首页
url：https://ma-xinhui.gitee.io/xlzl/#/
2.点击目录中[01.python基础]

#### Expected behaviour

gitee仓库地址：https://gitee.com/ma-xinhui/xlzl
配置文件在docs目录下

#### Other relevant information

- Docsify version:

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
联系 Gitee 技术支持吧，_sidebar.md 是200，Python 下是404。

<img width="1163" alt="image" src="https://github.com/docsifyjs/docsify/assets/33931153/35546770-408f-4a82-b1ac-2b33eb6d5cb3">
