### ISSUE TITLE
docsify search plugin could support excluding certain page

### ISSUE THREAD

**Issue by Koooooo-7** [docsifyjs/docsify#2328]
### Discussed in https://github.com/docsifyjs/docsify/discussions/2161

<div type='discussions-op-text'>

<sup>Originally posted by **michaelmartinth** August  4, 2023</sup>
Hi, I am wondering, is it possible to exclude certain pages from search results?
For example, I have changelog in my docsify, which is a requirement but not relevant for most reader.
Is it possible to 'blacklist' the changelog folder from search plugin?</div>

**Comment by vhscom** [comment]
Possible duplicate of #1809
