### ISSUE TITLE
Cannot preview permanent link

### ISSUE THREAD

**Issue by linrongbin16** [docsifyjs/docsify#2340]
#### Steps to reproduce

1. Copy a permanent link and paste to markdown docs.
2. Commit changes and Deploy to github pages.
3. Open the docs and see the permanent link.

For example, here's the commit:https://github.com/linrongbin16/commons.nvim/commit/fc783824ea34b0922fd9bb8a52535c49eb3685ab.

And github can preview the permanent link:

![Screenshot_2023-12-16-09-32-49-903_com android chrome-edit](https://github.com/docsifyjs/docsify/assets/6496887/0522ad9c-4ee2-4ddc-b755-d98d8968db05)

In the mean while, docsify cannot preview:

![Screenshot_2023-12-16-09-32-24-260_com android chrome-edit](https://github.com/docsifyjs/docsify/assets/6496887/4c2ea973-2689-40c3-8123-f84139167d08)

#### Current behaviour

See above example.

#### Expected behaviour

Also preview permanent link.

#### Other relevant information

- Docsify version: latest v4.x

- [x] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @linrongbin16 , the permanent link is not standard markdown syntax, github does the trick.
I post the code snippet here, it can not be render either.

## Functions

### `get_buf_option`

Get buffer option.

https://github.com/linrongbin16/commons.nvim/blob/487e197fe8ce9db28aec656df43df1c712710fac/lua/commons/buffers.lua#L3-L6

Parameters:

- `bufnr`: The buffer number.
- `name`: The option number.

**Comment by Koooooo-7** [comment]
Hi @linrongbin16 , If you do want import the `github permanent links` lines by urself, you may have a try on it. It is a little bit cumbersome tho.

- Define a placeholder/anchor as your custom `github permanent links` syntax in your md file.
```md
# MyContent

This is my markdown file.

=permanent-link(https://github.com/linrongbin16/commons.nvim/blob/487e197fe8ce9db28aec656df43df1c712710fac/lua/commons/buffers.lua#L14-L17)

> it should render above;
```

- Register a hook to parser the links and fetch the content from github.
```js
          function (hook, vm) {
            hook.beforeEach(html => {
             // find my own anchor
              var regex = /=permanent-link\((.*)\)/g;
              html = html.replace(regex, function (match, content) {
                 // get the permanent-link
                const api = content;
               // get which lines you want
                const tokens = content.split('#');
                const lines = tokens[1].replaceAll('L', '').split('-');
                const from_line = lines[0];
                const to_line = lines[1];
                // The Fetch the api to get the content and find the lines you want,  replace it now or later.
                fetch(api).then......
                // For more details, you could curl the https://github.com/linrongbin16/commons.nvim/blob/487e197fe8ce9db28aec656df43df1c712710fac/lua/commons/buffers.lua#L14-L17
                // In the $payload.blob.rawLines to get those lines you want and concat them
                return 'return the custom markdown code block with what you want to repalce the =permanent-link(...) stuff';
              });
              return html
            }

```

**Comment by linrongbin16** [comment]
really really thanks for your sharing!

**Comment by linrongbin16** [comment]
hi @Koooooo-7 , I had tried this solution, I have 1 more question. I need to first `fetch` the github file content, render the part of the source code into the html.

Now in the code snippet:

```javascript
    plugins: [
        function (hook, vm) {
            hook.beforeEach(function (html) {
              // =permanent-link
              var regex = /=permanent-link\((.*)\)/g;
              html = html.replace(regex, function (match, content) {
                // Get the permanent-link
                const api = content;
                // Get which lines you want
                const tokens = content.split("#");
                const lines = tokens[1].replaceAll("L", "").split("-");
                const from_line = lines[0];
                const to_line = lines[1];
                const raw = tokens[0].replaceAll(
                  "https://github.com/linrongbin16/commons.nvim/blob",
                  "https://raw.githubusercontent.com/linrongbin16/commons.nvim",
                );
                fetch(raw)
                  .then((response) => {
                    console.log("response:");
                    console.log(response);
                    return response;
                  })
                  .catch((err) => console.log(err));
                // In the $payload.blob.rawLines to get those lines you want and concat them
                return "return the custom markdown code block with what you want to repalce the =permanent-link(...) stuff";
              });
          });
       },
    ]
```

It seems the `fetch` operation is async, so in the returned html content, I cannot use the fetched response body?

**Comment by Koooooo-7** [comment]
> hi @Koooooo-7 , I had tried this solution, I have 1 more question. I need to first `fetch` the github file content, render the part of the source code into the html.
> It seems the `fetch` operation is async, so in the returned html content, I cannot use the fetched response body?

Hi @linrongbin16 , yes, the async way needs the hook with `next`, see [beforeach with async task](https://docsify.js.org/#/write-a-plugin?id=beforeeach).
So, we could do it like this.
```js
            hook.beforeEach((html, next) => {
              // collect all the match tasks
              const tasks = [];
              var regex = /=permanent-link\((.*)\)/g;
              html.replace(regex, function (match, content) {
                const api = content;
                const tokens = content.split('#');
                const lines = tokens[1].replaceAll('L', '').split('-');
                const from_line = lines[0];
                const to_line = lines[1];
                
                // fetch content
                const task = fetch(api)
                  .then(resp => resp.json())
                  .then(data => {
                    // ... process with data      
                    html = html.replace(match, data);
                  });

                tasks.push(task);
              });
             
             // all tasks done and return  
              Promise.all(tasks).then(finish => {
                next(html);
              });
            });
```

**Comment by linrongbin16** [comment]
thank you! @Koooooo-7
