### ISSUE TITLE
Publish to GitHub page， sidebar disappear

### ISSUE THREAD

**Issue by jazzii36** [docsifyjs/docsify#2357]
Publish to GitHub page， sidebar disappear
![image](https://github.com/docsifyjs/docsify/assets/35281744/4e0f4f87-12fc-4218-ad9a-fa6f93bda931)
![image](https://github.com/docsifyjs/docsify/assets/35281744/18ae59f3-6035-4a82-ac53-714d380ca6f9)

**Comment by sy-records** [comment]
you missing `.nojekyll`.

see https://docsify.js.org/#/custom-navbar
