### ISSUE TITLE
English quotes become Chinese quotes

### ISSUE THREAD

**Issue by kbmts** [docsifyjs/docsify#2360]
There are two bugs

1. English quotes become Chinese quotes. e.g.   `grep 'keyword'` become `grep ‘keyword’`
2. Two horizontal bars become one. e.g. `--exclude` become `–exclude`

Tried setting `smartypants` to `false` but it doesn't work.

How to fix it or how to change the default markdown parser?

**Comment by Koooooo-7** [comment]
Hi @kbmts , could you provide a reproduce？
It sounds weird.

**Comment by trusktr** [comment]
Markdown does what it does, not sure how to avoid. Do you add plugins? Can't see your issue directly. Can you link to an example?

If you want to show pieces of code, use back ticks. For example,

```md
Provide some `--option` to enable some feature. Internal code receives the string `'foo'`.
```

The output looks like this:

Provide some `--option` to enable some feature. Internal code receives the string `'foo'`.

**Comment by kbmts** [comment]
[test page](https://kbmts.github.io/docsify-test/#/)
@Koooooo-7 @trusktr

**Comment by Koooooo-7** [comment]
Hi, it seems the `docsify-themeable`  plugin styling issue.
```
<script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/js/docsify-themeable.min.js"></script>
```

**Comment by trusktr** [comment]
@kbmts There's something in the code (not CSS style) that is generating the character.

Here is the source markdown file:

https://kbmts.github.io/docsify-test/README.md

```md
# Docsify Test

## content1

ps -ef | grep 'web'

## content2

du -h --max-depth
```


A simple solution to this @kbmts is to wrap the code with backticks symbols (``` ` ```). Change the markdown content to the following:


```md
# Docsify Test

## content1

`ps -ef | grep 'web'`

## content2

`du -h --max-depth`
```

Here is a sample output:

> # Docsify Test
> 
> ## content1
> 
> `ps -ef | grep 'web'`
> 
> ## content2
> 
> `du -h --max-depth`

If you do this, then the normal text will have nicer looking quotes, but the inline code will not be transformed.

Also curious, if you remove docsify-themeable.min.js, does it stop transforming the quotes?

**Comment by kbmts** [comment]
@trusktr @Koooooo-7 Thank you very much. It's the docsify-themeable js issue!

**Comment by trusktr** [comment]
@jhildenbiddle does docsify-themeable.js change the quotes? If so, does it have a config option?

re-opening to track the quote issue (but feel free to unsubscribeif needed @kbmts).

**Comment by jhildenbiddle** [comment]
@trusktr --

I don't believe it does, but I will verify and report back.

**Comment by jhildenbiddle** [comment]
@kbmts @trusktr --

Bug confirmed and fixed. 

From [this](https://github.com/jhildenbiddle/docsify-themeable/issues/83#issuecomment-1899797992) comment: 

> It turns out the docsify-themeable JS was setting the markdown processor's `smartypants` option to `true`. Enabling this option "turns plain ASCII punctuation characters into "smart" typographic punctuation HTML entities" according to the [SmartyPants](https://github.com/othree/smartypants.js) project description. Mystery solved.
>
> I've made the necessary change on the [dev](https://github.com/jhildenbiddle/docsify-themeable) branch. I will publish an updated version when the next version of Docsify is released. That will hopefully happen in the next few weeks. In the meantime, you have two options:
> 
> 1. Wrap affected text in backticks (e,.g. `ps -ef | grep 'web'`) as @trusktr recommended [here](https://github.com/docsifyjs/docsify/issues/2360#issuecomment-1899152374).
> 2. [Download](https://docsify-themeable-preview.vercel.app/dist/js/docsify-themeable.min.js) and locally host the current preview build of `docsify-themeable.min.js` which contains the fix.
>
> Thanks!

**Comment by trusktr** [comment]
Nice!
