### ISSUE TITLE
image url begin with "/" should be AbsolutePath，not RelativePath

### ISSUE THREAD

**Issue by poerlang** [docsifyjs/docsify#2369]
#### Steps to reproduce

add a md file in a sub1 dir  `/docs/sub1/test.md`

add a img.png in `/docs/images`

add a imgLink in sub1/test.md:
`![](/images/img.png)`

#### Current behaviour

docsify render the image url to :

`/./sub1/images/img.png`

#### Expected behaviour

docsify should render the image url to :

`/images/img.png`

- Docsify version:

- [x ] Bug still occurs when all/other plugins are disabled?

#### Please create a reproducible sandbox

[reproducible  sandbox](https://codesandbox.io/p/sandbox/serverless-cookies-dxyf7t?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls5gtuki00063j6fe2bju6bc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls5gtukh00023j6frfliyl0b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls5gtukh00033j6fzcvmjaeo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls5gtukh00053j6fiz3pmt6m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B67.38223285429069%252C32.61776714570931%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls5gtukh00023j6frfliyl0b%2522%253A%257B%2522id%2522%253A%2522cls5gtukh00023j6frfliyl0b%2522%252C%2522activeTabId%2522%253A%2522cls5hde8m00463j6fofjtnzif%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsub1%252Ftest.md%2522%252C%2522id%2522%253A%2522cls5hde8m00463j6fofjtnzif%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cls5gtukh00053j6fiz3pmt6m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls5gtukh00043j6ftb8sud2m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2523%252F.%252Fsub1%252Ftest%2522%257D%255D%252C%2522id%2522%253A%2522cls5gtukh00053j6fiz3pmt6m%2522%252C%2522activeTabId%2522%253A%2522cls5gtukh00043j6ftb8sud2m%2522%257D%252C%2522cls5gtukh00033j6fzcvmjaeo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls5gtukh00033j6fzcvmjaeo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by poerlang** [comment]
the regular expression in `isAbsolutePath ` function only considers the cases of` http:// `or `https://`, but does not take into account URLs that start with `/`
```javascript
var isAbsolutePath = cached(function (path) {
    return /(:|(\/{2}))/g.test(path);
  });
```

**Comment by Koooooo-7** [comment]
Hi @poerlang , thx for your report!
We already  raised  this issue in  #1891, we still discuss on how to refactor its behavior and keep the things work more as expectation.

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
