### ISSUE TITLE
After invoking 'QuickStart' link from the left pane, the focus is getting lost.

### ISSUE THREAD

**Issue by msftedad** [docsifyjs/docsify#2411]
#### Steps to reproduce

1. Open [Writing more pages (docsify.js.org)](https://docsify.js.org/#/more-pages) in edge browser.
2. Navigate and invoke any links from the left pane ex: quickstart.
3. Now observe after clicking the left pane link focus lost observed.

#### Current behaviour

After invoking 'QuickStart' link from the left pane, the focus is getting lost.
[docsify--focus lost issue (1).webm](https://github.com/docsifyjs/docsify/assets/93735775/8e28f6ca-ccda-4827-994d-969b606e9125)

#### Expected behaviour

 After invoking 'QuickStart' link from the left pane, the focus should be land on the first interactive element in the opened pane.

#### Other relevant information

- Docsify version: 4.13.1

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by paulhibbitts** [comment]
Thanks very much @msftedad for reporting this issue. Thanks to the work of @jhildenbiddle there are some substantial accessibility improvements queued up for the next major release of Docsify (v5). Could you please try the preview release (https://docsify-preview-1f5eqpr0c-docsifyjs.vercel.app/preview/#/) and report back if this issue is still present? Thank you!

**Comment by msftedad** [comment]
Hi @paulhibbitts , This issue is not reproducible on the provided preview release instance. Thanks

**Comment by paulhibbitts** [comment]
Thanks for the follow-up @msftedad.

**Comment by msftedad** [comment]
Hi @paulhibbitts , This issue is fixed and we have closed our ticket.Thanks
