### ISSUE TITLE
missed to copy files in docker image when building Dockerfile

### ISSUE THREAD

**Issue by joker7blue** [docsifyjs/docsify#2412]
## Bug Report
missing `COPY .  .` in docker file

#### Steps to reproduce
- Go to https://docsify.js.org/#/deploy
- Scroll docker to docker part (Create Dockerfile)
- Copy the suggested docsify Dockerfile
- Go to yor docsify project,  and paste what you copied from docsify website into your project

- have a docker installed to you machine
- have docsify installed 
- have a docsify project

#### Current behaviour
The files are not copied to the docker image when building docker file, since we missed to  `COPY . .`

#### Expected behaviour

The docsify project should run as expected after building from docker

#### Other relevant information

- Docsify version: latest

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
Hi @joker7blue , it doesn't copy it into the Dockerfile, it mounts the files as volume instead. Hence, you can sync the live changes on time.
```
docker run -itp 3000:3000 --name=docsify -v $(pwd):/docs docsify/demo
```

If you wanna deploy your site via docker, either you put all your things inside the Docker image or mount it on runtime, thats both okay.

**Comment by joker7blue** [comment]
oh ok, Thanks for the explanation @Koooooo-7 👍🏽
