### ISSUE TITLE
Embedding a file in a sidebar is invalid

### ISSUE THREAD

**Issue by gyjcode** [docsifyjs/docsify#2423]
#### Steps to reproduce

[](./html+css/README.md ':include :type=markdown')
https://docsify.js.org/#/embed-files

#### Current behaviour

![image](https://github.com/docsifyjs/docsify/assets/45870098/1a7d3f0e-2c03-41a9-a213-1349c1efb330)

#### Other relevant information

- Docsify version:

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Thanks for your feedback.

Sidebar embedding is not supported.
