### ISSUE TITLE
Second-level table UI 

### ISSUE THREAD

**Issue by lowsury** [docsifyjs/docsify#2424]
Sample effect：

![WechatIMG24](https://github.com/docsifyjs/docsify/assets/7733424/0cdd8cd8-551e-428e-8443-15d9cfa4cd2a)

link Second-level table UI #2362

**Comment by sy-records** [comment]
Please provide the relevant reproduction environment.

**Comment by lowsury** [comment]
like these：
1.https://pay.weixin.qq.com/docs/merchant/apis/jsapi-payment/direct-jsons/jsapi-prepay.html
![WX20240508-103711@2x](https://github.com/docsifyjs/docsify/assets/7733424/362055d5-0914-4732-9b54-ab60ccd52963)

2.https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1
![WX20240508-104044@2x](https://github.com/docsifyjs/docsify/assets/7733424/1bdef606-148c-435a-8c44-b7afd270b2aa)

**Comment by sy-records** [comment]
Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

----

Please adhere to our community specifications and follow the issue template for creating issues, otherwise your issue may not be resolved.

**Comment by lowsury** [comment]
Heart tired, if I have achieved no reaction, I hope the original team to develop such a plug-in, not to submit their own plug-in

**Comment by sy-records** [comment]
I suggest you write a full feature request instead of putting up a few screenshots.

**Comment by lowsury** [comment]
this site use docsify. our own docs .

[https://developer-hubble-prod.sandload.com/#/ProjectDocs/business/applet/member/mem/等级权益信息](https://developer-hubble-prod.sandload.com/#/ProjectDocs/business/applet/member/mem/%E7%AD%89%E7%BA%A7%E6%9D%83%E7%9B%8A%E4%BF%A1%E6%81%AF)
