### ISSUE TITLE
Reset .markdown-section max-width to 800px

### ISSUE THREAD

**Issue by cippaciong** [docsifyjs/docsify#2429]
## Feature request
Reset .`markdown-section` `max-width` to `800px` or a similar value

#### Problem or desire
Docsify used to limit articles `max-width` to `800px` but this was changed to `80%` in #1017, claiming that such value would look better on wider screens.

As already mentioned by @jhildenbiddle in [a comment](https://github.com/docsifyjs/docsify/pull/1017#issuecomment-660260130) to that PR, I think this was a mistake since that would negatively affect the readability of the content.

IMO that change lead to two regressions:
- As said, readability becomes much harder on wider screens because line length is definitely too long
- Apparently readability was negatively affected also on smaller screens (e.g. mobile devices) since `80%` would introduce unwanted margins in that scenario. See for example [this comment](https://github.com/docsifyjs/docsify/pull/1017#issuecomment-654242844) and #1273

#### Proposal
Restore [.markdown-section max-width](https://github.com/docsifyjs/docsify/blob/0070e26da5f97204d1dbe2c47d3eaab7714a7137/src/themes/basic/_layout.styl#L363) to `800px` or a similar value.

#### Implementation
I'm not an expert, but I should manage to submit a PR if maintainers consider this change acceptable

**Comment by jhildenbiddle** [comment]
Thanks for filing the issue, @cippaciong.

We can make this fix and accommodate those who favor longer line lengths by doing the following:

1. Set the default line length (or "measure") of the markdown area to a font-size relative value that strikes a balance between readability best practices (no more than 80 characters) and aesthetics. After doing a bit of research, this looks to be between 80-95 characters per line which results in a markdown container width of roughly 700px +/- 20px.
2. Set the default line length (or "measure") of the markdown area to be roughly equivalent to the maximum recommended length of 80 characters. This is slightly larger than the recommendation of 45-75 characters I [previously shared](https://github.com/docsifyjs/docsify/pull/1017#issuecomment-660260130), but "no more than 80 characters" is also a common recommendation. If the result to too narrow visually, set the default line length to a value that strikes a balance between readability and aesthetics, with a goal of staying as close to the 80 character limit as possible.
3. Allow the markdown container's width to be configurable by site maintainers. This allows sites maintainers and theme authors using a different font to adjust the maximum width as needed to adhere to the "no more than 80 character" line length recommendation.

Inevitably, some people will feel that the new markdown container width "feels" too small on wide screens. The criticism isn't necessarily wrong. All of the Docsify alternatives I tested had line lengths greater than 80 (see below). Every one of those alternatives offers both left and right sidebars which help fill the horizontal space.

There are a few additional things we can do to try and reduce (but not eliminate) these concerns:

- Increase the default font size in Docsify's default themes to 16px. Larger text requires a wider markdown container to fit ~80 characters per line. Consider how increasing the font size effects the markdown container size when using Source Sans Pro (the web font used in Docsify's `vue.css` theme) with an 80 character line length:

  **Source Sans Pro (used in vue.css)**

  - 80 characters @ 16px = 550px container
  - 80 characters @ 15px = 515px container
  - 80 characters @ 14px = 470px container

- Consider alternative fonts that are more visually appealing at the desired line length. Consider how switching to San Francisco (the default sans-serif font on macOS) effects the markdown container size with an 80 character line length:

  **San Francisco (macOS)**

  - 80 characters @ 16px = 590px container
  - 80 characters @ 15px = 550px container
  - 80 characters @ 14px = 520px container

For comparison, here are the default line length, font size, and content container width values from a few Docsify alternatives:

- **Docusaurus**: 129 characters @ 16px = 958px
- **GitBook**: 109 characters @ 16px = 768px
- **Starlight**: 94 characters @ 16px = 720px
- **VitePress**: 90 characters @ 16px =  688px

For reference, here are the line lengths using Docsify with the `vue.css` theme and the previous max-width value of `800px`:

**Source Sans Pro (used in vue.css)**

- 16px = 117 characters
- 15px = 125 characters
- 14px = 133 characters

Switch to San Francisco on macOS produces the following results:

**San Francisco (macOS)**

- 16px = 110 characters
- 15px = 115 characters
- 14px = 124 characters

**Comment by paulhibbitts** [comment]
Thanks @cippaciong for identifying this issue and @jhildenbiddle for the detailed analysis and possible options etc.

In addition to numerical line lengths I think we could consider a few other aspects as well. For example, many folks have grown accustomed to the information density of the current 80% of screen width currently in Docsify (and possibly manually adjust their Browser windows to their liking). In addition, with digital text there are also other aspects coming into play such as the need to scroll to read and how much scrolling is involved etc. 

Here is a helpful article that highlights these additional aspects for reference:
https://www.roboleary.net/webdev/2023/03/10/ideal-line-length-digital-text.html

I don't think there is an ideal answer to a revised Markdown section width for Docsify, and the current 80% of screen has a lot of readability issues. 800px width may not be ideal either, but given the display of digital text and related aspects, somewhere around there some good candidates might still exist.

**Comment by jhildenbiddle** [comment]
This issue has been addressed by PR #2469. The changes will be available when Docsify v5 is released.

Once v5 is release, this issue can be resolved by modifying the following theme property:

```css
:root {
  --content-max-width: 72ch;
}
```
