### ISSUE TITLE
Search results are not announced in type doc search edit field.

### ISSUE THREAD

**Issue by msftedad** [docsifyjs/docsify#2435]
#### Environment (OS, Application, Versions)
OS: Windows 11
OS version: 23H2 ((OS Build 26052.1000)
Edge Version: 123.0.2380.1 (Official build) stable app, dev channel (64-bit)

#### Steps to reproduce
1. Open https://typedoc.org/api/ in edge browser.
2. Navigate to type doc search edit field present in the top right of the page and invoke it.
3. In search edit field enter some text and observe narrator announcement whether the search results are announced or not!

#### Current behaviour
while entering text in the search field narrator not announcing the displaying results.

#### Expected behaviour
while entering text in the search field narrator should announce the displaying results.

#### Other relevant information

- Docsify version: v0.25.13

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
Thank you for your feedback.

However, it appears that the document is using something other than docsify.
