### ISSUE TITLE
Removal of flags for language choice drop-down

### ISSUE THREAD

**Issue by paulhibbitts** [docsifyjs/docsify#2458]
#### Problem or desire
Country specific flags should not be associated with language choices, and doing so can be seen as culturally insensitive as flags represent countries, not languages.

#### Proposal
Remove the display of flags by each language choice if a Translations menu is present. For example, as seen with Microsoft's Docsify-built course 'Language' menu on Generative AI: https://microsoft.github.io/generative-ai-for-beginners

#### Implementation
List of languages without flags, or perhaps with the use language codes (e.g., "EN" for English) before each language choice.

**Comment by Koooooo-7** [comment]
Hi @paulhibbitts good propose.
I think when the transaction settle down(which langs we pick to remain), we could do this together that we remove the front flag of the langs menu.

**Comment by Koooooo-7** [comment]
link #2432

**Comment by paulhibbitts** [comment]
Thanks very much for considering this FR and linking it to the issue @Koooooo-7 👍🏻

**Comment by akshaybhinge19** [comment]
Hi @paulhibbitts @Koooooo-7  I've just opened a PR https://github.com/docsifyjs/docsify/pull/2468
