### ISSUE TITLE
[BUG] Coverpage Backgrounds - Image not shown.

### ISSUE THREAD

**Issue by aftwro** [docsifyjs/docsify#2491]
#### Steps to reproduce

1. Open `_coverpage.md`
2. Put your Coverpage Image in the directory you want
3. Put `![](/_assets/insert image file path here)` at the end of your `_coverpage.md` 
4. Commit, deploy, and you'll see that nothing changed.

#### Current behaviour

Cover page image is not being displayed in the background. It is only displaying the randomized color, rather than an image.

#### Expected behaviour

Background of the coverpage is supposed to become an image, instead of a color.

#### Other relevant information

- Docsify version: Latest

- [✔] Bug still occurs when all/other plugins are disabled?

#### Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

[Plugin list](https://github.com/aftwro/Knowledgebase/blob/e8a4c271badaa363151a989d65997900762cfbcf/index.html#L60
)

#### System:

- Your OS: Windows 10 22H2 
- Node.js version: Unavailable - Github Pages
- npm/yarn version: Unavailable - Github Pages
- Browser version: [https://github.com/Alex313031/thorium/releases/tag/M126.0.6478.231](Thorium Browser) `M126.0.6478.231 AVX2  60th Release`  

#### Please create a reproducible sandbox

(Unable, Apologies..)

#### Mention the docsify version in which this bug was not present (if any)

Latest.

#### Additional Information?

Please take a look at my repository, I might have a misconfiguration issue, but I really don't think so, I mostly need advice on what to do ***unless this is a bug.***

I have developer mode on (Caching off) in the cloudflare dashboard, changes are instantly shown after Github deploys the page.

Here's my `_coverpage.md` file for reference.

```md
# aftwr

> A person who you really don't know.

- Servers Administrator
- Breaks computers
- Studies electrical engineering

[Click me!](#howdy-there-🤠)

![](./_assets/coverpage_bg.webp)
```

[Here's a link to my repository.](https://github.com/aftwro/Knowledgebase/)

**Comment by paulhibbitts** [comment]
Answered on Discord #help channel.
