### ISSUE TITLE
Does the sidebar not support emoji?

### ISSUE THREAD

**Issue by CMRdev** [docsifyjs/docsify#2494]
#### Other relevant information

- Docsify version:

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment]
yep, it supports the emoji, please fill the template to better describe your issue.
