### ISSUE TITLE
建议支持不同目录可以有不同的配置

### ISSUE THREAD

**Issue by strongdevx** [docsifyjs/docsify#251]
类似每个目录可以有单独的_sidebar.md和_navbar.md。
我目前的应用可能需要根据不同的文档，maxLevel需要不一样。是否能考虑支持。非常感谢。

**Comment by QingWei-Li** [comment]
每个目录下放个 inedx.html 应该可以，跳转过去的路径用绝对路径

**Comment by strongdevx** [comment]
@QingWei-Li 试了在目录下放置一个index.html，但显示一直显示Loading...

**Comment by timaschew** [comment]
Please use English language.
