### ISSUE TITLE
Navigation Bar Not Loading in Subfolder

### ISSUE THREAD

**Issue by MJ-Zeng** [docsifyjs/docsify#2512]
## Issue Description:
When accessing the ai/machine-learning subfolder, the sidebar file is not being loaded correctly. The console logs an error: GET http://localhost:3000/ai/machine-learning/_sidebar.md 404 (Not Found).

Steps to Reproduce:
Navigate to http://localhost:3000/ai/machine-learning/.
Observe that the sidebar is not displayed.
Check the browser console for the 404 error.
### File Structure:
深色版本
.
├── _sidebar.md
├── _navbar.md
├── index.html
├── ai
│   └── machine-learning
│       ├── _sidebar.md
│       ├── 1-Model-Assessment.md
│       ├── 2-Matrix-Differentiation.md
│       ├── 3-Linear-Regression.md
│       └── 4-KNN.md
└── ...

### index.html File Content:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Code Wiki</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
      name: 'Code Wiki',
      repo: '',
      loadSidebar: true,
      subMaxLevel: 3,
      loadNavbar: true,
      navbar: '_navbar.md',
    };
  </script>
  <!-- Docsify v4 -->
  <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
</body>
</html>
```
### _navbar.md File Content:

- 🏠 [Code Wiki](/)
- 🛠️ [Basic Skills](/basic-skills/)
  -  [Markdown](/basic-skills/markdown/)
  -  [LaTeX](/basic-skills/latex/)
  -  [Git](/basic-skills/git)
- 💻 [Computer Basics](/computer-basics)
  -  [Algorithms](/computer-basics/algorithms)
  -  [Computer Networks](/computer-basics/computer-networks)
  -  [Linux OS](/computer-basics/linux-os)
- 📝 [Programming Languages](/programming-languages)
  -  [Python](/programming-languages/python)
  -  [Java](/programming-languages/java)
- 🛫 [Backend](/backend)
- 🤖 [Hardware](/hardware)
- 🧠 [Artificial Intelligence](/ai)
  -  [Machine Learning](/ai/machine-learning/)
  -  [Deep Learning](/ai/deep-learning)
  -  [Reinforcement Learning](/ai/reinforcement-learning)
- 🏆 [Contests](/contests)
  -  [ACM Programming](/contests/acm-programming)
  -  [Robotics](/contests/robotics)
  -  [App Development](/contests/app-development)
  -  [Cybersecurity](/contests/cybersecurity)
  -  [Big Data](/contests/big-data)
- 📚 [Reading](/reading)

###  ai/machine-learning/_sidebar.md File Content:
Markdown

- [Model Assessment](./1-Model-Assessment.md)
- [Matrix Differentiation](./2-Matrix-Differentiation.md)
- [Linear Regression](./3-Linear-Regression.md)
- [KNN](./4-KNN.md)

### Additional Information:
Docsify Version: 4
Browser: [Specify your browser and version]
Operating System: [Specify your operating system]

**Comment by sy-records** [comment]
There is no content in your file, add it and you can access it normally. https://github.com/MJ-Zeng/Code-Wiki/blob/main/docs/ai/machine-learning/README.md

<img width="628" alt="image" src="https://github.com/user-attachments/assets/7bfcd0bd-5623-4276-a40f-6cb0d62f03a1">
