### ISSUE TITLE
导航栏的子菜单选中时，如何让主菜单也有选中的效果？

### ISSUE THREAD

**Issue by strongdevx** [docsifyjs/docsify#252]
我的导航栏菜单下有多个子菜单，希望选择子菜单后，主菜单也有选中效果，

![image](https://user-images.githubusercontent.com/29698176/30266538-4636d638-9712-11e7-92e6-b45d7dc23126.png)

我的子菜单是单独的md文档。

**Comment by timaschew** [comment]
Please use English language.
