### ISSUE TITLE
get auth from  3rd party identity provider by vim _sidebar.md

### ISSUE THREAD

**Issue by xuanjinnan** [docsifyjs/docsify#2520]
## Feature request
  vue code work at _sidebar.md
#### Problem or desire

i want to auth the sidebar
redirect to docsify url like this:
```url
 http://localhost:4000/#/?token=EESDCCSSDA.AEEEXW.EEEEE
```
index.html
```html
<script>
    window.$docsify = {
      name: '',
      repo: '',
      loadSidebar: true,
      requestHeaders: {
        'x-token': 'xxx',
      },
        vueGlobalOptions: {
          data() {
            return {
              ],
              myRouter: []
            };
          },
          created() {
            fetch('http://localhost:8080/getRouterByToken?token=' + window.location.hash.substr(window.location.hash.search('=')+1))
              .then(response => response.json())
              .then(data => {
                this.myRouter = data
                console.log(this.myRouter,'this.myRouter')
              })
              .catch(err => console.log(err));
          }
```
my _sidebar.md
```markdown
{{ myRouter[0]}} <br> 
{{ myRouter[1]}} <br>
{{ myRouter[2]}} <br>
{{ myRouter[3]}} <br>

* [home](/)
* [guide](/guide.md " guide title")

```
but the display is :(
![image](https://github.com/user-attachments/assets/d6fd1308-dc29-4a75-a5a3-d077d0cca5f6)
it not work at ```_sidebar.md``` ,neithor at normal .md file

#### Proposal
maybe i take the wrong way use docsify,but my proposal is ```support auth the files```

#### Implementation

i think docsify's implement is ```html build by .md``` add ```html build by vue``` ,and display the ```total html```

can we change the order : ```mixed vue and .md to prue .md``` then ```pure md to html``` :)

i know the ```vue to .md``` is hard , i dont know how to implement ,sorry.

i'm a backend coder ,just want the request like a baby ,xd.

**Comment by sy-records** [comment]
The content should support loading remote files, but _sidebar.md doesn't, and you can generate it in some other way than loading it on access.

**Comment by trusktr** [comment]
@jhildenbiddle might have a hunch as to if Vue interpolation should work there. Seems like it should, for global Vue components. In theory it shouldn't be very difficult to apply it to sidebar in Docsify.

As a workaround you can use JavaScript to modify the sidebar in a custom way. Do it in a Docsify plugin:

https://docsify.js.org/#/write-a-plugin

Perhaps you'll want to do it in `hook.ready`:

https://docsify.js.org/#/write-a-plugin?id=ready
