### ISSUE TITLE
用 katex /sqrt 在 markdown list 語法中會顯示異常

### ISSUE THREAD

**Issue by tw-edu-csu-90618137** [docsifyjs/docsify#263]
我按照 #96 插入 katex，然後在 markdown list 語法中使用/sqrt，例如:
```
- $$\sqrt{27} \times \sqrt[3]{3}$$
``` 
產生出來的頁面會顯示異常：
![Imgur](https://i.imgur.com/uiihJAV.png)

不清楚是katex的問題還是docsify的問題，在此發問。

環境：
katex version : 0.8.3
docsify-cli version : 4.0.10

**Comment by upupming** [comment]
Hi, you can use https://github.com/upupming/docsify-katex now!
