### ISSUE TITLE
[Additional Feature Requests]

### ISSUE THREAD

**Issue by aslamabbas** [docsifyjs/docsify#264]
Thanks for making such an awesome tool. Have a few requests.

1. Option to give logo in _sidebar.md (at the top) as a replacement to the 'name' option.
2. Option to add "Last Edited : <Timestamp>" in each page. (Right now I do this manually)
3. Option to hide/remove the hyphen symbol '-', next to the items in Table of contents.
4. Option to change text of "not found" in 404.
5. Option to shrink the menu in Sidebar. At present, you can only expand, you can't shrink.

I hope you get time to do these issues.

**Comment by aslamabbas** [comment]
Please give priority to Point no 5. 

The option to collapse and expand the menu is very a basic requirement. 

Thanks,
Aslam

**Comment by QingWei-Li** [comment]
1. https://docsify.js.org/#/configuration?id=logo
2. https://docsify.js.org/#/configuration?id=formatupdated
3. Modify your own CSS
4. https://docsify.js.org/#/configuration?id=notfoundpage
5. Supported
