### ISSUE TITLE
[Feature request] Add authentification through Github OAuth for private repo

### ISSUE THREAD

**Issue by codeKonami** [docsifyjs/docsify#314]
I'd like to use docsify to generate private documentation pages.
Would it be possible to add an authentification layer to only authorize people to see the generated website if that have access to the repo?

**Comment by QingWei-Li** [comment]
You can customize the [request header[(https://docsify.js.org/#/configuration?id=requestheaders) if you want access the private repo on client.

**Comment by klangwiedergabe** [comment]
Can you expand the documentation on this Matter?
I'm really interest in having an Oauth on a Docsify project, but I just don't get it.

**Comment by toddpadwick** [comment]
I would also like a little more information on using request headers to require a password to access the site. I do not know how to do this from the documentation.
