### ISSUE TITLE
access to parsed markdown

### ISSUE THREAD

**Issue by VinzentE** [docsifyjs/docsify#322]
Hi there,

loving the tool! Very nice work.

we would need access to the object of the parsed file e.g. to access the "text" which is in heading 2.

I already looked for "marked" object and $docsify - but couldn't find it. 
Any ideas?

Thanks
Vinzent

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/markdown

```js
window.$docsify = {
  markdown: {
    renderer: {
      heading: function(text, level) {
        // ...
      }
    }
  }
}
```

**Comment by VinzentE** [comment]
Hi QingWei-Li ,

could you elaborate a bit?
Could I access that through the command line? I am not a fully fledged coder, but have some very solid understanding.

Core would be to have e.g. all the parsed markdown accessible in an object / variable e.g. called "parsedMarkdown": {...}.

any tip?
Thanks a lot
