### ISSUE TITLE
Pagination plugin breaks Zoom Image plugin

### ISSUE THREAD

**Issue by gxclarke** [docsifyjs/docsify#354]
I just wanted to let you know that when the pagination plugin and zoom image plugin work are both loaded, the zoom image doesn't work. Without the pagination plugin, zoom image works fine.

**Comment by timaschew** [comment]
For me with version `4.8.6` it works both in combination:

```
<script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
<script src="//unpkg.com/docsify-pagination/dist/docsify-pagination.min.js"></script>
<script src="//unpkg.com/docsify-copy-code"></script>
<script src="//unpkg.com/docsify/lib/plugins/zoom-image.min.js"></script>
```

But pagination doesn't work with `routerMode: 'history'` at all, nothing is shown in the footer.

**Comment by anikethsaha** [comment]
this seems to be fixed from above answer👍 

feel free to comment below if not there are any issue related to this
