### ISSUE TITLE
Search file configuraion

### ISSUE THREAD

**Issue by yzhang921** [docsifyjs/docsify#360]
Hi, is this possible to configure a folder or a wildcard in search plugin to enable all the file included in search target? 

```json
{
search : [
      '/',            // => /README.md
      '/zh-cn',      // => all the files in /zh-cn folder
      '/us-en/a*'  // => all the files that name start with 'a'
    ]
}
```

**Comment by trungly** [comment]
I think this would be an extremely useful feature for medium to large documentation repos.

**Comment by cliffhall** [comment]
exactly. I have a folder with a lot of files and don't want to add them individually.
