### ISSUE TITLE
Sidebar: Is there a way to set active state based on route and not id?

### ISSUE THREAD

**Issue by TimeDropsSB** [docsifyjs/docsify#370]
On a page, clicking on a heading link appends an id into the URL which also changes the active state of the sidebar link.  For example, https://docsify.js.org/#/more-pages?id=table-of-contents sets "Table of Contents" to active.

Is there a way to keep the active state of the sidebar to "Writing more pages" instead (which is the route name) even after clicking on a heading link?  Basically, is there a way for the above link to be the same as https://docsify.js.org/#/more-pages when setting the sidebar active state?

**Comment by mrpotatoes** [comment]
+1

I use a table of contents plugin for headings instead of the sidebar and losing the active state in the sidebar is very frustrating.

**Comment by gigaga** [comment]
+1, same behavior for me and same need :(
