### ISSUE TITLE
Is it compatible with firefox and safari?

### ISSUE THREAD

**Issue by kbhutiya** [docsifyjs/docsify#375]
I am trying to load polymer components using docsify for our documentation page ,it works fine in chrome but not in firefox and safari..is docsify good for firefox and safari too?

**Comment by QingWei-Li** [comment]
Yes, it’s should be compatible. What wrong do you get?

**Comment by kbhutiya** [comment]
Just that,polymer components don't render properly when used inside docsify for firefox and safari!

**Comment by QingWei-Li** [comment]
Please provide a demo. Thanks.
