### ISSUE TITLE
默认 cover 背景色会导致使用主题的时候先出现默认背景色,然后才变成主题色

### ISSUE THREAD

**Issue by Binaryify** [docsifyjs/docsify#397]
版本:4.6.3
浏览器:Chrome V64.0.3282.186
重现:使用 dark 主题,每次加载都会这样
定位:源码里的 cover 方法里的 section 直接默认使用了背景色,每次加载都会先渲染这个背景色,然后才变成主题色

**Comment by timaschew** [comment]
Please use English language.
