### ISSUE TITLE
Version 4.6.8 broke images (404)

### ISSUE THREAD

**Issue by augustogoncalves** [docsifyjs/docsify#415]
The following code for showing images is working fine on 4.6.7, but fails (404) on 4.6.8

`![](_media/account/activate_sub.png)`

**Comment by QingWei-Li** [comment]
https://github.com/QingWei-Li/docsify/releases/tag/v4.6.8

Yes, this is a small change. The relative path of this picture is expected behavior like github.

**Comment by yzhang921** [comment]
How to use absolute path link to image. After this change, looks like all the path works as related path, even a standard absolute path string start with "/" will be parser to relative path.

**Comment by willin** [comment]
粉转黑

**Comment by MisterFili** [comment]
I too would like to know more about this update. I noticed some .img files are loading and others are not. is this something you can further explain on the main docsify site?

**Comment by QingWei-Li** [comment]
@yzhang921 Starting with `/` is the absolute path

**Comment by MisterFili** [comment]
Thanks for responding to my previous question but I'm still having issues displaying images from outside of my current working directory. I've updated to the most recent build, running localy, set and unset `basePath`, and also forked the docsify site to see where I could be going wrong.

 If I place the file in the current working dir I can display the image. however, when I choose the path of `_imagefolder` which is not in my current working directory, the image does not render like so ![foo](bar.png)

Prior to the update `![foo](_media/bar.png)` this was working vs having to use `![foo](bar.png)` which means placing the image file in the current document file location. 

I've read over all the bug updates users have created and still couldn't understand the reasoning as to why my images are not showing up. if you have any suggestions or examples, do share. tried to duplicate [this](https://github.com/QingWei-Li/docsify/blame/master/docs/deploy.md#L15), your own image solution but failed to render image outside of current working dir.

**Comment by knightknight** [comment]
I think this is a similar issue.

I thought my sub-directory example/_coverpage.md would show the image from the root _images/example/example-logo.png directory. I even tried using `../_images/example/example-logo.png`.

<pre>
docsify
├── _images
│   └── example
│       └── example-logo.png
└── example
    ├── _coverpage.md | ![example-logo](_images/example/example-logo.png)
    ├── _sidebar.md
    └── README.md
_coverpage.md
_sidebar.md
index.html
README.md
</pre>

But it didn't work as @QingWei-Li has pointed out;

> path is relative to the current document file

What I needed to do was have an _images directory inside my /example directory and load them from there.

<pre>
docsify
└── example
    ├── _images
    │   └── example
    │       └── example-logo.png
    ├── _coverpage.md  | ![example-logo](_images/example/example-logo.png)
    ├── _sidebar.md
    ├── pages.md
    ├── posts.md
    └── README.md
_coverpage.md
_sidebar.md
index.html
README.md
</pre>

**Comment by qci-balagula** [comment]
Having the same issue. Would be nice not having to have an `images` or `_media` directory in every directory

**Comment by freedomlang** [comment]
@qci-balagula Use custom render function can do it.
```javascript
window.$docsify = {
    markdown: {
        renderer: {
          	image: function(href, title) {
            	return `<img src="${href}"/>`
          	}
        }
    }
}
```

**Comment by uwings** [comment]
> @qci-balagula Use custom render function can do it.
> 
> ```js
> window.$docsify = {
>     markdown: {
>         renderer: {
>           	image: function(href, title) {
>             	return `<img src="${href}"/>`
>           	}
>         }
>     }
> }
> ```

it worked.    but ....  ` ':size=xxx'  `  is dead

**Comment by waruqi** [comment]
这种改动 影响太广，就不能加个 配置来控制下么，可以让用户强制切回相对于basepath，使用相对于basepath下的image路径 需求还是很大的。。

这边打算迁移到docsify 但是很多文档已经使用了 相对于 basepath的 images，为了兼容已有的文档，以及现有对外输出的links，不能改动原有的image path结构。。

折腾了好久，还是没有找到很好的方式 处理这个。。

另外 alias路径 对于 image path 似乎也不行，只能处理 #/ 格式的 path alias
