### ISSUE TITLE
Nested menu sub-level not display properly...

### ISSUE THREAD

**Issue by Smilefounder** [docsifyjs/docsify#421]
Hi team,

It is very nice to use docify and thanks to the team for the wonderful project.

I'm facing the issue with nested menu sub-level not display properly, could you help advise?
![image](https://user-images.githubusercontent.com/3785721/37329236-85166ed4-26cf-11e8-85c1-22a2019d891a.png)

Thanks,
Huy

**Comment by keelii** [comment]
This PR may be solve your problem https://github.com/docsifyjs/docsify/issues/519
