### ISSUE TITLE
Same-level, sub-folder links, don't resolve properly

### ISSUE THREAD

**Issue by davestewart** [docsifyjs/docsify#424]
I'm finding that relative links don't resolve properly in subfolders.

Take this directory structure:

```
+- docs
    +- foo
        +- bar.md
        +- baz.md
```

If I'm in `/#/foo/bar` then click to navigate to `baz`:

```markdown
Click to go to the [baz](baz.md) page.
```

The HTML link renders like this:

```html
Click to go to the <a href="#/baz"> page
```

It should be:

```html
Click to go to the <a href="#/foo/baz"> page
```

I've also tried with history mode, but I get:

```html
<a href="/baz">
```

I've also tried changing the `basePath` configuration but no luck.

The only way I have managed to get this to work is with absolute paths:

```markdown
// within /foo/bar.md

[baz](/foo/baz.md)
```

Have I missed something?

Thanks!

**Comment by SidVal** [comment]
Mmm @davestewart did you try this https://github.com/docsifyjs/docsify/issues/451#issuecomment-395215415 ?

**Comment by Evidlo** [comment]
I believe this is solved by seting `relativePath` in your config.

https://docsify.js.org/#/configuration?id=relativepath

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
