### ISSUE TITLE
Absolute path for loadNavbar and loadSidebar

### ISSUE THREAD

**Issue by chauffer** [docsifyjs/docsify#429]
Hi,

Is this possible?

Right now putting `/README.md` as one of the fields just puts `/README.md` in the URL, while I want the sidebar to be the one in the root path of the domain.

Thanks!

**Comment by dmed256** [comment]
You could do
```html
<a href="./README.md">Hello</a>
```
or
```md
[Hello](/)
```

By default, Docsify automatically transforms relative directories (end with `/`) into the `README.md` inside that directory
