### ISSUE TITLE
[FEATURE REQUEST] Simplify generated links for code-style headings

### ISSUE THREAD

**Issue by davestewart** [docsifyjs/docsify#432]
Consider this Vue Docs link:

- https://vuejs.org/v2/api/#vm-watch

The markdown is written as so:

```
### vm.$watch( expOrFn, callback, [options] )
```

The link in Docsify markdown renders like so:

```
?id=vmwatch-exporfn-callback-options-
```

However, Hexo generates something more sensible:

```
#vm-watch
``` 

As a reasonable amount of our headers are going to be code, linking to them in Docsify is quite cumbersome, if I'm on another page, I have to reference it like so:

```
[watch](/api/index.md#vmwatch-exporfn-callback-options-)
```

If Docsify generated something more like Hexo does (i.e. only the words before the brackets) we would like to be able to link like so:

```
[watch](/api/index.md#vm-watch)
```
Would be great if this could be considered!

THANKS :)

**Comment by davestewart** [comment]
OK, so I managed to solve this by writing a plugin :)

```js
/**
 * Fix anchors for all headings with code in them
 *
 * @param hook
 */
function fixAnchors (hook) {

  hook.afterEach(function (html, next) {

    // find all headings and replace them
    html = html.replace(/<(h\d).+?<\/\1>/g, function (html) {
      // create dom
      var div = document.createElement('div')
      div.innerHTML = html

      // get anchor
      var link = div.querySelector('a[href*="?id"]')

      if (!link) {
        return html
      }

      // work out id
      var text = link.innerText
      var id = text
        .split('(')
        .shift()
        .toLowerCase()
        .replace(/\W+/g, '-')
        .replace(/^-+|-+$/g, '')
      var href = link.getAttribute('href')
        .replace(/\?id=.+/, '?id=' + id)

      // update dom
      link.setAttribute('href', href)
      link.setAttribute('data-id', id)
      link.parentElement.setAttribute('id', id)

      // return
      return div.innerHTML
    })

    // continue
    next(html)
  })
}
```

Obviously, would be great to see this in the core at some point :)

**Comment by bashkirtsevich** [comment]
Sad, but it doesn't working with Cyrillic.

**Comment by davestewart** [comment]
Nice :)

**Comment by bashkirtsevich** [comment]
After day long suffer with javascript I was found completely easy solution.
I just make local copy of `docsify.min.js` with this patch: 
```
var o=U(i.id||r).split('(').shift().toLowerCase().replace(/[^а-яa-z_]/g,'-').replace(/^-+|-+$/g,'')
```
Location (find by this part of code):
```
a.ignoreAllSubs=!0);var o=U(i.id||r),s=u.toURL(
```

I think this patch more comfortable instead worst plugins with half-working results.

Reason: Cyrillic paragraph links and compatibility with GitLab markdown (just as awful) engine.

May be this solution will helpful for someone.

**Comment by timaschew** [comment]
@davestewart I don't think that will scale.

If you have two functions with overloading:

```
### vm.$watch( arg1 )
### vm.$watch( arg1, arg2, arg3 )
```
Just omitting everything after the first bracket is not enough.
