### ISSUE TITLE
mathematical formula

### ISSUE THREAD

**Issue by flystarhe** [docsifyjs/docsify#439]
Does not support the mathematical formula?

**Comment by flystarhe** [comment]
such as:

```
$$
y = \frac{1}{x}
$$
```

**Comment by dmed256** [comment]
This type of transformation would have to be done as a plugin. For example, I made a `::: indent` transform that took

![indent2](https://user-images.githubusercontent.com/1812355/39675430-a4589e72-5120-11e8-8830-c754cbb33e00.png)

and transformed it to

![indent](https://user-images.githubusercontent.com/1812355/39675435-a9bf03a6-5120-11e8-9799-b409a3e33e96.png)

[Link to the code](https://github.com/libocca/libocca.org/blob/master/assets/occa.js#L40)

You would need to write a plugin to capture something similar:

```
\$\$(.*?)\$\$ -> <latex>$1</latex>
```

**Comment by yihengli** [comment]
https://github.com/docsifyjs/docsify/issues/96
