### ISSUE TITLE
{docsify-ignore-all}  should better be replaced with <!-- {docsify-ignore-all} -->

### ISSUE THREAD

**Issue by hao-lee** [docsifyjs/docsify#441]
`{docsify-ignore-all}` will be rendered by GitHub or other Markdown engines, it looks very strange if someone reads docs on GitHub directly. So I suggest using `<!-- {docsify-ignore-all} -->` instead.

**Comment by hlb8122** [comment]
This has the additional benefit of hiding the tags from appearing in the search results.

**Comment by anikethsaha** [comment]
I think this is better as it seems it will solve https://github.com/docsifyjs/docsify/issues/767 as well (not sure , need to try it out). 


Feel free to submit a PR
