### ISSUE TITLE
自定义404页面图片无法使用绝对路径

### ISSUE THREAD

**Issue by sumneko** [docsifyjs/docsify#443]
+ 我在选项中选择启用了自定义404页面
![default](https://user-images.githubusercontent.com/5213431/38235968-5f0a09b2-3755-11e8-9ce3-e44d71548870.png)

+ 在404页面中，我插入了一张图片，使用的是绝对路径。
![404](https://user-images.githubusercontent.com/5213431/38235986-6d30d598-3755-11e8-8518-32960de7e760.png)

+ 图片资源如下
![default](https://user-images.githubusercontent.com/5213431/38235988-6de6d410-3755-11e8-85e9-c656c66196b3.png)

+ 有时图片可以正常显示，但有时图片无法显示。
+ 图片无法显示时，查看这张图片的路径，发现路径不正确，看起来是当做了相对路径处理。
![default](https://user-images.githubusercontent.com/5213431/38235987-6d8a9f10-3755-11e8-83b1-a3a2d26af5a6.png)

**Comment by timaschew** [comment]
Please use English language.
