### ISSUE TITLE
Contributing a plugin

### ISSUE THREAD

**Issue by davestewart** [docsifyjs/docsify#475]
I've just written a page navigation plugin.

It shows the previous and next page navigation as actual titles (harvested from the sidebar) and is also navigable by keyboard left / right:

![image](https://user-images.githubusercontent.com/132681/39476583-564ec9ba-4d54-11e8-88aa-a8edea8f89b6.png)

You can see it in action here:

- https://davestewart.github.io/vuex-pathify

What would be the best way to contribute?

Break it out as a repo and load via unpkg.com ?

**Comment by QingWei-Li** [comment]
Welcome to contribute, any way you want. Remember to add a description to the document.

**Comment by jhildenbiddle** [comment]
How this is different from the existing pagination plugin listed here:

* https://github.com/imyelo/docsify-pagination

**Comment by davestewart** [comment]
I've no idea! It's been ages since I looked at the code or docsify.

**Comment by davestewart** [comment]
All the code is here:

- https://github.com/davestewart/vuex-pathify/blob/develop/docs/assets/js/plugins.js

Looks like keyboard navigation is also in there.
