### ISSUE TITLE
"404 not found" error when trying to create documents from asciidoc format

### ISSUE THREAD

**Issue by repomorphic** [docsifyjs/docsify#478]
Hello.Is it possible to create documents from asciidoc format?I add my asciidoc document on sidebar.md in the following way

```
* Getting started
  * [Oriented](ObjectOrientedJava.adoc)
```

Then I tried to click the Oriented link on docsify documentation then I get "404 not found error".
How can I fix this?

**Comment by dmed256** [comment]
I think docsify uses the URL path to:
- Fetch Markdown file based on the path (`/foo -> /foo.md` or `/foo/ -> /foo/README.md`)
- Uses [marked](https://github.com/markedjs/marked) to generate the HTML needed
- Processes plugins, etc

I doubt it'll be able to take another format and render a nice-looking webpage

If all you want is to host the file, it should be possible by using `<a></a>`
```md
* Getting started
  * <a href="./ObjectOrientedJava.adoc">Oriented</a>
```

**Comment by lostdinar2** [comment]
Thanks. I am trying to create HTML documentation from-asciidoc format. Maybe docsify only support markdown format.

**Comment by ItsPugle** [comment]
Yep, Docsify only supports parsing for Markdown right now. Unless one of the [Markdown parsers](https://docsify.js.org/#/markdown) that Docsify supports ([marked](https://marked.js.org/) and [mermaid](https://mermaidjs.github.io/)) is able to parse AsciiDoc, you'll need to use another tool.
