### ISSUE TITLE
Is it possible to deploy docsify on bitbucket server

### ISSUE THREAD

**Issue by tky753** [docsifyjs/docsify#491]
Hey guys.

Thank you for this nice tool. I've tried to use it in our projects and deploy it on our **bitbucket** server.

But I am a noob and don't know how to do it as it's not mentioned in the [doc](https://docsify.js.org/#/deploy).

Maybe it needs some add-on for bitbucket? Did anyone do this before?

**Comment by dmed256** [comment]
@tky753 For deployment, you need to be able to access your files from some URL

For example:

  https://myrepo.bitbucket.io/ → `<git-repo>/index.html`

then 

  https://myrepo.bitbucket.io/#/my-section → `<git-repo>/my-section.md`

With Github Pages, you might need to put them in `<git-repo>/docs` or in a branch. If Bitbucket lets you host in a similar way, then docsify should work automatically :)
