### ISSUE TITLE
Serving up pages outside of docsify

### ISSUE THREAD

**Issue by ryanvgates** [docsifyjs/docsify#497]
How can I have a page that is either omitted or outside of the docsify formatting? I need to have a page that shows a string of text saying the site is up for load balancing purposes. It would be something like

> This site is up and running.

The tool that we're using has a difficult time parsing a bunch of html and js to verify that same string. I'd like to have a page that just has that string.

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/embed-files
