### ISSUE TITLE
能否实现点击编辑按钮就打开本地文件的功能？

### ISSUE THREAD

**Issue by jintaixizhao** [docsifyjs/docsify#503]
我是在本地搭建服务器浏览的方式使用docsify的，经常在浏览时发现有内容需要修改，于是手动切换到文件对应路径，然后打开文件编辑。
我看到说明文档中的编辑功能是打开github相关文件，在github提供的编辑器中修改的，但我的markdown文件不打算上传到github，所以想知道是否可以提供一键打开本地md文件的功能？用户只需要配置好本地编辑器的位置，浏览时点击编辑按钮，即打开相应的文件。

**Comment by jintaixizhao** [comment]
这个我自己实现了，在本地另起一服务器，点击编辑按钮，通过访问该服务打开本地文件。但依然觉得docsify直接实现此功能比较好。

**Comment by timaschew** [comment]
Please use English language.
