### ISSUE TITLE
Put the hamburger where it belongs

### ISSUE THREAD

**Issue by petrdvorak** [docsifyjs/docsify#511]
I don't see why hamburger menu is in the bottom left corner. Nobody we showed the documentation was able to find it there. Is it possible to move the button to the upper left corner?

Also, the documentation "name" could be moved to the top of the sidebar, above the search bar.

See this quick mockup:

![group 2](https://user-images.githubusercontent.com/516597/40848557-e1c632fc-65bf-11e8-945e-eaaad1154653.png)

Having own custom layout can make a page look interesting, but it should not be at the sake of non-standard UX.

**Comment by jhildenbiddle** [comment]
Done! :wink:

https://jhildenbiddle.github.io/docsify-themeable

**Comment by petrdvorak** [comment]
@jhildenbiddle Love it! :)

I understand the problem with placing the burger into the sidebar... I believe that we can close this issue, if fixing can be done with a simple plugin...

**Comment by jhildenbiddle** [comment]
FWIW, [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) isn't a plugin. It's probably easiest to just describe it as a different theme, but it's really a few things:

* A complete rewrite of docsify's CSS with a focus on customization using CSS custom properties 
* A collection of themes based off of the rewritten CSS
* A plugins (6.3k min+gzip) that adds new features and fixes docsify issues and bugs

Just wanted to clarify for others that may stumble on the thread.

Thanks!

**Comment by Fmstrat** [comment]
Easiest way as of 2024:
```
The above no longer works. Use this instead:
```
.sidebar-toggle {
	background-color: unset;
	position: fixed !important;
	top: 0 !important;
	bottom: auto !important;
	padding: 10px 10px 10px 10px !important;
}

@media screen and (max-width: 768px) {
	.markdown-section {
		padding: 16px 16px 16px 36px !important;
	}
}
```
```
