### ISSUE TITLE
Can't embed files in embedded files

### ISSUE THREAD

**Issue by pboymt** [docsifyjs/docsify#512]
parent.md
```markdown
[filename](child.md ':include')
```
child.md
```markdown
[filename](grandchild.md ':include')
```
grandchild.md
```markdown
show as a hyperlink
```

`grandchild.md` wasn't embedded in `child.md`

**Comment by pboymt** [comment]
This problem only occurs when the embedded file contains a table

**Comment by yinheli** [comment]
same issue

**Comment by HuntiXz** [comment]
Having the same problem any news on this?

**Comment by gr4viton** [comment]
This is a crucial function, how do you want to write documentation, without reusing code. And how can you reuse code with only one level of embedding.
:+1:

**Comment by gr4viton** [comment]
Well this functions need to be called "recursivelly" if `':include'` is detected in the prerendered embed files.

Tho i am not `javascripter` :ocean: 

https://github.com/docsifyjs/docsify/blob/890a7bf9b6847cbee4d02675c9fa19cd6e1a41c1/src/core/render/embed.js

**Comment by stueynet** [comment]
Yeah. Would love to embed a block in the `_sidebar.md` file which is not possible. Big +1 here!

**Comment by lordfuoco** [comment]
Same here, also embedding multiple files in the same file sometimes causes one of them ( or more ) to not appear: https://korigan.github.io/Vue2Leaflet/#/components/l-map/ (refresh and it will happen )
