### ISSUE TITLE
Sidebar TOC bug / enhancement

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#517]
Details below, but this issue is easiest to understand with a demo:

1. Visit the [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) home page
1. Scroll past the coverpage and click on **Quick Start** in the sidebar
1. Now click on **Introduction** in the sidebar

I would like the **Introduction** link to navigate to the top of the introduction page, not back to the root of the site which results in the coverpage being displayed.

At first I thought this would be an easy fix: just update the sidebar link to point to the file instead of the root of the site.

```javascript
window.$docsify = {
  homepage   : 'index.md',
  loadSidebar: 'sidebar.md',
  subMaxLevel: 3,
  // ...
}
```

```markdown
<!-- sidebar.md -->
- [Introduction](/)
```

To this:

```markdown
<!-- sidebar.md -->
- [Introduction](index)
```

This change allows the **Introduction** link to work as intended: the `index.md` page is loaded rather than the site root, so the coverpage is only seen on initial load. Great!

Unfortunately, the above change comes with an unexpected side-effect: docsify no longer auto-generates a TOC for the page.

So instead of this:

```
|-- Introduction
    |-- Features
    |-- Contact & Support
    |-- License
|-- Quick Start
    ...
```

I only get this:

```
|-- Introduction
|-- Quick Start
    ...
```

Any ideas on how to set the **Introduction** link to load the introducton document *and* generate a TOC for the page?

Thanks!

**Comment by timaschew** [comment]
I can't reproduce it with these steps

> 1. Visit the docsify-themeable home page
> 2. Scroll past the coverpage and click on Quick Start in the sidebar
> 3. Now click on Introduction in the sidebar

Can you please verify

**Comment by jhildenbiddle** [comment]
I too am unable to reproduce this. Perhaps this was addressed inadvertently with some other sidebar updates.

Either way, happy to close it. :)
