### ISSUE TITLE
Zoom image plugin: only content / ignore linked

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#520]
The [zoom image plugin](https://docsify.js.org/#/plugins?id=zoom-image) currently targets all images except for emoji and those with `data-no-zoom` attribute.

https://github.com/QingWei-Li/docsify/blob/6c7ebc989dd1572f744fbe5fc8f5af710b790cce/src/plugins/zoom-image.js#L11

Two additional scenarios should excluded by default:

1. Images outside of the main content area.
1. Linked images (Ex: `<a href="#"><img src="image.jpg"></a>`)

I've added a fix-via-plugin to [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable), but it requires removing *all* event listeners via cloning the image node which is less than ideal.

- https://github.com/jhildenbiddle/docsify-themeable/blob/master/src/js/plugin-fix-zoomimage.js

Ideally these scenarios would be handled by default.

Thanks!

**Comment by billhennessy** [comment]
At least being able to exclude the logo from zoom would help. I had to remove the zoom image plugin.

**Comment by poppabear8883** [comment]
I agree with @billhennessy here, i'm having the same issue with the `logo` being zoom activated ... has there been at least a solution for this issue ?
