### ISSUE TITLE
Search plugin: ESC key does not clear search in Firefox

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#532]
When the search field contains text and the ESC key is pressed, other browser clear the search field and results. Unfortunately, the ESC key does nothing in Firefox.

Test with docsify 4.6.10 and Firefox 60.

**Comment by timaschew** [comment]
related: https://bugzilla.mozilla.org/show_bug.cgi?id=1055085

**Comment by jhildenbiddle** [comment]
Closing this since this is a browser-supplied behavior that is absent from Firefox (per the bug listed above).
