### ISSUE TITLE
Search plugin: add "show" class to parent element when showing results

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#535]
When showing results, the search plugin adds a "show" class to certain elements to change styles. Specifically, it adds the "show" class the the clear button and the results panel:

```html
<div class="search">
  <div class="input-wrap">
    <input type="search" value="" placeholder="Search...">
    <button class="clear-button show" aria-label="Clear search">...</button>
  </div>
  <div class="results-panel show">...</div>
</div>
```

It would be helpful to have this same class also added to the search wrapper as follows:

```html
<div class="search show">
```

Add this class to the search wrapper will allow the sidebar navigation to be hidden when the search results are displayed using only CSS.

This functionality has been added to [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable) by way of a small plugin, but ideally this would be handled by docsify out-of-the-box. Source code for the plugin can be viewed here:

* https://github.com/jhildenbiddle/docsify-themeable/blob/master/src/js/plugin-fix-search-results.js

(Making this change in the docsify source would be *much* easier than fixing this via plugin).

**Comment by cheng-kang** [comment]
I've raised a PR for adding a new option `hideSidebarOtherContent` to search plugin.

I wouldn't call it a bug though. This is a nice new feature. Hope it satisfies your need.
