### ISSUE TITLE
Sidebar only really works with bulleted lists

### ISSUE THREAD

**Issue by davestewart** [docsifyjs/docsify#539]
If you use para tags, it strips all content until the first list bullet:

Sidebar:

```
Overview

- this
- that
```

Result:
```
- this
- that
```

I know you have to do this to make it work:

```
- Overview

    - this
    - that
```

But it would be useful if you could specify your own structure, and override the CSS if needed.

I just started a new project and it tripped me up.

Saying that, paragraph tags seem to get pulled left, so that looked broken too.

It might be worth clarifying all of this in the docs.

**Comment by jhildenbiddle** [comment]
Support for additional tags in the sidebar is also the topic of #518.

If you're interested in customizing sidebar styles, have a look at [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/).

**Comment by davestewart** [comment]
Yeah, we've essential posted the same issue!

**Comment by cheng-kang** [comment]
Closed by https://github.com/docsifyjs/docsify/commit/22edfce3d8fe0000b9a5729f7424a168b2841d5c
