### ISSUE TITLE
Ability to customize page's 'title' HTML tag value

### ISSUE THREAD

**Issue by soulfly** [docsifyjs/docsify#540]
Right now, the  'title' HTML tag value is generated based on sidebar item value

Sometimes I want to make it more custom, e.g. to make it more convenient for SEO, but keep it short in sidebar

Would be great to have this ability

We can do it in the same way as ignoring subheaders works
https://docsify.js.org/#/more-pages?id=ignoring-subheaders

e.g.

`# Getting Started {docsify-title=Getting started with iOS machine learning SDK toolkit}`

**Comment by soulfly** [comment]
For everybody - I found a quick way to do it with a little of customization:

1) btw we can provide sidebar links with titles, e.g.
`  * [Getting Started](ios/getting-started.md "Getting started with iOS SDK toolkit")`

2) Then we need to customize a bit `docsify.js`:

In `getAndActive` function:

Replace this

```
if (autoTitle) {
      $.title = target ? ((target.innerText) + " - " + title) : title;
}
```

with this:

```
if (autoTitle) {
    if(target && target.title){
      $.title = target.title;
    }else{
      $.title = target ? ((target.innerText) + " - " + title) : title;
    }
 }
```

Actually I like how it works, 
going to prepare a PR with the fix

hope the Docsify team will merge it 👍

**Comment by soulfly** [comment]
PR prepared https://github.com/docsifyjs/docsify/pull/557

**Comment by Giraffeness** [comment]
I wanted to add a suffix to my titles, so I wrote a little plugin:
```js
    window.$docsify = {
      ...
      plugins: [
        titlePlugin({
          suffix: ' | My Website'
        })
      ]
    }

    function titlePlugin(config) {
      return (hook, vm) => {
        hook.doneEach((content) => {
          document.title += config.suffix
        });
      }
    }
```
