### ISSUE TITLE
如何让 gitalk 插件 给文档的每一篇文章都有一个新的 issue?

### ISSUE THREAD

**Issue by ripperhe** [docsifyjs/docsify#550]
我按照以下设置，最终得到的结果就是，整个文档都只有一个 gitalk 的 issue，如何设置 gitalk 的 `id` 参数，才能让每一篇文章都有自己的一个独立的 issue ？

```html
<link rel="stylesheet" href="//unpkg.com/gitalk/dist/gitalk.css">

<script src="//unpkg.com/docsify/lib/plugins/gitalk.min.js"></script>
<script src="//unpkg.com/gitalk/dist/gitalk.min.js"></script>
<script>
  const gitalk = new Gitalk({
    clientID: 'Github Application Client ID',
    clientSecret: 'Github Application Client Secret',
    repo: 'Github repo',
    owner: 'Github repo owner',
    admin: ['Github repo collaborators, only these guys can initialize github issues'],
    // facebook-like distraction free mode
    distractionFreeMode: false
  })
</script>

```

**Comment by QingWei-Li** [comment]
Gitalk 如果可以动态改 id 的话，那可以在 docsify 插件里用 doneEach 重新赋值。但是我看了下 Gitalk 并没有提供类似方法，建议你给该作者提 issue

**Comment by ripperhe** [comment]
好的，谢谢啦👍

**Comment by wzpan** [comment]
@ripperhe 这问题请问是否解决了？有方案吗？

**Comment by ripperhe** [comment]
@wzpan 我后来没有弄了，不过你可以参考一下这个网站的做法，他实现了每个文章一个issue [https://github.com/l-hammer/You-need-to-know-css](https://github.com/l-hammer/You-need-to-know-css)

**Comment by timaschew** [comment]
Please use English language.

**Comment by Q-Angelo** [comment]
@wzpan 
reference: https://www.nodejs.red/#/tools/docsify

**Comment by wzpan** [comment]
@Q-Angelo 
Yes I've solved this. Thanks.

**Comment by ywz978020607** [comment]
You can check my index.html in this repo: https://github.com/ywz978020607/leetcode 
the most import config is :
xxxxGitalkxxxx
id: window.location.pathname + (window.location.hash.split("/")[1]?window.location.hash.split("/")[1]:""),
----
By this way, you can use the common issue under the first directory of the project, and you can adjust it.

**Comment by ywz978020607** [comment]
> 我按照以下设置，最终得到的结果就是，整个文档都只有一个 gitalk 的 issue，如何设置 gitalk 的 `id` 参数，才能让每一篇文章都有自己的一个独立的 issue ？
> 
> ```
> <link rel="stylesheet" href="//unpkg.com/gitalk/dist/gitalk.css">
> 
> <script src="//unpkg.com/docsify/lib/plugins/gitalk.min.js"></script>
> <script src="//unpkg.com/gitalk/dist/gitalk.min.js"></script>
> <script>
>   const gitalk = new Gitalk({
>     clientID: 'Github Application Client ID',
>     clientSecret: 'Github Application Client Secret',
>     repo: 'Github repo',
>     owner: 'Github repo owner',
>     admin: ['Github repo collaborators, only these guys can initialize github issues'],
>     // facebook-like distraction free mode
>     distractionFreeMode: false
>   })
> </script>
> ```

```
You can check my index.html in this repo: https://github.com/ywz978020607/leetcode 
the most import config is :
xxxxGitalkxxxx
id: window.location.pathname + (window.location.hash.split("/")[1]?window.location.hash.split("/")[1]:""),
----
By this way, you can use the common issue under the first directory of the project, and you can adjust it.
```
