### ISSUE TITLE
Request: Please include changes to HTML in CHANGELOG

### ISSUE THREAD

**Issue by jhildenbiddle** [docsifyjs/docsify#552]
Author of [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) here.

I'd like to propose that any change to the generated HTML structure be included in the CHANGELOG with each update. Projects like docsify-themeable (or any other custom theme) will need to know about these changes so CSS can be updated accordingly. These changes are *very* hard to track down without some indication that a change has been made, so a hint in the CHANGELOG would be extremely helpful.

Thanks!

**Comment by timaschew** [comment]
@QingWei-Li why this was closed? Actually this makes lot of sense to me.
