### ISSUE TITLE
Inconsistent ID Anchor Jumps (revisited)

### ISSUE THREAD

**Issue by mlschuh** [docsifyjs/docsify#559]
Related to #332 but with a reproduced project file.

Attached is a slim version of our project where we were able to reproduce it. [docsify-anchor-jump-incorrect.zip](https://github.com/docsifyjs/docsify/files/2150037/docsify-anchor-jump-incorrect.zip)

To Reproduce:

```
npm i docsify-cli -g
docsify serve docs
```

Go to http://localhost:3000/#/isaac-gui-noimages?id=user-pane and see that it appears close to the anchor. 
Go to http://localhost:3000/#/isaac-gui?id=user-pane and see that it appears far from the anchor. 

The only difference between the two pages is the images being included or not.

-Mitch

**Comment by DixCar** [comment]
I have noticed similar problem. Some anchors are work correct with sidebar but some aren't.  


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32497506/42166374-b8c493c0-7e02-11e8-9bda-841d910c43f0.gif)

I'm using 'theme-simple-dark'

-Paw

**Comment by silentHoo** [comment]
@mlschuh This is the same I'm struggeling with. Problem is that images are async loaded, but docsify doesn't wait until images are present. So if the image has not a given height, the images height is 0 when first visiting the page. If the image is loaded later, the offset between your anchor jump and the current scroll position is exactly the height of the image(s).

**Comment by mlschuh** [comment]
@silentHoo That makes sense in my mind. I'll ask around to my web dev friends to see if there's a way to at least set some kind of (short) timeout on the anchor jump to at least give the browser a fighting chance of being closer. Tricky part in my mind is to make sure the user still has an impression that the page is loading during that timeout.

**Comment by rizdaprasetya** [comment]
This is what I did: https://github.com/docsifyjs/docsify/issues/351#issuecomment-528318227
