### ISSUE TITLE
Dead sidebar link in German docs

### ISSUE THREAD

**Issue by jrappen** [docsifyjs/docsify#561]
The link in the German docs for `de-de/embed-files.md` within `de-de/_sidebar.md`is dead. Other links seem fine. Will investigate later, couldn't find the cause with a quick check.

**Comment by SidVal** [comment]
It's because the page can't reach the example's files: `https://docsify.js.org/de-de/_media/example.md`.

I'm trying to find out why can't reach the resource 👎

**Comment by SidVal** [comment]
It's working now! 👍  

https://docsify.js.org/#/de-de/embed-files

**Comment by jrappen** [comment]
@QingWei-Li Maybe docsify should load the markdown anyway if loading embedded files fails?

**Comment by jrappen** [comment]
@anikethsaha I still believe this to be a bug.

**Comment by anikethsaha** [comment]
feel free to investigate and submit a fix
