### ISSUE TITLE
如何把docsify生成的网页导出成离线的网页

### ISSUE THREAD

**Issue by zwbao** [docsifyjs/docsify#566]
如果在本地预览，另存网页，侧边栏的目录都是 Localhost:4000 开头；若是用锚点改html界面也会出现问题，页面无法滚动。QAQ

**Comment by timaschew** [comment]
Please use English language.

**Comment by wan230114** [comment]
我也遇到同样的问题

**Comment by sy-records** [comment]
https://docsify.js.org/#/zh-cn/pwa @wan230114

**Comment by mindzheng** [comment]
解决了吗
