### ISSUE TITLE
Link to File (.csv, .pdf)

### ISSUE THREAD

**Issue by billhennessy** [docsifyjs/docsify#568]
Great tool, but I can't figure out how to link to a file for download. 

I have several csv files and PDFs in \docs\downloads linked with `[filename](./downloads/filename.pdf)`.  Gets 404 error, and path includes the `./`

I'm porting over from Slate, and this is the last major hurdle.

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/helpers?id=ignore-to-compile-link

**Comment by billhennessy** [comment]
Beautiful! Thanks. Sorry I missed that. You have an awesome app here, btw. Great work.

**Comment by msi-matthew** [comment]
I'm having issues when trying to download  a `.dmg` file using the ':ignore' flag.

**Comment by salmanfarisvp** [comment]
> Page Not Found" error when trying to download a `.dmg` file using the `':ignore'` flag.

Same for me! any solutions! Thanks.

**Comment by yanbutan** [comment]
Hi guys, is there a way to open pdf file in a another tab instead of downloading the file when clicked on link?
