### ISSUE TITLE
Full text search on different version

### ISSUE THREAD

**Issue by patrickboulay** [docsifyjs/docsify#572]
Hi,

I have several version of my documentation and I would like to let user to see older doc.
I have this structure:
/docs/v1.0
/docs/v1.1

I have index.html in both folders.
But when I search something in the v1.0, I can see the stuff in my v1.1.

If I look the cache in Chrome using this url: chrome://settings/
I can see the address of my docsify server without any /v1.0 or /v1.1.

How can I make my search independent?

In my index.html, I only have `search: 'auto',` in the window.$docsify parameters.

Thanks for help.

**Comment by billhennessy** [comment]
Try specifying your search files instead of auto. example:
```
search : [
      '/',            // => /README.md
      '/guide',       // => /guide.md
      '/get-started', // => /get-started.md
      '/zh-cn/',      // => /zh-cn/README.md
    ],
``` 

Read more here: https://docsify.js.org/#/plugins?id=full-text-search

**Comment by patrickboulay** [comment]
I understand but if you navigate on different versions of the documentation, the indexes are saved at the same place:
```
function saveData(maxAge) {
  localStorage.setItem('docsify.search.expires', Date.now() + maxAge)
  localStorage.setItem('docsify.search.index', JSON.stringify(INDEXS))
}
```
I think we should have the option to save the index at 'docsify.search.index.v1'  for example.
