### ISSUE TITLE
Private content via authentication?

### ISSUE THREAD

**Issue by jsodeman** [docsifyjs/docsify#579]
To control access to a docsify site my guess is that I need to replace the index.html file with a server rendered file (index.php for example)  that first checks the user's credentials. I see that requestHeaders allows you to send something like a token to the script, but it isn't clear what the script does with it.

**Comment by inakianduaga** [comment]
as an alternative, if you deploy `docsify` in S3 you could use a Cloudfront distribution in front of it and lambda@edge based auth to have a complete serverless solution

**Comment by Velliz** [comment]
+1 wondering if this can be provided in docsify...

**Comment by Maxou44** [comment]
I'm hyped by this feature too ✌
Do you think it's easy to support?

**Comment by suryasanchez** [comment]
What workaround did you find guys?

**Comment by Maxou44** [comment]
I created a directory with a "password" name and I have access to it from:
http://www.mywebsite.com/myawesomepassword/index html

**Comment by jugraj** [comment]
Is there any documentation for this situation? I am trying to access private repo, which requires a token to be supplied to it but its unclear on how to. 

So I am trying to get to
https://raw.githubusercontent.com/{ACCOUNT}/{REPO}/develop/docs/ but keep getting `error 403` as it requires token supplied to it.

**Comment by suryasanchez** [comment]
It might not be the expected answer but the workaround I did was to switch to GitBook.

**Comment by jugraj** [comment]
Thanks @suryasanchez but I need to create pages on the fly (which Docsify provides) but Gitbook provides a static page approach - unless that is not correct. :|

**Comment by hardfish82** [comment]
Is there any solution? I face the same situation.

**Comment by baur** [comment]
How to restrict access for every page, not only for whole index.html by custom render?

**Comment by egoist** [comment]
Does HTTP basic auth work for you?

**Comment by baur** [comment]
I'd like to generate content for every user dynamically

**Comment by baur** [comment]
> Does HTTP basic auth work for you? I'll send a PR that replaces XHR with `fetch` so that you can use `fetchOptions: {credentials: 'include'}` to make it work with basic auth.

I'll wait it, is this solution prevent direct access to *.md files

**Comment by baur** [comment]
I'd like to create telegram bot which will generate access link to site (passwordless access)

**Comment by rylincoln** [comment]
Here is a simple solution that doesn't use basic auth. This might be useful if you want to not leave your docs site open to the world but can't use the basic authentication pattern of `https://user:pass@mysite.mydomain.com` due to say chrome blocking this.

You would put this in your `index.html` file - this is using jquery selector and custom function to get [URL params](https://stackoverflow.com/questions/19491336/how-to-get-url-parameter-using-jquery-or-plain-javascript)


```javascript
<script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script>
      var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = window.location.search.substring(1),
          sURLVariables = sPageURL.split("&"),
          sParameterName,
          i;

        for (i = 0; i < sURLVariables.length; i++) {
          sParameterName = sURLVariables[i].split("=");

          if (sParameterName[0] === sParam) {
            return typeof sParameterName[1] === undefined
              ? true
              : decodeURIComponent(sParameterName[1]);
          }
        }
        return false;
      };
    </script>
  </head>
  <body id="theBody">
    <div id="app"></div>
  </body>
  <script>
    var token = getUrlParameter("token");
    if (token == "some random token - maybe use uuidgen to make it?") {
      window.$docsify = {
        loadSidebar: true,
        subMaxLevel: 5,
        name: "My sweet docs site",
      };
    } else {
      $("#theBody").html(`<div id="unauth">Unauthorized</div>`);
    }
  </script>
```
