### ISSUE TITLE
Hosting on SharePoint Online (365)

### ISSUE THREAD

**Issue by seqareen** [docsifyjs/docsify#583]
Running Docsify on GitHub Pages is working smoothly. Moving everything to a SharePoint site Page, will show the main page but all contents are showing loading. One page, with loading everywhere.

The only change has been done is renaming the **index.html** to **index.aspx** to be able to serve on SP.

How to make render properly?

**Comment by yahya2w** [comment]
Still not working, SP online allows only **aspx**. Besides renaming the entry file extension, would there be anything else requires changing?

**Comment by alpersilistre** [comment]
Sorry about writing to the closed issue.

Hey @seqareen , can you able to resolve this? I am trying to host docsify project but got the same issue as yours. The sidebar and content just display 'Loading...' and nothing happens.

**Comment by jdearaujo** [comment]
I apologise for also bumping an old thread, but there is a solution - use the **basepath** to configure the path to point to your markdown files.
You should also test whether you can output a hello world statement directly from the index.aspx file first. If there's no output, then docsify won't be able to render anything either.
Consider adding a content web part that points to your docsify index.html file - it allows you to separate your docsify files without having to constantly rename to .aspx.
