### ISSUE TITLE
如何调整正文显示宽带？

### ISSUE THREAD

**Issue by lovese** [docsifyjs/docsify#589]
希望把显示宽带再调宽一点，可以显示长一点的代码

**Comment by raylapse** [comment]
If you also use the docsify-themable plug-in, you can set the width by adding following code into the <head> section of index.html:
`  
  <style>
    :root {
      --content-max-width: 70em;
    }
  </style>`

I don't know if this also works without the themable plugin, please test that by yourself.

**Comment by timaschew** [comment]
Please use English language.
