### ISSUE TITLE
Links in (sub-)headings break generated sidebar navigation links

### ISSUE THREAD

**Issue by progmem64** [docsifyjs/docsify#591]
I found a bug regarding the auto-generated sidebar links for (sub-)headings.

If headings do not include links, sidebar works fine:
```md
## getActiveEventId(state) ⇒ <code>string</code> \| <code>null</code>
```

![sidebarworkingfine](https://user-images.githubusercontent.com/18649298/43358646-547ab85c-9295-11e8-8e49-c98e00074a71.png)

But if headings include a link, sidebar breaks:
```md
## getEvent(state, eventId) ⇒ [<code>TableEvent</code>](#tableevent) \| <code>null</code>
```

![screen shot 2018-07-28 at 18 39 05](https://user-images.githubusercontent.com/18649298/43358658-8e00fda2-9295-11e8-966b-bc6830b6abcb.png)

Link forces line-break. Anything that comes behind the link is not clickable anymore. Link leads to link-destination and not to heading.

Links in headings should be ignored when sidebar is generated.

Vanilla theme, no customization applied.

**Comment by dkebler** [comment]
similar issue here

if a markdown document is in a subdirectory and it is linked from the sidebar when you click the page render/loads but then the sidebar does not. I suspect it's a relative issue but docisfy should look in the root for _sidebar.md not in the directory of the md file that was loaded.

Looks like no one is currently maintaining this project so not likely to get any help.

**Comment by anikethsaha** [comment]
Working fine with latest version. Please update




![image](https://user-images.githubusercontent.com/26347874/74965000-6c4c5680-543a-11ea-8382-861afdfefdc2.png)
