### ISSUE TITLE
Feature request: support image caption

### ISSUE THREAD

**Issue by yzhang-gh** [docsifyjs/docsify#596]
For now, there is no good way to add a caption to an image in docsify. It would be better to have
1. a way to write a caption, like `{% include image.html url="..." description="..." %}` in Jekyll ([ref](https://stackoverflow.com/questions/19331362/using-an-image-caption-in-markdown-jekyll))
   or just raw HTML snippet `<figcaption>...</figcaption>` written by users themselves. Then we need
2. default styles for `figcaption`, e.g. gray foreground color and smaller font

---

Another example: [Hugo built-in shortcut](https://gohugo.io/content-management/shortcodes/#example-figure-input)

![image](https://user-images.githubusercontent.com/7588612/43501965-d627758c-958a-11e8-8218-a14ebf12d99d.png)

**Comment by nichtich** [comment]
See [image captions in Pandoc Markdown](https://pandoc.org/MANUAL.html#images): An image such as

    ![Steve Francia](/media/spf13.jpg)

Should be rendered with "Steve Francia" as caption instead of alt text.
