### ISSUE TITLE
[bug] Embed files with sidebar

### ISSUE THREAD

**Issue by dolanmiu** [docsifyjs/docsify#599]
The sidebar does not show sub menus if you do the following steps:

## To Reproduce:

1. Go to https://docx.js.org/#/
2. Click on `Examples` (the page which has the embedded files)
3. Refresh the page
4. Click on `Getting Started` or any other page on the documentation
5. Click back on `Examples`
6. The `sidebar` of `Examples` do not show anymore.

**Comment by jthegedus** [comment]
I followed your steps and could not reproduce. Could you give this another go to see if it is still an issue. This may have been an old issue.

**Comment by dolanmiu** [comment]
perhaps fixed, I cant reproduce either

closing for now
