### ISSUE TITLE
Upgrade `marked` package

### ISSUE THREAD

**Issue by neilsustc** [docsifyjs/docsify#600]
Thanks for this nice project.

The latest `marked` version is `0.4.0` but we still have `0.3.12` for `docsify`. It will be nice to upgrade it to the latest version.

---

One related issue is the parsing of raw HTML blocks. With the `marked` online demo, we have this result
![image](https://user-images.githubusercontent.com/7588612/43783880-5c1ac37e-9a95-11e8-9273-10595430e26a.png)

However, we get this result with `docsify`
![image](https://user-images.githubusercontent.com/7588612/43783959-91dd9946-9a95-11e8-8c3a-8450216e2d23.png)

**Comment by neilsustc** [comment]
Related #645.

**Comment by cheng-kang** [comment]
There is a PR for upgrading Marked. Hopefully we'll merge that one soon.
