### ISSUE TITLE
github page stays the same after file update

### ISSUE THREAD

**Issue by andrecarlucci** [docsifyjs/docsify#602]
Hi guys,

I hosted my docs pages using Github's pages.
It's working fine, but every time I create/update some file on Github, its changes are not reflected on the live version.

The only way to see the changes is if I manually delete all the local storage of my browser. Is it by design?

My documentation will change a lot and my user's won't know how to do that themselves. Any workaround or configuration?

Thanks for this great project!

**Comment by JollyGrin** [comment]
Does the page still not update hours later? 

I sometimes have a similar issue, yet if I wait a few hours then the newest version is available. I think it's github's servers, not this library (assuming we have the same problem)

**Comment by timaschew** [comment]
Usually your browser is caching some content, it depends on the HTTP headers.
@QingWei-Li do you have anything to add?

BTW: For me a hard reload works (chrome on mac: shift + cmd + r)

**Comment by QingWei-Li** [comment]
We can set the `cache-control` header on request.

https://docsify.js.org/#/configuration?id=requestheaders

```js
window.$docsify = {
  requestHeaders: {
    'cache-control': 'no-cache'
  }
};
```

**Comment by Levent0z** [comment]
This works with sidebar updates, but doesn't seem to work with the main README.md file.

**Comment by ibirnam** [comment]
@Levent0z - were you able to get it working with the main README?

@QingWei-Li - Any suggestions?

Appreciate all your help!

**Comment by sy-records** [comment]
Looks like normal

![image](https://user-images.githubusercontent.com/33931153/104665990-c36faf80-570d-11eb-8cd4-aa0b814e0025.png)
