### ISSUE TITLE
Feature request: partialfile include

### ISSUE THREAD

**Issue by mojo2012** [docsifyjs/docsify#606]
Hey, awesome software!
The only thing I miss is a way to only include a part of a file.
Say i only want to show a part of a source file, not the whole one.
Syntax could be like the regular url to the file, postfixed with `#$section` or `#11-22` for lines 11 till 22.
The section would have to be encoded into a comment, simular to how asciidoctor does it.

**Comment by mojo2012** [comment]
I think this would be really awesome!

**Comment by anikethsaha** [comment]
I didn't get this. 
Can you explain this more. With some more examples

**Comment by mojo2012** [comment]
I want to include only parts of a file, like a specific code snippet from a java class - not the whole file at once. 

Here is an example to include a whole file an render it inline (not a link):
```
[users.impex](https://raw.githubusercontent.com/spot-next/core-next/develop/spot-core/src/main/resources/data/initial/users.impex ':include')
```

It would be nice to have some sort of option, to only include some parts of the file, for example a specific line using a syntax like the following:
```
[users.impex](https://raw.githubusercontent.com/spot-next/core-next/develop/spot-core/src/main/resources/data/initial/users.impex#11-22 ':include')
```

> Mind the `#11-22` to indicate the lines!

**Comment by anikethsaha** [comment]
OK so as far as I understood.
if I have a file named `example.md`
```
1  this is first line
2  this is second
3
4
5  this is another lint
6
```

and I am embedding it using `[filename](example.md :include:)` , it will  render the whole
You are proposing 
`[filename](example.md#L2-4 :include:)` it will render 
```
 this is second


 this is another lint
``` 

If this is your proposal, then it's difficult to achieve cause we take the whole input as the source for rendering and if you want partial, then the source from where you are getting the file should response with partial data. 
I guess even Github responds with whole content even when using `#L` at the end. if the source content if partial then it will be rendered automatically partial.

one more reason its difficult is that there are many source from which you can link your files for embedding, not only from local path or from Github etc. So even if we make support for github, it wont work the same for local and other sites.


Closing this now, if you have any feedback or suggestion and even solution to this issue, comment below
