### ISSUE TITLE
Showing html file instead of README.md

### ISSUE THREAD

**Issue by petrk94** [docsifyjs/docsify#623]
Hello,
I would like to get displayed a custom html file instead of README.md, is it possible?
Thanks

**Comment by filosofikode** [comment]
You can write HTML in markdown. 

https://jsfiddle.net/3ey4ha2o/1/

https://gist.github.com/filosofikode/b6b1d6979d4c9875050e199bbef93664

**Comment by petrk94** [comment]
Yes I know, this work, but I want to embed even a php script and this doesnt work.

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/embed-files
