### ISSUE TITLE
Autoscroll from incoming links to sub-header topics fails to scroll topic to top of viewport

### ISSUE THREAD

**Issue by billhennessy** [docsifyjs/docsify#624]
Description: 
When linking directly to sub-header, autoscroll stops before the target sub-header comes into view. But clicking the link sidenav works as expected.

Repro:
Prereqs: At least 2 sublevels 
* Expand a header in sidenav
* Click a sub-header
RESULT: Autoscroll to subhead
* Copy the url, including the querystring 
* Paste the url with querystring into new browser window and hit Enter/return
RESULT: page opens well above the sub-header requested
EXPECTED: page scrolls to sub-header requested

Configuration:
```
window.$docsify = {
      name: 'Incentive 1.0 User Guide',
      ga: 'UA-56060399-4',
      auto2top: true,
      loadSidebar: true,
      loadNavbar: true,
      mergeNavbar: true,
      subMaxLevel: 3,
      themeColor: '#003da5',
      logo: '/images/logo.png',
      autoHeader: true,
      themeable: {
        responsiveTables: false // default
      },
      notFoundPage: '_404.md',
      search: {
        paths: [
          '/', // => /README.md
          '/communications',
          '/content',
          '/files',
          '/groups',
          '/help',
          '/programs',
          '/participants',
          '/programdeepdive',
          '/reports',
          '/rich_text_editor',
          '/release_notes'
        ],
        placeholder: 'Search',
        noData: 'Nothing Found',
        depth: 2
      },
```

**Comment by segmentseth** [comment]
I'm seeing this issue too and would LOVE guidance on fixing.  Thanks!

**Comment by billhennessy** [comment]
If anyone has ideas for workarounds, I'll try anything.

**Comment by billhennessy** [comment]
Anyone know if this being addressed by another issue? We need to be able to deep link from our product to the corresponding documentation, and this issue prevents that use case.

**Comment by jhildenbiddle** [comment]
@billhennessy --

Can you provide a link to a site or create a demo (stackblitz.com and codesandbox.io work well) that reproduces the issue?

I've followed the steps to reproduce on the following two pages:

* https://docsify.js.org/#/configuration?id=namelink
* https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=copy-code

On both sites, the header in question is positioned at the top of the viewport as expected, although on docsify.js.org it is roughly 20px lower when the URL is pasted vs. when it is clicked. So the issue you're describing doesn't present itself on all sites. 

Without looking at the source, I would guess that docsify's scroll calculations aren't accounting for content that loads asynchronously (like images) or is injected after the page has been rendered (via plugins) which can cause header positions to change. With a demo, I have something to troubleshoot. Without one, I have to first try and come up with a scenario that fails before I can fix anything.

**Comment by billhennessy** [comment]
John,

Thanks for the help.

My prototype site is at https://suspicious-lumiere-d001c9.netlify.com/#/

<https://suspicious-lumiere-d001c9.netlify.com/#/>
A <https://suspicious-lumiere-d001c9.netlify.com/#/>nd this site is heavy
on images, so your suspicion is probably a good one.

Thanks!

On May 4, 2019 at 16:15:31, John Hildenbiddle (notifications@github.com)
wrote:

@billhennessy <https://github.com/billhennessy> --

Can you provide a link to a site or create a demo (stackblitz.com and
codesandbox.io work well) that reproduces the issue?

I've followed the steps to reproduce on the following two pages:

   - https://docsify.js.org/#/configuration?id=namelink
   -
   https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=copy-code

On both sites, the header in question is positioned at the top of the
viewport as expected, although on docsify.js.org it is roughly 20px lower
when the URL is pasted vs. when it is clicked. So the issue you're
describing doesn't present itself on all sites.

Without looking at the source, I would guess that docsify's scroll
calculations aren't accounting for content that loads asynchronously (like
images) or is injected after the page has been rendered (via plugins) which
can cause header positions to change. With a demo, I have something to
troubleshoot. Without one, I have to first try and come up with a scenario
that fails before I can fix anything.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docsifyjs/docsify/issues/624#issuecomment-489366185>,
or mute the thread

**Comment by janikvonrotz** [comment]
Update: For people arriving here in 2020. I applied the fix as proposed by @oeway 

https://github.com/Mint-System/Knowledge/blob/fcc1778f57ab66240b3fd8235bcdfa47ca34f801/index.html#L66
