### ISSUE TITLE
Ability to Randomize Image on Coverpage

### ISSUE THREAD

**Issue by actuallyReallyAlex** [docsifyjs/docsify#628]
I'd like to create a plugin for adding the ability to randomize the image on the coverpage when a user refreshed the page.

I wrote a small bit of code that accomplished this for my own app, and I plan to made it into it's own npm package this week. I would also like to implement this in Docsify as a plugin.

Would you guys be interested in this?

Heres a demo:

![demo of random image](https://user-images.githubusercontent.com/41493792/45923096-680cba00-be91-11e8-8c6c-9a497be2baad.gif)

**Comment by jthegedus** [comment]
@alexlee-dev Have you created this package? I think the best way to get a plugin into this ecosystem would be to create it and publish it yourself, then PR an addition to [awesome-docsify plugins](https://github.com/docsifyjs/awesome-docsify/blob/master/README.md#plugins)

**Comment by alexlee-dev** [comment]
@jthegedus Yes but it isn't published yet. I need to go back and do that. I apologize for the delay. Will do this month ideally. Hard to find time.

**Comment by alexlee-dev** [comment]
Will close issue and linked to published package once done.

**Comment by jhildenbiddle** [comment]
Please add to community plugins in the [Awesome Docsify](https://github.com/docsifyjs/awesome-docsify) repo.
