### ISSUE TITLE
Associate CSS with sidebar sections

### ISSUE THREAD

**Issue by Kikobeats** [docsifyjs/docsify#643]
<img width="245" alt="screen shot 2018-10-10 at 21 09 02" src="https://user-images.githubusercontent.com/2096101/46759938-dc888b00-ccd0-11e8-8b8e-805fb7f5ac7b.png">

Hello,

I want to style different sidebar sections.

In the screenshot, `notification` correspond to a `h4` in markdown and the rest are `h5`.

The problem I found is a css class is not associated with the markup generated in the sidebar, so I can't apply different style.

right now

```
<li class="">
  <a class="section-link" href="#/?id=notification">notification</a>
</li>
```

expected

```
<li class="">
  <a class="section-link sidebar-h4" href="#/?id=notification">notification</a>
</li>
```

**Comment by cheng-kang** [comment]
You can target `h4` level subside bar element by using `.sidebar-nav > ul > li > ul > li > ul > ul > ul > li`.

**Comment by Kikobeats** [comment]
not too intuitive 🤔

**Comment by cheng-kang** [comment]
It's not ideal, but meets the need.

**Comment by didiraja** [comment]
Just what I needed, really into specify classname to elements

**Comment by Kikobeats** [comment]
EH EH DONT CLOSE BRO

**Comment by anikethsaha** [comment]
Please can you describe the issue you are requesting . 
The screen shot is not showing. maybe the link expired.

Please check

**Comment by anikethsaha** [comment]
ok please correct me if I am wrong 

you want to add `sidebar-h4` class to the `li > a` for sidebar-section ?

**Comment by trusktr** [comment]
I opened an issue about making better markup for the sidebar, https://github.com/docsifyjs/docsify/issues/1181, before I saw this one.

**Comment by trusktr** [comment]
I'll close this one in favor of the other one, where we can discuss more markup changes that in general can make the sidebar styling/theming more robust.
