### ISSUE TITLE
Bug in displaying the text of URL

### ISSUE THREAD

**Issue by acierto** [docsifyjs/docsify#647]
If to have in URL ending on closed bracket `)`  it will be displayed as a part of text, though it shouldn't.

Example:
`[Jenkins Job](https://jenkins-ng.com/jenkinsng/job/job/Plugins/job/Release/job/explorer/job/master/job/Release/explorer%20(No%20Tests))`

Btw, GitHub here in the comments displays it properly if to remove ticks :)

Result ->
![screen shot 2018-10-18 at 08 15 40](https://user-images.githubusercontent.com/2265094/47134722-0e3fba00-d2ae-11e8-8de9-3eb3b1e687e6.png)
Expected ->
Jenkins Job

**Comment by cheng-kang** [comment]
Just tried `marked@0.5.1`, it works as expected. 

I can see there is a [PR](https://github.com/docsifyjs/docsify/pull/645) upgrading `marked` to v0.5.1, so hopefully it will be merged soon and this will be resolved.

**Comment by cheng-kang** [comment]
Should have been fixed after `v4.8.0` https://github.com/docsifyjs/docsify/commit/137ae8d5b8c377cd8de79de8f60f4bb272bc7f62
