### ISSUE TITLE
SSR Docsify not showing sub-sidebars when entered from url with anchor

### ISSUE THREAD

**Issue by cheng-kang** [docsifyjs/docsify#650]
### How to reproduce?

- Open https://docsify.now.sh/plugins?id=google-analytics

Expecting:
<img width="290" alt="screenshot 2018-10-18 at 23 07 19" src="https://user-images.githubusercontent.com/8396515/47187070-995e9580-d32a-11e8-9c69-cb8838c8941f.png">

Got:
<img width="302" alt="screenshot 2018-10-18 at 23 07 46" src="https://user-images.githubusercontent.com/8396515/47187092-a8454800-d32a-11e8-9a78-a5a851780f0f.png">

This issue might be related to https://github.com/docsifyjs/docsify/issues/509.

**Comment by jthegedus** [comment]
@anikethsaha Are you willing to mark this as closed.

**Comment by anikethsaha** [comment]
I think it has been fixed. I will try to check this one more time and will close this then

**Comment by anikethsaha** [comment]
Yes , it has been fixed. Thanks for pointing @jthegedus

**Comment by trusktr** [comment]
Note: SSR is still experimental and incomplete, not ready for prime time. Plugins are not supported yet, and various features of Docsify do not work.
