### ISSUE TITLE
Release 4.8.0 break things, e.g. https://jhildenbiddle.github.io/docsify-tabs   tab doesn't work any more.

### ISSUE THREAD

**Issue by jonnyhsy** [docsifyjs/docsify#663]

**Comment by jonnyhsy** [comment]
Also, if I'd like to download and import docsify.min.js@4.7.1, where could I find it?

**Comment by jonnyhsy** [comment]
> Also, if I'd like to download and import docsify.min.js@4.7.1, where could I find it?

Reply myself in case this is useful to others:
**Use**
**`<script src="https://unpkg.com/docsify@4.7.1/lib/docsify.min.js"></script>`**
Instead of
`<script src="https://unpkg.com/docsify/lib/docsify.min.js"></script>`

**Comment by QingWei-Li** [comment]
You can specify the version number, for example

```html
<script src=//unpkg.com/docsify@4.7.0></script>
```

I will check it.

**Comment by jonnyhsy** [comment]
Thanks!

**Comment by QingWei-Li** [comment]
fixed in `4.8.1`

**Comment by QingWei-Li** [comment]
@jhildenbiddle 

This DOM has changed and caused docsify-tab to not work, can you fix it?
Now all html code will be in the p tag.

**Comment by jhildenbiddle** [comment]
Fixed in docsify-tabs 1.0.6

Thanks for the heads up, @QingWei-Li!

**Comment by QingWei-Li** [comment]
You are right. I reread the marked source code, it does not wrap the block-level elements.

**Comment by jhildenbiddle** [comment]
Hehe...

That's why I deleted my comment about wrapping all HTML in a `<p>`. Turns out `<button>` tags are wrapped, but not all HTML. 😄
