### ISSUE TITLE
Markdown for images isn't playing well with HTML anymore

### ISSUE THREAD

**Issue by dooart** [docsifyjs/docsify#667]
If you use the image markdown syntax to render an image and put it near HTML code, Docsify will render it as text. The problem was introduced in version 4.8.0.

For example, this would **not** render the image:
```
<div>
![](img.png)
</div>
```

This would also **not** render the image:
```
<br/>
![](img.png)
```

But this would (empty line between HTML and markdown):
```
<br/>

![](img.png)
```

**Comment by QingWei-Li** [comment]
@cheng-kang you're right.
We should follow the mainstream usage.

**Comment by QingWei-Li** [comment]
But I will add a new **custom component feature** so that we can use markdown in HTML.

**Comment by QingWei-Li** [comment]
I found this can be rendered by adding spaces in html...

https://codesandbox.io/s/z2k36lqlrp

```md
# Quick start

<div style='color: red;'>

- a
- b
- c

</div>
```

**Comment by chnuessli** [comment]
@cheng-kang your proposed way doesn't work for me in docsify
`<br/>

![logo](../assets/logo_srz.svg)`

**Comment by MirrorGarak** [comment]
Hi,
I am brand new to this but finally managed to deploy my site! Yay!
However, my images only show on localhost, not when hosted but github pages, with the exception of the sidebar SVG.

Code looks like this:
<p><img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250"></p>

Localhost inspect source:
<p>
<img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250">
</p>

Hosted (doesn't show image)
<img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250"></p>
    ::before
  </img>

Any advice? why is the local preview not the same as github pages?
Cheers

**Comment by MirrorGarak** [comment]
Hi,
I am brand new to this but finally managed to deploy my site! Yay!
However, my images only show on localhost, not when hosted but github pages, with the exception of the sidebar SVG.

Code looks like this:

`<p><img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250"></p>`

Localhost inspect source:

```
<p>
  <img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250">
</p>

```
Hosted (doesn't show image)

```
<p>
  <img src="/_media/banner_sg_lootopians.png" alt="banner_lootopian" width="750" height="250"></p>
    ::before
  </img>
</p>
```

Any advice? why is the local preview not the same as github pages?
Cheers

**Comment by trusktr** [comment]
Not sure what's up with your images. I would check what errors you see in console. Maybe where you serve them from the same URLs are not valid
