### ISSUE TITLE
Coverpage link bug in >= 4.8.1

### ISSUE THREAD

**Issue by dbanksdesign** [docsifyjs/docsify#677]
Here is my coverpage markdown file: https://github.com/amzn/style-dictionary/blob/master/docs/_coverpage.md

I noticed the github button styling broke in recent versions. I rolled back to 4.8.0 and they work again. Here is the issue that was filed on our repo: https://github.com/amzn/style-dictionary/issues/185

It looks like the docsify parser was not adding `data-button` to the github link for some reason. And the stylesheet in <= 4.8.0 was not targeting `data-button` to style those buttons.

**Comment by QingWei-Li** [comment]
`v4.8.4` is released.
