### ISSUE TITLE
Colon (`:`) between 2 words in header disappears

### ISSUE THREAD

**Issue by sylwekb** [docsifyjs/docsify#679]
Hey,

I use a header like this:

```md
### `/autocontrast:3/`
```

The result is:
<img width="190" alt="screen shot 2018-11-02 at 12 36 18" src="https://user-images.githubusercontent.com/2721405/47913315-f1a1a580-de9b-11e8-881a-2f0e22c2c372.png">

And the html looks like this:

<img width="395" alt="screen shot 2018-11-02 at 12 37 06" src="https://user-images.githubusercontent.com/2721405/47913342-09792980-de9c-11e8-8e6f-d57441487dc7.png">

Tried on Firefox and Chrome, in both cases the `:3` is missing. I have the `noEmoji: true,` setting but it seems docsify still tries to parse.

Please help :)

**Comment by sylwekb** [comment]
Hey, thanks for a quick answer, unfortunately it didn't work:

```md
### \`/autocontrast:3/\`
```
Produces:
<img width="234" alt="screen shot 2018-11-02 at 14 41 44" src="https://user-images.githubusercontent.com/2721405/47918657-7fd25780-dead-11e8-95f9-7632baa2a519.png">

**Comment by cheng-kang** [comment]
Ah, sorry, I missed the `:3` part. My guess is that the problem is with config parsing. Because Docsify allows users to configure by adding `:CONFIG_NAME=CONFIG_CONTENT`.

Will check later.

**Comment by sylwekb** [comment]
> ... Docsify allows users to configure by adding `:CONFIG_NAME=CONFIG_CONTENT`.

Thanks! I would be equally happy with a workaround if a proper fix is too complicated ;) Can you point to the documentation which describes this `:config` behavior? For me it looks like it's `alias` https://docsify.js.org/#/configuration?id=alias but i'm not sure

**Comment by cheng-kang** [comment]
This page describes a few configs you can use: https://docsify.js.org/#/helpers?id=customise-id-for-headings

**Comment by sylwekb** [comment]
To everybody who has the same problem. The [regexp is here](https://github.com/docsifyjs/docsify/blob/v4.8.5/src/core/render/compiler.js#L22). The workaround I found is to use other colon: https://unicode-table.com/en/A789/
Normal colon: `:`
Modifier Letter Colon: `꞉`

**Comment by sylwekb** [comment]
Just realized it not good workaround if you  allow users to copy it and use somewhere where the fact that it's a real colon is important ;D

**Comment by sylwekb** [comment]
AFAIU I does not make sense to set more than 1 id for heading, so it's enough to remove `g` at the end of the regexp       .replace(/:([\w-]+)=?([\w-]+)?/g, (m, key, value) => {

**Comment by QingWei-Li** [comment]
We should allow the user to use the content of `:xx=yy`, just match it to when `\:xx=yy` will not be processed.

**Comment by vsespb** [comment]
> We should allow the user to use the content of `:xx=yy`, just match it to when `\:xx=yy` will not be processed.

We're affected by current bug and we use same Markdown in docsify and NOT in docsify at same time. So adding escapes like this `\:xx=yy` to all our markdown will damage it for world outside of docsify.

maybe use this PR instead https://github.com/docsifyjs/docsify/pull/708
i.e. process configs only when there is a space/start of line before colon.

**Comment by Kikobeats** [comment]
Related: https://github.com/docsifyjs/docsify/issues/698

**Comment by jonesjj** [comment]
> To everybody who has the same problem. The [regexp is here](https://github.com/docsifyjs/docsify/blob/v4.8.5/src/core/render/compiler.js#L22). The workaround I found is to use other colon: https://unicode-table.com/en/A789/
> Normal colon: `:`
> Modifier Letter Colon: `꞉`

This proved an acceptable workaround for me.  Thanks @sylwekb

**Comment by sylwekb** [comment]
@jonesjj be careful. If you want your users/readers to be able to use the headline by copying it, they will copy the wrong colon, and anything that needs to interpret it won't work - that's my case.

**Comment by anikethsaha** [comment]
This has been resolved . Update to latest version 

PLease comment if it still an issue


Firefox 

![image](https://user-images.githubusercontent.com/26347874/74962589-37d69b80-5436-11ea-9251-1a682d80343d.png)

Chrome 

![image](https://user-images.githubusercontent.com/26347874/74962607-42913080-5436-11ea-840b-5ab79ddddf48.png)


Edge

![image](https://user-images.githubusercontent.com/26347874/74962710-6e141b00-5436-11ea-85d1-9377a194424e.png)
