### ISSUE TITLE
Breaking change on v4.8.*

### ISSUE THREAD

**Issue by dialex** [docsifyjs/docsify#681]
[This is my live website](https://dialex.github.io/start-testing/#/). Now it's fine because I've fixed docsify's version on `4.7.1`. However, if I change to `4.8.*` several issues occur:
- The background custom color is ignored
- The style of the button disappears
- The sidebar links break

I've already compared my index.html with the latest template and it looks fine. I have no idea what causes that. Examples below.

4.7.1 (ok):
<img width="467" alt="screenshot 2018-11-02 at 17 20 19" src="https://user-images.githubusercontent.com/2140450/47931308-5eca3080-dec6-11e8-887a-ea8a581ee236.png">

4.8.0 (not ok):
<img width="547" alt="screenshot 2018-11-02 at 17 20 08" src="https://user-images.githubusercontent.com/2140450/47931307-5eca3080-dec6-11e8-95b0-3feecbd4d54c.png">

4.8.0 (broken sidebar):
<img width="298" alt="screenshot 2018-11-02 at 17 35 56" src="https://user-images.githubusercontent.com/2140450/47931309-5eca3080-dec6-11e8-887c-6dca04b30eb1.png">

Thoughts?

**Comment by cheng-kang** [comment]
Please update to `4.8.3` and see if the issues stay.

**Comment by dialex** [comment]
Yup, same broken behaviour 😢

**Comment by cheng-kang** [comment]
According to https://marked.js.org/#/README.md#specifications`marked` is following [CommonMark](https://spec.commonmark.org/0.28/). Space in link is not supported as per [the specs](https://spec.commonmark.org/0.28/#link-destination).

Alternatively, for now, you could use `<img data-origin="linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%)" alt="color">`; so that you can still use latest version and have all other fixes applied to your site.

@QingWei-Li I guess we need to make a decision on whether or not to add support for space in link in Docsify.

**Comment by QingWei-Li** [comment]
@cheng-kang I think we should follow the rules. 
But to be compatible with using space characters in custom background color.

@dialex About the sidebar, You should split the line between the html tag and the markdown content. I don't think this is a bug in docsify, it will also render errors on github.

![image](https://user-images.githubusercontent.com/7565692/48108999-a82cce00-e280-11e8-8329-74d1f4aa6b7e.png)

**Comment by dialex** [comment]
@cheng-kang I followed your tip and replaced  `![color](linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%))` with `<img data-origin="linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%)" alt="color">` but it **didn't solve** the issue. 😢 

![image](https://user-images.githubusercontent.com/2140450/48279089-6bf79a00-e447-11e8-8d98-4cb8338983bd.png)

As for the sidebar, you were **right**, it just needed a newline between the html code and the markdown. Amazing, thanks a lot! 👍

**Comment by cheng-kang** [comment]
@dialex sorry, this should do the trick: `<p><img data-origin="linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%)" alt="color"></p>`.

Will resolve the issue ASAP.

**Comment by extrapixel** [comment]
For this reason I openend #665 and #666 which both are not fixed (but closed).

**Comment by cheng-kang** [comment]
@extrapixel they were closed because they were fixed by https://github.com/docsifyjs/docsify/pull/669

But the fix was reverted by https://github.com/docsifyjs/docsify/pull/678.

Reopening them now.

**Comment by cheng-kang** [comment]
@extrapixel I think both are closed because they are fixed. Have you tried latest version?

Regarding background colour, the case here is different.

**Comment by dialex** [comment]
@extrapixel if you use the latest Docsify (v4.8.3) and change the background colour declaration to something like: `<p><img data-origin="linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%)" alt="color"></p>` (like @cheng-kang suggested)...
- The correct background colour is displayed ✅
- And magically the button style gets also fixed ✅

Give it a try! I'll close this issue because it's fixed for me.
Thanks @cheng-kang !

**Comment by extrapixel** [comment]
> Give it a try! I'll close this issue because it's fixed for me.

It's not fixed. If you want to fix it, at least update the documentation: https://docsify.js.org/#/cover?id=custom-background

**Comment by dialex** [comment]
I'm still not sure if @cheng-kang code snippet is the new way of settings a bkg colour or just a workaround. Anyway you're right, I could do a PR, here it is https://github.com/docsifyjs/docsify/pull/724

**Comment by cheng-kang** [comment]
@extrapixel have you tried the latest version? I remember there was a fix released, and just checked `v4.8.6`, it's working as expected.

**Comment by cheng-kang** [comment]
@extrapixel chill...

Because I just tested again, created a new project with `docsify-cli`, using latest source code from `unpkg`. And this works:

```
![color](red)
```

Do you have a link for me to check?

**Comment by dialex** [comment]
@timaschew ,
as of the latest version (`4.9.4`) what is the proper way to set background colour use a gradient?

It used to be like this

```md
![color](linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%))
```

But then `4.8.0` broke it. As a workaround we could (and still can on `4.9.4`) use:

```
<p><img data-origin="linear-gradient(to left bottom, #F0FD37 0%, #ACF260 100%)" alt="color"></p>
```

Do we still need to use that workaround? Or is there a markdown way to do it? I don't see that feature listed in the official doc anymore.
