### ISSUE TITLE
Created a plugin for embedding pdf in Docsify

### ISSUE THREAD

**Issue by lazypanda10117** [docsifyjs/docsify#684]
I have created a plugin for embedding pdf in Docsify [here (published to npm)](https://www.npmjs.com/package/docsify-pdf-embed-plugin) and I think it might be useful for others who want to implement this functionality, yet I don't really know where to post this other than here in Docsify issue. Please let me know if there are better ideas. Thanks a lot.

**Comment by upupming** [comment]
It's awesome, maybe you can add it to [awesome-docsify](https://github.com/docsifyjs/awesome-docsify).

**Comment by lazypanda10117** [comment]
That's a good idea, thanks! I will do that after making a patch for the plugin.
