### ISSUE TITLE
how to set logo link target _blank

### ISSUE THREAD

**Issue by ArvoGuo** [docsifyjs/docsify#694]
<img width="312" alt="2018-11-09 11 07 07" src="https://user-images.githubusercontent.com/7940591/48241004-0b993600-e410-11e8-8dea-aa250b853948.png">
<img width="312" alt="2018-11-09 11 07 07" src="https://user-images.githubusercontent.com/7940591/48241026-1f449c80-e410-11e8-8963-a776f531561c.png">

怎么给 app-name-link 加个 target="_blank"

docsify@4.8.5

**Comment by anikethsaha** [comment]
@timaschew We need to tackle this kind of new tab request in a better way.

My suggestion

config would look like this

```js
window.$docsify = {
  name: {
    sitename: "your site name",
    href: "http:your.site",
    target: "_blank"
  }
};
```

And this type of refactoring can be done for all type of link configured by the config object

And simply
