### ISSUE TITLE
images broke with relative path to embedded file

### ISSUE THREAD

**Issue by jiao-zhangS** [docsifyjs/docsify#695]
I created a markdown file A with another markdown file B embedded in. 
For file B some images are added using relative path to file B. The problem is when file A is converted into html, images linked in file B do not render properly.  
It looks for the images in the relative path to file A but clearly they do not exist there. Is it possible to let docsify look for the images still using the relative path to file B?

**Comment by rilc0n** [comment]
I have the same problem...

**Comment by CoderFeiSu** [comment]
I have the same problem...

**Comment by filipgoc** [comment]
Me too.
