### ISSUE TITLE
如何去掉首页链接中的#号

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#696]
首页的链接也有 /#/，看起来好别扭，有没有办法去掉？多谢~

**Comment by cheng-kang** [comment]
可以将 `routerMode ` 设置为 `history`. https://docsify.js.org/#/configuration?id=routermode

**Comment by tonglei100** [comment]
我的站点是托管在 GithHub Pages 上的，设置了 history 模式，但服务端无法配置，这样会导致其他页面都是 loading 状态

其实我只是想首页去掉/#/就可以了，不知道这个有没有办法优化

**Comment by upupming** [comment]
#720
