### ISSUE TITLE
Escape `:` into markdown titles

### ISSUE THREAD

**Issue by Kikobeats** [docsifyjs/docsify#698]
I have documentation with `:` inside markdown title:

```
#### payment:create
```

The previous version was rendered fine, but now the docsify engine is escaping wrongly, just showing `payment`into the menu

expected:

![screenshot 2018-11-12 at 13 49 39](https://user-images.githubusercontent.com/2096101/48348499-d431c000-e681-11e8-90d1-bddfbae48885.png)

current:

![screenshot 2018-11-12 at 13 49 06](https://user-images.githubusercontent.com/2096101/48348507-d85ddd80-e681-11e8-8df2-6a693f0f0320.png)

**Comment by anikethsaha** [comment]
this has been resolved. please use the latest version
