### ISSUE TITLE
Links to headers starting with numbers are broken

### ISSUE THREAD

**Issue by dansanduleac** [docsifyjs/docsify#700]
Example:

```
## 1. First Section

later, refer to the [First Section](#1-first-section).
```

* the link under "First Section" doesn't work. It tries to visit `?id=1-first-section` 
* the link in the sidebar works, because it visits `?id=_1-first-section` (notice the leading underscore)

If docsify is prepending underscores to certain anchors, the targets of user's anchors should be transformed as well.

cc @iamdanfox

**Comment by anikethsaha** [comment]
This has been resolved. Please use the latest version .

Thanks
