### ISSUE TITLE
能不能去掉谷歌的css文件

### ISSUE THREAD

**Issue by Jadyli** [docsifyjs/docsify#701]
<img width="946" alt="2018-11-15 9 13 13" src="https://user-images.githubusercontent.com/15962904/48555184-6a344780-e91b-11e8-8d4b-dd85f5d08686.png">
能不能去掉谷歌的这个css文件，经常卡住加载不出来。

**Comment by MythRen** [comment]
@QingWei-Li  *.googleapis.com blocked by Chinese GFW, so users in China visit the docs site using docsify can't load the css & fonts from *.googleapis.com.   

i would suggest to load the assets from CDN, but currently i don't known which CDN is better for all of us.

**Comment by QingWei-Li** [comment]
In the next version I will provide the style files without built-in fonts.

**Comment by timaschew** [comment]
Please use English language.
