### ISSUE TITLE
Can the catalog of the sidebar be fully contracted

### ISSUE THREAD

**Issue by drdevelop** [docsifyjs/docsify#702]
Can the catalog of the sidebar be fully contracted, instead of the current level 3 title of the md file now shrinking? Because sometimes unnecessary directories all appear together, the visual feeling is very confusing

**Comment by trusktr** [comment]
I'm not sure exactly what you meant by this (and sorry for such a long time with no reply), but there is an issue for re-vamping the sidebar and making all sections collapsible: https://github.com/docsifyjs/docsify/issues/1180. I think this would cover any cleanup you mentioned.
