### ISSUE TITLE
Docsify rendering problem on newer versions, works on 4.7.1

### ISSUE THREAD

**Issue by satu0king** [docsifyjs/docsify#710]
Website: https://docs.circuitverse.org/#/getting_started

Rendering Error
![image](https://user-images.githubusercontent.com/2092958/49228785-18f38000-f412-11e8-8973-b8a1a164276f.png)

However when I rolled back to version 4.7.1, it started working correctly. 

Correct Rendering on 4.7.1
![image](https://user-images.githubusercontent.com/2092958/49229076-c1a1df80-f412-11e8-836a-d1628efe0df2.png)

**Comment by timaschew** [comment]
Still broken with 4.8.6

It's related to so video element (maybe also with others).

If you have more than 1 of these lines: `[filename](/video/drag.mp4 ':include :type=video')` it breaks
