### ISSUE TITLE
不能识别自定义组件里的方法，想实现在线编辑实时预览效果。

### ISSUE THREAD

**Issue by oyboyb** [docsifyjs/docsify#713]
之前尝试在.md文件中嵌入自定义vue组件，组件模板里如果是这样“ <my-input @change="changeFun"><my-input/> ”绑定方法，会直接当作字符串。
另外，script 里面的vue脚本也是没有用的，只能支持普通js脚本。

目的：想实现一个支持我们公司内部组件，并且能在线编辑实时预览内部组件变化的效果，麻烦给点意见
哈

**Comment by oyboyb** [comment]
打字错了，上一条信息应该是“给点意见”，抱歉。

**Comment by cheng-kang** [comment]
`marked` 不支持自定义标签所以可能没办法实现了。
