### ISSUE TITLE
TOC question with subfolders

### ISSUE THREAD

**Issue by chrisschaub** [docsifyjs/docsify#715]
It seems there is no way to automatically populate a complete TOC sidebar with all nested levels (even with alias) if you have subfolders. Once you view a doc in a subfolder, it will lose the navigation items from the higher parent level. It seems you have to explicitly create the _subfolder.md in this case at the top level, with all the links you want. Otherwise, just keep all docs in the main folder? Thanks.

**Comment by cheng-kang** [comment]
Answer is yes, there is no way.

`docsify` knows nothing about folder structure, and doesn't generate sidebar from folder structure. It either loads `_sidebar.md` or parses the `md` file of current url for sidebar data.
