### ISSUE TITLE
Question: is it possible to get the version number from the package.json file?

### ISSUE THREAD

**Issue by nidkil** [docsifyjs/docsify#716]
Love docsify! Thx!

I have used the docsify `_coverpage.md` file as the basis for my own coverpage. I would like to automatically update the version number that is displayed using the version number in the `package.json` file. Is their a way to do this? A caveat here is that the version number is bumbed (incremented) when I create a new release with [release-it](https://github.com/webpro/release-it).

Any help is appreciated. Thx!

**Comment by cheng-kang** [comment]
Sorry, I don't think this feature would be implemented in `docsify`.

My suggestion would be:

- adding a new node script that reads new version number in `package.json` and writes it to `_coverpage.md`
- hook it with [`scripts.afterBump`](https://github.com/webpro/release-it#scripts) of `release-it`.

Hope it helps.

**Comment by nidkil** [comment]
Thx. I have created a [small library] (https://github.com/nidkil/use-pkg-version) that can update version numbers in static files using regex.
