### ISSUE TITLE
Markdown header broken since v4.8.3

### ISSUE THREAD

**Issue by Kikobeats** [docsifyjs/docsify#717]
If I block the version to `v4.8.2`, the `Get Started` is correctly rendered

<img width="1392" alt="screenshot 2018-12-11 at 12 42 31" src="https://user-images.githubusercontent.com/2096101/49798349-5c1eee80-fd42-11e8-9560-d671e796cf34.png">

But using any version since that (v4.8.3 to latest), the first header is not rendered:

<img width="1392" alt="screenshot 2018-12-11 at 12 44 15" src="https://user-images.githubusercontent.com/2096101/49798409-7b1d8080-fd42-11e8-9209-e6e43c3c88a1.png">

**Comment by dabrave** [comment]
same issue here. Thanks Kikobeats for pointing it out!

**Comment by timaschew** [comment]
That is very strange. Can you double check if that is really related to the docsify?
Basically nothing has changed from [4.8.2. to 4.8.3](https://github.com/docsifyjs/docsify/compare/v4.8.2...v4.8.3)

**Comment by timaschew** [comment]
I found it it's related to the upgrade of the markdown parser, which happened unfortunately between 4.8.2 and 4.8.3 even if it's not documented nor seen by any package.json or package-lock.json (but this is another topic).

It seems that a [regex has changed](https://github.com/markedjs/marked/blob/c77a2244ab5d4a0e1dec0979a51b80df87ec6409/lib/marked.js#L19) which influence headers if they're used after html code.

@Kikobeats you're using a docsify plugin which prepends some HTML code for the edit button.
It seems that there is a requirement that if you want to mix HTML with markdown you need to use **two blanklinkes** (`\n`) as delimiter.

**Comment by Kikobeats** [comment]
It works! Thanks for addressing that 🙂
