### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wan766405890** [docsifyjs/docsify#719]
> docsify@4.8.6 watch:js F:\Pocs\docsify
> node build/build.js

ERROR: Task not found: "'css"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.8.6 watch:css: `run-p 'css -- -o themes -w'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.8.6 watch:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-14T02_54_01_730Z-debug.log
ERROR: "watch:css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.8.6 dev: `run-p serve watch:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.8.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-14T02_54_02_136Z-debug.log

**Comment by timaschew** [comment]
Please translate your question into English.

**Comment by keer6** [comment]
Execute the following code ： npm run bootstrap && npm run dev 。
Report errors

**Comment by timaschew** [comment]
Not reproducible or fixed
