### ISSUE TITLE
table in sub headers not rendering

### ISSUE THREAD

**Issue by hurshi** [docsifyjs/docsify#722]
Hi, thanks for docsify,
I am facing a problem that cannot be solved

#### Desc
I have a table in sub header, and so I taped some blank space key(a tab),it's ok in `typora`,but the table is not rendered after I push to docsify.

#### DEMO
https://hurshi.github.io/#/blog/android/bug_issues/not_support_table_with_tabs

**Comment by cheng-kang** [comment]
Seems `marked` and `typora` have different rules for parsing and rendering.

Solution is to add two new lines before the table:
```diff
* This is a TEST


  | test1 | test2 |
  | ----- | ----- |
  | t1    | T2    |
```

**Comment by hurshi** [comment]
#### thanks for your reply.
* It worked, the table was rendered

#### but it's not perfect for me

* The table is not align at the left of head like below:
	* The head of the table

		|t1|t2|
		|---|---|
		|b1|b2|
* docsify rendered like below:
	![nwiwant](https://user-images.githubusercontent.com/7411658/50389206-62f62a00-0762-11e9-9461-e0230bd39112.jpg)
* I updated the Demo: https://hurshi.github.io/#/blog/android/bug_issues/not_support_table_with_tabs

**Comment by cheng-kang** [comment]
@hurshi looks like this is a known issue of `marked`: https://github.com/markedjs/marked/issues/1246, will follow any update.

A temp workaround until this issue is resolved:

```

* This is what i want

<div style="margin-left: 1.5rem;">

  | test1 | test2 |
  | ----- | ----- |
  | t1    | T2    |

</div>
```

**Comment by hurshi** [comment]
OK, Thanks a lot 🙏

**Comment by timaschew** [comment]
Closing because this is a bug in markedjs/marked#1246

**Comment by mlms13** [comment]
The bug in `marked` has been fixed, but docsify is still depending on an outdated version. Merging #862 would be much appreciated, thanks!
