### ISSUE TITLE
多页时侧边栏配置了subMaxLevel无效

### ISSUE THREAD

**Issue by wsyks** [docsifyjs/docsify#726]
已经设置了subMaxLevel，在多页的情况下还是无法自动生成子目录，
```
window.$docsify = {
        subMaxLevel: 2,
        name: "",
        repo: "",
        loadSidebar: true,
        loadSidebar: "_sidebar.md",
        auto2top: true, //当路径改变时，滚到屏幕顶部
        maxLevel: 2,
        search: {
          paths: "auto", // or 'auto'
          placeholder: "搜索",
          noData: "No results"
        }
      };
```

**Comment by wsyks** [comment]
找到原因了，文件不能是中文

**Comment by hudc** [comment]
> 找到原因了，文件不能是中文

Hi，I test about the file name with chinese, it can auto generate the content.

**Comment by wsyks** [comment]
> > 找到原因了，文件不能是中文
> 
> Hi，I test about the file name with chinese, it can auto generate the content.

Yes，at the beginning, i change my file name from Chinese to English, the problem was solved ,so  i guess it  because of Chinese file name, but actually it due to the space in the file name,  
I created a codesandbox ,it is the origin file setting https://codesandbox.io/s/7porz3x7j.
