### ISSUE TITLE
code fund ad doesn't work

### ISSUE THREAD

**Issue by njleonzhang** [docsifyjs/docsify#729]
https://github.com/docsifyjs/docsify/blob/6ac7bace213145cb655e9a5e9e209384db08e5f9/docs/index.html#L80

as codefund upgrade, the api sia changed, you need change the token to a property id. follow the new document for more details. 

https://github.com/njleonzhang/docsify-plugin-codefund

**Comment by timaschew** [comment]
@njleonzhang thanks!
