### ISSUE TITLE
docsify如何设置资源文件根路径

### ISSUE THREAD

**Issue by RamblerW** [docsifyjs/docsify#732]
因访问github资源网速比较慢，我想把docsify中的资源文件全部使用对象存储的方式来引用，所以想请问下，有没有方式可以设置资源文件（如音频、图片、pdf等）的根路径，要不然每次迁移的时候都得去修改每个markdown文件

**Comment by watson8544** [comment]
我也是觉得github慢，想移到别的地方，试过放到阿里云的OSS是可以的，可是我想去掉URL里面的“#”，一直不知道怎么弄，别人说部署到now.sh，可是我又不会用now.sh

**Comment by watson8544** [comment]
> Please translate your question into English.

I want the more specific description about docs "how to deploy docs to now.sh" 

https://docsify.js.org/#/ssr

**Comment by timaschew** [comment]
Dupe of #759
