### ISSUE TITLE
image alt text shows while zooming (zoom-plugin)

### ISSUE THREAD

**Issue by jthegedus** [docsifyjs/docsify#738]
When using alt text with an image, the zoom-plugin shows the alt text while it is zooming

![zoom-plugin-weird-alt-text](https://user-images.githubusercontent.com/20798510/50732055-a0c56a80-11c6-11e9-94f9-eb49ed51918d.gif)

notice it on the left.

I am not sure how to go about debugging this issue.

This is the markdown so whomever can test this themselves:
```markdown
![firebase services gif](https://github.com/jthegedus/awesome-firebase/raw/master/images/firebase-services.gif "Firebase Services")
```

**Comment by anikethsaha** [comment]
@jthegedus can you confirm whether its still exist or not ?

**Comment by anikethsaha** [comment]
I cant reproduce this here https://posthtml.org/#/usage

**Comment by jthegedus** [comment]
I will have a look, could be gif related.
