### ISSUE TITLE
emoji in comment should not be processed

### ISSUE THREAD

**Issue by upupming** [docsifyjs/docsify#742]
The following md:
```md
So this: <!-- begin-inline-katex
\def\arraystretch{1.5}
   \begin{array}{c:c:c}
   a & b & c \\ \hline
   d & e & f \\
   \hdashline
   g & h & i
\end{array}
end-inline-katex-->
```

will be rendered as:

```html
<p>So this: <!-- begin-inline-katex
\def\arraystretch{1.5}
   \begin{array}{c<img class="emoji" src="https://assets-cdn.github.com/images/icons/emoji/c.png" alt="c" />c}
   a & b & c \\ \hline
   d & e & f \\
   \hdashline
   g & h & i
\end{array}
end-inline-katex--></p>
```

It is expected to leave the content in comments unchanged.

**Comment by anikethsaha** [comment]
Please use `__colon__` instead of colon

```
So this: <!-- begin-inline-katex
\def\arraystretch{1.5}
   \begin{array}{c__colon__c__colon__c}
   a & b & c \\ \hline
   d & e & f \\
   \hdashline
   g & h & i
\end{array}
end-inline-katex-->

```

Hope it helps

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/94878274-7aae2680-048f-11eb-869c-b222f2190a63.png)
@atuttle I tested normal, what's wrong with you?

**Comment by atuttle** [comment]
@sy-records I'm not saying that it doesn't work, I'm saying that it's undocumented. If this is the proper way to avoid unintentional conversion to emoji, it should be documented.
