### ISSUE TITLE
请支持loadNavbar位置设置并且支持多级目录

### ISSUE THREAD

**Issue by vvkkhjt** [docsifyjs/docsify#743]
navbar可以提供一个配置修改默认位置，并且请支持多级目录。

**Comment by upupming** [comment]
navbar不都是在上面的嘛？navbar没有目录呀，多级目录又是什么呢？

**Comment by vvkkhjt** [comment]
> navbar不都是在上面的嘛？navbar没有目录呀，多级目录又是什么呢？

是能提供一个位置从左还是从右开始排，多级目录就是
![tim 20190114165302](https://user-images.githubusercontent.com/12765476/51103216-e6181680-181c-11e9-8028-5d99e0351b3c.png)

**Comment by upupming** [comment]
哦哦，原来是这样，你上面这个有demo吗

**Comment by vvkkhjt** [comment]
> 哦哦，原来是这样，你上面这个有demo吗

这个是mkdocs的默认模板噢，可以看一下mkdocs呢。谢谢~

**Comment by upupming** [comment]
ok, I will check later~

**Comment by vvkkhjt** [comment]
@upupming 还有一个小问题，比如我的链接是一个文档，现在我目前的配置就会404not found，现在有配置非md文件默认是下载嘛？

**Comment by vvkkhjt** [comment]
@upupming 
![tim 20190114180152](https://user-images.githubusercontent.com/12765476/51106362-8161b980-1826-11e9-910b-e84a3fc6cf2f.png)

**Comment by upupming** [comment]
使用绝对链接可以解决这个问题，docsify目前不支持相对链接。

**Comment by upupming** [comment]
navbar 的位置可以自行设置，在 `index.html` 中自定义样式即可，或者直接修改相应的主题 css（比如 `vue.css`，去掉 `right: 0`）：

```html
  <style>
    nav.app-nav {
      position: absolute !important;
      right: 200px !important;
    }
  </style>
```

至于多级目录也是可以成功渲染的，只是现在的 `vue.css` 没有展示好：

![image](https://user-images.githubusercontent.com/24741764/51161938-4d8e9e80-18cf-11e9-951f-6f59b820587e.png)

同样是自行修改样式即可，去掉其中的 `overflow-y: auto;` 等等，可以自己尝试一番，甚至可以写一个新的 theme 然后 PR 呀！

**Comment by timaschew** [comment]
Please translate your question into English.

**Comment by vvkkhjt** [comment]
@timaschew 请支持loadNavbar位置设置并且支持多级目录
please support loadNavbar position and support render Multi-level directory

**Comment by timaschew** [comment]
> render Multi-level directory

Please explain what do you exactly mean with that.
What is you input (content of navbar.md, sidebar.md, docsifyConfig) and what is the expected output

Regarding the position of the navbar. Since the markup is completely up to you, you can create any HTML and CSS code you want.

**Comment by lqingjin** [comment]
如何将顶部导航栏navbar固定住，不随页面滚动
