### ISSUE TITLE
how to display the  author and create time in every md page？

### ISSUE THREAD

**Issue by Jasyl0519** [docsifyjs/docsify#750]

**Comment by Edgar-Spiir** [comment]
Not sure about the author, but you can add the date when the file was modified, by adding date format to the docsify config 
```
window.$docsify = {
	formatUpdated: '{YYYY}-{MM}-{DD}',
	...
}
```
and then using `{docsify-updated}` inside the markdown page.

**Comment by timaschew** [comment]
You can define the author via front matter and then use a docsify plugin to access the author property and render it where you want.

**Comment by jthegedus** [comment]
@timaschew an example doing so with the [`front-matter`](https://github.com/docsifyjs/docsify/blob/master/lib/plugins/front-matter.js) plugin would go a long way as it's not clear how that plugin is to be used.

**Comment by jthegedus** [comment]
I used it briefly and looked through the code and it strips the front-matter successfully, but it's not clear where the attributes end up.

https://github.com/docsifyjs/docsify/blob/c3345ba20c888cd7ea908a62024919fb4265ec0b/lib/plugins/front-matter.js#L488

```js
vm.frontmatter = attributes
```

how to we get this `vm.frontmatter` data in further plugins or our pages?

**Comment by timaschew** [comment]
Yes that was also my initial question. But then after I saw the page about [writing a plugin](https://docsify.js.org/#/write-a-plugin) I've realized that the `vm` is passed to the plugin function.

I guess you would need to write in your markdown something like `{{author}}` and then in the beforeHook you can do something like

```javascript
content.replace(/{{(.*)}}/g, function(match, group) {
  return vm.frontmatter[group]
})
```

But I think it makes sense to setup a convention for variables in general in docsify and provide to replace them by frontmatter attributes and implement it into the docsify core.

**Comment by jthegedus** [comment]
Ah okay, a working example people could look at would go a long way here. I fear many people would overlook using docsify because front matter does not work as people would expect.

I do agree that 

> a convention for variables in general in docsify and provide to replace them by frontmatter attributes and implement it into the docsify core

would go a long way and remove most of my concerns with this plugin :smile:

**Comment by timaschew** [comment]
see #758

**Comment by BinaryPaean** [comment]
I can't even figure out how to activate front-matter to simply prevent YAML frontmatter in my 'README.md' from polluting the docsify site.

I've tried variations of:
```js
window.$docsify = { frontMatter: true }
window.$docsify = { front-matter: true }
windows.$docsify = { front-matter: 'README.md' }
...
```
With no success. Can anyone point me at basic usage?

**Comment by szkiba** [comment]
You can substitute variables with [docsify-mustache](https://docsify-mustache.github.io/#/) plugin using mustache syntax `{{variable}}`. Variables can be defined in front matter, external JSON|XML files or in docsify configuration.
If you use front-matter plugin, then the front matter variables will be available. Here is a demo using front matter:
https://docsify-mustache.github.io/#/?id=front-matter
