### ISSUE TITLE
Documentation for page routes

### ISSUE THREAD

**Issue by gotjoshua** [docsifyjs/docsify#753]
[more-pages.md#L20](https://github.com/docsifyjs/docsify/blame/master/docs/more-pages.md#L20) seems to be missing the  `/#/`

For example if I go here:
https://dcomposed.github.io/docsify/markdown
I get a 404

but if i go here:
https://dcomposed.github.io/docsify/#/markdown
it works.

Small detail but i think the docs should read:
```text
docs/README.md        => http://domain.com
docs/guide.md         => http://domain.com/#/guide
docs/zh-cn/README.md  => http://domain.com/#/zh-cn/
docs/zh-cn/guide.md   => http://domain.com/#/zh-cn/guide
```

**Comment by mofadeyunduo** [comment]
solve my problem

**Comment by gotjoshua** [comment]
what is the status of this? It looks as if there is a commit that fixes it, but this issue is still open... 

Is that commit not yet merged?

**Comment by mofadeyunduo** [comment]
It's not merged.
I am very confused by this problem before I found this issues, I think this should be fix asap.
Any one help merge the pr? https://github.com/docsifyjs/docsify/pull/870 
@QingWei-Li
