### ISSUE TITLE
Is docsify still maintained?

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#754]
Hey @QingWei-Li

It seems that you're quite busy and that is okay.  
But it would be very nice if there will be other maintainers so that the work can be distributed.

I have some concerns to use docsify, especially when I see that last versions introduces some bugs which affects the output.

If you won't be able to maintain this project it's okay, I know exactly how much work it is. I was maintaining very actively two open source projects as well (componentjs and js2coffee) for half a year. 
So please just let us know if we should either fork this project or wait until you have time again and ideally add some other maintainers.

**Comment by QingWei-Li** [comment]
I can add you as a maintainer. If you need me to review code, just @ me.

**Comment by timaschew** [comment]
Sounds great.  
Maybe we can even do an announcement to request other maintainers?

So it's up to me to decide if I add you as a reviewer?  
Are there any important features/changes which you always would like to go over before merging?  
Or what kind of policy we should use?

**Comment by QingWei-Li** [comment]
We already have an announcement #603 

New feature PR please let me review.

I am now looking for time to finish the features of 5.0 #657. I am trying to finish it in February.

Do you have any ideas?

**Comment by timaschew** [comment]
> New feature PR please let me review.

Alright

> We already have an announcement #603 

Ah great! 

> I am now looking for time to finish the features of 5.0 #657. I am trying to finish it in February.
>Do you have any ideas?

Let's continue in #657.
