### ISSUE TITLE
Vue code cannot run

### ISSUE THREAD

**Issue by raylapse** [docsifyjs/docsify#755]
I see docsify now supports Vue, so I get a try by adding following code into one of my markdown file:

```
<div id="main">{{ posts }}</div>

<script>
    var vm = new Vue({
        el: '#main',
        data: {
            posts: null
        },
        created: function () {
            axios.get("https://jsonplaceholder.typicode.com/posts")
              .then(response => {this.posts = response.data})
        }
    }); 
</script>
````

I don't see any errors in the console, but no content is returned and redender. Any clues?

**Comment by timaschew** [comment]
Did you enable [executescript](https://docsify.js.org/#/configuration?id=executescript)?

**Comment by Aparksa** [comment]
No need if Vue is present, but i tried and there's no change..

**Comment by raylapse** [comment]
> Did you enable [executescript](https://docsify.js.org/#/configuration?id=executescript)?

Sure I enabled it in index.html

**Comment by timaschew** [comment]
@QingWei-Li any ideas?

**Comment by timaschew** [comment]
Please provide a full example for reproducibility.

**Comment by trusktr** [comment]
I can not run code in the sidebar. And for example, I tried the `docsify-tabs` plugin, and placed the markup in `_sidebar.md`, and that didn't work.

**Comment by trusktr** [comment]
I believe that my sidebar issue is just that Docsify hasn't implemented the same sort of executeScript for the sidebar, not that it isn't working, but such feature isn't there.

**Comment by yuxesd** [comment]
I have the same problem. Is there a solution now?
