### ISSUE TITLE
Explain how to configure server side routing

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#759]
See https://github.com/docsifyjs/docsify/issues/720#issuecomment-458060486

**Comment by ColinMaudry** [comment]
I think SSR stands for Server Side *Rendering*.

**Comment by syedsimanta03** [comment]
> I think SSR stands for Server Side _Rendering_.
> 
> https://docsify.js.org/#/ssr
> 
> Edit: reading at [#720 (comment)](https://github.com/docsifyjs/docsify/issues/720#issuecomment-458060486), I realize we simply talk about different things :)

not working. basepath is local docs folder. deploy error
