### ISSUE TITLE
The plugin caused the markdown setting to fail.

### ISSUE THREAD

**Issue by wll8** [docsifyjs/docsify#762]
- node: v8.9.4
- docsify-cli: 4.2.1

## 由于 `docsify-demo-box-vue` 插件导致 markdown 的配置失效

1. 正常运行的配置 `markdown: { breaks: true, },`
1. 添加插件文件 `docsify-demo-box-vue.js`
1. 初始化插件 `plugins: [ DemoBoxVue.create(jsResources, cssResources, bootCode) ]`
1. 导致 `markdown: { breaks: true, },` 失效

## Markdown configuration disabled due to `docsify-demo-box-vue` plugin
1. Normal operation configuration  `markdown: { breaks: true, },`
1. Add plugin file  `docsify-demo-box-vue.js`
1. Initialization plugin  `plugins: [ DemoBoxVue.create(jsResources, cssResources, bootCode) ]`
1. Lead to failure  `markdown: { breaks: true, },`

![image](https://user-images.githubusercontent.com/28223260/52283052-bf24ae80-299c-11e9-9195-82e0f3399c5e.png)

**Comment by timaschew** [comment]
Why do you think it's a problem with docsify itself and not the plugin?

**Comment by wll8** [comment]
@timaschew I should actually move this issue to the issues in which the plugin is located. is it?

我实际上应该将此问题转移到插件所在的问题。 是吗？
