### ISSUE TITLE
Help adding a translation

### ISSUE THREAD

**Issue by juliofortunato** [docsifyjs/docsify#763]
Hi :smile: 

What's the simplest way to add multiple translations do my documentation site, but I'd like to support languages as the Docsify documentation does with a dropdown selection, however they are using a repo per translation, which I don't wish to do. What I would like is to have each language have it's own folder under `docs/`

What do I need to add to `index.html`?

Thanks!

**Comment by sundowndev** [comment]
What was the solution please ?

**Comment by upupming** [comment]
See https://docsify.js.org/#/cover?id=multiple-covers
just use a sub folder!
