### ISSUE TITLE
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***

### ISSUE THREAD

**Issue by gotjoshua** [docsifyjs/docsify#766]
In my docker logs i see this:
`docs          | *** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***`
Where does it come from, and will it be removed in a future version?

Is it related to:
https://github.com/napcs/node-livereload/issues/94
?

**Comment by timaschew** [comment]
This is related to the CLI, not docsify itself.
