### ISSUE TITLE
How to add 'Edit' feature.

### ISSUE THREAD

**Issue by BeamerIsHere** [docsifyjs/docsify#786]
I want to add an edit button in the web page so that users can also edit the README.md file to make changes. Is this possible?

**Comment by upupming** [comment]
Did you mean this one https://github.com/njleonzhang/docsify-edit-on-github?

**Comment by upupming** [comment]
Just do something like this
https://github.com/docsifyjs/docsify/blob/a35531967a1c418421d811ef3e64c6b94cac2aa6/docs/index.html#L63
