### ISSUE TITLE
Markdown italic is not parsed correctly when used together with markdown link

### ISSUE THREAD

**Issue by TimeDropsDream** [docsifyjs/docsify#787]
See title.  Using Docsify 4.9.1.

Example:

```
*[link](/to/here)*
```

Shows up like this:

\*[link](/to/here)\*

**Comment by timaschew** [comment]
not related to docsify, it's a [markedjs thing](https://marked.js.org/demo/?text=_%5Blink%5D(%2Fto%2Fhere)_%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

It works with underscore `_`
