### ISSUE TITLE
docsify won‘t it IE explorer???

### ISSUE THREAD

**Issue by keer6** [docsifyjs/docsify#793]
docsify 不支持IE 吗？？？ 
RT ？
docsify won‘t it IE explorer???

**Comment by keer6** [comment]
support it IE

**Comment by timaschew** [comment]
Docsify will support only latest IE (11). Support will probably be dropped when Microsoft itself won't support it anymore in the future.

That does not affect Microsoft Edge.
See https://github.com/docsifyjs/docsify/issues/657#issuecomment-459245966 for more details
