### ISSUE TITLE
Tables render header text in every cell

### ISSUE THREAD

**Issue by selfawaresoup** [docsifyjs/docsify#794]
Docsify versions affected: 4.9.1, 4.9.0, 4.8.x (maybe more)

When rendering a markdown table like this:
```
| foo | bar |
| --- | --- |
| 123 | 456 |
```

It renders like this:
![Screen Shot 2019-03-18 at 15 39 39](https://user-images.githubusercontent.com/1770511/54538166-105c9080-4994-11e9-9d24-a4ee0c705baa.png)

The header text is rendered as `:before` pseudo elements via CSS put those should probably not be visible by default.

A quick fix is to include something like this in `index.html`:
```html
<style>
    td::before { display: none }
</style>
```

All themes seem to be affected.

**Comment by winshu** [comment]
> So, the same error is happening to our team. Won't you fix it?

please read this page.

https://jhildenbiddle.github.io/docsify-themeable/#/options?id=responsivetables

and this js

https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/js/docsify-themeable.js

`    function pluginResponsiveTables(hook, vm) {
        hook.init((function() {
            var isEnabled = ((window.$docsify || {}).themeable || {}).responsiveTables !== false;
            if (isEnabled) {
                var markdown = window.$docsify.markdown = window.$docsify.markdown || {};
                var renderer = markdown.renderer = markdown.renderer || {};
                markdown.smartypants = markdown.smartypants || true;
                renderer.table = renderer.table || function(header, body) {
                    var tableHtml = '\n                    <div class="table-wrapper">\n                        <table>\n                            <thead>'.concat(header, "</thead>\n                            <tbody>").concat(body, "</tbody>\n                        </table>\n                    </div>");
                    try {
                        var div = document.createElement("div");
                        var styleElm = document.head.appendChild(document.createElement("style"));
                        var styleSheet = styleElm.sheet;
                        var tableId = "_" + Math.random().toString(36).substr(2, 9);
                        div.innerHTML = tableHtml;
                        var tableElm = div.querySelector("table");
                        var thElms = Array.apply(null, tableElm.getElementsByTagName("th"));
                        var thTitles = thElms.map((function(thElm) {
                            return thElm.innerHTML.replace("&nbsp;", " ");
                        }));
                        thTitles.forEach((function(title, i) {
                            var rule = "#".concat(tableId, " td:nth-child(").concat(i + 1, ')::before{content:"').concat(title, '";}');
                            styleSheet.insertRule(rule, styleSheet.cssRules.length);
                        }));
                        tableElm.id = tableId;
                        tableHtml = div.innerHTML;
                    } catch (e) {
                        console.log("Failed to render responsive table: " + e);
                    }
                    return tableHtml;
                };
            }
        }));`
