### ISSUE TITLE
How to add search plugin properly. 

### ISSUE THREAD

**Issue by BeamerIsHere** [docsifyjs/docsify#795]
Hi everyone, 
 Created a page using docsify now i need to add search plugin, So I've added "<script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>" into the index.html file, 
And also added the search script according to the GitHub page. But search box is here  search result always shows as "No Results!" As I'm not at all an HTML programmer,  I'll add my index.html here. HELP ME TO RESOLVE THIS ISSUE.

Note: Index.html attached, Help will be appreciated.

[index.html.txt](https://github.com/docsifyjs/docsify/files/2980669/index.html.txt)

**Comment by oakgary** [comment]
@BeamerIsHere did you have any success? we have the same issue

**Comment by timaschew** [comment]
I'm not able to reproduce it. Please create a new issue using the issue template if you have still the problem.

**Comment by bibbs** [comment]
@BeamerIsHere 
It looks as if you forgot to enable the sidebar option.
Doing so, and putting links to all docs you want to have indexed into your _sidebar.md is required for the search to work.

**Comment by sri-shetty** [comment]
how to enable _sidebar.md option? I have added loadSidebar: true in my index.html

**Comment by db-ampetronic** [comment]
> The example index.html page that worked for me.
> 
> ```
> <script>
>     window.$docsify = {
>       loadSidebar: true,
>       subMaxLevel: 3,
>       name: '',
>       repo: '',
> 
>       search: 'auto', // default
> 
>       // complete configuration parameters
>       search: {
>         maxAge: 86400000, // Expiration time, the default one day
>         paths: 'auto',
>         placeholder: 'Type to search',
>         noData: 'No Results!',
>         // Headline depth, 1 - 6
>         depth: 6,
>         hideOtherSidebarContent: false, // whether or not to hide other sidebar content
>      }
>     }
>   </script>
>   <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
>   <script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>
> ```

@sri-shetty Using your example index.html page gives me an error:

```
Cannot read property 'classList' of null
```

I can resolve this error by adding some data into the `name` property (for example `name: 'docsify'`) but then I still get @BeamerIsHere's issue of 'No Results!' appearing whenever I search:

![image](https://user-images.githubusercontent.com/38653386/65702499-07ebbd80-e07b-11e9-9c2d-dd30b5b08ad9.png)

**Comment by db-ampetronic** [comment]
I finally figured my issue out, if you look into the browser's local storage (using Chrome: developer tools > application tab > local storage) you can see the content of Docsify's search index under the `docsify.search.index` key which helped to debug this.

I discovered my issue was a combination of two things:

- The search index had been built before I had added the content I was searching for. You can clear local storage in the debugger which helps to combat this, and I suppose using a shorter `maxAge` property would be sufficient in production if regular updates are expected.
- I was using a headline depth greater than the one specified in my `depth` property in my configuration, meaning the content was (correctly) not indexed. When a `depth` property isn't specified it looks like this defaults to 2, meaning any content under a heading like this (`### Heading`) would be hidden.

**Comment by mainameiz** [comment]
@db-ampetronic very helpful comment, thanks!

**Comment by MisakiSF** [comment]
thankx

**Comment by zumdar** [comment]
does anyone else have a problem with finding words if they are in bullet point format? for some reason the search doesnt seem to index words that are in bullet point format?

**Comment by sanamhub** [comment]
This thread is useful :)

**Comment by trusktr** [comment]
> does anyone else have a problem with finding words if they are in bullet point format? for some reason the search doesnt seem to index words that are in bullet point format?

Hello. Please open a specific issue for that
