### ISSUE TITLE
Sidebar does not update

### ISSUE THREAD

**Issue by geongeorge** [docsifyjs/docsify#803]
I tried clearing cache and everything. The _sidebar stays the same in production no matter what I do. 
In Incognito, it's changing.
I guess it's not stored in local storage because I've cleared it like 10 times now.
https://i.imgur.com/dZg47cJ.png

When I do `docsify serve .` it's updated live. But not on live version

**Comment by timaschew** [comment]
Please provide steps to reproduce.

**Comment by geongeorge** [comment]
1. Make a documentation
2. Add a side bar in _sidebar.md
3. open in the browser
4. Make some changes
5. Changes are updated in live hot reload server but not when loading directly

I have tried multiple ways like clearing the cache and even in incognito changes are not reflected

**Comment by jthegedus** [comment]
@geongeorge Are you able to provide a reproduction on codesandbox.io? Here's a template https://codesandbox.io/s/xv36w4695o

**Comment by kayaui** [comment]
same issue...

**Comment by timaschew** [comment]
Please create a new issue using the new template.
