### ISSUE TITLE
How can I initialise docsify on a later request

### ISSUE THREAD

**Issue by nothingrandom** [docsifyjs/docsify#804]
If I want to delay the init of docsify to then trigger it on my own terms, is that possible?

**Comment by timaschew** [comment]
You can delay loading the docsify script.

**Comment by nothingrandom** [comment]
Hmm, presuming you're suggesting I use a `setTimeout`?

Not quite what I want. I've got two window components in the same index.html, one for Vue and one for docsify. Vue is handling the whole of my app, including auth. I need to pass the auth token to docsify from Vue and then "start" docsify, because starting it before I have the auth token passed as a header gives me a 404 request (expected for our configuration). Which is why I'm asking if there's a way to reinitialise, or only start it when I want it to be started.

I wasn't able to find anything in the docs / wiki that would enable this though?

**Comment by timaschew** [comment]
You Can try something like this: https://github.com/docsifyjs/docsify/blob/d80aa2189b07b375be1d0df5b071ed0931f247ef/test/_helper.js#L42-L59

**Comment by timaschew** [comment]
Of course this is ugly any maybe even doesn't work for you since some of the function might not be expoed.

I will implement a single function which will be exposed to init docsify. In the config you can disable automatic initialization

**Comment by trusktr** [comment]
The above is too difficult to do. This will be addressed as a non-breaking change in https://github.com/docsifyjs/docsify/issues/799
