### ISSUE TITLE
Map path to route dynamically

### ISSUE THREAD

**Issue by psamim** [docsifyjs/docsify#808]
Hi,

I have some markdown files in `/docs/en/`. The links in these files are relative like `contribute`. Can I make Docsify to go to `/docs/en/contribute` when this link is clicked? Now if someone clicks on the link it will go to `/contribute` as if the links are absolute.

Thanks

**Comment by timaschew** [comment]
I think that was fixed by #714
I will deploy a new version soon.

**Comment by anikethsaha** [comment]
answer above
