### ISSUE TITLE
Display html files

### ISSUE THREAD

**Issue by psamim** [docsifyjs/docsify#809]
Hi,

Can some files be `html` (and not `md`)? So that Docsify display them without converting them.

Thanks

**Comment by timaschew** [comment]
HTML without html and body tags?

**Comment by psamim** [comment]
No, standard HTML.

I know we can embed HTML into markdown but sometimes it has indent problems or small issues. I wanted to know if there is way to just render the HTML file without any markdown conversion. 

For example Docusaurus (and others) has this [feature](https://docusaurus.io/docs/en/custom-pages#adding-static-pages):

> Static .html files can  also be used

**Comment by timaschew** [comment]
If Docsify should not touch them at all then you cannot **display** it with docsify.

You can serve the HTML just with any static HTTP server.

**Comment by psamim** [comment]
I mean some parts are markdown files some are plain HTML files.

**Comment by psamim** [comment]
If they were all HTML files, you were right, any static HTTP server would do it.

**Comment by timaschew** [comment]
You can files for docsify: https://docsify.js.org/#/configuration?id=nocompilelinks

**Comment by groliveira18** [comment]
Guys, part of my documentation has tags in the document. Is there a way to escape these tags? Docsify is rendering these tags and breaking my document.

**Comment by DanielYWoo** [comment]
same problem here. I want to use a very complicated page as the home page, which is impossible to be done in MD, how can I use something like a README.html instead of README.md as the homepage?

**Comment by trusktr** [comment]
Markdown is a superset of HTML. Just put any HTML you want in the markdown.

**Comment by trusktr** [comment]
Also you can put any HTML in your entry HTML file. You don't even have to load Docsify. You can load Docsify on a separate page.

**Comment by DanielYWoo** [comment]
Thanks for the quick help. I have the homepage html and markdown files in the Navbar, so docsify has to be loaded. Although markdown is a superset of html, but it is not easy when css and javascript modules, webpack or vite  are involved.
Is it possible to have both markdown file links and html links in the navbar?

**Comment by trusktr** [comment]
It is not currently possible to load HTML pages from the Docsify sidebar links. We could accept a PR for that though.

**Comment by trusktr** [comment]
> but it is not easy when css and javascript modules, webpack or vite are involved.

What problem did you have?

**Comment by DanielYWoo** [comment]
> > but it is not easy when css and javascript modules, webpack or vite are involved.
> 
> What problem did you have?

I mean, I need vite to replace and inject css/js but it only works with HTML, not with markdown. Anyway, it's not a problem if the navbar can have links to HTML pages.

**Comment by trusktr** [comment]
I'm not fully familiar with Vite, but it seems to me you could `import` CSS files in your JS code, then put the `<script>` tag in your markdown file for bundle made from your entry point.

**Comment by trusktr** [comment]
I just read a little, and Vite does produce static assets, which means there is a static script output somewhere. You should be able to include that as a script tag in any markdown file, for example.

**Comment by DanielYWoo** [comment]
really appreciate for your help， will give it a try。
________________________________
发件人: Joe Pea ***@***.***>
发送时间: Thursday, July 28, 2022 12:29:59 PM
收件人: docsifyjs/docsify ***@***.***>
抄送: Daniel Wu ***@***.***>; Comment ***@***.***>
主题: Re: [docsifyjs/docsify] Display html files (#809)


I just read a little, and Vite does produce static assets, which means there is a static script output somewhere. You should be able to include that as a script tag in any markdown file, for example.

―
