### ISSUE TITLE
Some errors occurred during the first run of the project

### ISSUE THREAD

**Issue by persevereVon** [docsifyjs/docsify#812]
1. `git clone https://github.com/docsifyjs/docsify.git`
2. `npm run bootstrap && npm run dev`
3. ![image](https://user-images.githubusercontent.com/3402811/55809361-58e11700-5b18-11e9-821e-e9f22a1439f7.png)
4. The reason for the problem is that there is no `themes` directory
5. Add `themes` directory to the root, problem solved

**Comment by hifocus** [comment]
The thing is, why don't you just run `docsify init ./docs`?

**Comment by persevereVon** [comment]
@hifocus Sorry, the documentation tells me to run `npm run bootstrap && npm run dev`.

**Comment by hifocus** [comment]
> @hifocus Sorry, the documentation tells me to run `npm run bootstrap && npm run dev`.

If you only want to setup a docsify, use `docsify init ./docs`.

But you looks like trying to do the development work. My misunderstanding, I do apologise.

**Comment by persevereVon** [comment]
@hifocus Yes, my expression is problematic.
