### ISSUE TITLE
Can't Scroll On Pages

### ISSUE THREAD

**Issue by Brumstar** [docsifyjs/docsify#814]
Hi everyone,

I'm just started to build out my documentation with docsify, which is very beautiful by the way. However, I noticed that I can't scroll on the pages that I create. I can navigate only by clicking the links in the sidebar. Is there some configuration that I am missing to make scrolling pages possible? Clearly, this is not an issue on the actual docsify site but it is on my generated pages. 

Thanks

**Comment by Brumstar** [comment]
Apparently the presence of this  **<script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>** in my index.html led to the no scrolling issue. Putting this here in case anyone ever runs into this, and closing.

**Comment by milo526** [comment]
While I first could not believe that removing the library would fix a problem, this issue made me realise that I imported docsify 2 times, that is a bit too much 😉. So if these issues arise it might indicate that you are double importing docsify.
