### ISSUE TITLE
我打算开发一个不依赖md，而是依赖数据的 Docsify 版本可以么

### ISSUE THREAD

**Issue by zhukunpenglinyutong** [docsifyjs/docsify#815]
Docsify 是一个很美丽的库，还有一些周边，这点非常试用于我目前的博客系统的文章页面的渲染，但是可惜的是，Docsify的定位是，提供静态站点，需要通过.md方式来进行渲染，我所需要的是可以通过数据来渲染的库，而我了解到，Docsify是基于 Marked.js来做的，这就给我有了机会，让我可以改变一下 Docsify 中读取md文档的方法，改为API数据读取，好的效果就是，不影响其他功能，周边的第三方框架还都可以使用，不多说了，开始做了

**Comment by timaschew** [comment]
Please use English language.
