### ISSUE TITLE
搜索按钮试了好多种方法都不成功，怎么添加呢？？（根本不能搜索，好奇怪）

### ISSUE THREAD

**Issue by flitdu** [docsifyjs/docsify#819]
https://flitdu.github.io/ml-note

index.html如下：
https://github.com/flitdu/ml-note/blob/master/docs/index.html

**Comment by xiaohao890809** [comment]
please add 
<script src="//cdn.jsdelivr.net/npm/docsify@latest/lib/plugins/search.min.js"></script>
in the end

**Comment by timaschew** [comment]
Please use issue template
