### ISSUE TITLE
Embed Files - random order of headers in sidebar

### ISSUE THREAD

**Issue by reinkepatrick** [docsifyjs/docsify#828]
## Bug Report
I have a docsify page with subpages by the `_sidebar.md`, this is hosted via GitHub pages. I wanted to separate the one page by embed files.  Now I have the problem that the order of the points in the sidebar changes randomly, these points are not the ones in the `_sidebar.md` but are generated by the headers. When I reload web page then the whole page is empty.

#### Steps to reproduce
Page hosted on GitHub-Pages. Under page added to the `_sidebar.md` and split by embed files.

```md
<!-- _sidebar.md -->

* [Point](point/index.md)
```

```md
<!-- point/index.md -->

# Point

[section1](sections/section1.md ':include')

[section2](sections/section2.md ':include')
```

```md
<!-- sections/section1.md -->

# Hello Section 1

## Hello World Section 1

```

```md
<!-- sections/section2.md -->

# Hello Section 2

## Hello World Section 2

```

#### What is current behaviour
The headers are displayed randomly. As an example:

```md
<!-- Example 1 -->

- Hello Section 2
  - Hello World Section 1
  - Hello World Section 2
- Hello Section 1

```

```md
<!-- Example 1 -->

- Hello Section 2
  - Hello World Section 2
- Hello Section 1
  - Hello World Section 1

```

#### What is the expected behaviour
The pages are imported in the order I specify them.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: -
- npm/yarn version: -
- Browser version: Google Chrome 74.0.3729.108
- Docsify version: 4.9.1
- Docsify plugins: -

**Comment by marisk** [comment]
This may be directly related to #791

**Comment by rolaguna** [comment]
I have a similar issue:

My sidebar shows the following:

* A -> points to A.md
  * BB -> points to B.md

Which is ok.

However, when I click in  A, the headers from A.md are included as submenus from A, at the same level that B:

* A -> points to A.md
  * BB -> points to B.md
  * A.AA -> points to A.md#AA

However, I'd like/expect it to be as follows:

* A -> points to A.md
  * A.AA -> points to A.md#AA  
  * BB -> points to B.md
