### ISSUE TITLE
Emoji is killing datetime 

### ISSUE THREAD

**Issue by VagnerDomingues** [docsifyjs/docsify#829]
![emoji :01: ](https://user-images.githubusercontent.com/5666881/56824178-1f085400-682c-11e9-8510-749713a993e3.png)

emoji :01: is breaking formatted datetime :cry:  i couldn't find an option to ignore them.

**Comment by timaschew** [comment]
Template was not used.

**Comment by VagnerDomingues** [comment]
@timaschew i think i didn't understand what you said...

but in the case you said that it was because i'm using different stylesheets i tested the issue in another docsify page project that i own that is pretty much a docsify.js running in raw state to prove that this is a bug.

![image](https://user-images.githubusercontent.com/5666881/57528040-9c8d9300-7307-11e9-8760-021f2ca95eb0.png)

what i need is to be able to write these datetimes... 
so what is this 'template' that you said i missed to use?

**Comment by timaschew** [comment]
You have deleted the GitHub issue template.

**Comment by VagnerDomingues** [comment]
###Expected Behavior
people should be able to write hourly periods with seconds in datetime objects representation in their documents, which means writing twice double dots between a number like this...    ` :01: `

###Actual Behavior
A emoji is appearing in the middle of datetime

###Steps to reproduce
Write a datetime with `:01:` in horly period
