### ISSUE TITLE
NPM does not have 4.9.2 as latest version

### ISSUE THREAD

**Issue by mkiddTempus** [docsifyjs/docsify#831]
## Bug Report
Latest version of docsify is not available through npm.

#### Steps to reproduce
I ran `npm update` and it only updated to 4.9.1.

#### What is current behaviour
relativePaths are not available.

#### What is the expected behaviour
able to use latest version of docsify

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by timaschew** [comment]
It was not published with the `latest` tag yet. But with the `next` tag.

```
$ npm info docsify

{ name: 'docsify',
  description: 'A magical documentation generator.',
  'dist-tags': { latest: '4.9.1', next: '4.9.2' },
  ...
}
```
