### ISSUE TITLE
Remove version from coverpage

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#833]
#### What problem does this feature solve?

coverpage is changing in git for each release

#### What does the proposed API look like?

omit the version from coverpage or render directly from package.json (with a plugin?)

**Comment by jrappen** [comment]
Compare the png image with npm version info via <https://shields.io> as in the <https://github.com/docsifyjs/docsify#readme> header for a dynamically generated one.

**Comment by Koooooo-7** [comment]
As for me , the version on coverpage leaned  on the icon , seems more comfortable:dog:
To be honest , it dones't matter whether remove it  or retain  it  on  another way .
Cos I can  edit  the coverpage  and I actually changed it  to what I want .
