### ISSUE TITLE
Rebase via a comment

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#839]
## Feature request
Integrate rebase feature: https://github.com/sschuberth/rebase

#### What problem does this feature solve?
Keep PRs up to date

#### What does the proposed API look like?
See the link

#### How should this be implemented in your opinion?
See the link

#### Are you willing to work on this yourself?
Yes

**Comment by anikethsaha** [comment]
Is it the same as the `update branch` button from the PRs ?

**Comment by timaschew** [comment]
I think so. But not sure if the contributor can press the button because of permissions.
