### ISSUE TITLE
I wanna open the repository page of GitHub in new tab

### ISSUE THREAD

**Issue by Shineeeee** [docsifyjs/docsify#843]
## Feature request
Open in new tab when set true to `openNewTab` key of `window.$docsify`

#### What problem does this feature solve?
Currently, open in currently tab when we click SVG of GitHub Corners.  
But I wanna open the repository page of GitHub when at that time.

#### What does the proposed API look like?
We'll be able to open the repository page of GitHub in new tab by using this API.

#### How should this be implemented in your opinion?
I think you should be able to open the repository page of GitHub in new tab when we set true to `openNewTab` key of `window.$docsify`.

#### Are you willing to work on this yourself?
No. Sorry, I'm so busy now,,,

**Comment by Koooooo-7** [comment]
Hi,
the issues  seems like #835  . 
and I tried to fix it #842  .

if you just wanna  change the corner, I think it  would  work  for you :smiley: 

Just import  your own `docsify.js` instead of 
` <script src="//unpkg.com/docsify"></script>` 
 `<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>`

change the `docsify.js `  like this 

add the ` target=\"_blank\" ` into this function `corner `

```
function corner(data) {
    ...

  return (
    "<a href=\"" + data + "\"   target=\"_blank\"   class=\"github-corner\" 
  ...

```

**Comment by Shineeeee** [comment]
Hi

THKU !!
I'll try it.

**Comment by quentinneyraud** [comment]
Hi,

I had the same issue an found an other solution maybe less restrictive:

```js
// after all docsify scripts
<script type="text/javascript">
    window.addEventListener('click', function(e) {
      if (e.target.parentNode.closest('.github-corner')) {
        e.preventDefault()
        window.open(document.querySelector('.github-corner').href, '_blank')
      }
    })
 </script>
```

**Comment by anikethsaha** [comment]
> Hi,
> 
> I had the same issue an found an other solution maybe less restrictive:
> 
> ```js
> // after all docsify scripts
> <script type="text/javascript">
>     window.addEventListener('click', function(e) {
>       if (e.target.parentNode.closest('.github-corner')) {
>         e.preventDefault()
>         window.open(document.querySelector('.github-corner').href, '_blank')
>       }
>     })
>  </script>
> ```

You can create a plugin as well with this script.
