### ISSUE TITLE
Translations are out of sync

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#845]
#### Steps to reproduce
Change code which affects the API, even small and backward compatible changes.

#### What is current behaviour
The author will probably update only the English documentation. Even if the author has another native language it’s annoying to do the change in another repository.

That means non English translations are most time out of sync with the codebase and the deployed/published version.

#### What is the expected behaviour
Either have no translations at all
Or have a way to flag some part half-automated to be outdated until the docs are translated. Try to avoid multi repositories.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by Koooooo-7** [comment]
:rofl: :rofl: :rofl:  take it easy .
you can  update only English document ,if possible. 
and find  some  contributors to  translate it   .
 On non-English translations'  pages , you can set the header/footer  ( in their native language) like 
 `This document is  just for reference , the document in English is latest !`  

BTW : enjoy your vocation :small_airplane: .
