### ISSUE TITLE
repo Support gitlab？

### ISSUE THREAD

**Issue by jinguowu** [docsifyjs/docsify#846]

**Comment by Koooooo-7** [comment]
Hi,you can  set   `repo : 'https://your_gitlab_url'`   to link your gitlab repo,
but the corner's icon is still Github , this configuration  would be enhanced  soon .

**Comment by jinguowu** [comment]
I set it up, but there is no dynamic pull，why？

**Comment by timaschew** [comment]
Issue template was not used/filled

**Comment by xsro** [comment]
> Hi,you can set `repo : 'https://your_gitlab_url'` to link your gitlab repo,
> but the corner's icon is still Github , this configuration would be enhanced soon .

Has this feature enhanced?

**Comment by Koooooo-7** [comment]
> > Hi,you can set `repo : 'https://your_gitlab_url'` to link your gitlab repo,
> > but the corner's icon is still Github , this configuration would be enhanced soon .
> 
> Has this feature enhanced?

u can use this plugin [docsify-corner](https://github.com/Koooooo-7/docsify-corner) to make it.
