### ISSUE TITLE
How to add images from root?

### ISSUE THREAD

**Issue by rilc0n** [docsifyjs/docsify#850]
For example, I have 2 folders in the root directory. There is a picture in the first folder (images).

The second folder (docs) contains the markdown file.

How do I insert an image into this markdown file that is located in the folder (images).

If I put it this way:

`![](/images/testimage.jpg)`

He tries to add it like this:

`/docs/images/testimage.jpg`

**Comment by timaschew** [comment]
Use https://docsify.js.org/#/configuration?id=relativepath

**Comment by rilc0n** [comment]
This changes the links but not the path to pictures. Am I doing something wrong?

**Comment by timaschew** [comment]
Hmm, it’s maybe a bug

**Comment by LemarkNova** [comment]
I confirm this is a bug. When you use 
`![](/img/img.png)`
it doesn't work, but when you use 
`<img src='/img/img.png'></img>`
it works

**Comment by TianYongwei** [comment]
Hmm .. 
this bug is fixed?

**Comment by LemarkNova** [comment]
Yes, now it works

**Comment by TianYongwei** [comment]
Hey @LemarkNova , Thanks for reply.

I am confused about the img tag compile result.

my markdown content is :
```md
![my img](/myimg.png)
``` 

The docsify compiled result is :
```html
<img src="/foldername/subfoldername/myimg.png" alt.../>
```

my expected result is :
```html
<img src="/myimg.png" alt.../>
```
because my all static img file is just in a single folder.

**Comment by TianYongwei** [comment]
I found that this 「long path」is not caused by "marked" —— docsify compile markdown file by it, 

It seems caused docsify ? 

something could be configed ?

**Comment by LemarkNova** [comment]
No finally it isn't fixed, I remember that I just use a workaround to use image in markdown:
I use `../picturefolder/picture.jpg`. So the real problem is that docsify doesn't compile correctly the markdown image. I don't know how you compile the markdown, but the problem is in the compilation of the markdown like in your previous comment.

**Comment by LemarkNova** [comment]
Does Docsify use the latest version of marked? But I just try with marked and it work.

**Comment by TianYongwei** [comment]
Thanks for your help. I note the workaround way.

I do nothing about the compilation of markdown files, just do some steps from the official documentation.

I am not sure the version of marked, but the docsify I installed is the latest version.

**Comment by ShusenTang** [comment]
> No finally it isn't fixed, I remember that I just use a workaround to use image in markdown:
> I use `../picturefolder/picture.jpg`. So the real problem is that docsify doesn't compile correctly the markdown image. I don't know how you compile the markdown, but the problem is in the compilation of the markdown like in your previous comment.

Hi, could you please help me? #936

**Comment by gigaga** [comment]
I've the same problem :(

**Comment by anikethsaha** [comment]
It's quite difficult to cover all the cases with a single syntax. I will try to look around this soon.

**Comment by gigaga** [comment]
@anikethsaha the behavior should be in function of relativePath?
Currently even if this parameter is false, img path generated still is in relative.

**Comment by anikethsaha** [comment]
> @anikethsaha the behavior should be in function of relativePath?

Yes

> Currently even if this parameter is false, img path generated still is in relative

Need an investigation about this.

**Comment by cptcanuck** [comment]
This is still an issue.

**Comment by woytu** [comment]
```js
hook.beforeEach(function(content) {
    return content.replace(new RegExp("/images", 'ig'), "../images");
})
```

**Comment by ngpeijiun** [comment]
It works by this:
`![](//images/testimage.jpg)`

**Comment by ngpeijiun** [comment]
In `core/render/compiler/image.js`
```
    import { isAbsolutePath, isRelativePath, getPath, getParentPath } from '../../router/util';

    ...

    if (!isAbsolutePath(href)) {
      url = getPath(contentBase, getParentPath(router.getCurrentPath()), href);
    } else if (isRelativePath(href) {
      url = getPath(contentBase, href);
    }
```

In `core\router\util.js`
```
export const isRelativePath = cached(path => {
  return /^\//g.test(path);
});
```

**Comment by computerphilosopher** [comment]
Use 'img src' instead of markdown link and attach "?raw=true" to end of image's URL.   
```
<img src="https://github.com/your/repo/blob/master/docs/images/img.png?raw=true"</img>
```
I don't know why, but it works.

**Comment by Maxlinn** [comment]
I come up with the same problem, i think the most convinent way is to turn `![]()` syntax into `<img src="" alt="">`.

**Comment by ninjadev64** [comment]
same issue here!

**Comment by jhildenbiddle** [comment]
Bug acknowledged. Tracking with #1891.
