### ISSUE TITLE
Customize HTML (add header, footer)

### ISSUE THREAD

**Issue by darkhan** [docsifyjs/docsify#852]
I tried to add custom HTML to index.html, but it looks like I need to re-write all CSS to make it visible or maybe I just didn't find how?

**Comment by Koooooo-7** [comment]
Hi, I think   the  [Write a Plugin](https://docsify.js.org/#/write-a-plugin) of Docsify documentation   could help u.

**Comment by anikethsaha** [comment]
answer above.

**Comment by saihaj** [comment]
is it possible to have the footer always at the bottom of page? With the above mentioned plugin it just puts it wherever the content finishes.
