### ISSUE TITLE
Emoji killing datetime

### ISSUE THREAD

**Issue by VagnerDomingues** [docsifyjs/docsify#853]
#### Steps to reproduce

Just Write a datetime with `:01:` in hourly period anywhere in the documentation.

#### What is current behaviour

An emoji is appearing in the middle of datetime like the image below:

![image](https://user-images.githubusercontent.com/5666881/57528040-9c8d9300-7307-11e9-8760-021f2ca95eb0.png)

#### What is the expected behaviour

People should be able to write hourly periods with seconds in datetime objects representation in their documents, which means writing twice double dots between a number like this...    ` :01: `

#### Other relevant information
There should be an option to disable these emojis.

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: v7.5.0
- npm version: 4.1.2

- Browser version: Chrome  74.0.3729.157 (official) 64 bits
- Docsify version: latest from cdn
- Docsify plugins: docsify-themeable, docsify-pagination

**Comment by Koooooo-7** [comment]
Hi , 
 the bug is a little bit funny :rofl: 。
it seems wrong to parse datetime  as emoji  syntax  `:emoji:`
I think  it should work that   making   datetime  in  the code syntax , add  \` 。
\` 2019-05-06 10:11:12\`

**Comment by VagnerDomingues** [comment]
i can't escape it like that because it'll loose original css styling which is made for ease readings,
i'm using it like this:

![image](https://user-images.githubusercontent.com/5666881/59214952-7b31f800-8b8e-11e9-90e2-4c3258e74081.png)

i just wanted to disable emoji feature because it will never be used in this documentation and it's already on production... cheers!

**Comment by VagnerDomingues** [comment]
please if anyone could help i'd be very thankfull.. 

you can check it on production here:
https://fairlay.com/api/#/public/?id=examples

**Comment by VagnerDomingues** [comment]
so... no way to get rid of emojis?

**Comment by Mkots** [comment]
> so... no way to get rid of emojis?

You can try: 
` window.$docsify = {
        noEmoji: true
      };`
