### ISSUE TITLE
How to get the compiled index.html?

### ISSUE THREAD

**Issue by PengHoliday** [docsifyjs/docsify#855]
I use docsify to generate a static html file in our website, so how can I get the compiled index.html instead of the whole project?

**Comment by anikethsaha** [comment]
Do you want the compiled HTML for the markdowns?

The static command is in our roadmap for `v5` and it will be shipped in `v5`.
And if you want the compiled markdowns, its a runtime compiling so I guess you cant extract the HTML from it. You can try using webpack-html-extract-plugin but I dont think it will work. 


Closing this as I hope this might help 👍 
Please comment below if you want to add something more
