### ISSUE TITLE
two articles share the same search content...

### ISSUE THREAD

**Issue by xiaohao890809** [docsifyjs/docsify#857]
## Bug Report
I have two articles developed by docsify, when I search the content in one article, then I search the same content in another different article, the result appears too. Why?

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: google mac os
- Docsify version: 4.7.1
- Docsify plugins: 4.3.0

**Comment by anikethsaha** [comment]
> I have two articles developed by docsify, when I search the content in one article, then I search the same content in another different article, the result appears too. Why?

Please explain in more details. I didnt get your issue
