### ISSUE TITLE
Support custom classes on "Embed Files" feature

### ISSUE THREAD

**Issue by shawntabrizi** [docsifyjs/docsify#858]
## Background

I am working on a plugin for Docsify which allows it to be used as a tutorial/playground for developers.

Plugin: https://github.com/shawntabrizi/docsify-codeview

Example: https://www.shawntabrizi.com/substrate-collectables-workshop/#/1/storing-a-value

To do this, I take advantage of the "Embed Files" feature to load code into the page, and then my custom plugin can detect that code and generate a code editor (using Microsoft's Monaco Editor).

## Feature request

Enable custom classes to be added to embedded code blocks.

#### What problem does this feature solve?

When creating embedded files, a user may want to add additional metadata, or truly style their embedded content. Right now the user only has access to a limited number of options:

https://docsify.js.org/#/embed-files

This feature would allow the user to extend the embedded files with their own classes.

#### What does the proposed API look like?

The proposed API would include a `:class` tag within the Embed Files syntax which would look identical to HTML.

```
[filename](_media/example.md ':include :class="class-one class-two"')
```

I would also suggest a breaking change to the syntax around `lang` for embedded code, where `:lang` is used to define the language of the code rather than it being assumed as a string at the end:

```
[](_media/example.html ':include :type=code :lang=text :class="class-one class-two"')
```

It seems it could be possible that we support backwards compatibility here.

It also seems we could generalize other such APIs like the iFrame:

```
// before
[cinwell website](https://cinwell.com ':include :type=iframe width=100% height=400px')
//after
[cinwell website](https://cinwell.com ':include :type=iframe :style="width=100%;height=400px;"')
```

#### How should this be implemented in your opinion?

Seems like we just need to improve the parser which manages this line, but I will need to look into it deeper.

#### Are you willing to work on this yourself?

I will start, but it will take me a bit to get familiar with exactly how it is being parsed.

If someone can suggest/make this simple addition, that would be awesome :)

Expect an update later today

**Comment by shawntabrizi** [comment]
I have successfully:
* updated the regular expression which parses the custom text for embedding files
* stored the "additional classes" into the `config` object which is passed around
* brought support for `:lang` syntax which is aligned with other attributes available in embedded files
    * does not break existing syntax
* added support for `additional_classes` in the html rendered for the embedded code [(ref)](https://github.com/docsifyjs/docsify/pull/859/files#diff-d73f215ac772d2673dd8c51f24976e4eR221)

I was not able to:
* Figure out how to actually pass the additional classes from the `config` to the render function...

Anyone can help me cross the finish line here?

**Comment by stigmollerhansen** [comment]
This would be a killer feature! I'm trying to get prism.js syntax highlighting to add line numbers and for this to work it is vital that the class "line-numbers" are added to the <pre> element when docsify parses it, otherwise prism.js won't know to add line numbers. This feature would solve this.

What's the status on this? Abandoned or just marked as 'wontfix' by the stale bot?
