### ISSUE TITLE
`loadSidebar: true` doesn't work well when script src doesn't contain `docsify.`

### ISSUE THREAD

**Issue by L3au** [docsifyjs/docsify#860]
#### Steps to reproduce

I create a bug showcase as below to reproduce this.

https://l3au.github.io/assets/docsify/

#### What is current behavior

`loadSidebar: true` config doesn't work

#### What is the expected behavior

Make it work even when the script url doesn't contain `docsify.` by the following ways

- fix `document.currentScript` using
- improve config fields coercion 

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS Mojave 10.14.5
- Node.js version: v10.15.3
- npm/yarn version: npm 6.4.1
- Browser version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
- Docsify version: 4.9.4
- Docsify plugins: none

**Comment by ddzy** [comment]
same problem

**Comment by L3au** [comment]
@timaschew @QingWei-Li 
Hi guys, would you be available to review this problem, I have given a solution to this issue #861. 

Thanks for the consideration. Please let me know if you have any other questions.

**Comment by methodbox** [comment]
This actually doesn't work at all.

using:

```js 
window.$docsify = {
        name: "",
        repo: "",
        loadSidebar: "summary.md"
      };
```
...simply does nothing. Even setting it to `false` doesn't get rid of the sidebar. Kind of sad that the owner doesn't seem to care because this renders their project useless since you can't even get rid of the useless sidebar.

Lame.
