### ISSUE TITLE
Korean Translate

### ISSUE THREAD

**Issue by JUNWOO45** [docsifyjs/docsify#871]
Hi!🤗
I finished translating in Korean.
I checked issue #484 , but I didn't understand 100%.
I've made a repo.
https://github.com/JUNWOO45/docsify-kr

What should I do from now on?

**Comment by Koooooo-7** [comment]
WOW ,it is awesome !
According to  the  #484  , you can  deploy your document site by yourself,
then , make a PR to [there](https://github.com/QingWei-Li/docsify/blob/master/docs/_navbar.md) (add a  link in the `_navbar.md`) as well.
but , I find the Spanish docs's address  is `https://docsify-es.js.org/#/` now .
you'd better wait for the Maintainer .:smile:

**Comment by Violet-Bora-Lee** [comment]
i want to join the proocess. :)
