### ISSUE TITLE
Issue using headers with custom id in search

### ISSUE THREAD

**Issue by Lowgain** [docsifyjs/docsify#873]
#### Steps to reproduce

- Create a heading using a custom id, for instance:
```markdown
## Great Heading :id=great
```

- Enable the search module, and search for a term that returns this content (eg. "great")

#### What is current behaviour

The heading is returned including the `:id=great` portion, and the id in the URL is incorrect (instead of `?id=great`, it includes `?id=great-heading-idgreat`

![image](https://user-images.githubusercontent.com/148485/60605449-88a26280-9d87-11e9-8ccb-5a01fa2f9bb5.png)

#### What is the expected behaviour

The heading returned in the search results should exclude the `:id=great`, and the URL should link to the correct id

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 12.4.0
- npm/yarn version: 6.9.0
- Browser version: Firefox 67.0.4, Chrome 75.0.3770.100
- Docsify version: 4.9.4
- Docsify plugins: search

**Comment by qwqoffice** [comment]
same problem
![image](https://user-images.githubusercontent.com/18651085/62947816-c332fc80-be15-11e9-9c46-b03964db6b72.png)

**Comment by eduardocarvalho1** [comment]
same problem here ;-;
