### ISSUE TITLE
Only one link in the navbar is underlined

### ISSUE THREAD

**Issue by oren** [docsifyjs/docsify#876]
#### Steps to reproduce
1. https://oren.github.io/#/articles/zeronet/
1. Notice that the navbar have two links. only one of them is underlined.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
> Notice that the navbar have two links. only one of them is underlined.

I cant see any navbar or something. Please update the steps 👍

**Comment by oren** [comment]
it looks like my entire website doesn't show the navbar. I didn't change anything in the last few weeks so I am not sure what's going on. I'll look into the issue and comment here. Thank you!

**Comment by oren** [comment]
I just noticed that I can see the navbar when running it locally with `docsify serve`. Only when I push the repo to my github pages (https://oren.github.io/#/) the issue is happening.

**Comment by anikethsaha** [comment]
Can you share your project structure and config
Also if possible just try some other hoisting service to cross check like Netlify or now

**Comment by oren** [comment]
Here is the codebase: https://github.com/oren/oren.github.io

**Comment by anikethsaha** [comment]
I need to manually check this and I can't do that till dec 5.
So in the meantime try hosting it in some other platform
