### ISSUE TITLE
`This site can’t be reached Error` in IIS

### ISSUE THREAD

**Issue by msi-matthew** [docsifyjs/docsify#878]
#### Steps to reproduce

1. Host docsify project in Windows IIS

#### What is current behaviour

Browser returns

This site can’t be reached docs.domain.com’s server IP address could not be found.

#### What is the expected behaviour

Project to load like when `docsify serve` is run

#### Other relevant information

- [X] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 
- npm/yarn version: 
- Browser version: Chrome
- Docsify version: 4.9.4
- Docsify plugins: Emoji, Clipboard, Search

**Comment by msi-matthew** [comment]
When setting the `web.config` file to redirect requests to `index.html`

```<configuration>
   <system.webServer>
      <httpRedirect enabled="true" exactDestination="true" httpResponseStatus="Found">
         <add wildcard="*.php" destination="/default.htm" />
      </httpRedirect>
   </system.webServer>
</configuration>```

The side bar and mainpage display `"Loading..."`, but never load.

**Comment by anikethsaha** [comment]
Please verifies the directories or the router.
Not sure about IIS and `web.config`

The usual flow is 
you can either create your docs using `docsify init <your docs folder>` and start writing markdown files in it and using `docsify serve <your docs folder>` command it will create a live-server where you can preview the site in realtime. Now to host it, simply host the `<your docs folder>` in your hosting platform and it should work properly.

> This site can’t be reached docs.domain.com’s server IP address could not be found.

I guess you might did something wrong with lookups. 

See here how routing in docsify works : https://docsify.js.org/#/more-pages

Hope this might help.
Closing this. 👍 
Please comment below if you want to add anything to it

**Comment by alexpeasleyghc** [comment]
@msi-matthew After setting the Mime type for Markdown (see below) then my site rendered as expected. You should be able to copy everything from your docs folder into your target website folder. 

Add Meme with these values.
Extension: "md"
Mime Type: "text/x-markdown"

**Comment by msi-matthew** [comment]
@alexpeasleyghc Where are you setting the mime type? 

Is this an IIS setting?

**Comment by alexpeasleyghc** [comment]
@msi-matthew - Yep, in IIS. Google "Mime Type in IIS"
