### ISSUE TITLE
search show html when MD have html

### ISSUE THREAD

**Issue by ghouman** [docsifyjs/docsify#879]
## Bug Report
search show html
#### Steps to reproduce
1. open chrome and access https://faq.isolarcloud.com/
2. input 25 to seach
3. the result contain html

#### What is current behaviour
the result contain html
![image](https://user-images.githubusercontent.com/6038779/60862873-893c6c80-a251-11e9-83f6-012b48f9a395.png)

#### What is the expected behaviour
the result not contain html

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: chrome 73.0.3683.86
- Docsify version:  v4.8.3
- Docsify plugins:

**Comment by anikethsaha** [comment]
the issue is unclear to me please elaborate.
Also I tested the link you gave. Not sure as the content was in Chinese but when typing 25 I could see some results with 25 in them

**Comment by anikethsaha** [comment]
Please comment if it still exist 👍 
thanks
