### ISSUE TITLE
How to change markdown parser

### ISSUE THREAD

**Issue by qazzyl** [docsifyjs/docsify#882]
## Feature request

Can I change parser from marked to markdown-it. I really need the footnote features.

**Comment by berot3** [comment]
This was already asked in #789. I would like to add here some more reasons for markdown-it.

1. docute seems to have it? ;) https://github.com/egoist/docute-markdown-it
2. marked does not have many [features](https://marked.js.org/#/USING_ADVANCED.md)
3. markdown-it has many plugins, see this screenshot for example below.
<details><summary>screenshot</summary>
<p>

![screen](https://raw.githubusercontent.com/ravenq/markdown-it-vue/master/doc/markdown-it-vue.png)

</p>
</details>

### More plugins I need: 

- https://github.com/markdown-it/markdown-it-footnote
- https://github.com/markdown-it/markdown-it-deflist
- https://github.com/markdown-it/markdown-it-abbr
- https://github.com/camelaissani/markdown-it-include
- https://github.com/markdown-it/markdown-it-mark
- https://github.com/adam-p/markdown-it-smartarrows
- https://github.com/tatsy/markdown-it-imsize
- https://github.com/arve0/markdown-it-underline
- https://www.npmjs.com/package/markdown-it-center-text
- https://github.com/markdown-it/linkify-it
- https://github.com/docarys/markdown-it-admonition

---

FYI: I am coming from mkdocs and there I have all those features. But of course I'd like to use docsify!

**Comment by rcarmo** [comment]
I’m interested in using Remarkable instead, so I’m chiming in here in case this becomes a build option.

**Comment by berot3** [comment]
I am with you, remarkable would be fine too!

**Comment by berot3** [comment]
Maybe there is already some kind of way? I need a clever guy to figure it out! :)

Because in this comment https://github.com/docsifyjs/docsify/issues/144#issuecomment-291851948 @QingWei-Li states that...
> 
> 
> `markdown-it` size is very big. I do not think it's a big problem. But you can custom markdown parser by `markdown` option https://docsify.js.org/#/markdown

I'm not sure what he means by "`markdown-it` size is very big"...

As it states on the markdown-docs:
```
window.$docsify = {
  markdown: function(marked, renderer) {
    // ...

    return marked
  }
}
```

so maybe we can say this instead?:
```
markdown: function(mardown-it, renderer) {
    // ...

    return markdown-it
  }
```

**Comment by varadpoddar** [comment]
It's doable using [custom plugins](https://docsify.now.sh/write-a-plugin?id=write-a-plugin).
For example : 

```
\\ Script files added before calling window.$docsify.
\\ Markdown-it V10.0
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/10.0.0/markdown-it.min.js" integrity="sha256-YASERpEeN8gRNr/Fy4Km34WGFqIq1h6HkJMAQnVHlhk=" crossorigin="anonymous"></script>
\\ Markdown-It-Attrs for Markdown-it
<script src="https://wzrd.in/standalone/markdown-it-attrs@latest" charset="utf-8"></script>
```

Now within your window.$docsify you can create a custom plugin to do the markdown for you.

```
window.$docsify = {
            plugins:[
            function (hook,vm) {
                hook.beforeEach(function (html) {
                    var md = window.markdownit();

                    md.use(markdownItAttrs, {
                        // optional, these are default options
                        leftDelimiter: '{',
                        rightDelimiter: '}',
                        allowedAttributes: []  // empty array = all attributes are allowed
                    });
                    return md.render(html);
                });
            }
            ]
        };
```
This would let you render the doc using markdown-it & since there would be no other markdown left, the other renderer would leave it alone. However, there could be performance implications. (Redundency)

**Comment by rockmanvnx6** [comment]
@varadpoddar your solution doesn't render footnote, plus the todo check list seems to be broken, is there any thing i have to add on?

**Comment by varadpoddar** [comment]
@rockmanvnx6 

The footnotes and task lists functionality is a part of [markdown's extended syntax](https://www.markdownguide.org/extended-syntax)

You should add these corresponding packages for markdown-it. (If you choose to use markdown-it).

- [markdown-it-task-list](https://github.com/revin/markdown-it-task-lists)
- [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote)

PS : If you are a web developer, you should test these plugins out using [browsify's CDN](https://wzrd.in/)

Example Code : 
```html
\\ Script files added before calling window.$docsify.

\\ Markdown-it V10.0
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/10.0.0/markdown-it.min.js" integrity="sha256-YASERpEeN8gRNr/Fy4Km34WGFqIq1h6HkJMAQnVHlhk=" crossorigin="anonymous"></script>

\\ Markdown-It-Attrs for Markdown-it
<script src="https://wzrd.in/standalone/markdown-it-attrs@latest" charset="utf-8"></script>

\\ Markdown-It-Footnote for Markdown-it
<script src="https://wzrd.in/standalone/markdown-it-footnote@latest" charset="utf-8"></script>

\\ Markdown-It-Task-List for Markdown-it
<script src="https://wzrd.in/standalone/markdown-it-task-list@latest" charset="utf-8"></script>

\\ Docsify

<script>
        window.$docsify = {
            plugins:[
            function (hook,vm) {
                hook.beforeEach(function (html) {
                    var md = window.markdownit();

                    md.use(markdownItAttrs, {
                        // optional, these are default options
                        leftDelimiter: '{',
                        rightDelimiter: '}',
                        allowedAttributes: []  // empty array = all attributes are allowed
                    }).use(markdownitFootnote).use(taskLists);
                    return md.render(html);
                });
            }
            ]
        };
</script>

**Comment by rockmanvnx6** [comment]
@varadpoddar thank you, for the script to work, I've to modify a bit:
```
        function (hook,vm) {
                hook.beforeEach(function (html) {
                    var md = window.markdownit();

                    md.use(window.markdownItAttrs, {
                        // optional, these are default options
                        leftDelimiter: '{',
                        rightDelimiter: '}',
                        allowedAttributes: []  // empty array = all attributes are allowed
                    }).use(window.markdownItFootnote)
                    .use(markdownItTaskList.default);
                    return md.render(html);
                });
        },
```

**Comment by varadpoddar** [comment]
@QingWei-Li Can I add the above workaround in the current docs in the form of a PR?
I believe this can also help close the issue.

**Comment by anikethsaha** [comment]
**You cant change the parser**

 It is in our roadmap for using a new pluggable parser for `v5`.
https://github.com/docsifyjs/docsify/issues/823#issuecomment-557700008

Closing this as it will be considered if required.
Please comment below if you want to add any more
