### ISSUE TITLE
Broken image at the bottom of README.md

### ISSUE THREAD

**Issue by lalaithan** [docsifyjs/docsify#885]
#### Steps to reproduce
Visit README.md with Chromium Version 75.0.3770.90 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)

#### What is current behaviour
There's a broken image symbol instead of showing the FOSSA status badge

#### What is the expected behaviour
FOSSA status badge should be shown.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  LinuxMint 19.1 (64-bit)
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
Feel Free to submit a PR with the fix
