### ISSUE TITLE
table can't work when i use order list

### ISSUE THREAD

**Issue by gotodoit** [docsifyjs/docsify#886]
## Bug Report
table can't work when i use order list
#### Steps to reproduce
```
1. test1
2. test2

   1. t1
   2. t2

      | name | age |
      | ---- | --- |
      | tom  | 12  |
      | jim  | 32  |

3. test3
```
#### What is current behaviour
![image](https://user-images.githubusercontent.com/10516736/61350403-fd05f700-a899-11e9-8309-c24c2d3039e8.png)

#### What is the expected behaviour

![image](https://user-images.githubusercontent.com/10516736/61350372-eeb7db00-a899-11e9-9e72-31a62ea61337.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: v12.4.0
- npm/yarn version: 6.9.0
- Browser version: 
- Docsify version: 4.9.4
- Docsify plugins: 
//unpkg.com/docsify/lib/plugins/zoom-image.js
//unpkg.com/docsify/lib/plugins/search.js

**Comment by anikethsaha** [comment]
This is related to `markedjs` as we are using [`markedjs`](https://github.com/markedjs/marked) to process our markdown.
You can submit an issue in their repo.

Closing this 👍 
Please comment below if you think it didnt solve your issue or you are looking for something else
