### ISSUE TITLE
Block highlight lost when printing from Chrome

### ISSUE THREAD

**Issue by msi-matthew** [docsifyjs/docsify#888]
#### Steps to reproduce

Print document from Chrome

#### What is current behaviour

Code block highlighting is lost when printing document

<img width="404" alt="Screen Shot 2019-07-30 at 1 50 14 PM" src="https://user-images.githubusercontent.com/36428623/62156622-fc755380-b2d0-11e9-9c45-cdfe24d609b9.png">

#### What is the expected behaviour

<img width="806" alt="Screen Shot 2019-07-30 at 1 49 09 PM" src="https://user-images.githubusercontent.com/36428623/62156580-e9fb1a00-b2d0-11e9-8880-a61104faecd1.png">

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS
- Node.js version: NA
- npm/yarn version: NA
- Browser version: 75.0.3770.142
- Docsify version: 4.9.4
- Docsify plugins: NA

**Comment by anikethsaha** [comment]
This is not an issue with docsify. You try to print Github's code snippets you will see the same behavior. 

Closing this. 👍 
Please comment below if you want to add anything to it 👍
