### ISSUE TITLE
Template ul ol margin must be for the firts list level only

### ISSUE THREAD

**Issue by xmedeko** [docsifyjs/docsify#889]
#### Steps to reproduce
Create nested lists, e.g.
```markdown
* First level list
  * Second level list
```
And use template buble or dark. 

#### What is current behaviour
buble and dark templates define `ul, ol` margin as `margin 1.2em 0` and it's applied for the nested `ul, ol` too, which is not right.

#### What is the expected behaviour
Apply the margin (top and bottom only) to the first level of the lists only.

I am not the CSS expert, but I think it could be fixed by CSS selector:
`.markdown-section > ul, .markdown-section > ol`

#### Other relevant information
- Docsify version: 4.9.4

**Comment by anikethsaha** [comment]
> buble and dark templates define ul, ol margin as margin 1.2em 0 and it's applied for the nested ul, ol too, which is not right.

Please share the screenshots.
I am wondering why it's not right and need to see where is breaking.

For time being, you can use https://jhildenbiddle.github.io/docsify-themeable so customize the styling. We will support customizing natively soon with v5 using docsify-themeable.

**Comment by xmedeko** [comment]
#### What is current behaviour
See https://codesandbox.io/s/docsify-bug-tetpp

![Docsify_bug_889](https://user-images.githubusercontent.com/1101801/69495707-3692e280-0eca-11ea-8514-ab27851650f1.png)

#### What is the expected behaviour
Uncomment the `buble-fix.css` in the `index.html` to see what I would expect. Or see the the screenshots:

![Docsify_bug_889_expected](https://user-images.githubusercontent.com/1101801/69495705-31359800-0eca-11ea-9996-6d1a7ad00915.png)

**Comment by anikethsaha** [comment]
Feel free to submit the fix

**Comment by xmedeko** [comment]
I do not know CSS well, the `buble-fix.css` more a workaround than fix. If I remove the rule from `buble.styl`:
```styl
.markdown-section figure, .markdown-section p, .markdown-section ul, .markdown-section ol
  margin 1.2em 0
```
Then the margins are a bit smaller, but it looks ok for me. Moreover, there's one more rule with `ul, ol` margin:
```styl
.markdown-section p, .markdown-section ul, .markdown-section ol
  line-height 1.6rem
  margin 0 0 1em 0
  word-spacing 0.05rem
```

So, instead of adding new rules, the `buble.style` should be cleared and fixed, but do not know exactly how to fix that.

**Comment by anikethsaha** [comment]
This bug still exists !

PR welcome

**Comment by jhildenbiddle** [comment]
Fixed in upcoming v5-related PR.
