### ISSUE TITLE
Do not replace the leading digit of the anchor link

### ISSUE THREAD

**Issue by bgpat** [docsifyjs/docsify#895]
#### Steps to reproduce

Create `link.md`, and start the dev srerver.

<details>
<summary>link.md</summary>

```md
# 1. one

111

# 2. two

222

# 3. three

333
```

</details>

#### What is current behaviour

Docsify adds `_` into between `#` and the leading digit.

![image](https://user-images.githubusercontent.com/6045753/62559316-b2cecf00-b8b5-11e9-8ae2-df4250005c37.png)

#### What is the expected behaviour

I expect that it doesn't add like GitHub's parser.

![image](https://user-images.githubusercontent.com/6045753/62559466-0b05d100-b8b6-11e9-8d05-ec290b4f2f84.png)

---

GitHub's markdown parser:

![image](https://user-images.githubusercontent.com/6045753/62561622-85385480-b8ba-11e9-9c67-64e4734ecb96.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS
- Node.js version: v11.12.0
- npm/yarn version: 6.9.0
- Browser version: Firefox 67.0.4
- Docsify version: develop branch (https://github.com/docsifyjs/docsify/commit/1d3246a26f5225fb5e82d69e2b03b908ba6c0196)
- Docsify plugins: nothing

**Comment by anikethsaha** [comment]
Are you facing any issue having `_` in front?

If yes, then we can consider it as a bug after reviewing.
Else I don't think it is causing if works fine and it's just a different approach to solving a problem.

**Comment by bgpat** [comment]
> Are you facing any issue having `_` in front?

The fragment link which starts of `_` and works on GitHub's Markdown parser doesn't work through Docsify. I faced this problem in creating the TOC to numbered heading block, e.g., `## 1. foo` or `## 2. bar`.
