### ISSUE TITLE
能不能给静态assets添加hash？

### ISSUE THREAD

**Issue by uwings** [docsifyjs/docsify#897]
能不能给静态assets添加hash？  毕竟在编写过程中内容是经常变化的,总去清除浏览器缓存还会误伤其他需要保留的内容，自己又不会加……

**Comment by felangel** [comment]
Can you please rewrite the question in English? Closing for now.

**Comment by calmchang** [comment]
可以利用ext参数解决
例如:
ext:`.md?ms=${Date.now()}`
