### ISSUE TITLE
feature request: placement for search bar

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#903]
## Feature request

ability to also place the search bar under the title

#### What problem does this feature solve?

Keeps the title/logo in the prime location. Search feature is secondary.

**Comment by trusktr** [comment]
Applying `docsify-themable`'s CSS handles it. Cool!

**Comment by anikethsaha** [comment]
> Applying docsify-themable's CSS handles it.

closing in favor of this .

Please comment if this is not what you are looking for as a flow
