### ISSUE TITLE
Request: Remove subLevel for certain links

### ISSUE THREAD

**Issue by danbulant** [docsifyjs/docsify#905]
#### What problem does this feature solve?

I have an overview of categories where I have titles and then 2-3 sentences about them. When the overview is opened, the categories are shown twice (first the subs, then the real ones) 

#### What does the proposed API look like?

in links in sidebar, an option like --noSubLevel

#### Are you willing to work on this yourself?

I don't know how to do it.

**Comment by anikethsaha** [comment]
Unclear about the Request.
Closing this. Feel free to submit a new issue with detailed requirements
