### ISSUE TITLE
[bug] [search] Result incorrectly duplicated, pointing to multiple pages.

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#910]
#### Steps to reproduce

Not sure.

#### What is current behaviour

I only have one page titled "Hello 3D", however searching for "Hello 3D" (with search plugin) results in 5 results pointing to 5 different pages:

<img width="304" alt="Screen Shot 2019-08-19 at 9 57 01 PM" src="https://user-images.githubusercontent.com/297678/63318732-4ba91580-c2cc-11e9-9e01-5d1b8096ff54.png">

Each one of those results leads to an entirely different page, and only the first result goes to the page with "hello" in it. 

#### What is the expected behaviour

There's only one page called "Hello 3D" , so I would expect there to be only one result for that page.

Each one of those "Hello 3D" results takes me to an unrelated page.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Docsify version: 4.9.4
- Docsify plugins: search

**Comment by trusktr** [comment]
Alright, I know why it happened!! The search index is being stored in Local Storage. When I make new pages, I copy one page, then rename it. If I save the page, before renaming it and changing the content, then the search feature indexes it and saves it in Local Storage (duplicate content).

After changing the page content, the search index stays incorrect.

I was able to clear the Local Storage in devtools, and refresh, and the problem went away.

Seems like some care needs to be taken to ensure that the index does not contain content for non-existent pages.

**Comment by anikethsaha** [comment]
> Alright, I know why it happened!! The search index is being stored in Local Storage. When I make new pages, I copy one page, then rename it. If I save the page, before renaming it and changing the content, then the search feature indexes it and saves it in Local Storage (duplicate content).
> 
> After changing the page content, the search index stays incorrect.
> 
> I was able to clear the Local Storage in devtools, and refresh, and the problem went away.
> 
> Seems like some care needs to be taken to ensure that the index does not contain content for non-existent pages.

Thanks for the detailed explanation. Yes its a bug. 

Feel free to submit the fix 👍 

_perhaps for time being we can add an instruction to the search plugin page about this issue_

**Comment by anikethsaha** [comment]
cc @trusktr can you take this ? if it still exists ?

**Comment by sy-records** [comment]
You can use `pathNamespaces` to distinguish between. https://docsify.js.org/#/plugins?id=full-text-search

**Comment by AlexHolly** [comment]
Added ```localStorage.clear();``` in index.html after ```window.$docsify``` execution seems to work.
