### ISSUE TITLE
[search] Don't index encoded content, decode it first.

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#911]
#### What problem does this feature solve?

I noticed that the search plugin indexes encoded content, which looks strange in the results.

I have a title, like

```md
# &lt;obj-model&gt;
```

because otherwise if I write 

```md
# <obj-model>
```

the Markdown parser will try to render a `<obj-model>` element, and therefore the title will not appear (it will be an empty `<obj-model>` in the DOM).

But the search plugin will index the encoded content, so it will look like this:

<img width="313" alt="Screen Shot 2019-08-19 at 10 06 06 PM" src="https://user-images.githubusercontent.com/297678/63319063-98412080-c2cd-11e9-856a-b431c1555436.png">

#### What does the proposed API look like?

Perhaps the search plugin should unencode the content? Not sure if there's any bad outcomes of doing that.

#### How should this be implemented in your opinion?

`decodeURIComponent` might do the trick.

#### Are you willing to work on this yourself?

I may get around to it. For now, I'll change my title and make due.

**Comment by anikethsaha** [comment]
> Perhaps the search plugin should unencode the content? Not sure if there's any bad outcomes of doing that.

I think there can be bad outcomes for this, this may lead to XSS if unencoding in the rendered dom.

[refer this](https://stackoverflow.com/questions/33184716/is-it-safe-to-display-html-code-decoded-by-decodeuricomponent-from-a-url)

Closing this for now. Please create a new issue if you think you can work it out safely or you have something more to share about it 

Thanks 👍

**Comment by trusktr** [comment]
If we display text (not execute it) there's no security issue.

If we do want to execute it (f.e. accept HTML and render it) then we can use DOMPurify, but I don't think we want to render HTML code in the search results.

I think we should keep this open because the behavior currently horrible.

This is my sidebar using default markdown features:

![bad-search-results](https://user-images.githubusercontent.com/297678/82841000-6fb40b80-9e89-11ea-827d-5bdfd4715a9b.png)

It is not readable. I think we should fix this.

**Comment by trusktr** [comment]
Plus, this leads to the search having results based on the source code of the website, which is also confusing for the end user.

**Comment by trusktr** [comment]
Or for example, see here the search for "code" shows totally unrelated search results just because of the source using `<code>` markup:

![code-results](https://user-images.githubusercontent.com/297678/82841462-08975680-9e8b-11ea-9b46-3cbe4ed56ba0.png)

Hmmmm. Now that I think about it, I wonder why my site has these source code results, but Docsify's site doesn't. I think this may be due to adding a custom markdown plugins, f.e.:

```
			markdown: {
				// `this` in the following hooks is an instace of Marked Renderer
				renderer: {
					code: function(code, lang) {
						// support for mermaid (diagrams via markdown)
						if (lang === 'mermaid') {
							return '<div class="mermaid">' + mermaid.render('mermaid-svg-' + num++, code) + '</div>'
						}

						return this.origin.code.apply(this, arguments)
					},
				}
				// etc...
```

**Comment by trusktr** [comment]
Hmmmm. Now that I think about it, I wonder why my site has these source code results, but Docsify's site doesn't seem to have this problem.

Maybe it is due to custom markdown plugins? f.e.:

```js
markdown: {
	renderer: {
		code: function(code, lang) {
			if (lang === 'mermaid') {
				return '<div class="mermaid">' + mermaid.render('mermaid-svg-' + num++, code) + '</div>'
			}

			return this.origin.code.apply(this, arguments)
		},

		html(html) {
			const matches = html.matchAll(reAnchorWithHref)

			const {linkTarget, router} = vm.compiler

			for (const match of matches) {
				if (match[0].startsWith('<a docsify-link')) continue

				let href = match[1] || match[2] || match[3]

				const originalHref = href

				const hasQuotes = !!(match[1] || match[2])

				// based on Docsify's Compiler._initRenderer() logic for the markdown "link" hook {{{

				// TODO make some syntax for telling it to ignore the compiling the href
				const ignoreLink = false

				if (
					!Docsify.util.isAbsolutePath(href) &&
					!vm.compiler._matchNotCompileLink(href) &&
					!ignoreLink &&
					// skip hrefs like `#/page?id=section`, which
					// are already in the format Docsify compiles
					// hrefs to
					// TODO move this to router.toURL
					!href.trim().startsWith('#/')
				) {
					if (href === vm.compiler.config.homepage) {
						href = 'README'
					}
					href = router.toURL(href, null, router.getCurrentPath())
				}

				// }}}

				if (!hasQuotes) href = '"' + href + '"'

				html = html.replace(originalHref, href)
			}

			return html
		},

		// TODO move this to Docsify?
		paragraph(text) {
			// in case the paragraph text contains inline HTML
			text = this.html(text)

			return this.origin.paragraph.call(this, text)
		},
	},
},
```

**Comment by trusktr** [comment]
We may also need a way to specify which content is searchable in cases where some content is being excluded.

**Comment by trusktr** [comment]
Hmmm. So in my auto-generated markdown files (from code JSDoc comments), I have some stuff like

```md
# <code>class <b>Node</b> extends [ImperativeBase](ImperativeBase.md), HTMLNode</code> :id=Node
```

which is valid markdown, and renders like

![title-code](https://user-images.githubusercontent.com/297678/82845720-7f881b80-9e9a-11ea-9799-e93764d21550.png)

I wonder how we can handle these forms of valid markdown.

**Comment by anikethsaha** [comment]
We can discuss this about the non-executable.
