### ISSUE TITLE
Missing rel="noreferrer noopener" for links opening in new tab/window

### ISSUE THREAD

**Issue by vkallore** [docsifyjs/docsify#914]
#### Steps to reproduce

Add a link in md file.

#### What is current behaviour

The default configuration opens a link in new tab/window. Missing rel="noreferrer noopener".

#### What is the expected behaviour
Don't we need to add rel="noreferrer noopener"?

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: NA
- Node.js version: NA
- npm/yarn version: NA
- Browser version: NA
- Docsify version: 4.9.4
- Docsify plugins: NA

**Comment by anikethsaha** [comment]
did you try `_self` in `externalLinkTarget` ?

**Comment by vkallore** [comment]
Sorry missed this comment as we continued discussion on the PR #917

**Comment by anikethsaha** [comment]
Issue description is explained in details in #917
