### ISSUE TITLE
Support GLOSSORY.md like gitbook?

### ISSUE THREAD

**Issue by lanthree** [docsifyjs/docsify#919]
#### What problem does this feature solve?
To write glossory in one place.

#### What does the proposed API look like?
Just use glossory.md by defualt. the glossory.md maybe like this:
```
# word
meaning
```

#### How should this be implemented in your opinion?
Highlight the words of glossory.md for every pages. 
Pop a tips when cursor hover on it. 
Open a new glossory page standalone, when click on it.

#### Are you willing to work on this yourself?
Not really.

**Comment by TheGreenToaster** [comment]
I wrote a plugin for this here https://github.com/TheGreenToaster/docsify-glossary. I have also created a PR to get it added to awesome docsify. If you have any issues or improvements just submit an issue on the repo.

**Comment by anikethsaha** [comment]
> I wrote a plugin for this here https://github.com/TheGreenToaster/docsify-glossary. 

Closing this in favor of the above plugin. I guess that should work for your request. Please create a separate issue if this is not you were looking for and explain a bit extra for that. 

Thanks 👍
