### ISSUE TITLE
When accessing a page that does not exist, the page will be in the pending state and the page will be stuck.

### ISSUE THREAD

**Issue by yuxesd** [docsifyjs/docsify#920]
## Bug Report
When accessing a page that does not exist, the page will be in the pending state and the page will be stuck.
#### Steps to reproduce
For example，When I visit campus.xxxx.com/compute/uhost/introduction/uhost/dhag.md, this page does not exist. 
1. using  routermode  history
2. setting  alias   '/.*/_sidebar.md': '/_sidebar.md'
3.using the latest version of Docsify

#### What is current behaviour
1. Response return  200，not 404 
2. The page will be requested multiple times
3. The content returned is index.html's content
4. Last request returned to pending， the page cannot be accessed
![](https://static.ucloud.cn/c34db52cb5b047cd9fdb6f2dbdc1d6fb.png)

#### What is the expected behaviour
1. when pages  does not exist,  response return 404, page content display 404 not found

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: centos
- Node.js version:  v6.2.2
- npm/yarn version: 
- Browser version: Google Chrome  76.0.3809.100
- Docsify version: 4.9.4
- Docsify plugins: docsify-pagination  docsify-copy-code  zoom-image

**Comment by yuxesd** [comment]
I found the reason, because I used the history mode, I set the nginx configuration ,as follows：
“try_files $uri $uri/ index.html”.
If the page does not exist, it will return index.html.
How can I solve the problem that the page does not exist, it will return 404？

**Comment by yuxesd** [comment]
using  history router,  notFoundpages  doesn't work. How to solve  this problem in history mode?

**Comment by yuxesd** [comment]
found a solution, using  alias

**Comment by lvyongfeng** [comment]
@yuxesd 您好，请问你使用 alias  解决 404  的配置语法可以共享一下吗？

**Comment by lvyongfeng** [comment]
@yuxesd Hello, can you share the configuration syntax of 404 using alias?

**Comment by yuxesd** [comment]
> @yuxesd 您好，请问你使用 alias 解决 404 的配置语法可以共享一下吗？

alias比较麻烦，我最后用nginx来解决404的，配置如下
server {
   location ~* .(md)$ {
      }
      location / {
          index  index.html;
         try_files $uri $uri/ /index.html;
         error_page 403 /index.html;
       }
}

window.$docsify = {
  notFoundPage:'404.md',
}

https://docs.ucloud.cn/

**Comment by lvyongfeng** [comment]
@yuxesd OK ，Thanks 。

PS: We may be colleagues 。
