### ISSUE TITLE
[Question] onlyCover with loadNavbar

### ISSUE THREAD

**Issue by mpfaff** [docsifyjs/docsify#923]
Is it possible to load the navbar with `onlyCover` enabled?

**Comment by anikethsaha** [comment]
```js
window.$docsify = {
  name: "REPO",
  repo: "https://github.com/some/repo",
  loadNavbar: true,
  coverpage: true,
  onlyCover: true
};
```

I guess you cant. And it makes sense if your docs site is only having the cover page, then having navbar doesn't do anything

**Comment by anikethsaha** [comment]
Closing this 👍 
Please comment below if you think this didnt help you or you have something else to add 👍
