### ISSUE TITLE
support prism.js autoloader plugin

### ISSUE THREAD

**Issue by CatchLife** [docsifyjs/docsify#924]
prism.js provide  a autoloader plugin for automatically loads languages when necessary.
but docsify load document by request ,not server render ,So docsify can trigger the autoloader plugin again after rendering.

![https://s2.ax1x.com/2019/09/24/ukqGSf.png](https://s2.ax1x.com/2019/09/24/ukqGSf.png)

**Comment by anikethsaha** [comment]
@CatchLife can you explain this a bit. is it a feature request or bug ?

**Comment by Erimus-Koo** [comment]
read this
Autoloader ▲ Prism plugins
https://prismjs.com/plugins/autoloader/

This needs a new attribute to element like:
data-dependencies="markup,css!"

then the prism can auto loader highlights for it.

**Comment by trusktr** [comment]
The script tag can be included one's self in the HTML entry of a Docsify site.
