### ISSUE TITLE
When `relativePath: true`, relative path links in _sidebar do not resolve reasonably

### ISSUE THREAD

**Issue by StoneyJackson** [docsifyjs/docsify#925]
## Bug Report

First, let me say, I'm loving Docsify! Great stuff! 👍

Now on to my issue... 

When using both `loadSidebar:true` and `relativePath:true` relative paths in _sidebar.md files are resolved against the page being rendered rather than the location of the _sidebar.md file. This leads to surprising results. When one writes a relative path in a file, one expects it to be relative to that file, not some other file that implicitly includes it in some subdirectory.

***The work around*** is to only use absolute paths in _sidebar.md files since they may be rendered in arbitrarily nested subdirectories. The problem with this is that it makes it difficult to move an entire subdirectory that contains a _sidebar.md, and it requires authors to know and encode the full path to their subsite.

I am in an environment where we pull documentation from multiple projects and integrate them into one website. I don't want authors to encode the full path to their project's documentation in the main site. This creates an unnecessary dependency, making it challenging to reorganize the structure of the combined site, and it also places additional burden on authors to know the path of their subsite.

So I'm hoping that it's possible to resolve relative URLs in _sidebar.md files against the location of the _sidebar.md file. 🤞 

##### GIVEN

```bash
$ tree
.
├── README.md
├── _sidebar.md
├── index.html
├── subdir1
│   └── README.md
└── subdir2
    └── README.md

2 directories, 5 files

$ cat _sidebar.md
- [Home](README.md)
  - [Subdir1](subdir1/README.md)
  - [Subdir2](subdir2/README.md)

$ cat index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>LibreFoodPantry</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
      loadSidebar: true,
      relativePath: true,
    };
	</script>
	<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
</body>
</html>
$
```

##### WHEN

1. Run the server
2. Browse to http://localhost:3000/#/
3. Click Subdir1
4. Click Subdir2

#### What is current behaviour

Get a 404

#### What is the expected behaviour

Display Subdir2

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: MacOS
- Node.js version: v12.9.1
- npm/yarn version: 1.17.3
- Browser version: Google Chrome 77.0.3865.90 (Official Build) (64-bit)
- Docsify version: Latest from unpkg.com (see index.html)
- Docsify plugins: None

**Comment by anikethsaha** [comment]
It's nice to have this feature like from each markdown file have some similar attribute like
`relativeURL: self` or `relativePath:self`. the paths will be appended with `__dirname` to make itself relative. _thats what I am thinking_

But we are not sure if we can ship it soon or in `v4.x` as we are having quite a big number of bugs to fix.

But it's considerable 👍 .
I will put this in our discussion. I am pretty sure you can implement this using a custom plugin also.

Creating plugins is quite simple, perhaps you can try creating this one 👍 ?

**Comment by StoneyJackson** [comment]
@anikethsaha Thanks for the feedback, and promoting this to discussion.

I like the idea of a plugin. I might just try that. If I do, I'll post a link to it here.

**Comment by anikethsaha** [comment]
> I like the idea of a plugin. I might just try that. If I do, I'll post a link to it here.

Great 👍

**Comment by dellagustin-sap** [comment]
I recently found out this very same behavior.
I was going to report it to ask if it is working as designed or if this is a bug.

In my opinion, with respect to sidebar, it is a bug, as I could not imagine any commonly used scenario where this behaviour would be desireable.

@anikethsaha, do you see any supported scenario that would break if the links from sidebar, when relative, would be always relative to the file location, instead of relative to the location of the file used to generate the current page?

**Comment by anikethsaha** [comment]
@dellagustin-sap thanks for your time. Can you submit an issue!
I lost context of these two issues so I need a fresh start on these.

**Comment by StoneyJackson** [comment]
Sorry I never got around to this :(

**Comment by ms-ati** [comment]
This still seems to be an issue in 2025?
