### ISSUE TITLE
Unable to start the application with npm run bootstrap && npm run dev cmd

### ISSUE THREAD

**Issue by THARAKS** [docsifyjs/docsify#926]
#### Steps to reproduce
clone the application
run the command:npm run bootstrap && npm run dev

#### What is current behaviour
node build/build.js

ERROR: Task not found: "'css"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.9.4 watch:css: `run-p 'css -- -o themes -w'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.9.4 watch:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tharamani\AppData\Roaming\npm-cache\_logs\2019-09-26T13_17_13_748Z-debug.log
Serving "C:\Users\tharamani\Documents\docsify" at http://127.0.0.1:3000
ERROR: "watch:css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.9.4 dev: `run-p serve watch:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.9.4 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tharamanik\AppData\Roaming\npm-cache\_logs\2019-09-26T13_17_14_425Z-debug.log
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: windows
- Node.js version:  v11.7.0
- npm/yarn version: v6.11.3
- Browser version: latest
- Docsify version:4.9.4 
- Docsify plugins: none

**Comment by jianse** [comment]
That's because the apostrophe in windows is considered part of the command by npm-run-all. In order to solve this problem, there are two solutions.

1. If you use win10 preview, wsl is a good choice.
2. Modify the `script` part of  `package.json` to modify `'` into the `\"`. And you should remove the wildcard (*.styl), stylus does not work well with wildcards under windows.

like this
```
"scripts": {
    "bootstrap": "npm i && lerna bootstrap && npm run build:ssr",
    "serve": "node server",
    "serve:ssr": "cross-env SSR=1 node server",
    "dev": "run-p serve watch:*",
    "dev:ssr": "run-p serve:ssr watch:*",
    "lint": "eslint {src,packages} --fix",
    "test": "mocha test/*/**",
    "css": "stylus src/themes/ -u autoprefixer-stylus",
    "watch:css": "run-p \"css -- -o themes -w\"",
    "watch:js": "node build/build.js",
    "build:css:min": "mkdir lib/themes && run-p \"css -- -o lib/themes\" && node build/mincss.js",
    "build:css": "mkdir -p  themes && run-p \"css --  -o themes\"",
    "build:js": "cross-env NODE_ENV=production node build/build.js",
    "build:ssr": "node build/ssr.js",
    "build:cover": "node build/cover.js",
    "build": "rimraf lib themes/* && run-s build:js build:css build:css:min build:ssr build:cover",
    "pub:next": "cross-env RELEASE_TAG=next sh build/release.sh",
    "pub": "sh build/release.sh",
    "postinstall": "opencollective postinstall"
  },
```
Forgive my English, hope it's help

**Comment by THARAKS** [comment]
after updating the package.json , i am facing new issue,

opencollective postinstall

'opencollective' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.9.4 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tharamanik\AppData\Roaming\npm-cache\_logs\2019-09-27T06_48_45_374Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify@4.9.4 bootstrap: `npm i && lerna bootstrap && npm run build:ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docsify@4.9.4 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tharamanik\AppData\Roaming\npm-cache\_logs\2019-09-27T06_48_46_743Z-debug.log

kindly help me to fix

**Comment by THARAKS** [comment]
Hi ,
I have tried to fix this error by doing
npm i -g opencollective
after that i ran the command npm run bootstrap && npm run dev , application started without any error
but the web page is showing up as blank page , with loading message on it
in console i was getting some errors  as shown below may be is it because of that , 

docsify.js:2408 Uncaught ReferenceError: tinydate is not defined
    at docsify.js:2408
(anonymous) @ docsify.js:2408
prism-bash.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-bash.min.js:1
(anonymous) @ prism-bash.min.js:1
prism-markdown.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-markdown.min.js:1
(anonymous) @ prism-markdown.min.js:1
prism-nginx.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-nginx.min.js:1
(anonymous) @ prism-nginx.min.js:1
(index):108 Live reload enabled.

kindly help to resolve the issue

**Comment by jianse** [comment]
try run
```
npm install
```
then run 
```
rpm run dev
```

**Comment by THARAKS** [comment]
tried your solution,

application is starting but web page is not loading , it is still a blank white page

in console i can see the following error
docsify.js:2408 Uncaught ReferenceError: tinydate is not defined
    at docsify.js:2408
(anonymous) @ docsify.js:2408
prism-bash.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-bash.min.js:1
(anonymous) @ prism-bash.min.js:1
prism-markdown.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-markdown.min.js:1
(anonymous) @ prism-markdown.min.js:1
prism-nginx.min.js:1 Uncaught ReferenceError: Prism is not defined
    at prism-nginx.min.js:1
(anonymous) @ prism-nginx.min.js:1
(index):108 Live reload enabled.

**Comment by jianse** [comment]
This only happens when you first clone the codebase and run the development environment, because the files in the lib directory are not built at that time. You just need to click the refresh button to apply the file you just built.

**Comment by THARAKS** [comment]
I have refreshed the codebase still i am facing same issue in the chrome console

**Comment by jianse** [comment]
I can't reproduce what you said, I am very sorry that I can't help you.

**Comment by THARAKS** [comment]
please tell me how to start the application after cloning it , i will delete node modules and try again

**Comment by jianse** [comment]
npm install
npm run dev

**Comment by THARAKS** [comment]
ok 2 minutes i am trying again

**Comment by THARAKS** [comment]
Hi I have tried with your commands , still i am facing the same issue , attaching the screen shot

![image](https://user-images.githubusercontent.com/15693408/66185583-8d83f480-e69d-11e9-8323-fcd301190db7.png)

**Comment by jianse** [comment]
Refresh this page, can you still see this error?

**Comment by THARAKS** [comment]
yes, even after refreshing also the error is still coming

**Comment by THARAKS** [comment]
are able to reproduce this error? any solution on how to resolve this

**Comment by THARAKS** [comment]
i wanted to inform you one thing that i am able run the application on localhost with this command
`docsify serve docs`

**Comment by jianse** [comment]
Is there a `lib` directory in your project directory?

**Comment by THARAKS** [comment]
yes it is there

**Comment by jianse** [comment]
Is there anything inside?

**Comment by THARAKS** [comment]
![image](https://user-images.githubusercontent.com/15693408/66187020-6deecb00-e6a1-11e9-9ff9-d11ebb9b8d44.png)

also plugins folders contains many files

**Comment by THARAKS** [comment]
i need one more information , i want to ship my docsify application to users, is there any dependency they have to install to view this application like node js and npm dependencies

or will it just work with docsify serve docs command?

**Comment by THARAKS** [comment]
In fact , i do not want my users to install any peer dependency , i just want to run as a static html file

for eg: user can just open index.html file , everything should work as normal

**Comment by jianse** [comment]
You only need to deploy your document on a static file server, users can view it directly through the browser.

**Comment by THARAKS** [comment]
thanks , i knew that , what about docsify serve docs command , does it need any peer dependency like node js , or it just works without any dependencies, i do not want to deploy it to any server so

**Comment by jianse** [comment]
sorry, I do not know that

**Comment by THARAKS** [comment]
okay lets resolve this issue which i am facing please

**Comment by anikethsaha** [comment]
Please share a minimal reproduction repo for this. 

> clone the application

I am not getting which application you are trying to run
