### ISSUE TITLE
Is it possible to serve the application as static html files, after building it

### ISSUE THREAD

**Issue by THARAKS** [docsifyjs/docsify#928]
#### What problem does this feature solve?

Instead of installing the dependency in all the system , i want to serve this as a static application

#### What does the proposed API look like?

share the application as zip file and download the zip file, open the index.html, it should start the application automatically

#### How should this be implemented in your opinion?
no idea

**Comment by wisniewski94** [comment]
What you can try is generating your docsify index.html, then open in in the browser, open dev tools, and download source and then save it to new .html file. Just make sure all links to scripts and stylesheets are correct.

**Comment by anikethsaha** [comment]
We have it on our roadmap https://github.com/docsifyjs/docsify/pull/802
