### ISSUE TITLE
Is this repository no longer managed?

### ISSUE THREAD

**Issue by JUNWOO45** [docsifyjs/docsify#932]
## Feature request
- I translated docsify to KOREAN ( https://github.com/JUNWOO45/docsify-kr )
#### What problem does this feature solve?
- But I dont know how to merge.

#### How should this be implemented in your opinion?
- Plz tell me how.

#### Are you willing to work on this yourself?
- Sure!

**Comment by timrodz** [comment]
Make a Pull Request from your repository :)

![image](https://user-images.githubusercontent.com/7434353/66361210-72392200-e9da-11e9-8a6b-13bfc585312b.png)

Make sure that your branch is going into docsify/master:

![image](https://user-images.githubusercontent.com/7434353/66361200-651c3300-e9da-11e9-8de2-b7527fc3cb93.png)

**Comment by timaschew** [comment]
This is the wrong place for these kind of questions. Use google: https://www.wikihow.com/Create-a-Pull-Request-on-Github
