### ISSUE TITLE
The Prism.js support code displays the line number. Why does the docsify do not have the corresponding configuration?

### ISSUE THREAD

**Issue by xiao-xiaoming** [docsifyjs/docsify#933]
#### What problem does this feature solve?
```
<pre class="line-numbers">
  ...
</pre>
```
It's like this Prism.js can display the line number, but I don't know docsify how to configure.

**Comment by anikethsaha** [comment]
I think its good to have it but as a configurable extension.

I guess prism uses [line number plugin for this](https://prismjs.com/plugins/line-numbers/).

We need to integrate it with docsify configuration as I dont think this is customizable with remark.

Feel free to submit a PR for this or better create a docsify plugin for this.
