### ISSUE TITLE
how to insert images

### ISSUE THREAD

**Issue by ShusenTang** [docsifyjs/docsify#936]
I already have a written document:
```
- docs
  - chap1
     - doc1.md
  ...
  - img
     - img1.png 
```

here I inserted the image `img1.png` into `doc1.md` using

```
<div align=center>
<img width="200" src="../img/img1.png"/>
</div>
```
This will show the img1 very well in GitHub or other markdown editor. But if I deploy the doc in gitpages, the image broken. 

If I use
```
<div align=center>
<img width="200" src="./img/img1.png"/>
</div>
```
it works.

But I don't want to make changes to my doc, how should I configure docsify to show the image properly?

**Comment by seconde-vie-ordi** [comment]
There's no way to configure docsify to show the image with ../ without changing your code.  ./ is the good way to write it. In the other issue, I was talking about the markdown syntax which is incorrect ![name](../url), that would be converted in html like this <img alt="name" src="./url" />.

**Comment by ShusenTang** [comment]
> There's no way to configure docsify to show the image with ../ without changing your code. ./ is the good way to write it. In the other issue, I was talking about the markdown syntax which is incorrect ![name](../url), that would be converted in html like this ![name](./url).

Thanks for your reply. I solved my problem using a workaround, I added
```
hook.beforeEach(function(content) {
            return content.replace(/..\/..\/img/g, "img");
          })
```
into `index.html` to convert all "../../img" into "img" before each parsing the Markdown file.
