### ISSUE TITLE
Add Registration Login and Manage Members' Reading Rights

### ISSUE THREAD

**Issue by despacito008** [docsifyjs/docsify#938]

**Comment by anikethsaha** [comment]
Please add more explanation with use-cases for your feature request 

Also please use the issue template and dont remove the contents. 

Thanks 👍

**Comment by Koooooo-7** [comment]
Halo.
In my opinion.Docisify is designed as  a lightweight documents site  generator that u can use/deploy  it easily. 
Docicify doesn't hv something like “Admin Manage”.. in other words.. it hasn't the BACK END. 
It seems a lot of things to do (user login/block/delete/user roles...etc) to make Docisify has an “User Manage”(has an BACK END)...and it would make Docisify  too heavy .
What u want I think it is  a Documentary/Content Manage System.

you'd better chosen a  CMS/Wiki application which has User Manage  to resolve ur demand. 

or...u can deploy ur own web application which has  the User Manage as a Interceptor/Filter  and then  redirect to Docisify pages.
