### ISSUE TITLE
docsify-edit-on-gitlab

### ISSUE THREAD

**Issue by wickedest** [docsifyjs/docsify#939]
## Feature request

A plugin for editing on gitlab, similar to https://github.com/njleonzhang/docsify-edit-on-github

#### What problem does this feature solve?

A convenience "Edit on gitlab" link at the top of each page to facilitate collaborative editing.

#### What does the proposed API look like?

See https://github.com/njleonzhang/docsify-edit-on-github

#### How should this be implemented in your opinion?

As a plugin

#### Are you willing to work on this yourself?

Yes.  By the way, I am _really_ impressed with docsify.  Good work.

**Comment by maximilienGilet** [comment]
Hi @wickedest I faced the same problem but a gitlab plugin is not needed.

Here is my simple configuration to get it working with our self-hosted gitlab

```javascript
plugins: [
    EditOnGithubPlugin.create("https://gitlab.dev.<yourdomain>.com/<group>/<repo>/tree/master/docs/",
    undefined,
    "Edit on Gitlab")
],
```

**Comment by wickedest** [comment]
@maximilienGilet, thanks for that!  it worked perfectly.

**Comment by maximilienGilet** [comment]
@wickedest Better an even better solution is to set the gitlab link to the corresponding `webide` view of the page. The users goes directly in the multiple files edit mode.

It should look like `https://<your-gitlab>/-/ide/project/<group>/<repo>/blob/master/-/docs/`
