### ISSUE TITLE
Link to another person to use, can't locate to the specified location and back to the home page

### ISSUE THREAD

**Issue by hpugongying** [docsifyjs/docsify#941]
#### Steps to reproduce
clone the application
Deployed to the server and run the command: docsify serve docs
send link(http://docs.oa.com/) to others use

#### What is current behaviour
eg: http://docs.oa.com/#/readme.md
others open this link can't locate to current location and back to the home page (http://docs.oa.com/)

#### What is the expected behaviour
can locate to current location (http://docs.oa.com/#/readme.md)

#### Other relevant information
- Your OS: macOS
- Node.js version:  v8.8.1
- npm/yarn version:  6.1.0
- Browser version:  chrome 78.0.3904.70（正式版本） （64 位）
- Docsify version:  4.3.0
- Docsify plugins:  none

**Comment by anikethsaha** [comment]
Can you please share your project structure 👍 .

**Comment by anikethsaha** [comment]
please look how docsify structured the docs https://github.com/docsifyjs/docsify/tree/develop/docs . 
You can access the readme docs  from here itself https://docsify.js.org/#/

**Comment by hpugongying** [comment]
> please look how docsify structured the docs https://github.com/docsifyjs/docsify/tree/develop/docs .
> You can access the readme docs from here itself https://docsify.js.org/#/

**Comment by hpugongying** [comment]
@anikethsaha  same structure as docsify。
 Deploy on the server,  config nginx。 Open several more browser stealth windows access this link(http://docs.oa.com/#/readme.md),  can't locate to current location
