### ISSUE TITLE
language highlight

### ISSUE THREAD

**Issue by superxxl** [docsifyjs/docsify#942]
How to introduce all code highlighting,reference Typora

# Simplified Chinese
如何引入全部代码高亮，参考Typora那样

**Comment by anikethsaha** [comment]
> https://docsify.js.org/#/language-highlight

is this what you are looking for?

docsify uses [`marked`](https://github.com/markedjs/marked) for parsing markdowns and I guess you can custom highlighter (https://marked.js.org/#/USING_ADVANCED.md#highlight)
