### ISSUE TITLE
Sidebar is not ultrawide display friendly

### ISSUE THREAD

**Issue by dellagustin-sap** [docsifyjs/docsify#944]
Ultrawide displays are becoming very common.
Athough users may split their desktop into sections, it is also common to maximize a browser window.
Normally, the main content is centered, and that is also the case with docsify.

The problem here is that when a user maximizes a website generated with docsify (standard theme) the sidebar is too far to the left.

Any ideas on how to tackle this?

**Comment by anikethsaha** [comment]
I couldnt find it too left with the default theme.

1. With the current width `300px`
🔽 
![image](https://user-images.githubusercontent.com/26347874/69337093-0d821000-0c86-11ea-9419-4d6c86df9208.png)

2. `sidebar width 500px`
🔽 
![image](https://user-images.githubusercontent.com/26347874/69337040-edeae780-0c85-11ea-85e9-9b57d625c6d7.png)

I can see the white gap in the `1` one but it aligns properly with the font-sizes and all.

The second implementation is might be looking centered but it requires the font-size to be increased which is not match with the other font

Perhaps you can show some PoCs

**Comment by anikethsaha** [comment]
I dont think its a good idea to change the sidebar from current style. Please submit a new issue if you have better proposal or a better solution.
Thanks

**Comment by dellagustin-sap** [comment]
Hello @anikethsaha , thanks for your responses and please accept my apologies for being unresponsive.
I could not address this due to my own priorities, but it is a tracked issue in the project where I use docsify, so I will do as you suggested and come back with a new issue when I have the time to work on this.
