### ISSUE TITLE
侧边栏显示与隐藏无效?

### ISSUE THREAD

**Issue by wonb168** [docsifyjs/docsify#947]
官网左下角的'三'是可以显示、隐藏侧边栏的，我的怎么无效，需要什么特殊配置吗？我是多个md文件的。
另外，超出一页的部分没有滚动条，显示不了。
请教。

**Comment by anikethsaha** [comment]
Please write it in english 👍

**Comment by timaschew** [comment]
This happened so many times. Some people just ignore the issue template. It's really hard to keep an overview, so I've started to close the issues immediately and reopen when the author changing rewriting it into english.

**Comment by anikethsaha** [comment]
Good move 👍
