### ISSUE TITLE
使用了docsify-demo-box-vue，但里面写了sass貌似编译不了，如何能支持模板里的sass

### ISSUE THREAD

**Issue by gFeng123** [docsifyjs/docsify#957]

**Comment by gFeng123** [comment]
使用docsify-demo-box-vue，写了sass，不能编译，导致写一个template,需要相应额外生成一个css文件引入，理想的效果是直接将模板里面的《style lang=“scss”》里面的sass编译成css，如何支持sass编译

**Comment by anikethsaha** [comment]
Please translate it to english and follow the template
