### ISSUE TITLE
string in angled brackets(<, >) is not printed

### ISSUE THREAD

**Issue by computerphilosopher** [docsifyjs/docsify#958]
## Bug Report

string that includes angled brackets is not printed

#### Steps to reproduce

write this in md file.

```
\<some string\>
```

#### What is current behaviour

angled brackets with escape character are not printed. 

angled bracekts are printed properly in [marked demo](https://marked.js.org/demo/). So I think it isn't marked's issue

#### What is the expected behaviour

\<angled brackets with escape character should be printed.\>

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: macOS 10.14.6
- Node.js version: 13.1.0
- npm/yarn version: npm 6.12.1, yarn 1.19.2
- Browser version: safari 12.1.2
- Docsify version: 4.4.0 
- Docsify plugins: docsify-themeable

**Comment by anikethsaha** [comment]
I will take A look in it soon. 
Thanks for pointing this

**Comment by computerphilosopher** [comment]
I think this issue occured because marked is old.

When I choose 0.5.1 version in marked demo, this issue is reproduced.

probably new release can fix this.

**Comment by anikethsaha** [comment]
try using `docsify@4.10.2`

**Comment by anikethsaha** [comment]
Please comment if its still exist
