### ISSUE TITLE
Please add a button of light or dark theme to be switching

### ISSUE THREAD

**Issue by tonglei100** [docsifyjs/docsify#959]
## Feature request
add a button which will switch the light or dark theme

#### How should this be implemented in your opinion?

a button on the  top right corner

**Comment by anikethsaha** [comment]
Please translate to english

**Comment by anikethsaha** [comment]
There is already an issue open about this #740 
You can try creating plugin for it Or even a script in navbar.md will work. 


You can take A look at #740 
Closing this,  if you have something else, please comment.

**Comment by boopathikumar018** [comment]
Try [docsify-darklight-theme](boopathikumar018.github.io/docsify-darklight-theme)

**Comment by fnoop** [comment]
> Try [docsify-darklight-theme](boopathikumar018.github.io/docsify-darklight-theme)

404

**Comment by boopathikumar018** [comment]
Please find the updated link for **docsify-darklight-theme**  [https://docsify-darklight-theme.boopathikumar.me](https://docsify-darklight-theme.boopathikumar.me)
