### ISSUE TITLE
Nested README

### ISSUE THREAD

**Issue by designermonkey** [docsifyjs/docsify#961]
I can set my `homepage` to something other than `README.md` but not any other subdirectory indexes. Anything else must always be `something/README.md`.

Why can't we have something like `something/index.md` or even for the simplest use case of case insensitive pages, `something/readme.md` (this fails with a 404)

**Comment by anikethsaha** [comment]
are you looking for something like this ? https://docsify.js.org/#/more-pages?id=more-pages

**Comment by designermonkey** [comment]
Hi, yes I am, but the ability to choose the filename, as we can with the `homepage` config option, so I could set a global `index` option for example.

The code is hardcoded to look for `README.md`, whereas I may want `index.md` or even a lowercase `readme.md`.

Does that make sense?

**Comment by anikethsaha** [comment]
I am sorry but I am not able to get your issue.
Can you show some snippet with before/after comparing the use-case.

**Comment by designermonkey** [comment]
This works:

```
/ --> /README.md
/something --> /something/README.md
/something/else --> /something/else.md
```

Using the `homepage` config option set to `homepage.md`

```
/ --> /homepage.md
/something --> /something/README.md
/something/else --> /something/else.md
```

I would like to be able to do `homepage` config option set to `index.md`, and/or an `index` config option set to `index.md` so I can do

```
/ --> /index.md
/something --> /something/index.md
/something/else --> /something/else.md
```

**Comment by anikethsaha** [comment]
oh I get it now.

you want the homepage to be used as +/the fallback page right?

In general : - 
We have `README.md` for fallback as for markdown based docs, readme.md works as the index.
You can see the same in GitHub as well.

So I wouldn't name my default or index points for a markdown based docs site to anything other than `README.md`

The homepage is different than fallback of the root index page.

But If something explicit ( like a config ) is mentioned  like `fallbackHomepage : yourhome.md`
then it would be more appropriate.

As of now, it are not explicitly working on any new feature for v4. so I cant tell you now how much time it would take to support it.

_perhaps you want to try itt out and create a PR if its ok_

Also I guess you can make some kind of workaround with [`alias`](https://docsify.js.org/#/configuration?id=alias) config

**Comment by anikethsaha** [comment]
use https://docsify.js.org/#/configuration?id=homepage
