### ISSUE TITLE
github页面不能正常加载边栏md

### ISSUE THREAD

**Issue by mandaren** [docsifyjs/docsify#963]
本来以为是_siderbar.md这个下划线的问题，然后改了名，去掉下划线，并将index.html里的设置改成loadsiderbar：‘siderbar.md’，检查下浏览器，发现还是报404，没加载成功

**Comment by anikethsaha** [comment]
Please translate it to english

**Comment by mandaren** [comment]
操蛋

**Comment by anikethsaha** [comment]
?

**Comment by mandaren** [comment]
翻译你妹，中文看不懂，装啥逼

**Comment by mandaren** [comment]
搞形式的人可悲至极

**Comment by liawnliu** [comment]
使用alias配置项，https://docsify.js.org/#/configuration?id=alias，这样可以避免不必要的404

**Comment by sy-records** [comment]
You need to create a `.nojekyll` in `./docs` to prevent GitHub Pages from ignoring files that begin with an underscore.

see https://docsify.js.org/#/more-pages?id=sidebar

**Comment by Koooooo-7** [comment]
please keeping chat and questions in  English to respect the rules here, don't be so rude.
