### ISSUE TITLE
Incorrect position of text between bracket (markdown)

### ISSUE THREAD

**Issue by PicchiKevin** [docsifyjs/docsify#967]
#### Steps to reproduce
Case 1:
1. https://docsify.js.org/#/more-pages?id=sidebar
2. Look at the `Create the _sidebar.md:` part
3. The part between the bracket is suddenly at the top and on top of each other (See screenshot)

Same behavior is happening there:
- https://docsify.js.org/#/custom-navbar?id=html
- https://docsify.js.org/#/custom-navbar?id=nesting
- Probably on other pages too...

I'm sure its happening on other pages too.

#### What is current behaviour

![image](https://user-images.githubusercontent.com/4269168/69947238-26d85700-14e5-11ea-97aa-ad8518618274.png)

#### What is the expected behaviour

![image](https://user-images.githubusercontent.com/4269168/69947287-45d6e900-14e5-11ea-9a73-79f8d72465e5.png)

#### Other relevant information

Tested on Chromium and Firefox

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version:
- Docsify version: 
- Docsify plugins:

**Comment by PicchiKevin** [comment]
I've got a fix ready if it's ok

**Comment by anikethsaha** [comment]
Go on 👍
