### ISSUE TITLE
[BUG]Edge browse show <li>unfriendly,but the chrome show well

### ISSUE THREAD

**Issue by czz1233** [docsifyjs/docsify#971]
## Bug Report
the bug is edge browers show unfriendly
![image](https://user-images.githubusercontent.com/27494661/70016283-dcc1a500-15ba-11ea-921d-e4936561d9cb.png)

#### Steps to reproduce

I think should change the js,but i don't where.

#### What is current behaviour
this is my code
```html
<li>page
            <ul>
                <li><a href="https://github.com/czz1322" target="_blank">Doocs</a></li>
                <li><a href="https://github.com/czz1233" target="_blank">Author</a></li>
            </ul>
        </li>

```
![image](https://user-images.githubusercontent.com/27494661/70016575-acc6d180-15bb-11ea-87e4-42933d9bd157.png)

#### What is the expected behaviour

i hope to adapt the edge browser
like chrome
![image](https://user-images.githubusercontent.com/27494661/70016443-4e99ee80-15bb-11ea-9fa6-47f4e29dc677.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS:  windows10
- Node.js version: github
- npm/yarn version:  github
- Browser version: Microsoft EdgeHTML 17.17134
- Docsify version:  4.9.4
- Docsify plugins: 4.9.4

**Comment by anikethsaha** [comment]
Can you send the style from inspecting the elements

**Comment by czz1233** [comment]
> Can you send the style from inspecting the elements
I useed  the `<link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">`  css
![image](https://user-images.githubusercontent.com/27494661/70031279-d72d8480-15e5-11ea-9b8b-9269272e9d77.png)

**Comment by anikethsaha** [comment]
Can you share for the chrome?

There might be some compatibility issues with cross-browser styling. The styling in the theme seems fine. Need to investigate that.

**Comment by anikethsaha** [comment]
Please feel to investigate and submit the fix. I am might not have time to fix it soon.

**Comment by czz1233** [comment]
> Please feel to investigate and submit the fix. I am might not have time to fix it soon.

think you,i believe that i can deal with the problem.

**Comment by anikethsaha** [comment]
> > Please feel to investigate and submit the fix. I am might not have time to fix it soon.
> 
> Think you,i believe that i can deal with the problem.

great 👍

**Comment by anikethsaha** [comment]
It should be fixed with inline styles or custom styling. 
Feel free to comment if this is still an issue
