### ISSUE TITLE
When accessing a page that does not exist, the page will be in the pending state and the page will be stuck.

### ISSUE THREAD

**Issue by lvyongfeng** [docsifyjs/docsify#973]
## Bug Report
When accessing a page that does not exist, the page will be in the pending state and the page will be stuck.
#### Steps to reproduce

For example，When I visit campus.xxxx.com/compute/uhost/introduction/uhost/dhag.md, this page does not exist.

using routermode history
setting alias '/.*/_sidebar.md': '/_sidebar.md'
3.using the latest version of Docsify

#### What is current behaviour
Response return 200，not 404
The page will be requested multiple times
The content returned is index.html's content
Last request returned to pending， the page cannot be accessed
![image](https://user-images.githubusercontent.com/16010230/70301966-d0e21700-1836-11ea-81fe-c28e0ddaa23b.png)

#### What is the expected behaviour

when pages does not exist, response return 404, page content display 404 not found

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Centos 7.4
- Node.js version: 
- npm/yarn version: 
- Browser version: Chrome 77.0.3865.90
- Docsify version: 4.9.4
- Docsify plugins: docsify-copy-code docsify.min.js  search.js zoom-image.js

**Comment by anikethsaha** [comment]
share your config !

and also your docs project structure. 
I cant re-create the error as I am getting the 404s in my setup and even from the docs site

**Comment by lvyongfeng** [comment]
The main problem is to configure "routerMode: 'history'," then 404 will not work。I use nginx to build docsify and the index.html configuration is as follows:

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>UCloud-中立 安全 可信赖的云计算服务商</title>
  <link rel="icon" href="_media/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css"title="vue">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/dark.css" title="dark" disabled>
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/buble.css" title="buble" disabled>
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/pure.css" title="pure" disabled>
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
	auto2top: true,
	executeScript: true,
	loadSidebar: true,
	autoHeader: true,
	loadNavbar: true,
	subMaxLevel: 4,
	mergeNavbar: true,
	notFoundPage: '_404.md',
  	routerMode: 'history',
	alias: {
	    '/.*/_sidebar.md': '/_sidebar.md',
	    '/.*/_navbar.md': '/_navbar.md'
	},
	search: {
	  paths: 'auto',
	  placeholder: '搜索',
	  noData: '没有结果',
	  depth: 6,
	},
	name: '<div><b style="font-size: 22px">UCloudStack 企业专有云</b></div>',
	formatUpdated: '{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}',
	plugins: [
	function(hook) {
        hook.beforeEach(function (html) {
        return html
	+ '\n----\n'
	+ '<div style="float:left" align="left"> Copyright © 2012-2019 UCloud 版权所有 </div>'
  	+ '<div style="float:right" align="right"> 更新时间：{docsify-updated} </div>'
         })
	}
	]
    }
  </script>
  <script src="//unpkg.com/docsify-copy-code"></script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
</body>
</html>

**Comment by lvyongfeng** [comment]
The main problem is to configure "routerMode: 'history'," then 404 will not work。I use nginx to build docsify and the index.html configuration is as follows:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>test</title>
  <link rel="icon" href="_media/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css"title="vue">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/dark.css" title="dark" disabled>
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/buble.css" title="buble" disabled>
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/pure.css" title="pure" disabled>
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
	auto2top: true,
	executeScript: true,
	loadSidebar: true,
	autoHeader: true,
	loadNavbar: true,
	subMaxLevel: 4,
	mergeNavbar: true,
	notFoundPage: '_404.md',
  	routerMode: 'history',
	alias: {
	    '/.*/_sidebar.md': '/_sidebar.md',
	    '/.*/_navbar.md': '/_navbar.md'
	},
	search: {
	  paths: 'auto',
	  placeholder: '搜索',
	  noData: '没有结果',
	  depth: 6,
	},
	name: '<div><b style="font-size: 22px">test</b></div>',
	formatUpdated: '{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}',
	plugins: [
	function(hook) {
        hook.beforeEach(function (html) {
        return html
	+ '\n----\n'
	+ '<div style="float:left" align="left"> Copyright © 2012-2019 test 版权所有 </div>'
  	+ '<div style="float:right" align="right"> 更新时间：{docsify-updated} </div>'
         })
	}
	]
    }
  </script>
  <script src="//unpkg.com/docsify-copy-code"></script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
</body>
</html>
```

**Comment by lvyongfeng** [comment]
nginx configuration is as follows：

```
    server {
        listen       80;
        server_name  docs.ucloudstack.com;
        autoindex    off;
        ssi          on;
        ssi_silent_errors on;

        location / {
            root         /root/docs/;
            index        index.html;
            try_files $uri $uri/ /index.html;                                                                                                             
        }                        
```

**Comment by lvyongfeng** [comment]
The document directory structure is as follows:

```
.
├── AdminGuide
│   ├── arch.png
│   ├── AdminGuide.md
│   └── UStack_log.jpg
├── advantages.md
├── APIGuide
│   └── APIGuide.md
├── arch.md
├── changelog.md
├── docschangelog.md
├── faq.md
├── features.md
├── index.html
├── Introduction.pdf
├── _media
│   ├── arch.png
│   ├── core.png
│   ├── favicon.ico
│   ├── pdf.png
│   ├── storage_arch.png
│   └── ustacklog.png
├── _navbar.md
├── README.md
├── scenario.md
├── _sidebar.md
├── techadv.md
├── TechWhitepaper
│   ├── TechWhitepaper2.md
│   ├── TechWhitepaper.md
└── UserGuide
    ├── UserGuide.md

```

**Comment by lvyongfeng** [comment]
@anikethsaha  Some members use alias to solve the same problem, but I don't understand how the alias name can solve this problem. Questions are as follows:
https://github.com/docsifyjs/docsify/issues/920

**Comment by anikethsaha** [comment]
Alias is helpful for custom routes or if you want to change Or add some routing behavior
In this you are using can you just check with `hash` mode.

**Comment by lvyongfeng** [comment]
I want to delete the `#` of each page URL of the document station, so I use the `history` mode, and I expect to restore 404 pages in` history` mode. Like # 920 issue, hope to solve the problem through configuration.

**Comment by anikethsaha** [comment]
need investigation. I will look into this soon

**Comment by lvyongfeng** [comment]
@anikethsaha OK, look forward to your investigation and solution, thanks.

**Comment by anikethsaha** [comment]
In the meantime, if you can provide a reproducible repo, It would be great for speeding things up.
Also feel free to investigate from your side as well and submit a fix if you find it. 
It will speed up the process.

Thanks

**Comment by lvyongfeng** [comment]
OK, I will continue to investigate and try to fix it.

**Comment by anikethsaha** [comment]
> OK, I will continue to investigate and try to fix it.

Great 👍

**Comment by lvyongfeng** [comment]
@anikethsaha Through investigation and trying, I couldn't find a solution. I am going to use the 'hash' routing mode, thanks for your help.

**Comment by anikethsaha** [comment]
Ok i am looking at this . Will let you know here if I find something

**Comment by zhangjingle** [comment]
window.$docsify = {
     ....
     routerMode: 'history',
     ....
 }
部署到 GitHub pages后,正常访问页面没问题,但是刷新页面或者回退页面会提示404,切换到hash模式一切正常,
我不喜欢#号..........................
请问这个问题解决了吗?
