### ISSUE TITLE
how to search content in embed md files 

### ISSUE THREAD

**Issue by itflash** [docsifyjs/docsify#975]
#### Steps to reproduce

1.embed a markdown file like the code below.
`[filename](_media/example.md ':include')`

2.type some words that example.md contains and start searching.

#### What is current behaviour

cannot search content in embed md files 

#### What is the expected behaviour

display search result correctlly

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
you want to embed a markdown file ? and then search from that ?

**Comment by itflash** [comment]
@anikethsaha yes, is it possible to do that?

**Comment by anikethsaha** [comment]
how you are planning to embed markdown inside markdown ?
as far as I know, embedding markdown is not possible unless its process to html file.

**Comment by itflash** [comment]
@anikethsaha `[filename](_media/example.md ':include')`

**Comment by anikethsaha** [comment]
I couldn't find any spec for using this over markedjs (_may be I am missing something_)
 anyway, even if it is supported by marked, it cant be searched inside the embedded ones.

**Comment by gagandaroach** [comment]
is there a workaround for this? @anikethsaha

**Comment by gagandaroach** [comment]
Maybe there is a way to statically generate the main guide, then have the search index that?
