### ISSUE TITLE
Installing docsify-cli fails on postinstall

### ISSUE THREAD

**Issue by from-nibly** [docsifyjs/docsify#978]
## Bug Report
`npm i -g docsify-cli` results in a failure due to a postinstall error
```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! docsify@4.10.0 postinstall: `opencollective postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the docsify@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

#### Steps to reproduce
`npm i -g docsify@4.10.0`

#### What is current behaviour

Fails to install

#### What is the expected behaviour

Shouldn't fail on install.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: linux
- Node.js version: v12.13.0
- npm/yarn version: 6.12.0
- Browser version: N/A
- Docsify version: 4.10.0
- Docsify plugins: N/A

**Comment by anikethsaha** [comment]
Thanks for pointing this. Looks like we are using outdate opencollective CLI which is not compatible. I will fix it soon

**Comment by anikethsaha** [comment]
Please check with this https://www.npmjs.com/package/docsify/v/4.10.2

**Comment by anikethsaha** [comment]
![image](https://user-images.githubusercontent.com/26347874/70946356-0b408500-207d-11ea-95c4-cf18dd6d2470.png)

Its installing properly.

Please comment if its still existing 👍

**Comment by from-nibly** [comment]
Awesome turnaround thanks!
