### ISSUE TITLE
Allow access to the markdown API within plugins.

### ISSUE THREAD

**Issue by mrpotatoes** [docsifyjs/docsify#980]
## Feature request
I recently finished a plugin for Docsify to allow someone to pull in a github source file (or bits of a file) and inline it into the document. It's very simple in how it does it but one thing that I am not able to do is style the code. It would be great if I had access to the markdown parser so that I could pass it a string like ` ```js console.log()``` and I get the formatted text back for me to put back into the document.

The plugin in question: https://github.com/mrpotatoes/docsify-github-embed

#### What problem does this feature solve?
Styled code that is styled like the rest of the code on the docsify page.

#### What does the proposed API look like?
```js
$docsify.plugins = [
  (hook, vm) => {
    hook.afterEach(async (html, next) => {
      const someString = "```js\nconsole.log('foo bar')\n```"
      const newHTML = html + ' - ' + $docsify.markd.render(someString)

      next(newHTML)
    })
  }
].concat($docsify.plugins || [])
```

#### How should this be implemented in your opinion?
No idea, as I don't know the internals of Docsify

#### Are you willing to work on this yourself?
I cannot unfortunately otherwise I would have made a PR.

**Comment by anikethsaha** [comment]
You want to parse the markdown to HTML and then want to return that ?

**Comment by mrpotatoes** [comment]
Yes, exactly. I would rather not bring in yet another package to just style the code if at all possible.

**Comment by anikethsaha** [comment]
`beforeEach` hook is when you will get the markdown and `afterEach` when you will get the html.
We cant pass the whole `marked` library as it might make the operation slow and its less effective to pass the whole parser. 

In future we may change the markdown parser to some pluggable parser where you can write our own markdown transforms as per your need.

If you want to make changes acc to lang, then you can use the [`markdown`](https://docsify.js.org/#/markdown) config. 

I actually still didnt get what exactly you are looking for. Can you share the before/after details.

**Comment by mrpotatoes** [comment]
`beforeEach` does allow me to return what I want but it doesn't allow for `async` `await` so I'll have to think about how I do this. Thanks!
