### ISSUE TITLE
After updating to the latest version, the css configured on "name" does not take effect

### ISSUE THREAD

**Issue by lvyongfeng** [docsifyjs/docsify#981]
## Bug Report
After updating to the latest version, the css configured on "name" does not take effect。
Example：
```name: '<div><b style="font-size: 22px">test</b></div>', ```
#### Steps to reproduce
```
window.$docsify = {
name: '<div><b style="font-size: 22px">test</b></div>',
 }
```
Use "docsify" latest version

#### What is current behaviour
![image](https://user-images.githubusercontent.com/16010230/70959163-65117100-20b6-11ea-999a-dc9c9ddf2cae.png)

#### What is the expected behaviour

![image](https://user-images.githubusercontent.com/16010230/70959616-b4a46c80-20b7-11ea-8a22-10899eced6be.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.10.2
- Docsify plugins: 
```
  <script src="//unpkg.com/docsify-copy-code"></script>
  <script src="//unpkg.com/docsify/lib/docsify.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-bash.min.js"></script>
```

**Comment by anikethsaha** [comment]
DO you have `config.logo` set ?

Usually ,  you need to add the logo in `config.logo` and set a string name for `config.name`

It will break if you assign an image to `name`

**Comment by lvyongfeng** [comment]
I don't want to use a picture as the title on the sidebar. However, after upgrading to the latest version, titles configured with "name" cannot be bolded or enlarged with "CSS". Available when 'name' is configured with the '4.9.4' version.
Hope that can be helped, thanks.

**Comment by anikethsaha** [comment]
Actually in new version we are escaping the special characters like 
`<>` etc. 
So as of now we you can style. 
Try to get the classname and style it from your stylesheet. 
I will try to figure out a way to cover this use case soon

**Comment by lvyongfeng** [comment]
OK，Thanks !

**Comment by anikethsaha** [comment]
You can find the motivation behind this change here #972

**Comment by trusktr** [comment]
Maybe we need more flexibility to use all features in the sidebar. https://github.com/docsifyjs/docsify/issues/984
