### ISSUE TITLE
Show Gist In Markdown 

### ISSUE THREAD

**Issue by haozibi** [docsifyjs/docsify#982]
## Bug Report

hello,I have a problem. I write gist embed link in markdown,but docsify don't show it.

I want to know how to show gist in docsify

#### Steps to reproduce

- index.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="icon" href="_media/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">

  <!-- mermaid -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css">
  <script src="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
</head>

<body>
  <div id="app"></div>
  <script>
    mermaid.initialize({ startOnLoad: false });
    window.$docsify = {
      repo: 'haozibi/',
      auto2top: true,
      subMaxLevel: 2,

      executeScript: true,

      loadSidebar: true,
      loadNavbar: true,
      search: 'auto', 
      markdown: {
        renderer: {
          code: function (code, lang) {
            if (lang === "mermaid") {
              return (
                '<div class="mermaid">' + mermaid.render(lang, code) + "</div>"
              );
            }
            return this.origin.code.apply(this, arguments);
          }
        }
      },
    }
  </script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>

  <script src="//unpkg.com/docsify/lib/plugins/external-script.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/emoji.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
  <script src="//unpkg.com/docsify-copy-code"></script>

  <script src="//unpkg.com/prismjs/components/prism-go.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-bash.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-python.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-markdown.js"></script>
</body>

</html>
```

- markdown

```markdown
# test

<script src="https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63.js"></script>
```

#### What is current behaviour

Chrome console show

```conosle
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
```

I am not very good at the FrontEnd, so I am confused about the problem. sorry~~

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OS 10.13.6
- Node.js version: 
- npm/yarn version: 
- Browser version: 79.0.3945.79（64 Bit）
- Docsify version: 
- Docsify plugins:

**Comment by anikethsaha** [comment]
can you share a reproducible repo.

**Comment by haozibi** [comment]
> can you share a reproducible repo.

like this: https://gist.github.com/haozibi/3a7a87ec010374c4ad5b926bd695fca9

```javascript
<script src="https://gist.github.com/haozibi/3a7a87ec010374c4ad5b926bd695fca9.js"></script>
```

**Comment by anikethsaha** [comment]
Not the gist , a repo would have been better.
Ok leave, I will take a look in this soon 👍

**Comment by haozibi** [comment]
> Not the gist , a repo would have been better.
> Ok leave, I will take a look in this soon 👍

Maybe u can look [https://github.com/haozibi/t-docsify](https://github.com/haozibi/t-docsify)

step 👇

```shell
$ git clone git@github.com:haozibi/t-docsify.git
$ cd t-docsify
$ docsify init docs

Initialization succeeded! Please run docsify serve docs

# insert gist
$ docsify serve docs

Serving /Users/bi/Desktop/t-docsify/docs now.
Listening at http://localhost:49635
```

**Comment by anikethsaha** [comment]
You need to enable this `executescript:true`  in order to run the inline scripts , here is the docs https://docsify.js.org/#/configuration?id=executescript

**Comment by haozibi** [comment]
> executescript:true

same problem, but console log is different.

u can look https://github.com/haozibi/t-docsify/commit/6fa6dfb190149de0df315050c061de23b76e7549


![image](https://user-images.githubusercontent.com/13708418/71010530-f6b8c700-2126-11ea-920e-9e3ccee6833c.png)

**Comment by anikethsaha** [comment]
Thanks , I will take a look soon.
In the meant time,  could try with other external links and just check if the behavior is the same or not.

**Comment by Koooooo-7** [comment]
In my opinion.u can't include the "Gist  js "directly.
There is a  part of content of the "Gist js "such as u posted（`https://gist.github.com/haozibi/3a7a87ec010374c4ad5b926bd695fca9.js  `). 

```js
document.write('<link rel="stylesheet"... 
```
We can't use the `document. write` in async loading after the document loaded over. 
I think u should change another way to resolve this issue.

**Comment by MichaelCurrin** [comment]
I could not get the gist embed script to work on Docsify.

But using Docify's [embed](https://docsify.now.sh/embed-files?id=embedded-file-type) approach and a raw URL, this works great to embed a gist.

e.g. Pulling in and rendering markdown content

```
[run_docsify_locally.md ](//gist.githubusercontent.com/MichaelCurrin/c2bece08f27c4277001f123898d16a7c/raw/docsify_embed_gist.md ':include')
```

I use this here: https://michaelcurrin.github.io/docsify-js-tutorial/#/?id=docsify-cli

I wrote a short tutorial on this here: [gist](https://gist.github.com/MichaelCurrin/c2bece08f27c4277001f123898d16a7c).

**Comment by MichaelCurrin** [comment]
I'm happy to add to the Docsify embed section with a short explanation on how to embed a gist like this, as an alternative to script tag.

**Comment by anikethsaha** [comment]
> I'm happy to add to the Docsify embed doc with a short explanation on how to embed a gist like this, as an alternative to script tag.

feel free to submit a PR

**Comment by MichaelCurrin** [comment]
Sorry this was at the back of my mind. I'll still do the PR discussed above for the enable scripts approach and my alt approach

**Comment by MichaelCurrin** [comment]
I'll get it in today

**Comment by MichaelCurrin** [comment]
Added! :tada: :memo:
