### ISSUE TITLE
history mode, nginx second-level directory 403

### ISSUE THREAD

**Issue by imruxin** [docsifyjs/docsify#988]
when I used history mode，refresh the web，show 403 Forbidden.
the first is ok.

docsify config:

```bash
...
routerMode: 'history',
...
```

doc directory:

```bash
.
├── .nojekyll
├── README.md
├── _navbar.md
├── _sidebar.md
├── guide
│   ├── README.md
│   ├── _sidebar.md
│   └── git-flow-guide.md
├── index.html
```

the first view url/guide/ is ok, after refresh show 403 forbidden.

url/guide/git-flow-guide is always ok. not show 403

nginx config:

```bash
server {
    listen 80;
    server_name url;

    root /data/www/doc;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

}
```

how to fix it ?

thanks

**Comment by lvyongfeng** [comment]
Please check the permissions of "nginx" for the directory '/ data / www / doc', and also check if the 'user' in the nginx configuration file is consistent with the directory permissions.

**Comment by imruxin** [comment]
@lvyongfeng permissions is ok. In my option, this question maybe is lack of index file on the 'url/guide/' when direct access it. 

> the first view url/guide/ is ok, after refresh show 403 forbidden.
url/guide/git-flow-guide is always ok. not show 403 forbidden.

**Comment by imruxin** [comment]
nginx add `error_page 403 /index.html;` fix it.
