### ISSUE TITLE
HTML (image) stopped working in name property on Github pages

### ISSUE THREAD

**Issue by Hainesy** [docsifyjs/docsify#990]
We had a logo top left using HTML embedded in the name field but it's suddenly stopped working in Github pages.

```js
window.$docsify = {
    name: `\
    <svg width="136" height="28" xmlns="http://www.w3.org/2000/svg">\
      <g fill="#D90268">\
         <path d="..."/>\
      </g>\
    </svg><br>\
    Our custom header`
}
```

**Comment by anikethsaha** [comment]
Actually we recently did escaping of tags and other char in the latest version. But I am thinking of reverting that.
Till the next release use `v4.9.4`
