### ISSUE TITLE
Cover page background color can't be changed to gradient

### ISSUE THREAD

**Issue by ghost** [docsifyjs/docsify#993]
#### Steps to reproduce
Create Cover page with Gradient 
`![color](linear-gradient(to left bottom, #b3ffc8 0%, #eeffb3 100%))`

#### What is current behaviour
It's just displaying as text on the Cover page

#### What is the expected behaviour
Backrgound of Cover page should change to a gradient

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: v12.14.0
- npm/yarn version: npm v6.13.4
- Browser version: Firefox 71.0
- Docsify version: 4.10.2
- Docsify plugins: docsify-fontawesome

**Comment by anikethsaha** [comment]
> `![color](linear-gradient(to left bottom, #b3ffc8 0%, #eeffb3 100%))`

You cant use `to left bottom` here cause it contains spaces so `marked` won't create a `p.img` tag here
so our regex [`here`](https://github.com/docsifyjs/docsify/blob/develop/src/core/render/index.js#L182) wont match and it won't render the styles

you can try this [`here`](<https://marked.js.org/demo/?outputType=html&text=%0AMarked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%3C!--%20background%20color%20--%3E%0A%0A!%5Bcolor%5D(linear-gradient(to-right%2Cred%2Cyellow))%0A%0A%0A!%5Bcolor%5D(linear-gradient(to%20right%2Cred%2Cyellow))%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%2C%0Acover%20%3A%20true%0A%7D&version=master>)

**Comment by radarNetwork** [comment]
That worked. It's not documentated (which is really ironic) how to use a linear-gradient.
Thanks a lot!

**Comment by anikethsaha** [comment]
> That worked.

would you share your workaround?
maybe update the docs as well with your code snippet
