### ISSUE TITLE
Collapse one page?

### ISSUE THREAD

**Issue by Fenny** [docsifyjs/docsify#994]
I have one README.md file that has the following structure:
```
# Gettings started
Blabla

## Install
Blabla

## Hello world
Blabla
```

This works fine with docsify and I get a nice sidemenu:
```
Getting started
 - Install
 - Hello world
```

But i cannot find an option to collapse this menu. 
And I don't want to separate my sections into multiple files, I rather have an one-page.

Any solutions?

**Comment by anikethsaha** [comment]
> But I cannot find an option to collapse this menu.

They are kind of collapsible but not with the effect.
We don't support complete collapsible behavior right now. Maybe in a future release or maybe some plugin can come to the rescue. 

Silimar discussion is here https://github.com/docsifyjs/docsify/issues/984
