### ISSUE TITLE
Remove globals (when we get a chance)

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#995]
## Feature request

Let's remove globals. Does `_paq` need to be a global?

#### What problem does this feature solve?

Cleaner more robust code.

#### What does the proposed API look like?

no globals

#### How should this be implemented in your opinion?

move things off global and share the variables only the scopes where needed.

#### Are you willing to work on this yourself?

As with everything, when/if I get the time.

**Comment by trusktr** [comment]
Arrgh, apparently Matomo requires the global `_paq` var: https://developer.matomo.org/guides/tracking-javascript-guide

**Comment by anikethsaha** [comment]
Globals are hard to determine whether they are being used or not.
It's too risky to remove unless we have tests
