### ISSUE TITLE
.md file and directory with the same name

### ISSUE THREAD

**Issue by yuxesd** [docsifyjs/docsify#997]
## Bug Report
In the same path, if there is an .md file and folder with the same name, when accessing the md file with the same name, it will automatically access the readme under the folder with the same name

#### Steps to reproduce
ef:
In the test directory, there are both the uname.md file and the uname directory.  I want to visit https://dsda.com/test/uname, but  the url will jump to https://dsda.com/test/uname/, return  readme.md file under the uname directory

#### What is current behaviour

the url will jump to https://dsda.com/test/uname/, return  readme.md file under the uname directory.

#### What is the expected behaviour

I want to  visit uname.md file
#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 4.9
- Docsify plugins:

**Comment by anikethsaha** [comment]
whats the behavior for https://dsda.com/test/uname/uname.md ?

**Comment by yuxesd** [comment]
> https://dsda.com/test/uname/uname.md的行为是什么？

The page can be displayed normally

**Comment by yuxesd** [comment]
> whats the behavior for https://dsda.com/test/uname/uname.md ?

The page can be displayed normally

**Comment by yuxesd** [comment]
> whats the behavior for https://dsda.com/test/uname/uname.md ?

**Comment by anikethsaha** [comment]
Okay so what I understood from your issue is

```
- uname
 |- uname.md
 |- README.md
```

So when visiting

- `dsda.com/test/uname` --> it will show the `uname/README.md`
- `dsda.com/test/uname/uname.md` --> it will show the `uname/uname.md`

**right ?**

Well, this is the expected behavior as `README.md` is the default markdown file when works like `index.js` for a js project.

You can change the default markdown file from `README.md` -> `someother.md` using this https://docsify.js.org/#/configuration?id=homepage

**Comment by yuxesd** [comment]
> Okay so what I understood from your issue is
> 
> ```
> - uname
>  |- uname.md
>  |- README.md
> ```
> 
> So when visiting
> 
> * `dsda.com/test/uname` --> it will show the `uname/README.md`
> * `dsda.com/test/uname/uname.md` --> it will show the `uname/uname.md`
> 
> **right ?**
> 
> Well, this is the expected behavior as `README.md` is the default markdown file works like `index.js` for a js project.
> 
> You can change the default markdown file from `README.md` -> `someother.md` using this https://docsify.js.org/#/configuration?id=homepage
> 
> It works like a homepage



> Okay so what I understood from your issue is
> 
> ```
> - uname
>  |- uname.md
>  |- README.md
> ```
> 
> So when visiting
> 
> * `dsda.com/test/uname` --> it will show the `uname/README.md`
> * `dsda.com/test/uname/uname.md` --> it will show the `uname/uname.md`
> 
> **right ?**
> 
> Well, this is the expected behavior as `README.md` is the default markdown file works like `index.js` for a js project.
> 
> You can change the default markdown file from `README.md` -> `someother.md` using this https://docsify.js.org/#/configuration?id=homepage
> 
> It works like a homepage


My project structure is that

> - test
>   - uname.md
>   - uname
>      |- uname.md
>      |- README.md
> ```

I want to visit   /test/uname ,but  url will jump to  /test/uname/ ， readme.md file under the uname directory.

**Comment by yuxesd** [comment]
I have solved this problem。
alias:{
  '/(.*)(\/)$':'$1.md'
}
