### ISSUE TITLE
Add code block highlight for more language.

### ISSUE THREAD

**Issue by Saul-Mirone** [docsifyjs/docsify#998]
#### What problem does this feature solve?
I try to use docsify for my typescript project but I found that typescript cannot be highlight

#### How should this be implemented in your opinion?
maybe highlight.js will be useful

#### Are you willing to work on this yourself?
I will give it a try.

**Comment by anikethsaha** [comment]
You can add `highlight.js` to `markedjs` config
https://docsify.js.org/#/markdown
https://github.com/markedjs/marked/blob/master/docs/USING_ADVANCED.md

**Comment by Saul-Mirone** [comment]
> You can add `highlight.js` to `markedjs` config
> https://docsify.js.org/#/markdown
> https://github.com/markedjs/marked/blob/master/docs/USING_ADVANCED.md

Great!
